In [1]:
import pandas as pd
from jira import JIRA
import sys
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import get_mysql
mysql=get_mysql()
jira=JIRA('https://research.quantumgalaxy.cn/', basic_auth=('bot2', "jira_bot2"))

In [2]:
#受世界线影响：.fields.customfield_11412

In [3]:
df=pd.read_csv(r'E:\wangzhilin\QuantumGalaxy\世界线_标的_标的全表.csv')
df=df[['公司名称','公司简述','相关世界线']]
df['code']=None
df

,公司名称,公司简述,相关世界线,code
0,光力科技,NaN,半导体划片机国产替代,None
1,拓荆科技,薄膜气象沉积设备,薄膜沉积设备国产化,None
2,北方华创,NaN,薄膜沉积设备国产化,None
3,微导纳米,“PECVD/ALD薄膜化学气相沉积设备”。同作为产业链上游，半导体设备的市场表现弱于数据中...,"薄膜沉积设备国产化,钙钛矿电池量产",None
4,茂莱光学,NaN,"光刻机国产化,前道检测设备国产化",None
...,...,...,...,...
397,汇洲智能,NaN,NaN,None
398,青云科技,NaN,NaN,None
399,小商品城,商业模式：商铺店租、跨境结算，Chinagood平台会员费等\n利润增长方式：更多商户入驻平...,"消费降级,人民币国际化",None
400,福昕软件,商业模式：PDF编辑器，海外版叫Foxit，占营收91%，分为年费149美元，99美元，79...,"数据重要性提升,AI+教育,AI+传媒",None
401,伟创电气,商业模式：低压变频器、伺服系统、PLC（可编程）\n利润增长方式：向机器人企业销售伺服系统\...,NaN,None

In [4]:
for i,r in df.iterrows():
    name=r['公司名称']
    sql='select code from ticker_info where name like "%%%s%%"'%name
    code=mysql.read_query(sql)
    if code:
        df.loc[i,'code']=code[0][0]
        pass
    else:
        print(name)

电科网安
中新塞克
瑞普眼科
遥望科技
百纳千成
三五互联
晶盛电机
固高科技
新松机器人
沈阳机床
乐凯新材
赛为智能
台海核电
奥雅股份
和林微钠
北京文化
兆龙互联
汇洲智能

In [16]:
df = df.fillna(value=0)

In [17]:
df

,公司名称,公司简述,相关世界线,code
0,光力科技,0,半导体划片机国产替代,300480.SZ
1,拓荆科技,薄膜气象沉积设备,薄膜沉积设备国产化,688072.SH
2,北方华创,0,薄膜沉积设备国产化,002371.SZ
3,微导纳米,“PECVD/ALD薄膜化学气相沉积设备”。同作为产业链上游，半导体设备的市场表现弱于数据中...,"薄膜沉积设备国产化,钙钛矿电池量产",688147.SH
4,茂莱光学,0,"光刻机国产化,前道检测设备国产化",688502.SH
...,...,...,...,...
397,汇洲智能,0,0,0
398,青云科技,0,0,688316.SH
399,小商品城,商业模式：商铺店租、跨境结算，Chinagood平台会员费等\n利润增长方式：更多商户入驻平...,"消费降级,人民币国际化",600415.SH
400,福昕软件,商业模式：PDF编辑器，海外版叫Foxit，占营收91%，分为年费149美元，99美元，79...,"数据重要性提升,AI+教育,AI+传媒",688095.SH
401,伟创电气,商业模式：低压变频器、伺服系统、PLC（可编程）\n利润增长方式：向机器人企业销售伺服系统\...,0,688698.SH

In [78]:
epics={}
'a' in epics.keys()

False

In [81]:
groups={}
for i,r in df.iterrows():
     if r['相关世界线'] and r['code']:
            target_epics=r['相关世界线'].split(',')
            #print(target_epics)
            issues=jira.search_issues(f'project = COMPSTUDY AND issuetype = 公司研究 AND 万得代码 ={r["code"]}')
            if not issues:
                 print(f'r["code"] has no jira issue')
            else:
                 issue=issues[0]
                 current_epics=issue.fields.customfield_11412
                 epics=[]
                 if current_epics:
                      current_epics=current_epics.split(', ')
                      #list or None
                      
                      for e in current_epics:
                           name=jira.issue(e).fields.summary
                           epics.append(name)
                 for target_epic in target_epics:
                      if target_epic in epics: #jiraissue已经关联了此世界线
                           print(target_epic)
                           continue
                      else:  
                           if target_epic in groups.keys():
                                groups[target_epic].append((r['公司名称'],r['code']))
                                pass
                           else:
                                groups[target_epic]=[]
                                groups[target_epic].append((r['公司名称'],r['code']))
                           pass
                           #将此世界线的id添加到issue的世界线field
                      
                      

    

     else:
        #print(r['公司名称'])
        pass

薄膜沉积设备国产化
薄膜沉积设备国产化
光刻机国产化
半导体划片机国产替代
数据重要性提升
数据重要性提升
AI自主可控
算力紧缺（数据中心建设）
AI自主可控
算力紧缺（数据中心建设）
医疗消费需求恢复
AI自主可控
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
模型能力提升
模型能力提升
模型能力提升
AI+教育
数据重要性提升
数据重要性提升
数据重要性提升
数据重要性提升
数据重要性提升
数据重要性提升
医疗消费需求恢复
医疗消费需求恢复
AI+影视
AI+影视
AI+影视
AI+影视
AI+影视
AI+影视
AI+影视
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
AI+游戏
人民币国际化
人民币国际化
航空军工机床自主可控
航空军工机床自主可控
AI+教育
AI+教育
AI+教育
海上风电装机量提升
海上风电装机量提升
海上风电装机量提升
国产风电零部件出口增加
海上风电装机量提升
海上风电装机量提升
海上风电装机量提升
海上风电装机量提升
风机大型化
国产风电零部件出口增加
风机大型化
风机大型化
风机大型化
国产风电零部件出口增加
风机大型化
风机大型化
风机大型化
数据重要性提升
PET铜箔替代锂电铜箔
PET铜箔替代锂电铜箔
PET铜箔替代锂电铜箔
PET铜箔替代锂电铜箔
PET铜箔替代锂电铜箔
AI+传媒
中国电动车需求增加
中国电动车需求增加
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
AI+机器人
数据重要性提升
AI+影视
AI+传媒
医疗消费需求恢复
AI+传媒
算力紧缺（数据中心建设）
中特估
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
算力紧缺（数据中心建设）
数据重要性提升
医疗消费需求恢复
AI+传媒
算力紧缺（数据中心建设）
数据重要性提升
AI+教育
数据重要性提升
锂电回收
锂电回收

In [82]:
groups

{'半导体划片机国产替代': [('光力科技', '300480.SZ'),
  ('中科飞测', '688361.SH'),
  ('精测电子', '300567.SZ')],
 '薄膜沉积设备国产化': [('微导纳米', '688147.SH')],
 '钙钛矿电池量产': [('微导纳米', '688147.SH'),
  ('捷佳伟创', '300724.SZ'),
  ('京山轻机', '000821.SZ'),
  ('奥来德', '688378.SH'),
  ('杰普特', '688025.SH')],
 '光刻机国产化': [('茂莱光学', '688502.SH')],
 '前道检测设备国产化': [('茂莱光学', '688502.SH')],
 'AI自主可控': [('佰维存储', '688525.SH'),
  ('江波龙', '301308.SZ'),
  ('中国软件', '0354.HK'),
  ('中科信息', '300678.SZ'),
  ('富乐德', '301297.SZ')],
 'N型电池替代P型电池': [('海目星', '688559.SH'),
  ('捷佳伟创', '300724.SZ'),
  ('帝科股份', '300842.SZ')],
 'HJT电池量产': [('捷佳伟创', '300724.SZ'),
  ('迈为股份', '300751.SZ'),
  ('金辰股份', '603396.SH'),
  ('高测股份', '688556.SH'),
  ('奥特维', '688516.SH')],
 '算力紧缺（数据中心建设）': [('博创科技', '300548.SZ'),
  ('太辰光', '300570.SZ'),
  ('德科立', '688205.SH'),
  ('光迅科技', '002281.SZ'),
  ('中恒电气', '002364.SZ'),
  ('欧陆通', '300870.SZ'),
  ('依顿电子', '603328.SH'),
  ('欧比特', '300053.SZ'),
  ('超讯通信', '603322.SH'),
  ('一博科技', '301366.SZ'),
  ('胜宏科技', '300476.SZ'),
  ('沪电股份', '002463.SZ'),
  ('广和通', '300638.SZ'),
  ('中国移动', '0941.HK'),
  ('东田微', '301183.SZ'),
  ('顺网科技', '300113.SZ'),
  ('兆龙互连', '300913.SZ'),
  ('南凌科技', '300921.SZ'),
  ('铭普光磁', '002902.SZ'),
  ('工业富联', '601138.SH')],
 '模型能力提升': [('百度集团', '9888.HK'), ('阿里巴巴', '01609WAQ5.N'), ('商汤', '0020.HK')],
 'AI+游戏': [('昆仑万维', '300418.SZ'),
  ('浙数文化', '600633.SH'),
  ('恺英网络', '002517.SZ'),
  ('盛天网络', '300494.SZ'),
  ('姚记科技', '002605.SZ'),
  ('华立科技', '301011.SZ'),
  ('ST天润', '002113.SZ'),
  ('惠程科技', '002168.SZ'),
  ('世纪华通', '002602.SZ'),
  ('神州泰岳', '300002.SZ'),
  ('中青宝', '300052.SZ'),
  ('IGG', '0799.HK'),
  ('华星创业', '300025.SZ'),
  ('金马游乐', '300756.SZ'),
  ('顺网科技', '300113.SZ')],
 '数据重要性提升': [('绿盟科技', '300369.SZ'),
  ('迪普科技', '300768.SZ'),
  ('锐捷网络', '301165.SZ'),
  ('安恒信息', '688023.SH'),
  ('朗玛信息', '300288.SZ'),
  ('金自天正', '600560.SH'),
  ('中体产业', '600158.SH'),
  ('中广天择', '603721.SH'),
  ('福昕软件', '688095.SH')],
 'AI+影视': [('华策影视', '300133.SZ'),
  ('浙数文化', '600633.SH'),
  ('光线传媒', '300251.SZ'),
  ('欢瑞世纪', '000892.SZ'),
  ('奥飞娱乐', '002292.SZ'),
  ('慈文传媒', '002343.SZ'),
  ('华星创业', '300025.SZ')],
 '人民币国际化': [('天阳科技', '300872.SZ'),
  ('信安世纪', '688201.SH'),
  ('启明星辰', '002439.SZ'),
  ('四方精创', '300468.SZ'),
  ('高伟达', '300465.SZ'),
  ('小商品城', '600415.SH')],
 '激光钻孔色设备国产化': [('大族数控', '301200.SZ')],
 'AI+教育': [('方直科技', '300235.SZ'),
  ('实益达', '002137.SZ'),
  ('佳发教育', '300559.SZ'),
  ('科德教育', '300192.SZ'),
  ('数字人', '835670.BJ'),
  ('南方传媒', '601900.SH'),
  ('宇华教育', '6169.HK'),
  ('鸥玛软件', '301185.SZ'),
  ('福昕软件', '688095.SH')],
 '海上风电装机量提升': [('长盛轴承', '300718.SZ'),
  ('力星股份', '300421.SZ'),
  ('中集集团', '000039.SZ'),
  ('振华重工', '600320.SH'),
  ('天海防务', '300008.SZ'),
  ('亚星锚链', '601890.SH'),
  ('亨通光电', '600487.SH')],
 '风机大型化': [('广大特材', '688186.SH')],
 '机械及工程制造出口': [('荣旗科技', '301360.SZ'), ('北方股份', '600262.SH')],
 '医疗消费需求恢复': [('兴齐眼药', '300573.SZ'), ('朗玛信息', '300288.SZ')],
 'PET铜箔替代锂电铜箔': [('骄成超声', '688392.SH'),
  ('光华科技', '002741.SZ'),
  ('阿石创', '300706.SZ')],
 '加快建设充电基础设施': [('双杰电气', '300444.SZ'),
  ('通合科技', '300491.SZ'),
  ('万马股份', '002276.SZ'),
  ('金冠电气', '688517.SH'),
  ('北巴传媒', '600386.SH')],
 '中国电动车需求增加': [('理想', '2015.HK'), ('蔚来', '9866.HK'), ('华工科技', '000988.SZ')],
 'AI+机器人': [('埃夫特', '688165.SH'),
  ('新时达', '002527.SZ'),
  ('双环传动', '002472.SZ'),
  ('上海机电', '600835.SH'),
  ('丰立智能', '301368.SZ'),
  ('埃斯顿', '002747.SZ'),
  ('英威腾', '002334.SZ'),
  ('优德精密', '300549.SZ'),
  ('昊志机电', '300503.SZ'),
  ('鼎智科技', '873593.BJ'),
  ('爱仕达', '002403.SZ'),
  ('卓翼科技', '002369.SZ'),
  ('拓斯达', '300607.SZ'),
  ('雷赛智能', '002979.SZ'),
  ('机器人', '2252.HK'),
  ('均普智能', '688306.SH'),
  ('凯尔达', '688255.SH'),
  ('克来机电', '603960.SH'),
  ('信邦智能', '301112.SZ'),
  ('迈赫股份', '301199.SZ'),
  ('博众精工', '688097.SH'),
  ('博实股份', '002698.SZ'),
  ('小米集团', '1810.HK'),
  ('景业智能', '688290.SH'),
  ('康拓红外', '300455.SZ'),
  ('奥比中光', '688322.SH'),
  ('奥普特', '688686.SH'),
  ('海康威视', '002415.SZ'),
  ('远大智能', '002689.SZ'),
  ('思特威', '688213.SH'),
  ('格科微', '688728.SH'),
  ('韦尔股份', '603501.SH'),
  ('长光华芯', '688048.SH'),
  ('柯力传感', '603662.SH'),
  ('瑞松科技', '688090.SH'),
  ('泽宇智能', '301179.SZ'),
  ('有方科技', '688159.SH'),
  ('巨能股份', '871478.BJ'),
  ('通力科技', '301255.SZ'),
  ('大烨智能', '300670.SZ'),
  ('睿能科技', '603933.SH'),
  ('兆威机电', '003021.SZ'),
  ('中科信息', '300678.SZ'),
  ('萤石网络', '688475.SH'),
  ('新华文轩', '0811.HK'),
  ('贝斯特', '300580.SZ'),
  ('盛通股份', '002599.SZ')],
 '高温导致甘蔗减产': [('南宁糖业', '000911.SZ')],
 '智能电网设备需求增加': [('众智科技', '301361.SZ'), ('迦南智能', '300880.SZ')],
 '政府IT建设': [('中科信息', '300678.SZ')],
 'AI+传媒': [('荣信文化', '301231.SZ'),
  ('山东出版', '601019.SH'),
  ('利欧股份', '002131.SZ'),
  ('中广天择', '603721.SH'),
  ('人民网', '603000.SH'),
  ('福昕软件', '688095.SH')],
 'AI+AR/VR/MR': [('清越科技', '688496.SH'),
  ('虹软科技', '688088.SH'),
  ('冠石科技', '605588.SH'),
  ('利通电子', '603629.SH'),
  ('利和兴', '301013.SZ'),
  ('天禄科技', '301045.SZ'),
  ('翔腾新材', '001373.SZ'),
  ('奥拓电子', '002587.SZ')],
 '中特估': [('重药控股', '000950.SZ')],
 '脑机接口技术': [('三博脑科', '301293.SZ'), ('奥精医疗', '688613.SH')],
 '生物制药': [('诺泰生物', '688076.SH')],
 '煤炭进口增加 ': [('浙能电力', '600023.SH'),
  ('京能电力', '600578.SH'),
  ('华能国际', '0902.HK')],
 '通信网络+6G': [('国盾量子', '688027.SH')],
 '国内旅游需求增加': [('九华旅游', '603199.SH')],
 '消费降级': [('小商品城', '600415.SH')]}

In [44]:
epics=jira.search_issues('project = WORLDEPICSTUDY AND summary ~ "AI+设计" ORDER BY created DESC')
epics[0]

In [56]:
issues=jira.search_issues(f'project = COMPSTUDY AND issuetype = 公司研究 AND summary ~光力科技')
issue=issues[0]
issue.fields.customfield_11412

In [65]:
issue

In [68]:
from atlassian import Jira
jira1 = Jira(
    url='https://research.quantumgalaxy.cn/',
    username='bot2',
    password='jira_bot2')
jira1.get_issue_changelog('COMPSTUDY-6435')['histories']

[{'id': '344613',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=bot',
   'name': 'bot',
   'key': 'JIRAUSER10200',
   'emailAddress': 'jira_bot@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://www.gravatar.com/avatar/3d75f49b419a66aa39f16798646dd968?d=mm&s=48',
    '24x24': 'https://www.gravatar.com/avatar/3d75f49b419a66aa39f16798646dd968?d=mm&s=24',
    '16x16': 'https://www.gravatar.com/avatar/3d75f49b419a66aa39f16798646dd968?d=mm&s=16',
    '32x32': 'https://www.gravatar.com/avatar/3d75f49b419a66aa39f16798646dd968?d=mm&s=32'},
   'displayName': '研究机器人',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-21T15:50:15.000+0800',
  'items': [{'field': 'Link',
    'fieldtype': 'jira',
    'from': None,
    'fromString': None,
    'to': 'POSITION-4432',
    'toString': 'This issue 指导交易 POSITION-4432'}]},
 {'id': '344615',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=bot2',
   'name': 'bot2',
   'key': 'JIRAUSER11415',
   'emailAddress': 'jira_bot2@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=48',
    '24x24': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=24',
    '16x16': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=16',
    '32x32': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=32'},
   'displayName': '指标机器人',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-21T15:50:17.000+0800',
  'items': [{'field': 'status',
    'fieldtype': 'jira',
    'from': '10001',
    'fromString': '退出',
    'to': '10101',
    'toString': '优选层'}]},
 {'id': '344624',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=bot2',
   'name': 'bot2',
   'key': 'JIRAUSER11415',
   'emailAddress': 'jira_bot2@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=48',
    '24x24': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=24',
    '16x16': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=16',
    '32x32': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=32'},
   'displayName': '指标机器人',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-21T15:52:48.000+0800',
  'items': [{'field': 'resolution',
    'fieldtype': 'jira',
    'from': None,
    'fromString': None,
    'to': '10101',
    'toString': 'Done'},
   {'field': 'status',
    'fieldtype': 'jira',
    'from': '10101',
    'fromString': '优选层',
    'to': '10001',
    'toString': '退出'}]},
 {'id': '345270',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=bot2',
   'name': 'bot2',
   'key': 'JIRAUSER11415',
   'emailAddress': 'jira_bot2@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=48',
    '24x24': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=24',
    '16x16': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=16',
    '32x32': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=32'},
   'displayName': '指标机器人',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-21T17:12:54.000+0800',
  'items': [{'field': '受世界线影响',
    'fieldtype': 'custom',
    'from': '',
    'fromString': None,
    'to': 'WORLDEPICSTUDY-166',
    'toString': '半导体划片机国产替代'}]},
 {'id': '348119',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=zhly05',
   'name': 'zhly05',
   'key': 'JIRAUSER10000',
   'emailAddress': 'zhanglingyu@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://research.quantumgalaxy.cn/secure/useravatar?ownerId=JIRAUSER10000&avatarId=10604',
    '24x24': 'https://research.quantumgalaxy.cn/secure/useravatar?size=small&ownerId=JIRAUSER10000&avatarId=10604',
    '16x16': 'https://research.quantumgalaxy.cn/secure/useravatar?size=xsmall&ownerId=JIRAUSER10000&avatarId=10604',
    '32x32': 'https://research.quantumgalaxy.cn/secure/useravatar?size=medium&ownerId=JIRAUSER10000&avatarId=10604'},
   'displayName': '张凌宇',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-24T20:24:23.000+0800',
  'items': [{'field': 'priority',
    'fieldtype': 'jira',
    'from': '5',
    'fromString': 'B（不可用）',
    'to': '10301',
    'toString': '跟随'}]},
 {'id': '349383',
  'author': {'self': 'https://research.quantumgalaxy.cn/rest/api/2/user?username=bot2',
   'name': 'bot2',
   'key': 'JIRAUSER11415',
   'emailAddress': 'jira_bot2@quantumgalaxy.cn',
   'avatarUrls': {'48x48': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=48',
    '24x24': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=24',
    '16x16': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=16',
    '32x32': 'https://www.gravatar.com/avatar/5147d02633be4fc81f14fdc76b8e6cbe?d=mm&s=32'},
   'displayName': '指标机器人',
   'active': True,
   'timeZone': 'Asia/Shanghai'},
  'created': '2023-06-26T20:25:02.000+0800',
  'items': [{'field': '受世界线影响',
    'fieldtype': 'custom',
    'from': 'WORLDEPICSTUDY-166',
    'fromString': '半导体划片机国产替代',
    'to': '',
    'toString': None}]}]

In [69]:
jira1.update_issue_field('COMPSTUDY-6435', {'customfield_11412':'WORLDEPICSTUDY-141'})

HTTPError: customfield_11412: Field 'customfield_11412' cannot be set. It is not on the appropriate screen, or unknown.

In [62]:
issue.update(customfield_11412=[epic])

TypeError: Object of type Issue is not JSON serializable

In [75]:
epic=jira.issue('WORLDEPICSTUDY-206')
epic.fields.customfield_11411

'COMPSTUDY-6655, COMPSTUDY-6580, COMPSTUDY-6585, COMPSTUDY-6596'

In [74]:
jira.fields()

[{'id': 'customfield_11441',
  'name': 'X值走廊参数',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11441]', 'X值走廊参数'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 11441}},
 {'id': 'fixVersions',
  'name': '修复的版本',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['fixVersion'],
  'schema': {'type': 'array', 'items': 'version', 'system': 'fixVersions'}},
 {'id': 'customfield_11440',
  'name': '发生地域',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11440]', '发生地域'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 11440}},
 {'id': 'customfield_11443',
  'name': '研究经验值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11443]', '研究经验值'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11443}},
 {'id': 'customfield_11200',
  'name': '组内停留时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11200]', '组内停留时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 11200}},
 {'id': 'resolution',
  'name': '解决结果',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['resolution'],
  'schema': {'type': 'resolution', 'system': 'resolution'}},
 {'id': 'customfield_11442',
  'name': '拟分配人员',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11442]', '拟分配人员'],
  'schema': {'type': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:userpicker',
   'customId': 11442}},
 {'id': 'customfield_11201',
  'name': '整体报告地址-废弃',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11201]', '整体报告地址-废弃'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11201}},
 {'id': 'customfield_11720',
  'name': '持仓价值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11720]', '持仓价值'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11720}},
 {'id': 'customfield_11202',
  'name': '资料包地址',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11202]', '资料包地址'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11202}},
 {'id': 'customfield_11203',
  'name': '紧迫性等级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11203]', '紧迫性等级'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-lexo-rank',
   'customId': 11203}},
 {'id': 'customfield_11711',
  'name': 'QG_Code',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11711]', 'QG_Code'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 11711}},
 {'id': 'customfield_10621',
  'name': '自动更新的近期市值均值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10621]', '自动更新的近期市值均值'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10621}},
 {'id': 'customfield_10104',
  'name': 'Sprint',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10104]', 'Sprint'],
  'schema': {'type': 'array',
   'items': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-sprint',
   'customId': 10104}},
 {'id': 'customfield_11436',
  'name': '逻辑简述',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11436]', '逻辑简述'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textarea',
   'customId': 11436}},
 {'id': 'customfield_11710',
  'name': 'C指标操作台',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11710]', 'C指标操作台'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-row-cf',
   'customId': 11710}},
 {'id': 'customfield_10622',
  'name': '未来情景日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10622]', '未来情景日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10622}},
 {'id': 'customfield_10105',
  'name': '等级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10105]', '等级'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-lexo-rank',
   'customId': 10105}},
 {'id': 'customfield_11713',
  'name': 'E指标值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11713]', 'E指标值'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 11713}},
 {'id': 'customfield_10623',
  'name': '预测目标日乐观市值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10623]', '预测目标日乐观市值'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10623}},
 {'id': 'customfield_10106',
  'name': 'Story Point',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10106]', 'Story Point'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10106}},
 {'id': 'customfield_11438',
  'name': '全情景年化收益倍数',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11438]', '全情景年化收益倍数'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11438}},
 {'id': 'customfield_11712',
  'name': 'T指标值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11712]', 'T指标值'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 11712}},
 {'id': 'customfield_10625',
  'name': '隐藏备注标记',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': [],
  'schema': {'type': 'any',
   'custom': 'de.stagil.jira.stagil-hide-comment:stagil-hide-comment-hideCommentCF',
   'customId': 10625}},
 {'id': 'customfield_10900',
  'name': '已标记',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10900]', '已标记'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 10900}},
 {'id': 'customfield_10626',
  'name': '最新预测',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10626]', '最新预测'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-wiki-text-field',
   'customId': 10626}},
 {'id': 'customfield_11439',
  'name': '可参会时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11439]', '可参会时间'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 11439}},
 {'id': 'customfield_11716',
  'name': '参会场次',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11716]', '参会场次'],
  'schema': {'type': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:radiobuttons',
   'customId': 11716}},
 {'id': 'customfield_10903',
  'name': '所在层级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10903]', '所在层级'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-single-select-field',
   'customId': 10903}},
 {'id': 'customfield_10508',
  'name': '所在市场',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10508]', '所在市场'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10508}},
 {'id': 'customfield_10629',
  'name': '缓存域',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10629]', '缓存域'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10629}},
 {'id': 'customfield_10904',
  'name': '特选层日期-废弃',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10904]', '特选层日期-废弃'],
  'schema': {'type': 'date',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-dateonly-field',
   'customId': 10904}},
 {'id': 'customfield_10509',
  'name': '纳入普通层时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10509]', '纳入普通层时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 10509}},
 {'id': 'customfield_10905',
  'name': '缓存文本',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10905]', '缓存文本'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10905}},
 {'id': 'lastViewed',
  'name': '最近查看的',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['lastViewed'],
  'schema': {'type': 'datetime', 'system': 'lastViewed'}},
 {'id': 'customfield_12000',
  'name': '指标操作台',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12000]', '指标操作台'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 12000}},
 {'id': 'customfield_12002',
  'name': '被反映',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12002]', '被反映'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 12002}},
 {'id': 'customfield_12001',
  'name': '反映',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12001]', '反映'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 12001}},
 {'id': 'priority',
  'name': '优先级',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['priority'],
  'schema': {'type': 'priority', 'system': 'priority'}},
 {'id': 'customfield_10100',
  'name': '史诗链接',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10100]', '史诗链接'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-link',
   'customId': 10100}},
 {'id': 'customfield_10101',
  'name': 'Epic状态',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10101]', 'Epic状态'],
  'schema': {'type': 'option',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-status',
   'customId': 10101}},
 {'id': 'customfield_11431',
  'name': '指标单位',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11431]', '指标单位'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textfield',
   'customId': 11431}},
 {'id': 'customfield_10102',
  'name': '史诗名称',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10102]', '史诗名称'],
  'schema': {'type': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-label',
   'customId': 10102}},
 {'id': 'customfield_10620',
  'name': '预测基准日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10620]', '预测基准日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10620}},
 {'id': 'customfield_10103',
  'name': 'Epic颜色',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10103]', 'Epic颜色'],
  'schema': {'type': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-color',
   'customId': 10103}},
 {'id': 'customfield_10610',
  'name': '市场情绪估计',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10610]', '市场情绪估计'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-single-select-field',
   'customId': 10610}},
 {'id': 'customfield_11303',
  'name': '情景贡献人',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11303]', '情景贡献人'],
  'schema': {'type': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:userpicker',
   'customId': 11303}},
 {'id': 'aggregatetimeoriginalestimate',
  'name': 'Σ 原预估时间',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': [],
  'schema': {'type': 'number', 'system': 'aggregatetimeoriginalestimate'}},
 {'id': 'customfield_10614',
  'name': '最新拆解详情',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10614]', '最新拆解详情'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10614}},
 {'id': 'timeestimate',
  'name': '剩余的估算',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['remainingEstimate', 'timeestimate'],
  'schema': {'type': 'number', 'system': 'timeestimate'}},
 {'id': 'customfield_11429',
  'name': '指标代码',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11429]', '指标代码'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textfield',
   'customId': 11429}},
 {'id': 'versions',
  'name': '影响版本',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['affectedVersion'],
  'schema': {'type': 'array', 'items': 'version', 'system': 'versions'}},
 {'id': 'customfield_11706',
  'name': '属于公司',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11706]', '属于公司'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11706}},
 {'id': 'customfield_11705',
  'name': '存在情景',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11705]', '存在情景'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11705}},
 {'id': 'customfield_11707',
  'name': '参与人',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11707]', '参与人'],
  'schema': {'type': 'array',
   'items': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multiuserpicker',
   'customId': 11707}},
 {'id': 'customfield_10619',
  'name': '纳入优选层时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10619]', '纳入优选层时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 10619}},
 {'id': 'issuelinks',
  'name': '链接的问题',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': [],
  'schema': {'type': 'array', 'items': 'issuelinks', 'system': 'issuelinks'}},
 {'id': 'assignee',
  'name': '经办人',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['assignee'],
  'schema': {'type': 'user', 'system': 'assignee'}},
 {'id': 'customfield_11709',
  'name': '星图截图',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11709]', '星图截图'],
  'schema': {'type': 'string',
   'custom': 'com.apwide.document.file-field:apwide-doc-field',
   'customId': 11709}},
 {'id': 'status',
  'name': '状态',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['status'],
  'schema': {'type': 'status', 'system': 'status'}},
 {'id': 'components',
  'name': '模块',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['component'],
  'schema': {'type': 'array', 'items': 'component', 'system': 'components'}},
 {'id': 'issuekey',
  'name': '关键字',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['id', 'issue', 'issuekey', 'key']},
 {'id': 'customfield_11300',
  'name': '预测目标日区间半径',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11300]', '预测目标日区间半径'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 11300}},
 {'id': 'customfield_11422',
  'name': '涉及骨干',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11422]', '涉及骨干'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11422}},
 {'id': 'customfield_11302',
  'name': '研究成果地址',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11302]', '研究成果地址'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11302}},
 {'id': 'customfield_11414',
  'name': '有子世界线',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11414]', '有子世界线'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11414}},
 {'id': 'customfield_10203',
  'name': '结论基准日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10203]', '结论基准日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10203}},
 {'id': 'customfield_10601',
  'name': '万得简称',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10601]', '万得简称'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10601}},
 {'id': 'customfield_10602',
  'name': '潜在问题',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10602]', '潜在问题'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10602}},
 {'id': 'customfield_11415',
  'name': '有父世界线',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,