In [3]:
import pandas as pd
from jira import JIRA

In [4]:
import sys
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import get_mysql
mysql=get_mysql()

In [5]:
df=pd.read_csv(r'E:\wangzhilin\QuantumGalaxy\世界线_标的_标的全表.csv')
df=df[['公司名称','公司简述','相关世界线']]
df['code']=None
df

,公司名称,公司简述,相关世界线,code
0,光力科技,NaN,半导体划片机国产替代,None
1,拓荆科技,薄膜气象沉积设备,薄膜沉积设备国产化,None
2,北方华创,NaN,薄膜沉积设备国产化,None
3,微导纳米,“PECVD/ALD薄膜化学气相沉积设备”。同作为产业链上游，半导体设备的市场表现弱于数据中...,"薄膜沉积设备国产化,钙钛矿电池量产",None
4,茂莱光学,NaN,"光刻机国产化,前道检测设备国产化",None
...,...,...,...,...
397,汇洲智能,NaN,NaN,None
398,青云科技,NaN,NaN,None
399,小商品城,商业模式：商铺店租、跨境结算，Chinagood平台会员费等\n利润增长方式：更多商户入驻平...,"消费降级,人民币国际化",None
400,福昕软件,商业模式：PDF编辑器，海外版叫Foxit，占营收91%，分为年费149美元，99美元，79...,"数据重要性提升,AI+教育,AI+传媒",None
401,伟创电气,商业模式：低压变频器、伺服系统、PLC（可编程）\n利润增长方式：向机器人企业销售伺服系统\...,NaN,None

In [6]:
for i,r in df.iterrows():
    name=r['公司名称']
    sql='select code from ticker_info where name like "%%%s%%"'%name
    code=mysql.read_query(sql)
    if code:
        df.loc[i,'code']=code[0][0]
        pass
    else:
        print(name)

电科网安
中新塞克
瑞普眼科
遥望科技
百纳千成
三五互联
晶盛电机
固高科技
新松机器人
沈阳机床
乐凯新材
赛为智能
台海核电
奥雅股份
和林微钠
北京文化
兆龙互联
汇洲智能

In [37]:
df.loc[df[df['公司名称']=='汇洲智能'].index,'公司名称']='ST天马'

In [46]:
df.dropna(subset=['code'],inplace=True)

df

     公司名称                                               公司简述       code
0    光力科技                                                NaN  300480.SZ
1    拓荆科技                                           薄膜气象沉积设备  688072.SH
2    北方华创                                                NaN  002371.SZ
3    微导纳米  “PECVD/ALD薄膜化学气相沉积设备”。同作为产业链上游，半导体设备的市场表现弱于数据中...  688147.SH
4    茂莱光学                                                NaN  688502.SH
..    ...                                                ...        ...
397  ST天马                                                NaN  002122.SZ
398  青云科技                                                NaN  688316.SH
399  小商品城  商业模式：商铺店租、跨境结算，Chinagood平台会员费等\n利润增长方式：更多商户入驻平...  600415.SH
400  福昕软件  商业模式：PDF编辑器，海外版叫Foxit，占营收91%，分为年费149美元，99美元，79...  688095.SH
401  伟创电气  商业模式：低压变频器、伺服系统、PLC（可编程）\n利润增长方式：向机器人企业销售伺服系统\...  688698.SH

[401 rows x 3 columns]

In [1]:
import numpy as np
type(df.iloc[400,1])

NameError: name 'df' is not defined

In [9]:
jira.fields()

[{'id': 'customfield_11441',
  'name': 'X值走廊参数',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11441]', 'X值走廊参数'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 11441}},
 {'id': 'fixVersions',
  'name': '修复的版本',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['fixVersion'],
  'schema': {'type': 'array', 'items': 'version', 'system': 'fixVersions'}},
 {'id': 'customfield_11440',
  'name': '发生地域',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11440]', '发生地域'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 11440}},
 {'id': 'customfield_11443',
  'name': '研究经验值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11443]', '研究经验值'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11443}},
 {'id': 'customfield_11200',
  'name': '组内停留时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11200]', '组内停留时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 11200}},
 {'id': 'resolution',
  'name': '解决结果',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['resolution'],
  'schema': {'type': 'resolution', 'system': 'resolution'}},
 {'id': 'customfield_11442',
  'name': '拟分配人员',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11442]', '拟分配人员'],
  'schema': {'type': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:userpicker',
   'customId': 11442}},
 {'id': 'customfield_11201',
  'name': '整体报告地址-废弃',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11201]', '整体报告地址-废弃'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11201}},
 {'id': 'customfield_11720',
  'name': '持仓价值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11720]', '持仓价值'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11720}},
 {'id': 'customfield_11202',
  'name': '资料包地址',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11202]', '资料包地址'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11202}},
 {'id': 'customfield_11203',
  'name': '紧迫性等级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11203]', '紧迫性等级'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-lexo-rank',
   'customId': 11203}},
 {'id': 'customfield_11711',
  'name': 'QG_Code',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11711]', 'QG_Code'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 11711}},
 {'id': 'customfield_10621',
  'name': '自动更新的近期市值均值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10621]', '自动更新的近期市值均值'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10621}},
 {'id': 'customfield_10104',
  'name': 'Sprint',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10104]', 'Sprint'],
  'schema': {'type': 'array',
   'items': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-sprint',
   'customId': 10104}},
 {'id': 'customfield_11436',
  'name': '逻辑简述',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11436]', '逻辑简述'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textarea',
   'customId': 11436}},
 {'id': 'customfield_11710',
  'name': 'C指标操作台',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11710]', 'C指标操作台'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-row-cf',
   'customId': 11710}},
 {'id': 'customfield_10622',
  'name': '未来情景日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10622]', '未来情景日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10622}},
 {'id': 'customfield_10105',
  'name': '等级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10105]', '等级'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-lexo-rank',
   'customId': 10105}},
 {'id': 'customfield_11713',
  'name': 'E指标值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11713]', 'E指标值'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 11713}},
 {'id': 'customfield_10623',
  'name': '预测目标日乐观市值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10623]', '预测目标日乐观市值'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10623}},
 {'id': 'customfield_10106',
  'name': 'Story Point',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10106]', 'Story Point'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 10106}},
 {'id': 'customfield_11438',
  'name': '全情景年化收益倍数',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11438]', '全情景年化收益倍数'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-number-field',
   'customId': 11438}},
 {'id': 'customfield_11712',
  'name': 'T指标值',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11712]', 'T指标值'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 11712}},
 {'id': 'customfield_10625',
  'name': '隐藏备注标记',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': [],
  'schema': {'type': 'any',
   'custom': 'de.stagil.jira.stagil-hide-comment:stagil-hide-comment-hideCommentCF',
   'customId': 10625}},
 {'id': 'customfield_10900',
  'name': '已标记',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10900]', '已标记'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 10900}},
 {'id': 'customfield_10626',
  'name': '最新预测',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10626]', '最新预测'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-wiki-text-field',
   'customId': 10626}},
 {'id': 'customfield_11439',
  'name': '可参会时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11439]', '可参会时间'],
  'schema': {'type': 'array',
   'items': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes',
   'customId': 11439}},
 {'id': 'customfield_11716',
  'name': '参会场次',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11716]', '参会场次'],
  'schema': {'type': 'option',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:radiobuttons',
   'customId': 11716}},
 {'id': 'customfield_10903',
  'name': '所在层级',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10903]', '所在层级'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-single-select-field',
   'customId': 10903}},
 {'id': 'customfield_10508',
  'name': '所在市场',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10508]', '所在市场'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10508}},
 {'id': 'customfield_10629',
  'name': '缓存域',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10629]', '缓存域'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10629}},
 {'id': 'customfield_10904',
  'name': '特选层日期-废弃',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10904]', '特选层日期-废弃'],
  'schema': {'type': 'date',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-dateonly-field',
   'customId': 10904}},
 {'id': 'customfield_10509',
  'name': '纳入普通层时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10509]', '纳入普通层时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 10509}},
 {'id': 'customfield_10905',
  'name': '缓存文本',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10905]', '缓存文本'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10905}},
 {'id': 'lastViewed',
  'name': '最近查看的',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['lastViewed'],
  'schema': {'type': 'datetime', 'system': 'lastViewed'}},
 {'id': 'customfield_12000',
  'name': '指标操作台',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12000]', '指标操作台'],
  'schema': {'type': 'string',
   'custom': 'com.keplerrominfo.jira.plugins.databasecf:anova-database-table-cf',
   'customId': 12000}},
 {'id': 'customfield_12002',
  'name': '被反映',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12002]', '被反映'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 12002}},
 {'id': 'customfield_12001',
  'name': '反映',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[12001]', '反映'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 12001}},
 {'id': 'priority',
  'name': '优先级',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['priority'],
  'schema': {'type': 'priority', 'system': 'priority'}},
 {'id': 'customfield_10100',
  'name': '史诗链接',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10100]', '史诗链接'],
  'schema': {'type': 'any',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-link',
   'customId': 10100}},
 {'id': 'customfield_10101',
  'name': 'Epic状态',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10101]', 'Epic状态'],
  'schema': {'type': 'option',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-status',
   'customId': 10101}},
 {'id': 'customfield_11431',
  'name': '指标单位',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11431]', '指标单位'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textfield',
   'customId': 11431}},
 {'id': 'customfield_10102',
  'name': '史诗名称',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10102]', '史诗名称'],
  'schema': {'type': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-label',
   'customId': 10102}},
 {'id': 'customfield_10620',
  'name': '预测基准日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10620]', '预测基准日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10620}},
 {'id': 'customfield_10103',
  'name': 'Epic颜色',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10103]', 'Epic颜色'],
  'schema': {'type': 'string',
   'custom': 'com.pyxis.greenhopper.jira:gh-epic-color',
   'customId': 10103}},
 {'id': 'customfield_10610',
  'name': '市场情绪估计',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10610]', '市场情绪估计'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-single-select-field',
   'customId': 10610}},
 {'id': 'customfield_11303',
  'name': '情景贡献人',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11303]', '情景贡献人'],
  'schema': {'type': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:userpicker',
   'customId': 11303}},
 {'id': 'aggregatetimeoriginalestimate',
  'name': 'Σ 原预估时间',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': [],
  'schema': {'type': 'number', 'system': 'aggregatetimeoriginalestimate'}},
 {'id': 'customfield_10614',
  'name': '最新拆解详情',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10614]', '最新拆解详情'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10614}},
 {'id': 'timeestimate',
  'name': '剩余的估算',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['remainingEstimate', 'timeestimate'],
  'schema': {'type': 'number', 'system': 'timeestimate'}},
 {'id': 'customfield_11429',
  'name': '指标代码',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11429]', '指标代码'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:textfield',
   'customId': 11429}},
 {'id': 'versions',
  'name': '影响版本',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['affectedVersion'],
  'schema': {'type': 'array', 'items': 'version', 'system': 'versions'}},
 {'id': 'customfield_11706',
  'name': '属于公司',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11706]', '属于公司'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11706}},
 {'id': 'customfield_11705',
  'name': '存在情景',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11705]', '存在情景'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11705}},
 {'id': 'customfield_11707',
  'name': '参与人',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11707]', '参与人'],
  'schema': {'type': 'array',
   'items': 'user',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:multiuserpicker',
   'customId': 11707}},
 {'id': 'customfield_10619',
  'name': '纳入优选层时间',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10619]', '纳入优选层时间'],
  'schema': {'type': 'number',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-duration-field',
   'customId': 10619}},
 {'id': 'issuelinks',
  'name': '链接的问题',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': [],
  'schema': {'type': 'array', 'items': 'issuelinks', 'system': 'issuelinks'}},
 {'id': 'assignee',
  'name': '经办人',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['assignee'],
  'schema': {'type': 'user', 'system': 'assignee'}},
 {'id': 'customfield_11709',
  'name': '星图截图',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11709]', '星图截图'],
  'schema': {'type': 'string',
   'custom': 'com.apwide.document.file-field:apwide-doc-field',
   'customId': 11709}},
 {'id': 'status',
  'name': '状态',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['status'],
  'schema': {'type': 'status', 'system': 'status'}},
 {'id': 'components',
  'name': '模块',
  'custom': False,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['component'],
  'schema': {'type': 'array', 'items': 'component', 'system': 'components'}},
 {'id': 'issuekey',
  'name': '关键字',
  'custom': False,
  'orderable': False,
  'navigable': True,
  'searchable': False,
  'clauseNames': ['id', 'issue', 'issuekey', 'key']},
 {'id': 'customfield_11300',
  'name': '预测目标日区间半径',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11300]', '预测目标日区间半径'],
  'schema': {'type': 'number',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:float',
   'customId': 11300}},
 {'id': 'customfield_11422',
  'name': '涉及骨干',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11422]', '涉及骨干'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11422}},
 {'id': 'customfield_11302',
  'name': '研究成果地址',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11302]', '研究成果地址'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:url',
   'customId': 11302}},
 {'id': 'customfield_11414',
  'name': '有子世界线',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[11414]', '有子世界线'],
  'schema': {'type': 'array',
   'custom': 'de.stagil.jira.stagil-assets:stagil-assets-relation',
   'customId': 11414}},
 {'id': 'customfield_10203',
  'name': '结论基准日',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10203]', '结论基准日'],
  'schema': {'type': 'date',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:datepicker',
   'customId': 10203}},
 {'id': 'customfield_10601',
  'name': '万得简称',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10601]', '万得简称'],
  'schema': {'type': 'string',
   'custom': 'com.atlassian.jira.plugin.system.customfieldtypes:readonlyfield',
   'customId': 10601}},
 {'id': 'customfield_10602',
  'name': '潜在问题',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,
  'clauseNames': ['cf[10602]', '潜在问题'],
  'schema': {'type': 'any',
   'custom': 'com.innovalog.jmcf.jira-misc-custom-fields:calculated-text-field',
   'customId': 10602}},
 {'id': 'customfield_11415',
  'name': '有父世界线',
  'custom': True,
  'orderable': True,
  'navigable': True,
  'searchable': True,

In [13]:
jira=JIRA('https://research.quantumgalaxy.cn/', basic_auth=('bot2', "jira_bot2"))
issues=jira.search_issues(f'project = COMPSTUDY AND issuetype = 公司研究 AND 万得代码 =300480.SZ')
issues

In [14]:
i=issues[0]

In [15]:
i.fields.customfield_11412

'WORLDEPICSTUDY-166'

In [19]:
epic=jira.issue('WORLDEPICSTUDY-166')
epic.fields.summary

'半导体划片机国产替代'

In [49]:
import time

In [64]:
for i,r in df.iterrows():
    
        try:
            issues=jira.search_issues('project = COMPSTUDY AND issuetype = 公司研究 AND 万得代码 = %s'%r['code'])
            if issues:
                issue=issues[0]
            else:
                
                issue=jira.create_issue(fields={'issuetype':{'id':10100},'project':{'id':10000},'summary':r['公司名称'],'customfield_10201':r['code']})
            #if issue.fields.status.id=='10001':
                #jira.transition_issue(issue,311)
            if type(r['公司简述'])==str:
                issue.update(fields={'description':r['公司简述']})
            print(issue.fields.summary)
        except Exception as e:
            print('falied!!%s'%r['公司名称'],e)
        #time.sleep(0.5)

丰立智能

In [23]:
issue=issues[0]
issue.fields.status

In [54]:
issue.fields.status.id=='10101'

True

In [32]:
issue.fields.__dict__

{'customfield_11441': '2.39, 0.37, 2024-01-16',
 'customfield_11200': None,
 'customfield_11443': 0.0324165167422098,
 'resolution': None,
 'customfield_11201': None,
 'customfield_11442': None,
 'customfield_11202': None,
 'customfield_11203': '0|i004pr:',
 'customfield_10621': 271.886,
 'customfield_10104': None,
 'customfield_11436': None,
 'customfield_10622': '2024-01-16',
 'customfield_10105': '1|i00f7b:',
 'customfield_10623': None,
 'customfield_11438': -1.270361762805744,
 'customfield_10625': None,
 'customfield_10900': None,
 'customfield_10626': '尚无预测',
 'customfield_11439': None,
 'customfield_10903': '普通层',
 'customfield_11716': None,
 'customfield_10508': 'A股（沪）',
 'customfield_10904': None,
 'customfield_10509': None,
 'customfield_10905': None,
 'lastViewed': '2023-06-14T15:44:23.073+0800',
 'priority': <JIRA Priority: name='B', id='5'>,
 'customfield_10100': None,
 'customfield_10620': None,
 'customfield_10610': '正常',
 'customfield_11303': None,
 'customfield_10614': '2022-09-19, 276.0, 3.01',
 'aggregatetimeoriginalestimate': None,
 'timeestimate': None,
 'customfield_11706': None,
 'customfield_11705': 'SCENARIO-1104',
 'customfield_10619': None,
 'issuelinks': [],
 'customfield_11709': None,
 'assignee': None,
 'status': <JIRA Status: name='优选层', id='10101'>,
 'customfield_11300': None,
 'customfield_11302': None,
 'customfield_10203': '2023-03-16',
 'customfield_10601': None,
 'customfield_10602': None,
 'aggregatetimeestimate': None,
 'creator': <JIRA User: displayName='万小滔', key='JIRAUSER10213', name='wanxiaotao'>,
 'subtasks': [<JIRA Issue: key='COMPSTUDY-6403', id='29512'>],
 'reporter': <JIRA User: displayName='张凌宇', key='JIRAUSER10000', name='zhly05'>,
 'aggregateprogress': <jira.resources.PropertyHolder at 0x1dfc8fb44c0>,
 'customfield_10201': '688256.SH',
 'customfield_11412': 'WORLDEPICSTUDY-155, WORLDEPICSTUDY-175',
 'customfield_11411': None,
 'customfield_11403': None,
 'customfield_11402': None,
 'customfield_11405': None,
 'customfield_11800': <JIRA CustomFieldOption: value='C-不太确定', id='11203'>,
 'customfield_11803': "<table class='aui'><tr><th>date</th><th>收盘</th><th>成交量</th><th>总市值</th><th>月涨幅(%)</th><th>波动率</th><th>月标幅(%)</th><th>季标幅(%)</th></tr><tr><td>2023-06-13</td><td>232.90</td><td>12729925</td><td>970.0</td><td>18.83</td><td>7.79</td><td>40.42</td><td>109.1</td></tr></table>",
 'progress': <jira.resources.PropertyHolder at 0x1dfc8fb4c40>,
 'votes': <JIRA Votes: votes=0>,
 'worklog': <jira.resources.PropertyHolder at 0x1dfc8fb41c0>,
 'issuetype': <JIRA IssueType: name='公司研究', id='10100'>,
 'timespent': None,
 'project': <JIRA Project: key='COMPSTUDY', name='研究管理项目', id='10000'>,
 'customfield_11000': 'https://quantumgalaxy.feishu.cn/drive/folder/fldcn2pcjLaevYVXffGbTAExVF1',
 'customfield_11001': None,
 'customfield_11002': None,
 'aggregatetimespent': None,
 'customfield_11003': <JIRA CustomFieldOption: value='正常', id='10602'>,
 'customfield_11005': '2021-08-27T12:55:26.000+0800',
 'customfield_10302': '2023-06-13',
 'customfield_10700': None,
 'customfield_10701': None,
 'customfield_10702': None,
 'customfield_10703': None,
 'customfield_10704': None,
 'resolutiondate': None,
 'workratio': -1,
 'watches': <JIRA Watchers at 2060513269792>,
 'created': '2021-08-27T12:55:26.000+0800',
 'customfield_11105': None,
 'customfield_11502': None,
 'customfield_10930': '{}',
 'customfield_11106': None,
 'customfield_11107': None,
 'customfield_11900': None,
 'customfield_10932': None,
 'customfield_11108': '2023-06-13 ~ 2024-01-16<br>21.66 ~ [7.99, 10.91, 14.9]<br>970.0 ~ [369.02, 503.9, 688.09]',
 'customfield_10933': None,
 'updated': '2023-06-14T15:44:54.000+0800',
 'timeoriginalestimate': None,
 'description': '商业模式：云端算力服务、计算集群\n利润增长方式：大模型训练带来算力需求，英伟达被限制向中国提供高端算力卡\n涨前市值：420亿（2023年3月）\n当前市值：951亿\n涨幅量化：500亿 = 10亿相信年化回报 = （年销售40万套思元芯片 * 每套售价十万）*60%毛利润 - 年研发投入15万',
 'customfield_11220': None,
 'customfield_11100': <JIRA User: displayName='吴宇杰', key='JIRAUSER10847', name='wuyujie'>,
 'customfield_11101': None,
 'customfield_11102': '1.上次做出的预测近端情况：无此前预测<br>\n2.自动更新的市场近端情况：271.886 ± 57.568 on 2022-04-30<br>\n',
 'timetracking': <JIRA TimeTracking at 2060661754848>,
 'customfield_11104': None,
 'customfield_11215': None,
 'customfield_11216': None,
 'customfield_11217': None,
 'customfield_11218': None,
 'attachment': [],
 'customfield_11219': 0.062,
 'customfield_10928': 57.568,
 'customfield_10929': None,
 'summary': '寒武纪-U',
 'customfield_10000': '{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@1e3a7f48[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@5d9826ce[overall=PullRequestOverallBean{stateCount=0, state=\'OPEN\', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@60fe43bd[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@7c4cb73a[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@60ca6647[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@50c25ba3[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@42b319ad[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@5b5f93a6[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@68142ed4[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@2a497f36[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@706d75a3[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@57881aab[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={"cachedValue":{"errors":[],"configErrors":[],"summary":{"pullrequest":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":"OPEN","details":{"openCount":0,"mergedCount":0,"declinedCount":0,"total":0},"open":true},"byInstanceType":{}},"build":{"overall":{"count":0,"lastUpdated":null,"failedBuildCount":0,"successfulBuildCount":0,"unknownBuildCount":0},"byInstanceType":{}},"review":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":null,"dueDate":null,"overDue":false,"completed":false},"byInstanceType":{}},"deployment-environment":{"overall":{"count":0,"lastUpdated":null,"topEnvironments":[],"showProjects":false,"successfulCount":0},"byInstanceType":{}},"repository":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}},"branch":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}}}},"isStale":false}}',
 'customfield_11210': None,
 'customfield_11211': None,
 'customfield_11212': None,
 'customfield_11214': None,
 'customfield_11204': None,
 'customfield_11722': 40.42,
 'customfield_11721': None,
 'customfield_11206': <JIRA CustomFieldOption: value='M=Xn+A模式', id='10800'>,
 'customfield_10636': None,
 'customfield_11208': None,
 'customfield_11209': None,
 'duedate': None,
 'customfield_10914': 0.8,
 'customfield_10915': None,
 'customfield_10916': 8.0,
 'comment': <jira.resources.PropertyHolder at 0x1dfc9030c70>,
 'customfield_10918': 15.0,
 'customfield_10919': 0.2}

In [47]:
r=jira.create_issue(fields={'issuetype':{'id':10100},'project':{'id':10000},'summary':df.loc[0,'公司名称'],'customfield_10201':df.loc[0,'code']})
r

In [49]:
r.update(fields={'description':df.loc[0,'公司简述']})
jira.transition_issue(r,311)

{}

In [31]:
issue.update(fields={'description':df.loc[1,'公司简述']})

In [26]:
jira.find_transitionid_by_name(issue,'进行关注')
jira.transition_issue(issue,311)

{}

In [9]:
for i,r in df.iterrows():
    name=r['公司名称']
    sql='select code from ticker_info where name like "%%%s%%"'%name
    print(sql)
    break

select code from ticker_info where name like "%微导纳米%"

In [32]:
issues=jira.search_issues(jql_str='project = COMPSTUDY AND text ~ "%s"'%'000301.SZ')
issues

In [35]:
issue.fields.__dict__

{'customfield_11441': None,
 'customfield_11200': None,
 'resolution': None,
 'customfield_11201': None,
 'customfield_11442': None,
 'customfield_11202': None,
 'customfield_11720': None,
 'customfield_11203': '0|i00cyf:',
 'customfield_10621': 906.449,
 'customfield_10104': None,
 'customfield_11436': None,
 'customfield_10622': None,
 'customfield_10105': '1|hzzqi0:i',
 'customfield_10623': None,
 'customfield_11438': None,
 'customfield_10625': None,
 'customfield_10900': None,
 'customfield_10626': '预测基准日：2021-06-03，市值区间是 781 ± 154\n预测目标日：2024-06-03，市值区间是 1805 ± 610，\n预测原因：按每个产品新增后总产能*价格预测\nhttp://cloudapp.quantumgalaxy.cn/?stockcode=000301.SZ',
 'customfield_11439': None,
 'customfield_10903': '尚未纳入',
 'customfield_10508': 'A股（深）',
 'customfield_10904': None,
 'customfield_10509': 54950400.0,
 'customfield_10905': '初步',
 'lastViewed': None,
 'priority': <JIRA Priority: name='B', id='5'>,
 'customfield_10100': None,
 'customfield_10620': None,
 'customfield_11303': None,
 'customfield_10614': '2022-08-18, 1537.0, 4.0',
 'aggregatetimeoriginalestimate': None,
 'timeestimate': None,
 'customfield_11703': '{"rows":[["2022-11-24","13.62","25678553","846.0","1.04","3.09","6.11"]],"ts":1669359305148,"rowNo":1}',
 'customfield_11706': None,
 'customfield_11705': 'SCENARIO-282',
 'customfield_11708': None,
 'customfield_10619': None,
 'issuelinks': [<JIRA IssueLink: id='13350'>, <JIRA IssueLink: id='25603'>],
 'customfield_11709': None,
 'assignee': None,
 'status': <JIRA Status: name='关注中', id='10903'>,
 'customfield_11300': None,
 'customfield_11302': None,
 'customfield_10601': None,
 'customfield_10602': None,
 'aggregatetimeestimate': None,
 'creator': <JIRA User: displayName='潘思昂', key='JIRAUSER10206', name='pansiang'>,
 'subtasks': [],
 'reporter': <JIRA User: displayName='张凌宇', key='JIRAUSER10000', name='zhly05'>,
 'aggregateprogress': <jira.resources.PropertyHolder at 0x29c9b361220>,
 'customfield_10201': '000301.SZ',
 'customfield_11412': None,
 'customfield_11411': None,
 'customfield_11403': None,
 'customfield_11402': None,
 'customfield_11405': None,
 'customfield_11800': None,
 'progress': <jira.resources.PropertyHolder at 0x29c9b3611c0>,
 'votes': <JIRA Votes: votes=0>,
 'issuetype': <JIRA IssueType: name='公司研究', id='10100'>,
 'timespent': None,
 'project': <JIRA Project: key='COMPSTUDY', name='研究管理项目', id='10000'>,
 'customfield_11000': 'https://quantumgalaxy.feishu.cn/drive/folder/fldcnfo2jF01onHrEFG921Y2suf',
 'customfield_11001': None,
 'customfield_11002': None,
 'aggregatetimespent': None,
 'customfield_11003': <JIRA CustomFieldOption: value='冷淡', id='10603'>,
 'customfield_11005': '2022-09-08T15:20:46.000+0800',
 'customfield_10700': None,
 'customfield_10701': None,
 'customfield_10702': None,
 'customfield_10703': None,
 'customfield_10704': None,
 'resolutiondate': None,
 'workratio': -1,
 'watches': <JIRA Watchers at 2871642166896>,
 'created': '2020-11-17T19:21:30.000+0800',
 'customfield_11105': None,
 'customfield_11502': None,
 'customfield_10930': "{'baseDate':'2021-06-03','baseEvMid':780.565,'baseEvRadius':153.913,'targetDate':'2024-06-03','targetEvMid':1804.5,'targetEvRadius':609.5,'reason':'按每个产品新增后总产能*价格预测'}",
 'customfield_11106': '2021-09-14',
 'customfield_11107': None,
 'customfield_11108': None,
 'customfield_10933': None,
 'updated': '2022-09-21T19:18:47.000+0800',
 'timeoriginalestimate': None,
 'description': '*走廊研究：*\r\n纵向一体化，向上游扩张+横向扩张、收购资产+下游需求恢复，产品价格增长。结论：维持在普通层。\r\n*补充报告：*\r\n国产替代增强需求的长期成长趋势和空间+光伏EVA树脂环节兼具周期和成长属性。结论：维持在普通层。',
 'customfield_11220': None,
 'customfield_11100': None,
 'customfield_11101': None,
 'customfield_11102': '1.上次做出的预测近端情况：780.565 ± 153.913 on 2021-06-03<br>\n2.自动更新的市场近端情况：906.449 ± 156.267 on 2022-04-30<br>\n',
 'customfield_11104': None,
 'customfield_11215': None,
 'customfield_11216': None,
 'customfield_11217': None,
 'customfield_11218': None,
 'customfield_11219': None,
 'customfield_10928': 156.267,
 'customfield_10929': None,
 'summary': '东方盛虹',
 'customfield_10000': '{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@5ca3220a[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@1675d1c6[overall=PullRequestOverallBean{stateCount=0, state=\'OPEN\', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3e7ca5d9[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@63fa831[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@4c37943f[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@64cb3292[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3fc211bf[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@44475856[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3421aa8d[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@9c34139[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2623e657[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@58d89f2d[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={"cachedValue":{"errors":[],"configErrors":[],"summary":{"pullrequest":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":"OPEN","details":{"openCount":0,"mergedCount":0,"declinedCount":0,"total":0},"open":true},"byInstanceType":{}},"build":{"overall":{"count":0,"lastUpdated":null,"failedBuildCount":0,"successfulBuildCount":0,"unknownBuildCount":0},"byInstanceType":{}},"review":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":null,"dueDate":null,"overDue":false,"completed":false},"byInstanceType":{}},"deployment-environment":{"overall":{"count":0,"lastUpdated":null,"topEnvironments":[],"showProjects":false,"successfulCount":0},"byInstanceType":{}},"repository":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}},"branch":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}}}},"isStale":false}}',
 'customfield_11210': None,
 'customfield_11211': None,
 'customfield_11212': '2022-09-08T15:20:46.000+0800',
 'customfield_11214': '2022-01-11T00:26:00.000+0800',
 'customfield_11204': None,
 'customfield_11722': 1.04,
 'customfield_11721': None,
 'customfield_11206': None,
 'customfield_10636': '2022-09-08T15:20:46.000+0800',
 'customfield_11208': '2021-04-16T14:56:40.000+0800',
 'customfield_11209': None,
 'duedate': None,
 'customfield_10914': None,
 'customfield_10915': None,
 'customfield_10916': None,
 'customfield_10918': None,
 'customfield_10919': 0.152}

In [41]:
new=jira.create_issue(fields={'project':'10000','issuetype':'公司研究','summary':'jira创建测试','customfield_10201':'321321.SZ',})
new

In [10]:
issue=issues[0]

In [24]:
issue.key

'COMPSTUDY-454'

In [58]:
res=[]

In [59]:
for i,r in df.iterrows():
    code=r['代码']
    issues=jira.search_issues(jql_str='project = COMPSTUDY AND issuetype = 公司研究 AND text ~ "%s"'%code)
    if len(issues)==0:
        res.append('未找到')
    elif len(issues)==1:
        res.append(issues[0].key)
    else:

        res.append(str([issue.key for issue in issues]))
res

['COMPSTUDY-2306',
 'COMPSTUDY-5281',
 'COMPSTUDY-5375',
 'COMPSTUDY-5578',
 'COMPSTUDY-5207',
 'COMPSTUDY-2581',
 'COMPSTUDY-5709',
 'COMPSTUDY-5157',
 'COMPSTUDY-5622',
 'COMPSTUDY-5156',
 'COMPSTUDY-5710',
 'COMPSTUDY-1829',
 'COMPSTUDY-122',
 'COMPSTUDY-5711',
 'COMPSTUDY-5645',
 'COMPSTUDY-5293',
 'COMPSTUDY-5630',
 'COMPSTUDY-5123',
 'COMPSTUDY-5712',
 'COMPSTUDY-5713',
 'COMPSTUDY-1755',
 'COMPSTUDY-669',
 'COMPSTUDY-5687',
 'COMPSTUDY-2433',
 'COMPSTUDY-5507',
 'COMPSTUDY-5714',
 'COMPSTUDY-5614',
 'COMPSTUDY-5647',
 'COMPSTUDY-2221',
 'COMPSTUDY-5715',
 'COMPSTUDY-5716',
 'COMPSTUDY-5646',
 'COMPSTUDY-2325',
 'COMPSTUDY-5717',
 'COMPSTUDY-5718',
 'COMPSTUDY-5719',
 'COMPSTUDY-5720',
 'COMPSTUDY-5721',
 'COMPSTUDY-66',
 'COMPSTUDY-891',
 'COMPSTUDY-1891',
 'COMPSTUDY-5691',
 'COMPSTUDY-5615',
 'COMPSTUDY-5722',
 'COMPSTUDY-5723',
 'COMPSTUDY-4728',
 'COMPSTUDY-5651',
 'COMPSTUDY-5654',
 'COMPSTUDY-1623',
 'COMPSTUDY-5705',
 'COMPSTUDY-5724',
 'COMPSTUDY-1904',
 'COMPSTUDY-5725',
 'COMPSTUDY-5596',
 'COMPSTUDY-5726',
 'COMPSTUDY-5638',
 'COMPSTUDY-2045',
 'COMPSTUDY-5727',
 'COMPSTUDY-4392',
 'COMPSTUDY-5728',
 'COMPSTUDY-5690',
 'COMPSTUDY-2566',
 'COMPSTUDY-5729',
 'COMPSTUDY-5730',
 'COMPSTUDY-2380',
 'COMPSTUDY-5731',
 'COMPSTUDY-5732',
 'COMPSTUDY-5689',
 'COMPSTUDY-5700',
 'COMPSTUDY-5733',
 'COMPSTUDY-2166',
 'COMPSTUDY-5734',
 'COMPSTUDY-2126',
 'COMPSTUDY-5656',
 'COMPSTUDY-5319',
 'COMPSTUDY-5735',
 'COMPSTUDY-2544',
 'COMPSTUDY-1917',
 'COMPSTUDY-5125',
 'COMPSTUDY-5474',
 'COMPSTUDY-5641',
 'COMPSTUDY-5736',
 'COMPSTUDY-218',
 'COMPSTUDY-5737',
 'COMPSTUDY-5738',
 'COMPSTUDY-4903',
 'COMPSTUDY-5668',
 'COMPSTUDY-4790',
 'COMPSTUDY-21',
 'COMPSTUDY-2355',
 'COMPSTUDY-5333',
 'COMPSTUDY-2211',
 'COMPSTUDY-5477',
 'COMPSTUDY-5696',
 'COMPSTUDY-5739',
 'COMPSTUDY-5740',
 'COMPSTUDY-1621',
 'COMPSTUDY-2371',
 'COMPSTUDY-5498',
 'COMPSTUDY-5707',
 'COMPSTUDY-5666',
 'COMPSTUDY-5648',
 'COMPSTUDY-5199',
 'COMPSTUDY-5698',
 'COMPSTUDY-5567',
 'COMPSTUDY-912',
 'COMPSTUDY-5741',
 'COMPSTUDY-1916',
 'COMPSTUDY-5742',
 'COMPSTUDY-5661',
 'COMPSTUDY-5693',
 'COMPSTUDY-5743',
 'COMPSTUDY-2598',
 'COMPSTUDY-5606',
 'COMPSTUDY-5635',
 'COMPSTUDY-2022',
 'COMPSTUDY-5694',
 'COMPSTUDY-5744',
 'COMPSTUDY-5745',
 'COMPSTUDY-5676',
 'COMPSTUDY-4398',
 'COMPSTUDY-5746',
 'COMPSTUDY-834',
 "['COMPSTUDY-63', 'COMPSTUDY-428', 'COMPSTUDY-2249', 'COMPSTUDY-218']",
 'COMPSTUDY-5747',
 'COMPSTUDY-718',
 'COMPSTUDY-5748',
 'COMPSTUDY-5749',
 'COMPSTUDY-5750',
 'COMPSTUDY-4391',
 'COMPSTUDY-5583',
 'COMPSTUDY-5575',
 'COMPSTUDY-5650',
 'COMPSTUDY-5649',
 'COMPSTUDY-5620',
 'COMPSTUDY-5751',
 'COMPSTUDY-5752',
 'COMPSTUDY-5753',
 'COMPSTUDY-5754',
 'COMPSTUDY-5665',
 'COMPSTUDY-117',
 'COMPSTUDY-5755',
 'COMPSTUDY-5660',
 'COMPSTUDY-5659',
 'COMPSTUDY-1881',
 'COMPSTUDY-5756',
 'COMPSTUDY-1928',
 'COMPSTUDY-2363',
 'COMPSTUDY-2129',
 'COMPSTUDY-5757',
 'COMPSTUDY-803',
 'COMPSTUDY-5173',
 'COMPSTUDY-5758',
 'COMPSTUDY-5759',
 'COMPSTUDY-4587',
 'COMPSTUDY-5697',
 'COMPSTUDY-5515',
 'COMPSTUDY-5222',
 'COMPSTUDY-5760',
 'COMPSTUDY-5692',
 'COMPSTUDY-5514',
 'COMPSTUDY-802',
 'COMPSTUDY-5455',
 'COMPSTUDY-2215',
 'COMPSTUDY-5597',
 'COMPSTUDY-5761',
 'COMPSTUDY-5762',
 'COMPSTUDY-1902',
 'COMPSTUDY-2348',
 'COMPSTUDY-5763',
 'COMPSTUDY-5302',
 'COMPSTUDY-5667',
 'COMPSTUDY-2138',
 'COMPSTUDY-2146',
 'COMPSTUDY-2147',
 'COMPSTUDY-751',
 'COMPSTUDY-5292',
 'COMPSTUDY-1869',
 'COMPSTUDY-5699',
 'COMPSTUDY-1938',
 'COMPSTUDY-5213',
 'COMPSTUDY-2270',
 'COMPSTUDY-5463',
 'COMPSTUDY-2162',
 'COMPSTUDY-5538',
 'COMPSTUDY-2127',
 'COMPSTUDY-2124',
 'COMPSTUDY-5655',
 'COMPSTUDY-5764',
 'COMPSTUDY-5765',
 'COMPSTUDY-5766',
 'COMPSTUDY-5767',
 'COMPSTUDY-5768',
 'COMPSTUDY-5769',
 'COMPSTUDY-5770',
 'COMPSTUDY-5771',
 'COMPSTUDY-5772',
 'COMPSTUDY-2445',
 'COMPSTUDY-4822',
 'COMPSTUDY-5773',
 'COMPSTUDY-5774',
 'COMPSTUDY-5194',
 'COMPSTUDY-5775',
 'COMPSTUDY-5776',
 'COMPSTUDY-5777',
 'COMPSTUDY-5778',
 'COMPSTUDY-5779',
 'COMPSTUDY-5780',
 'COMPSTUDY-93',
 'COMPSTUDY-530',
 'COMPSTUDY-454',
 'COMPSTUDY-5781',
 'COMPSTUDY-5782',
 'COMPSTUDY-2623',
 'COMPSTUDY-5783',
 'COMPSTUDY-1619',
 'COMPSTUDY-5784',
 'COMPSTUDY-5785',
 'COMPSTUDY-5786',
 'COMPSTUDY-5787',
 'COMPSTUDY-4140',
 'COMPSTUDY-2043',
 'COMPSTUDY-5788',
 'COMPSTUDY-5789',
 'COMPSTUDY-5662',
 'COMPSTUDY-5790',
 'COMPSTUDY-5791',
 'COMPSTUDY-5792',
 'COMPSTUDY-5793',
 'COMPSTUDY-5794',
 'COMPSTUDY-5371',
 'COMPSTUDY-5404',
 'COMPSTUDY-5795',
 'COMPSTUDY-5796',
 'COMPSTUDY-5797',
 'COMPSTUDY-5798',
 'COMPSTUDY-5799',
 'COMPSTUDY-5800',
 'COMPSTUDY-5801',
 'COMPSTUDY-5802',
 'COMPSTUDY-5733',
 'COMPSTUDY-5803',
 'COMPSTUDY-5804',
 'COMPSTUDY-5805',
 'COMPSTUDY-5806',
 'COMPSTUDY-2165',
 'COMPSTUDY-2168',
 'COMPSTUDY-5807',
 'COMPSTUDY-5808',
 'COMPSTUDY-256',
 'COMPSTUDY-5809',
 'COMPSTUDY-5446',
 'COMPSTUDY-5810',
 'COMPSTUDY-1780',
 'COMPSTUDY-5811',
 'COMPSTUDY-5812',
 'COMPSTUDY-5813',
 'COMPSTUDY-57',
 'COMPSTUDY-5814',
 'COMPSTUDY-224',
 'COMPSTUDY-2567',
 'COMPSTUDY-1814',
 'COMPSTUDY-1800',
 'COMPSTUDY-2282',
 'COMPSTUDY-687',
 'COMPSTUDY-5489']

'安进'

In [53]:
len(res)

107

In [49]:
import re,json
for r in res:
    r['summary']=r['summary'].strip()

In [50]:
res[:3]

[{'project': '10000',
  'issuetype': '公司研究',
  'summary': 'ST龙净',
  'customfield_10201': '600388.SH'},
 {'project': '10000',
  'issuetype': '公司研究',
  'summary': 'Teladoc Health',
  'customfield_10201': 'TDOC.N'},
 {'project': '10000',
  'issuetype': '公司研究',
  'summary': '安进',
  'customfield_10201': 'AMGN.O'}]

In [55]:
r=jira.create_issues(res[:1])
r.status

AttributeError: 'list' object has no attribute 'status'

In [57]:
r[0]['status']

'Error'

In [60]:
df1=pd.DataFrame(data=res,columns=['name'])
df1.to_excel('E:\wangzhilin\QuantumGalaxy\cache.xlsx')

In [21]:
!pip install openpyxl

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting openpyxl
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7b/60/9afac4fd6feee0ac09339de4101ee452ea643d26e9ce44c7708a0023f503/openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     -------------------------------------- 242.1/242.1 kB 4.9 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10

In [ ]:
jira.search_issues(max)