In [1]:
import sys
import requests
sys.path.append(r'E:\wangzhilin\QuantumGalaxy')
sys.path.append(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints')
from live_editor.models import bitable_works
import json
from QGI.feishu import base_fetch_func,fetch_tenant_token
from copy import deepcopy
bitapp_auth={'app_id':'cli_a1fc0a192db8100c','app_secret':'nNk1fT8h2eVi8B2ymIFangHTpYrOAJTD'}
import pandas as pd
def build_headers():
    
    token=fetch_tenant_token(bitapp_auth)
    #token='u-3atGsodiN9391_BlvmfeZh1kkwt5hlQxo0G0hgew2Ijc'
    headers = {
        'Authorization':
        'Bearer ' + token,  # your access token
        #'Content-Type': 'application/json; charset=utf-8'
    }
    return headers

In [2]:
import logging
def get_logger(name):
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    fh = logging.FileHandler(
        r"E:\wangzhilin\QuantumGalaxy\opt\combine_check\log\log.log",
        'a',
        encoding='utf-8')
    fh.setLevel(logging.INFO)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
        #fmt='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        fmt='%(levelname)-8s %(message)s',
        datefmt='%m-%d %H:%M')
    ch.setFormatter(formatter)
    fh.setFormatter(formatter)
    logger.addHandler(ch)
    logger.addHandler(fh)
    return logger
logger=get_logger('combine_check')

In [3]:
logger.warning('start')

WARNING  start

#### 将2个（多个？）骨干多维表格中的外骨干节点和关系抽出，进行对照，排除冲突和错误

规则：
1. 表格内外部节点/边是否都有外部骨干名字，外部骨干名字（只有写了外部骨干才是外部节点）
2. 表格内外部节点和边是否意义对应（表格内有外部节点的话，则至少有1条外部边从内部节点或其他外部节点连向该外部节点），存在不对应的点和边则加入error，该表不联查 另，外部节点连向外部节点的边和节点都warning，不参与检查和报错

3. 满足以上两条规则的表格可以参与联合检查，每张表每张表排除自身error和warning后生成n组外边（主主体关系客体）及其外骨干名
对m张表的外边匹配相应外骨干的外边，如果匹配失败则加入该表的错误外边，成功的一对外边成为星图边界

4. 对各个粗骨干的内部节点命名进行唯一性检查，如果重复则是可能的外部节点
4. 最终生成匹配成功的星图边界表和其他表的错误报告（节点和边不对应error，外边匹配失败error，多层2边warning）
5. 画图（原本的内容+正确的外点外边，但是点和边有重复,解决冲突后用cypher可以录入）

In [4]:
def append_df(df,new_row):
    '''["level","body","backbone",""rough"]'''
    df=pd.concat((df,pd.DataFrame(data=[new_row],columns=['level','body','backbone','rough'])))
    return df
def get_mark(backbone_mark):
    if backbone_mark:
        mark=[]
        
        for record in backbone_mark:
            fields=record['fields']
            #print(fields)
            if fields['本骨干标记']:
                mark.append(fields['骨干名'])
        if mark:
            if len(mark)==1:
                return (True,mark[0])

            else:
                return (False,'找到复数勾选骨干：%s'%mark)
        else:
            return (False,'没有勾选骨干标记')
    else:
        return (False,'没有勾选本骨干')

In [5]:
def get_files(fold_token):
    logger.info('开始检查文件，文件夹地址为　https://quantumgalaxy.feishu.cn/drive/folder/%s'%fold_token)
    r0=requests.get('http://82.156.248.152:81/fs/fold_meta?token=%s'%fold_token).json()
    
    r1=requests.get('http://82.156.248.152:81/fs/fold_children?fld_token=%s'%fold_token).json()
    if r0['code']==0 and r1['code']==0:
        files=r1['data']['files']
        data={}
        for file in files:
            if file['name'] not in ['电力储能骨干核心表Demo','xx骨干核心表模板及范例']:
            #if file['type']=='bitable' and '核心表' in file['name'] and file['name']!='xx骨干核心表Demo':
            #if True:
                data[file['name']]=file['token']
            else:
                logger.warning('排除该文件，类型:%s,名称:%s'%(file['type'],file['name']))
        num=len(data)
        
        logger.info('检查文件夹成功，共查到%d张多维表格参与联查，如下：'%num)
        for d in data.keys():
            logger.info(d)
        
        return {'code':0,'data':data}
    else:
        logger.info('检查文件夹失败，检查地址')
        return {'code':r0['code'],'data':r0}

In [6]:
def external_check(internal_result,files,report_df):
    '''对所有表格中externallinks+backbonemark进行检查，其对应的
    external_link结构：  
    'external_links': [{'bitapp_id': 'recNx4LYVO',
    'source': 'reclwpDIsc',
    'target': 'recDC1O4Rf',
    'category': '父节点',
    'checked': True,
    'source_name': '精煤',
    'target_name': '动力煤',
    'external_backbone_name': '电力',
    'external_backbone': '未知'},
    
    A表 有externallink L1,其external_backbone为B，则B表必须有相同sourcenametargaetname的externallink L1，其externalbackbone为A。成功则L1 l2为正确边界(只判断L1在出报告更方便？），否则暴露L1为错误'''
    result=deepcopy(internal_result)
    for token,data in result.items():
        logger.critical('对标记为"%s"的表格的边界进行检查,该表共有%s条外边参与联调'%(data['backbone_mark'],len(data['external_links'])))
        logger.critical(data['backbone_mark'])
        data['error_external_links']=[]
        data['good_external_links']=[]
        #print(data['external_links'])
        for link in data['external_links']:
            linktext=link['source_name']+'--'+link['category']+'->'+link['target_name']
            other_token=link['external_backbone']
            #print(internal_result[other_token])
            #othertoken是在internalcheck时根据file表查到
            get=False
            if other_token in internal_result.keys():
                for other_link in internal_result[other_token]['external_links']:
                #当表格在files里，但权限有问题，该表的token不会出现在internalresult中，需要提示
                    otherlinktext=other_link['source_name']+'--'+other_link['category']+'->'+other_link['target_name']
                    if otherlinktext==linktext:
                        get=True
                        if other_link['external_backbone']==token:
                            try:
                                if link.get('target'):
                                    link['source']=other_link['source']
                                else:
                                    print(link)
                                    print(other_link)
                                    link['target']=other_link['target']
                                data['good_external_links'].append(link)
                                logger.info('星图边界识别成功，在"%s"骨干中查到对应边："%s"'%(link['external_backbone_name'],linktext))
                            except:
                               data['error_external_links'].append(link) 
                               body='找到文本相同的星图边界但起终点有问题，可能是方向写反了或者外骨干标重了，如无法解决联系王之霖。边信息：%s'%linktext
                               logger.error(body)
                               report_df=append_df(report_df,['error',body,data['backbone_mark'],True])
                        else:
                            
                            data['error_external_links'].append(link)
                            body='星图边界识别到对应的边，但对应边的外骨干标记与本骨干不符，对应边的外骨干标记为："%s"，对应边为："%s"'%(link['external_backbone_name'],linktext)
                            logger.error(body)
                            report_df=append_df(report_df,['error',body,data['backbone_mark'],True])
                        break
            else:
                data['error_external_links'].append(link)
                body='星图边界识别失败，该边："%s"所对应的"%s"骨干没有经过内部检查，这是对应骨干而非本边的问题'%(linktext,link['external_backbone_name'])
                logger.error(body)
                report_df=append_df(report_df,['error',body,data['backbone_mark'],True])
            if not get:
                data['error_external_links'].append(link)
                body='星图边界识别失败，该边："%s"在对应"%s"骨干中没找到对应边界'%(linktext,link['external_backbone_name'])
                logger.error(body)
                report_df=append_df(report_df,['error',body,data['backbone_mark'],True])
        logger.critical('完成对标记为"%s"的表格的边界进行检查,该表共有%s条外边参与联调，通过边%s条，冲突边%s条\n'%(data['backbone_mark'],len(data['external_links']),len(data['good_external_links']),len(data['error_external_links'])))
        #print(data['backbone_mark'])
        data.pop('external_links')
    return result,report_df

In [7]:
def internal_check(data1,files,report_df):
    '''对多维表格data进行内部检查，梳理出所有外部节点和其对应边，其中孤立外部节点加入error，多层外部节点加入warning，其他加入external,并把原data中其他数据分类到
    'internal_links':[],'external_links':[],'warning_links':[],'error_nodes':[],'internal_nodes':[],'external_nodes':[],
    加上骨干标记'''
    data=deepcopy(data1)
    result={'internal_links':[],'external_links':[],'warning_links':[],'error_links':[],'error_nodes':[],'internal_nodes':[],'external_nodes':[]}
    r,mark=get_mark(data['backbone_mark'])
    if r:
        logger.critical('本骨干标记：')
        logger.critical(mark)
        result['backbone_mark']=mark
    else:
        body='检查到骨干定义表问题：%s'%mark
        logger.error(body)
        report_df=append_df(report_df,['error',body,mark,True])
        return None,None
    
    #result.update(data)
    for link in data['links']:
        if not link['category'] in ['原材料','储运','父节点','供应','同位','生产','反映']:
            link['error']=True
            result['error_links'].append(link)
            body='该边的关系有误：“%s”'%link['category']
            logger.error(body)
            report_df=append_df(report_df,['error',body,mark,True])
        for o in data['nodes']:
            if o['bitapp_id']==link['target']:
                link['target_name']=o['name']
            if o['bitapp_id']==link['source']:
                link['source_name']=o['name']
        if not (link.get('target_name') and link.get('source_name')):
            link['error']=True
            result['error_links'].append(link)
            body='出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"%s",起点："%s" 终点:"%s"'%(link.get('bitapp_id'),link.get('source_name_ref','unknown'),link.get('target_name_ref','unknown'))
            logger.error(body)
            report_df=append_df(report_df,['error',body,mark,True])
            
    for node in data['nodes']:
        if not node['more_info'].get('external_backbone'):
            result['internal_nodes'].append(node)
        else:
            
            id=node['bitapp_id']
            backbone=node['more_info'].get('external_backbone')

            if backbone:
                backbone=backbone[0]
            check=0
            if not files.get(backbone,None):
                '''该外部节点的‘所属外部骨干’字段与文件目录files比对结果，因此要求字段内骨干名与files名一致，不然认为没有找到外骨干'''
                '''涉及errornode的边移入errorlink'''
                logger.error('“%s”节点没有找到对应的外部骨干：“%s”'%(node['name'],backbone))
                #error
                result['error_nodes'].append(node)
                for link in data['links']:
                    if link['source']==id or link['target']=='id':
                        if link['source']==id :
                            other=link['target']
                            for o in data['nodes']:
                                if o['bitapp_id']==other :
                                    #link['source_name']=node['name']
                                    #link['target_name']=o['name']
                                    link['external_backbone_name']=backbone
                                    link['external_backbone']=files.get(backbone,'未知')
                        else:
                            other=link['source']
                            for o in data['nodes']:
                                if o['bitapp_id']==other :
                                    #link['source_name']=o['name']
                                    #link['target_name']=node['name']
                                    link['external_backbone_name']=backbone
                                    link['external_backbone']=files.get(backbone,'未知')
                        result['error_links'].append(link)
                        body='因“%s”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[%s]-(%s)->[%s]'%(node['name'],link['source_name'],link['category'],link['target_name'])
                        logger.error(body)
                        report_df=append_df(report_df,['error',body,mark,True])
                        link['error']=True
            else:
                result['external_nodes'].append(node)

                for link in data['links']:
                    
                        if link['source']==id :
                            
                            #从data中除去该边，只留纯外边
                            other=link['target']
                            for o in data['nodes']:
                                if o['bitapp_id']==other :
                                        
                                        
                                        link['source_name']=node['name']
                                        link['target_name']=o['name']
                                        link['external_backbone_name']=backbone
                                        link['external_backbone']=files.get(backbone,'未知')
                                        if not (o['more_info'].get('external_backbone') or o['category']=='指标'):
                                            #说明另一点为内部
                                            link1=deepcopy(link)
                                            link1.pop('source')
                                            logger.info('检查到与“%s”骨干间的正确星图边界：[%s]-(%s)->[%s]'%(backbone,link['source_name'],link['category'],link['target_name']))
                                            result['external_links'].append(link1)
                                            check=max(check,2)
                                            
                                        else:
                                        
                                            if not link.get('checked'):
                                                result['warning_links'].append(link)
                                                #说明另一点为外部,该边加入warning
                                                body='检查到本骨干之外的,属于“%s”骨干的边，该边不参与冲突检查：[%s]-(%s)->[%s]'%(backbone,link['source_name'],link['category'],link['target_name'])
                                                logger.warning(body)
                                                report_df=append_df(report_df,['warning',body,mark,True])
                                            check=max(check,1)
                                        continue
                            link['checked']=True

                                
                                
                        elif link['target']==id:
                            
                            other=link['source']
                            for o in data['nodes']:
                                if o['bitapp_id']==other:
                                        
                                        
                                        link['source_name']=o['name']
                                        link['target_name']=node['name']
                                        link['external_backbone_name']=backbone
                                        link['external_backbone']=files.get(backbone,'未知')
                                        if not (o['more_info'].get('external_backbone') or o['category']=='指标'):
                                            #说明另一点为内部,该边加入external
                                            link1=deepcopy(link)
                                            link1.pop('target')
                                            logger.info('检查到与“%s”骨干间的正确星图边界：[%s]-(%s)->[%s]'%(backbone,link['source_name'],link['category'],link['target_name']))
                                            result['external_links'].append(link1)
                                            check=max(check,2)
                                            
                                        else:
                                            
                                            if not link.get('checked'):
                                                
                                                result['warning_links'].append(link)
                                                #说明另一点为外部,该边加入warning
                                                body='检查到本骨干之外的,属于“%s”骨干的边，该边不参与冲突检查：[%s]-(%s)->[%s]'%(backbone,link['source_name'],link['category'],link['target_name'])
                                                logger.warning(body)
                                                report_df=append_df(report_df,['warning',body,mark,True])
                                            check=max(check,1)
                                        continue
                            link['checked']=True
                        else:
                            #result['internal_links'].append(link)
                            pass
                            '''所有边均未触发则error 该外部节点为孤立，未连入当前骨干'''
                        
                if check==2:
                    #ok
                    pass
                elif check==1:
                    #warning
                    pass
                else:
                    body='检查到孤立外骨干节点，该点为内部错误，不参与冲突检查：%s'%node['name']
                    logger.error(body)
                    report_df=append_df(report_df,['error',body,mark,True])
                    #error
                    result['error_nodes'].append(node)
                    pass
    for link in data['links']:
                if not link.get('checked'):
                    if not link.get('error'):
                        #没有check表示起终点均不是外部
                        result['internal_links'].append(link)
    return result,report_df
#data1=deepcopy(data)
#internal_check(data1)

In [8]:
testfiles={'第一个高级权限设置和外骨干范例': 'bascnzsAjUXwr4gUkaIpqi8BBaf','第二个高级权限设置和外骨干范例':'bascn9HmmVcWhW7fYfQdpJZXtdh'}

In [9]:
def find_common_elements(result,files):
    #检查所有表格里 internal_nodes 的name是否有重复，有的话给出表格token和节点name
    dictionary={}
    for k,v in result.items():
        names=[]
        #if v.get('good_external_nodes'):
        for item in v['internal_nodes']:
        #for item in v['good_external_nodes']:
            if item['category']!='企业':
                names.append(item['name'])
        dictionary[k]=names
    
    common_elements = []
    for key1, lst1 in dictionary.items():
        for key2, lst2 in dictionary.items():
            if key1 != key2:
                for element in lst1:
                    if element in lst2  and not ([element,(key1,key2)]  in common_elements or ([element,(key2,key1)]  in common_elements)):
                        common_elements.append([element,(key1,key2)])
    for i in common_elements:
        tokens=i.pop(1)
        names=({v:k for k,v in files.items()}[tokens[0]],{v:k for k,v in files.items()}[tokens[1]])
        i.append(names)

    return common_elements

In [10]:
def work1(files,report_df):
    logger.info('start')

    
    
    raw_datas={}
    internals={}
    externals={}
    internal_result={}
    errorfile=[]
    #result={'raw':raw_datas,'internal':internals,'external':externals}
    for name,token in files.items():
        '''file:{name,token}'''

        #data=bitable_works(token,subgraph_name='粗骨干图')
        data=bitable_works(token)
        raw_datas[token]=data
        logger.critical('对 “%s”  多维表格进行内部检查'%name)
        if data.get('code'):
            body='对 “%s”  多维表格进行内部检查失败，错误信息：%s\n'%(name,data)
            logger.critical(body)
            report_df=append_df(report_df,['critical',body,name,True])
            errorfile.append(name)
            continue
        r,report_df=internal_check(data,files,report_df)
        if r:
            internal_result[token]=r
            logger.critical('完成对 “%s”  多维表格进行内部检查\n'%name)
        else:
            errorfile.append(name)
            logger.critical('无法对 “%s”  多维表格进行内部检查\n'%name)
    logger.critical('内部检查完成，以下表格出现问题不参与联调:%s\n'%errorfile)
    #for errorname in errorfile:
        #files.pop(errorname)
    return internal_result,report_df
def work2(internal_result,files,report_df):

    logger.critical('开始外部联调，参与表格为：')
    logger.critical(str(list(files.keys()))+'\n')
    
    result,report_df=external_check(internal_result,files,report_df)
    
    '''外部检查'''
        
    return result,report_df

In [11]:

files={'区域':'DARKb6rCUaV2OqstRYdcyANBnbc'}

In [12]:
r=requests.get(
            r'http://172.21.0.14:81/bitapp/tables?app_token=%s' % 'DARKb6rCUaV2OqstRYdcyANBnbc')
r.json()

{'code': 0,
 'data': [{'name': '节点表', 'revision': 10, 'table_id': 'tbl0X22l77e57rYz'},
  {'name': '关系表', 'revision': 8, 'table_id': 'tblmKxDCwLyVBzw8'},
  {'name': '监测指标表', 'revision': 2, 'table_id': 'tblhsMhLWddJG5xZ'},
  {'name': '局部图列表', 'revision': 0, 'table_id': 'tblkHxVIKJnRJwih'},
  {'name': '世界线跟踪表', 'revision': 0, 'table_id': 'tblGeDtlfBNPGWg9'},
  {'name': '关系定义表', 'revision': 1, 'table_id': 'tblibBqeLKEIID7r'},
  {'name': '骨干定义表', 'revision': 6, 'table_id': 'tbltGzurJw2WV4YD'},
  {'name': '画图草稿', 'revision': 3, 'table_id': 'tblx8OCevTMu1jYx'}]}

In [13]:
logger.info('start')

INFO     start

In [14]:
fold='fldcn2VlYvt8Efb9PqZwO51GWud'
files=get_files(fold)
if files['code']==0:
        files=files['data']
files

INFO     开始检查文件，文件夹地址为　https://quantumgalaxy.feishu.cn/drive/folder/fldcn2VlYvt8Efb9PqZwO51GWud
WARNING  排除该文件，类型:bitable,名称:xx骨干核心表模板及范例
INFO     检查文件夹成功，共查到36张多维表格参与联查，如下：
INFO     医药
INFO     钠离子电池
INFO     通信
INFO     半导体
INFO     锂离子电池
INFO     工业制造
INFO     钢铁
INFO     光伏
INFO     煤炭
INFO     电力储能
INFO     风电
INFO     贵金属
INFO     海运
INFO     消费电子
INFO     种植
INFO     汽车制造
INFO     教育
INFO     零售餐饮
INFO     广告传媒
INFO     石油天然气
INFO     银行
INFO     石油化工
INFO     互联网云计算
INFO     家居
INFO     环保
INFO     矿产
INFO     电影
INFO     食品饮料
INFO     陆运
INFO     地产
INFO     区域图
INFO     纺织业
INFO     航空航天
INFO     畜牧业
INFO     美妆
INFO     旅游

{'医药': 'I6SFbcZLnaNP8nscvFCcKDRknqf',
 '钠离子电池': 'bascn57r5wVM7sM6aApFQtS7eYb',
 '通信': 'bascnfhDdoFtGSgqD9AuNzhswLf',
 '半导体': 'bascnbzucap8DFko3LgSLe0q1Kd',
 '锂离子电池': 'ZG1YbzKjQaPjIpsmk9NcSTBZnag',
 '工业制造': 'bascnQfxCAOxlZRfN0pv1YA28Hf',
 '钢铁': 'IEWKbVaDLayP0Bskj6ucfJB8nGc',
 '光伏': 'bascngo31Pi722JP5rBWEMgQL4e',
 '煤炭': 'bascnTB3mCMQdzSb3kJ37ATgQyg',
 '电力储能': 'bascnsACceveT2H48fktBz3xK7f',
 '风电': 'bascn5vPLSXteiWCaBOBYxoN8Vh',
 '贵金属': 'bascnk6XVDWXO7mUipEnqaNnAJf',
 '海运': 'BfmAbCOziaY61NsAFk6cMa7Ynvc',
 '消费电子': 'HMN8bAg6saMwZdsrHpHcRtBfnAg',
 '种植': 'Rr4XbrLEzaargtsgfF1c9ppxnsc',
 '汽车制造': 'bascnIRb34I8uajC8l70BZYtrYe',
 '教育': 'A164bE8RCabsnCss1tlcacuPn5b',
 '零售餐饮': 'DBnAb4TSCa29aXsqWhPcD2Pmn0f',
 '广告传媒': 'VUPJbq9T3azkGLseojQcbIGNnih',
 '石油天然气': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g',
 '银行': 'NQX9b6UZ6astfrsthMac8fcgnTb',
 '石油化工': 'YwFYbfJs8asYqIs2IdscNjUHn0c',
 '互联网云计算': 'bascnX3JNXBB9J428M3qHmJv1Me',
 '家居': 'DH5wbDbqAaFpz9sZc51cyJimnzg',
 '环保': 'VZcSblwVaa1lgHsZADOcEyAgnEe',
 '矿产': 'MrRSbYezbakf3esxarucPL3snvc',
 '电影': 'bascnCFrkVGczkkyWTXqAdLTLqe',
 '食品饮料': 'BQfjb41pka6j8os5iIZcqCpjnV1',
 '陆运': 'bascnipf2OKC7NYIMkWvAe5Fwhf',
 '地产': 'HRwdbhrmTaAOBws3hLhcKhKbnlh',
 '区域图': 'FFb1bDuHkaOwFJsJp2Hc2jPan8f',
 '纺织业': 'KfNAbDo9GaFPWusomZgck7Zeneh',
 '航空航天': 'bascn7y2rkPgE6WpXTxT8K93OHb',
 '畜牧业': 'HmoFbzbXNakHFpsyCDUctlOTnIb',
 '美妆': 'bascnarvMG0rEz78FNgUsIImkKe',
 '旅游': 'bascnoh0v8aKAFhMqihl6dxxTdf'}

In [15]:
files

{'医药': 'I6SFbcZLnaNP8nscvFCcKDRknqf',
 '钠离子电池': 'bascn57r5wVM7sM6aApFQtS7eYb',
 '通信': 'bascnfhDdoFtGSgqD9AuNzhswLf',
 '半导体': 'bascnbzucap8DFko3LgSLe0q1Kd',
 '锂离子电池': 'ZG1YbzKjQaPjIpsmk9NcSTBZnag',
 '工业制造': 'bascnQfxCAOxlZRfN0pv1YA28Hf',
 '钢铁': 'IEWKbVaDLayP0Bskj6ucfJB8nGc',
 '光伏': 'bascngo31Pi722JP5rBWEMgQL4e',
 '煤炭': 'bascnTB3mCMQdzSb3kJ37ATgQyg',
 '电力储能': 'bascnsACceveT2H48fktBz3xK7f',
 '风电': 'bascn5vPLSXteiWCaBOBYxoN8Vh',
 '贵金属': 'bascnk6XVDWXO7mUipEnqaNnAJf',
 '海运': 'BfmAbCOziaY61NsAFk6cMa7Ynvc',
 '消费电子': 'HMN8bAg6saMwZdsrHpHcRtBfnAg',
 '种植': 'Rr4XbrLEzaargtsgfF1c9ppxnsc',
 '汽车制造': 'bascnIRb34I8uajC8l70BZYtrYe',
 '教育': 'A164bE8RCabsnCss1tlcacuPn5b',
 '零售餐饮': 'DBnAb4TSCa29aXsqWhPcD2Pmn0f',
 '广告传媒': 'VUPJbq9T3azkGLseojQcbIGNnih',
 '石油天然气': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g',
 '银行': 'NQX9b6UZ6astfrsthMac8fcgnTb',
 '石油化工': 'YwFYbfJs8asYqIs2IdscNjUHn0c',
 '互联网云计算': 'bascnX3JNXBB9J428M3qHmJv1Me',
 '家居': 'DH5wbDbqAaFpz9sZc51cyJimnzg',
 '环保': 'VZcSblwVaa1lgHsZADOcEyAgnEe',
 '矿产': 'MrRSbYezbakf3esxarucPL3snvc',
 '电影': 'bascnCFrkVGczkkyWTXqAdLTLqe',
 '食品饮料': 'BQfjb41pka6j8os5iIZcqCpjnV1',
 '陆运': 'bascnipf2OKC7NYIMkWvAe5Fwhf',
 '地产': 'HRwdbhrmTaAOBws3hLhcKhKbnlh',
 '区域图': 'FFb1bDuHkaOwFJsJp2Hc2jPan8f',
 '纺织业': 'KfNAbDo9GaFPWusomZgck7Zeneh',
 '航空航天': 'bascn7y2rkPgE6WpXTxT8K93OHb',
 '畜牧业': 'HmoFbzbXNakHFpsyCDUctlOTnIb',
 '美妆': 'bascnarvMG0rEz78FNgUsIImkKe',
 '旅游': 'bascnoh0v8aKAFhMqihl6dxxTdf'}

In [16]:
report_df=pd.DataFrame(columns=['level','body','backbone','rough'])
report_df

Empty DataFrame
Columns: [level, body, backbone, rough]
Index: []

In [17]:

internal_result,report_df=work1(files,report_df)
internal_result

INFO     start

good table

CRITICAL 对 “医药”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 医药
CRITICAL 完成对 “医药”  多维表格进行内部检查

good table

CRITICAL 对 “钠离子电池”  多维表格进行内部检查
ERROR    检查到骨干定义表问题：没有勾选本骨干
CRITICAL 无法对 “钠离子电池”  多维表格进行内部检查

good table

CRITICAL 对 “通信”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 通信
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[互联网数据中心]-(原材料)->[宽带通信服务]
INFO     检查到与“消费电子”骨干间的正确星图边界：[手机]-(原材料)->[移动通信需求]
INFO     检查到与“消费电子”骨干间的正确星图边界：[天线模块]-(原材料)->[手机]
WARNING  检查到本骨干之外的,属于“消费电子”骨干的边，该边不参与冲突检查：[射频模块]-(原材料)->[手机]
WARNING  检查到本骨干之外的,属于“消费电子”骨干的边，该边不参与冲突检查：[基带模块]-(原材料)->[手机]
CRITICAL 完成对 “通信”  多维表格进行内部检查

good table

CRITICAL 对 “半导体”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 半导体
INFO     检查到与“航空航天”骨干间的正确星图边界：[创益通]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[电连技术]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[中航光电]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[航天电器]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[维峰电子]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[珠城科技]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[奕东电子]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[胜蓝股份]-(生产)->[电连接器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[广信材料]-(生产)->[涂料]
INFO     检查到与“航空航天”骨干间的正确星图边界：[广信材料]-(生产)->[光刻胶]
INFO     检查到与“航空航天”骨干间的正确星图边界：[航天长峰]-(生产)->[信息安全芯片]
INFO     检查到与“航空航天”骨干间的正确星图边界：[航天长峰]-(生产)->[通信芯片]
INFO     检查到与“航空航天”骨干间的正确星图边界：[航天长峰]-(生产)->[电源管理模块]
INFO     检查到与“电力储能”骨干间的正确星图边界：[明微电子]-(生产)->[LED模组]
INFO     检查到与“电力储能”骨干间的正确星图边界：[明微电子]-(生产)->[电源管理芯片，电源管理IC]
INFO     检查到与“航空航天”骨干间的正确星图边界：[纳睿雷达]-(生产)->[通信芯片]
INFO     检查到与“航空航天”骨干间的正确星图边界：[欧比特]-(生产)->[通信芯片]
INFO     检查到与“光伏”骨干间的正确星图边界：[乾照光电]-(生产)->[LED模组]
INFO     检查到与“光伏”骨干间的正确星图边界：[石英股份]-(生产)->[高纯石英砂]
INFO     检查到与“光伏”骨干间的正确星图边界：[苏州固锝]-(生产)->[半导体分立器件]
INFO     检查到与“光伏”骨干间的正确星图边界：[微导纳米]-(生产)->[芯片封装测试设备]
INFO     检查到与“光伏”骨干间的正确星图边界：[微导纳米]-(生产)->[半导体薄膜沉积设备]
INFO     检查到与“光伏”骨干间的正确星图边界：[正帆科技]-(生产)->[半导体制造设备]
INFO     检查到与“光伏”骨干间的正确星图边界：[正帆科技]-(生产)->[电子特种气体]
INFO     检查到与“航空航天”骨干间的正确星图边界：[臻镭科技]-(生产)->[通信芯片]
INFO     检查到与“航空航天”骨干间的正确星图边界：[臻镭科技]-(生产)->[射频模组]
INFO     检查到与“航空航天”骨干间的正确星图边界：[中航电测]-(生产)->[半导体传感器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[AC/DC交流-直流转换器]-(原材料)->[充电器]
INFO     检查到与“电力储能”骨干间的正确星图边界：[固德威]-(生产)->[储能逆变器]
INFO     检查到与“电力储能”骨干间的正确星图边界：[功率模块]-(原材料)->[储能逆变器]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[ROM]-(原材料)->[存储服务器]
INFO     检查到与“电力储能”骨干间的正确星图边界：[功率模块]-(原材料)->[电力逆变器]
INFO     检查到与“光伏”骨干间的正确星图边界：[有研硅]-(生产)->[多晶硅料]
INFO     检查到与“光伏”骨干间的正确星图边界：[神工股份]-(生产)->[多晶硅料]
INFO     检查到与“光伏”骨干间的正确星图边界：[中晶科技]-(生产)->[多晶硅料]
INFO     检查到与“光伏”骨干间的正确星图边界：[多晶硅料]-(原材料)->[半导体级单晶硅片]
INFO     检查到与“风电”骨干间的正确星图边界：[IGBT模块]-(原材料)->[风电变流器]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业ADC]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业DSP]
INFO     检查到与“工业制造”骨干间的正确星图边界：[芯片，集成电路，IC]-(父节点)->[工业IC]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业PLC]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业MEMS]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业MCU]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业隔离器]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[光传感器]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业存储]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(原材料)->[工业生产线]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[工业IC]-(父节点)->[工业MEMS]
INFO     检查到与“工业制造”骨干间的正确星图边界：[东软载波]-(生产)->[工业MCU]
INFO     检查到与“工业制造”骨干间的正确星图边界：[恒烁股份]-(生产)->[工业MCU]
INFO     检查到与“工业制造”骨干间的正确星图边界：[乐鑫科技]-(生产)->[工业MCU]
INFO     检查到与“工业制造”骨干间的正确星图边界：[芯海科技]-(生产)->[工业MCU]
INFO     检查到与“工业制造”骨干间的正确星图边界：[中颖电子]-(生产)->[工业MCU]
INFO     检查到与“工业制造”骨干间的正确星图边界：[*ST紫晶]-(生产)->[工业存储]
INFO     检查到与“工业制造”骨干间的正确星图边界：[复旦微电]-(生产)->[工业存储]
INFO     检查到与“工业制造”骨干间的正确星图边界：[佰维存储]-(生产)->[工业存储]
INFO     检查到与“工业制造”骨干间的正确星图边界：[威贸电子]-(生产)->[工业生产线]
INFO     检查到与“工业制造”骨干间的正确星图边界：[至纯科技]-(生产)->[光传感器]
INFO     检查到与“工业制造”骨干间的正确星图边界：[法尔胜]-(生产)->[光传感器]
INFO     检查到与“工业制造”骨干间的正确星图边界：[光莆股份]-(生产)->[光传感器]
INFO     检查到与“工业制造”骨干间的正确星图边界：[南大光电]-(生产)->[光传感器]
INFO     检查到与“光伏”骨干间的正确星图边界：[固德威]-(生产)->[光伏逆变器]
INFO     检查到与“光伏”骨干间的正确星图边界：[IGBT模块]-(原材料)->[光伏逆变器]
INFO     检查到与“航空航天”骨干间的正确星图边界：[逻辑芯片]-(原材料)->[航空电子]
INFO     检查到与“消费电子”骨干间的正确星图边界：[LDO，低压线性稳压器]-(原材料)->[摄像头]
INFO     检查到与“消费电子”骨干间的正确星图边界：[昀冢科技]-(生产)->[摄像头]
INFO     检查到与“消费电子”骨干间的正确星图边界：[DC/DC直流-直流转换器]-(原材料)->[数码相机]
INFO     检查到与“消费电子”骨干间的正确星图边界：[经纬辉开]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[艾比森]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[清越科技]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[光罩，光掩膜基板]-(原材料)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[长信科技]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[凯盛科技]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[彩虹股份]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[龙腾光电]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[和辉光电-U]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[深科达]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[冠石科技]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[翰博高新]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[联得装备]-(生产)->[显示器]
INFO     检查到与“消费电子”骨干间的正确星图边界：[ST星星]-(生产)->[显示器]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[汽车电子]-(原材料)->[新能源汽车]
WARNING  检查到本骨干之外的,属于“汽车制造”骨干的边，该边不参与冲突检查：[我国汽车产量]-(反映)->[新能源汽车]
INFO     检查到与“消费电子”骨干间的正确星图边界：[DC/DC直流-直流转换器]-(原材料)->[智能手机]
CRITICAL 完成对 “半导体”  多维表格进行内部检查

good table

CRITICAL 对 “锂离子电池”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 锂离子电池
INFO     检查到与“电力储能”骨干间的正确星图边界：[储能电池]-(父节点)->[储能锂电池]
INFO     检查到与“电力储能”骨干间的正确星图边界：[孚能科技]-(生产)->[储能电池]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池后段设备]-(父节点)->[化成分容设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池后段设备]-(父节点)->[电池组装设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池后段设备]-(父节点)->[电池检测设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池后段设备]-(原材料)->[锂电池模组]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池后段设备]-(原材料)->[锂离子电池]
INFO     检查到与“工业制造”骨干间的正确星图边界：[杭可科技]-(生产)->[电池后段设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[华自科技]-(生产)->[电池后段设备]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[锂电池生产设备]-(父节点)->[电池后段设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[星云股份]-(生产)->[电池后段设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(原材料)->[锂电池正极极片]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(原材料)->[锂电池负极极片]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(父节点)->[涂布机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(父节点)->[真空搅拌机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(父节点)->[辊压机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(父节点)->[分切机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池前段设备]-(父节点)->[制片机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[海目星]-(生产)->[电池前段设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[金银河]-(生产)->[电池前段设备]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[锂电池生产设备]-(父节点)->[电池前段设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池中段设备]-(父节点)->[卷绕机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池中段设备]-(父节点)->[叠片机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池中段设备]-(父节点)->[电芯入壳机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池中段设备]-(父节点)->[注液机]
INFO     检查到与“工业制造”骨干间的正确星图边界：[电池中段设备]-(原材料)->[锂电池电芯]
INFO     检查到与“工业制造”骨干间的正确星图边界：[海目星]-(生产)->[电池中段设备]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[锂电池生产设备]-(父节点)->[电池中段设备]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[动力锂电池]-(原材料)->[电源系统]
WARNING  检查到本骨干之外的,属于“汽车制造”骨干的边，该边不参与冲突检查：[电动汽车销量]-(反映)->[电源系统]
WARNING  检查到本骨干之外的,属于“汽车制造”骨干的边，该边不参与冲突检查：[电动汽车产量]-(反映)->[电源系统]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚丙烯]-(原材料)->[干法隔膜]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚乙烯]-(原材料)->[湿法隔膜]
INFO     检查到与“工业制造”骨干间的正确星图边界：[利元亨]-(生产)->[锂电池生产设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[先导智能]-(生产)->[锂电池生产设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[星云股份]-(生产)->[锂电池生产设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[锂电池生产设备]-(父节点)->[激光焊切设备]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[锂辉石]-(原材料)->[锂精矿]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[锂矿]-(父节点)->[锂辉石]
INFO     检查到与“矿产”骨干间的正确星图边界：[锂精矿]-(原材料)->[碳酸锂]
INFO     检查到与“矿产”骨干间的正确星图边界：[锂精矿]-(原材料)->[氢氧化锂]
INFO     检查到与“矿产”骨干间的正确星图边界：[融捷股份]-(生产)->[锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[盛新锂能]-(生产)->[锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[天齐锂业]-(生产)->[锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[中矿资源]-(生产)->[锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[天齐锂业]-(生产)->[锂精矿]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[锂矿]-(父节点)->[盐湖锂矿]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[锂矿]-(父节点)->[锂云母]
INFO     检查到与“矿产”骨干间的正确星图边界：[融捷股份]-(生产)->[锂矿]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[锂云母]-(原材料)->[锂云母精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[江特电机]-(生产)->[锂云母精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[锂云母精矿]-(原材料)->[碳酸锂]
INFO     检查到与“矿产”骨干间的正确星图边界：[永兴材料]-(生产)->[锂云母精矿]
INFO     检查到与“钠离子电池”骨干间的正确星图边界：[隔膜]-(原材料)->[钠离子电池电芯]
INFO     检查到与“消费电子”骨干间的正确星图边界：[消费电子]-(父节点)->[手机、电脑]
INFO     检查到与“通信”骨干间的正确星图边界：[储能锂电池]-(原材料)->[通信基站]
INFO     检查到与“矿产”骨干间的正确星图边界：[膜产品]-(原材料)->[盐湖锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[提锂剂]-(原材料)->[盐湖锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[西藏城投]-(生产)->[盐湖锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[西藏矿业]-(生产)->[盐湖锂精矿]
INFO     检查到与“矿产”骨干间的正确星图边界：[盐湖锂精矿]-(原材料)->[碳酸锂]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[盐湖锂矿]-(原材料)->[盐湖锂精矿]
CRITICAL 完成对 “锂离子电池”  多维表格进行内部检查

good table

CRITICAL 对 “工业制造”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 工业制造
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rectgKn3ka",起点："数控机床" 终点:"工业生产线"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recloBNkkK",起点："工业机器人" 终点:"工业生产线"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recFO4UKq9",起点："工业生产线" 终点:"智能工厂"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recdkmHOeI",起点："工业云服务" 终点:"智能工厂"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recEveFxOe",起点："机床导轨" 终点:"传动系统"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reciPwjFT9",起点："驱动系统" 终点:"数控机床"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reclEdPx5v",起点："主轴电机" 终点:"驱动系统"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recwGt1Rr1",起点："伺服电机" 终点:"驱动系统"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recdmoWW0k",起点："步进电机" 终点:"驱动系统"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recdMsBCRF",起点："四方达" 终点:"立方氮化硼 "
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rect1GYmIF",起点："工业IC" 终点:"工业MEMS"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recu7C7sy9",起点："工业IC" 终点:"工业DSP"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recQYAmp5W",起点："工业IC" 终点:"工业ADC"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recpXQkKtZ",起点："工业IC" 终点:"工业隔离器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reco7nk841",起点："工业IC" 终点:"工业MCU"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reckSq8tXX",起点："奥比中光" 终点:"3D感知解决方案"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reclenvMYT",起点："敏芯股份" 终点:"工业MEMS"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recTErePNP",起点："工业IC" 终点:"光传感器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recAmE75wP",起点："思特威" 终点:"光传感器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recxk7gjwR",起点："韦尔股份" 终点:"光传感器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reczKL00nr",起点："上海贝岭" 终点:"工业ADC"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recNLBSlic",起点："芯海科技" 终点:"工业ADC"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recSfbfAZz",起点："纳芯微" 终点:"工业隔离器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recrgmdj5x",起点："思瑞浦" 终点:"工业隔离器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rechSpVAjt",起点："中颖电子" 终点:"工业MCU"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"receTl3L8v",起点："兆易创新" 终点:"工业MCU"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recasgLycI",起点："工业IC" 终点:"工业存储"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recHAK2ok5",起点："聚辰股份" 终点:"工业存储"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recLYTCxSC",起点："兆易创新" 终点:"工业存储"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recyQiR3n4",起点："谐波减速器" 终点:"工业机器人"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recEDpVdvr",起点："工业机器人驱动器" 终点:"工业机器人"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec0rV3GGx",起点："工业机器人控制器" 终点:"工业机器人"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recOYrVTkl",起点："汇川技术" 终点:"工业机器人驱动器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recWeSxe8g",起点："雷赛智能" 终点:"工业机器人驱动器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec1MSeW61",起点："绿的谐波" 终点:"谐波减速器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reccPY48xS",起点："埃斯顿" 终点:"谐波减速器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec7Hf5bek",起点："埃斯顿" 终点:"工业机器人驱动器"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recdgAFFUF",起点："工业IC" 终点:"工业生产线"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recY6D6T84",起点："3D感知解决方案" 终点:"工业生产线"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec2SmhdxL",起点："硬质合金" 终点:"工程钻齿"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recjw8GFEI",起点："立方氮化硼 " 终点:"机床刀具"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recd5Jij7e",起点："工业通用部件" 终点:"工业生产线"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec0Rogcm0",起点："伟创电气" 终点:"驱动系统"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recIYKn0lM",起点："海达股份" 终点:"工业通用部件"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec5mXcKAx",起点："中密控股" 终点:"工业通用部件"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recxaEKSE6",起点："康平科技" 终点:"主轴电机"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recc0ACbip",起点："金沃股份" 终点:"工业通用部件"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reckTe1CY7",起点："海泰科" 终点:"工业通用部件"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recZvCwSiN",起点："怡合达" 终点:"工业通用部件"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recgGrrA0n",起点："湘电股份" 终点:"主轴电机"
ERROR    检查到孤立外骨干节点，该点为内部错误，不参与冲突检查：碳化钨
INFO     检查到与“半导体”骨干间的正确星图边界：[工业IC]-(原材料)->[工业网络设备]
CRITICAL 完成对 “工业制造”  多维表格进行内部检查

good table

CRITICAL 对 “钢铁”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 钢铁
INFO     检查到与“陆运”骨干间的正确星图边界：[钢型材]-(父节点)->[钢轨]
INFO     检查到与“陆运”骨干间的正确星图边界：[铁路货运]-(储运)->[钢材]
INFO     检查到与“地产”骨干间的正确星图边界：[建筑材料]-(父节点)->[型钢]
INFO     检查到与“地产”骨干间的正确星图边界：[建筑材料]-(父节点)->[结构钢管]
INFO     检查到与“地产”骨干间的正确星图边界：[建筑材料]-(父节点)->[螺纹钢]
WARNING  检查到本骨干之外的,属于“地产”骨干的边，该边不参与冲突检查：[建筑业PMI、建筑钢材总库存]-(反映)->[建筑材料]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[钢带]-(原材料)->[汽车密封条]
INFO     检查到与“陆运”骨干间的正确星图边界：[钢带]-(原材料)->[铁路桥梁]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[轧钢板]-(原材料)->[汽车骨架]
WARNING  检查到本骨干之外的,属于“汽车制造”骨干的边，该边不参与冲突检查：[全国汽车产量]-(反映)->[汽车骨架]
INFO     检查到与“海运”骨干间的正确星图边界：[轧钢板]-(原材料)->[集装箱]
INFO     检查到与“电力储能”骨干间的正确星图边界：[余热锅炉]-(原材料)->[电力]
WARNING  检查到本骨干之外的,属于“电力储能”骨干的边，该边不参与冲突检查：[电价]-(反映)->[电力]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[采选]-(原材料)->[钨精矿]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨精矿]-(原材料)->[钨矿火法分解]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨精矿]-(原材料)->[钨矿湿法分解]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨矿]-(原材料)->[采选]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[采选]-(原材料)->[钨铁]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[采选]-(原材料)->[钨酸钠]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[氢气]-(原材料)->[钨粉]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[三氧化钨]-(原材料)->[钨粉]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨粉]-(原材料)->[钨材]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨粉]-(原材料)->[碳化钨]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨矿火法分解]-(原材料)->[三氧化钨]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨矿湿法分解]-(原材料)->[三氧化钨]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[碳酸钠]-(原材料)->[钨矿火法分解]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[碳酸钠]-(原材料)->[钨矿湿法分解]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨材]-(父节点)->[钨条]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨材]-(父节点)->[钨锭]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨材]-(父节点)->[钨丝]
INFO     检查到与“矿产”骨干间的正确星图边界：[钨铁]-(原材料)->[炼钢]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[碳粉]-(原材料)->[碳化钨]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[钨丝]-(原材料)->[灯泡]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[碳化钨]-(原材料)->[硬质合金]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[碳化钨]-(原材料)->[医疗器械]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[硬质合金]-(原材料)->[钻头]
WARNING  检查到本骨干之外的,属于“工业制造”骨干的边，该边不参与冲突检查：[硬质合金]-(原材料)->[机床刀具]
INFO     检查到与“医药”骨干间的正确星图边界：[不锈钢]-(原材料)->[医疗器械]
INFO     检查到与“海运”骨干间的正确星图边界：[干散货航运]-(储运)->[铁矿石]
WARNING  检查到本骨干之外的,属于“海运”骨干的边，该边不参与冲突检查：[波罗的海干散货指数]-(反映)->[干散货航运]
INFO     检查到与“海运”骨干间的正确星图边界：[港口]-(储运)->[铁矿石]
WARNING  检查到本骨干之外的,属于“海运”骨干的边，该边不参与冲突检查：[港口铁矿石库存量]-(反映)->[港口]
INFO     检查到与“海运”骨干间的正确星图边界：[型钢]-(原材料)->[船舶]
INFO     检查到与“海运”骨干间的正确星图边界：[铝合金]-(原材料)->[船舶]
WARNING  检查到本骨干之外的,属于“海运”骨干的边，该边不参与冲突检查：[中船防务]-(生产)->[船舶]
WARNING  检查到本骨干之外的,属于“海运”骨干的边，该边不参与冲突检查：[中国船舶]-(生产)->[船舶]
INFO     检查到与“医药”骨干间的正确星图边界：[铸件，锻件]-(父节点)->[医疗器械零部件]
INFO     检查到与“电力储能”骨干间的正确星图边界：[铝合金]-(原材料)->[高压导线]
INFO     检查到与“航空航天”骨干间的正确星图边界：[铝铜合金]-(原材料)->[航天器零部件]
INFO     检查到与“工业制造”骨干间的正确星图边界：[白铜]-(原材料)->[精密机械]
INFO     检查到与“工业制造”骨干间的正确星图边界：[青铜]-(原材料)->[轴承]
INFO     检查到与“航空航天”骨干间的正确星图边界：[铸件，锻件]-(父节点)->[航空发动机零部件]
INFO     检查到与“航空航天”骨干间的正确星图边界：[钛合金]-(原材料)->[航空发动机零部件]
INFO     检查到与“航空航天”骨干间的正确星图边界：[铝合金]-(原材料)->[航空器外壳，航空器骨架]
INFO     检查到与“航空航天”骨干间的正确星图边界：[钛合金]-(原材料)->[航空器外壳，航空器骨架]
ERROR    “镍矿”节点没有找到对应的外部骨干：“券商”
ERROR    因“镍矿”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[镍矿]-(父节点)->[硫化镍矿]
ERROR    因“镍矿”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[镍矿]-(父节点)->[氧化镍矿，红土镍矿]
INFO     检查到与“风电”骨干间的正确星图边界：[钢材]-(原材料)->[风塔]
INFO     检查到与“风电”骨干间的正确星图边界：[无缝钢管]-(原材料)->[风电轴承]
INFO     检查到与“煤炭”骨干间的正确星图边界：[焦炭]-(原材料)->[高炉炼铁]
CRITICAL 完成对 “钢铁”  多维表格进行内部检查

good table

CRITICAL 对 “光伏”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 光伏
INFO     检查到与“半导体”骨干间的正确星图边界：[IGBT模块]-(原材料)->[光伏逆变器]
INFO     检查到与“半导体”骨干间的正确星图边界：[多晶硅料]-(原材料)->[半导体级单晶硅片]
WARNING  检查到本骨干之外的,属于“锂离子电池”骨干的边，该边不参与冲突检查：[储能锂电池]-(原材料)->[电化学储能站]
INFO     检查到与“电力储能”骨干间的正确星图边界：[电化学储能站]-(原材料)->[光伏电站]
INFO     检查到与“电力储能”骨干间的正确星图边界：[科士达]-(生产)->[光伏逆变器]
INFO     检查到与“电力储能”骨干间的正确星图边界：[逆变器]-(父节点)->[储能逆变器]
CRITICAL 完成对 “光伏”  多维表格进行内部检查

good table

CRITICAL 对 “煤炭”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 煤炭
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rectCsaqn2",起点："蓝焰控股" 终点:"液化天然气"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recoku0JaO",起点："云南能投" 终点:"液化天然气"
INFO     检查到与“钢铁”骨干间的正确星图边界：[焦炭]-(原材料)->[高炉炼铁]
WARNING  检查到本骨干之外的,属于“钢铁”骨干的边，该边不参与冲突检查：[高炉炼铁]-(原材料)->[生铁]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[广汇能源]-(生产)->[液化天然气LNG]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[煤制天然气]-(原材料)->[液化天然气LNG]
INFO     检查到与“电力储能”骨干间的正确星图边界：[动力煤]-(原材料)->[火力发电]
WARNING  检查到本骨干之外的,属于“电力储能”骨干的边，该边不参与冲突检查：[火电发电量]-(反映)->[火力发电]
WARNING  检查到本骨干之外的,属于“电力储能”骨干的边，该边不参与冲突检查：[中国发电量累计同比]-(反映)->[火力发电]
ERROR    检查到孤立外骨干节点，该点为内部错误，不参与冲突检查：航天工程
CRITICAL 完成对 “煤炭”  多维表格进行内部检查

good table

CRITICAL 对 “电力储能”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 电力储能
WARNING  检查到本骨干之外的,属于“锂离子电池”骨干的边，该边不参与冲突检查：[电池级碳酸锂]-(原材料)->[储能锂电池]
WARNING  检查到本骨干之外的,属于“锂离子电池”骨干的边，该边不参与冲突检查：[储能钠电池]-(同位)->[储能锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[储能电池]-(父节点)->[储能锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[电池测试设备]-(原材料)->[储能锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[豪鹏科技]-(生产)->[储能锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[*ST雪莱]-(生产)->[储能锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[超威动力]-(生产)->[储能锂电池]
WARNING  检查到本骨干之外的,属于“钠离子电池”骨干的边，该边不参与冲突检查：[钠离子电池]-(父节点)->[储能钠电池]
INFO     检查到与“钠离子电池”骨干间的正确星图边界：[铁空气电池]-(同位)->[储能钠电池]
INFO     检查到与“钠离子电池”骨干间的正确星图边界：[储能电池]-(父节点)->[储能钠电池]
WARNING  检查到本骨干之外的,属于“矿产”骨干的边，该边不参与冲突检查：[电池级碳酸锂]-(原材料)->[动力锂电池]
INFO     检查到与“矿产”骨干间的正确星图边界：[永兴材料]-(生产)->[电池级碳酸锂]
WARNING  检查到本骨干之外的,属于“锂离子电池”骨干的边，该边不参与冲突检查：[动力锂电池]-(原材料)->[新能源汽车]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[电池测试设备]-(原材料)->[动力锂电池]
WARNING  检查到本骨干之外的,属于“汽车制造”骨干的边，该边不参与冲突检查：[车规级芯片]-(原材料)->[新能源汽车]
WARNING  检查到本骨干之外的,属于“半导体”骨干的边，该边不参与冲突检查：[功率半导体]-(原材料)->[车规级芯片]
WARNING  检查到本骨干之外的,属于“半导体”骨干的边，该边不参与冲突检查：[半导体]-(父节点)->[功率半导体]
INFO     检查到与“钠离子电池”骨干间的正确星图边界：[钠离子电池模组]-(原材料)->[钠离子电池]
INFO     检查到与“煤炭”骨干间的正确星图边界：[煤]-(原材料)->[火力发电]
INFO     检查到与“煤炭”骨干间的正确星图边界：[苏能股份]-(生产)->[煤]
INFO     检查到与“煤炭”骨干间的正确星图边界：[恒源煤电]-(生产)->[煤]
INFO     检查到与“煤炭”骨干间的正确星图边界：[华电重工]-(储运)->[煤]
INFO     检查到与“煤炭”骨干间的正确星图边界：[皖能电力]-(生产)->[煤]
INFO     检查到与“煤炭”骨干间的正确星图边界：[动力煤]-(原材料)->[火力发电]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[天然气]-(原材料)->[热电联产]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[美能能源]-(生产)->[天然气]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[天富能源]-(生产)->[天然气]
INFO     检查到与“半导体”骨干间的正确星图边界：[赛晶科技]-(生产)->[半导体]
INFO     检查到与“半导体”骨干间的正确星图边界：[功率模块]-(原材料)->[储能逆变器]
INFO     检查到与“半导体”骨干间的正确星图边界：[功率模块]-(原材料)->[电力逆变器]
INFO     检查到与“光伏”骨干间的正确星图边界：[博菲电气]-(生产)->[光伏组件边框]
WARNING  检查到本骨干之外的,属于“光伏”骨干的边，该边不参与冲突检查：[光伏组件边框]-(原材料)->[光伏组件]
CRITICAL 完成对 “电力储能”  多维表格进行内部检查

good table

CRITICAL 对 “风电”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 风电
INFO     检查到与“半导体”骨干间的正确星图边界：[IGBT模块]-(原材料)->[风电变流器]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(原材料)->[风电塔筒]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(父节点)->[特种钢]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(父节点)->[钢锭]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(父节点)->[无缝钢管]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(父节点)->[硅钢]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢材]-(父节点)->[硼钢]
CRITICAL 完成对 “风电”  多维表格进行内部检查

good table

CRITICAL 对 “贵金属”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 贵金属
CRITICAL 完成对 “贵金属”  多维表格进行内部检查

good table

CRITICAL 对 “海运”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 海运
INFO     检查到与“石油天然气”骨干间的正确星图边界：[原油航运]-(储运)->[原油]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[英国布伦特原油]-(反映)->[原油]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[成品油航运]-(储运)->[成品油]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[液化天然气航运]-(储运)->[液化天然气]
INFO     检查到与“钢铁”骨干间的正确星图边界：[干散货航运]-(储运)->[铁矿石]
INFO     检查到与“种植”骨干间的正确星图边界：[干散货航运]-(储运)->[纸浆]
INFO     检查到与“种植”骨干间的正确星图边界：[纸浆船运输]-(储运)->[纸浆]
INFO     检查到与“种植”骨干间的正确星图边界：[干散货航运]-(储运)->[粮食作物]
INFO     检查到与“地产”骨干间的正确星图边界：[干散货航运]-(储运)->[水泥]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[滚装船航运]-(储运)->[汽车]
INFO     检查到与“钢铁”骨干间的正确星图边界：[轧钢板]-(原材料)->[集装箱]
CRITICAL 完成对 “海运”  多维表格进行内部检查

good table

CRITICAL 对 “消费电子”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 消费电子
INFO     检查到与“半导体”骨干间的正确星图边界：[存储芯片]-(原材料)->[消费电子]
INFO     检查到与“半导体”骨干间的正确星图边界：[芯片]-(父节点)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[GPU]-(原材料)->[消费电子]
INFO     检查到与“半导体”骨干间的正确星图边界：[GPU]-(原材料)->[手机]
INFO     检查到与“半导体”骨干间的正确星图边界：[CPU]-(原材料)->[消费电子]
INFO     检查到与“半导体”骨干间的正确星图边界：[CPU]-(原材料)->[手机]
ERROR    “百联股份”节点没有找到对应的外部骨干：“零售餐饮线下消费”
ERROR    因“百联股份”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[百联股份]-(生产)->[消费电子产品销售]
CRITICAL 完成对 “消费电子”  多维表格进行内部检查

good table

CRITICAL 对 “种植”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 种植
INFO     检查到与“食品饮料”骨干间的正确星图边界：[粮食作物]-(原材料)->[粮食作物加工]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[粮食作物]-(原材料)->[粮食作物加工]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[粮食作物加工]-(原材料)->[成品粮食]
INFO     检查到与“海运”骨干间的正确星图边界：[干散货航运]-(储运)->[粮食作物]
INFO     检查到与“海运”骨干间的正确星图边界：[干散货航运]-(储运)->[纸浆]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[大米]-(原材料)->[白酒]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[成品粮食]-(父节点)->[大米]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[苏垦农发]-(生产)->[大米]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[小麦]-(原材料)->[面粉]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[小麦]-(原材料)->[能量原材料]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[玉米]-(原材料)->[能量原材料]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[高粱]-(原材料)->[能量原材料]
INFO     检查到与“纺织业”骨干间的正确星图边界：[玉米]-(原材料)->[再生蛋白质纤维]
INFO     检查到与“纺织业”骨干间的正确星图边界：[大豆]-(原材料)->[再生蛋白质纤维]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[小麦]-(原材料)->[白酒]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[高粱]-(原材料)->[白酒]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[玉米]-(原材料)->[白酒]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[麦芽]-(原材料)->[啤酒]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[大豆油]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[大豆榨取]-(原材料)->[大豆油]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[嘉华股份]-(生产)->[大豆油]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[玉米油]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[玉米]-(原材料)->[玉米油]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[一级玉米油价格]-(反映)->[玉米油]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[棕榈油]-(原材料)->[膨化食品]
INFO     检查到与“地产”骨干间的正确星图边界：[木材]-(原材料)->[家具]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[纸浆]-(原材料)->[纸质包装]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[美盈森]-(生产)->[纸质包装]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[棕榈油]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[棕榈树，油棕树]-(原材料)->[棕榈油]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[油菜籽榨取]-(原材料)->[菜籽油]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[菜籽油]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[菜粕]-(原材料)->[植物性蛋白]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[豆粕]-(原材料)->[植物性蛋白]
INFO     检查到与“纺织业”骨干间的正确星图边界：[天然纤维]-(父节点)->[棉]
INFO     检查到与“纺织业”骨干间的正确星图边界：[天然纤维]-(父节点)->[麻]
INFO     检查到与“纺织业”骨干间的正确星图边界：[棉]-(原材料)->[再生纤维素纤维]
INFO     检查到与“纺织业”骨干间的正确星图边界：[木材]-(原材料)->[再生纤维素纤维]
INFO     检查到与“纺织业”骨干间的正确星图边界：[麻]-(原材料)->[麻布]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[饮料作物]-(父节点)->[茶叶]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[饮料作物]-(父节点)->[咖啡豆]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[经济作物]-(父节点)->[饮料作物]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[咖啡豆]-(原材料)->[咖啡]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[茶叶]-(原材料)->[茶饮料]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[英记茶庄集团]-(储运)->[茶叶]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[水果]-(父节点)->[甘蔗]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[经济作物]-(父节点)->[水果]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[生鲜食品]-(父节点)->[水果]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[水果]-(原材料)->[蜜饯果干]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[宏辉果蔬]-(生产)->[水果]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[丝路能源]-(生产)->[水果]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[经济作物]-(父节点)->[蔬菜]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[生鲜食品]-(父节点)->[蔬菜]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[糖料作物]-(父节点)->[甜菜]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[糖料作物]-(父节点)->[甘蔗]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[经济作物]-(父节点)->[糖料作物]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[糖料作物]-(原材料)->[食糖]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[种子]-(父节点)->[玉米种子]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[种子]-(父节点)->[大豆种子]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[种子]-(父节点)->[小麦种子]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[种子]-(父节点)->[水稻种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[种子]-(原材料)->[农作物]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[敦煌种业]-(生产)->[种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[丰乐种业]-(生产)->[种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[隆平高科]-(生产)->[种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[绿亨科技]-(生产)->[种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[登海种业]-(生产)->[玉米种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[万向德农]-(生产)->[玉米种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[荃银高科]-(生产)->[玉米种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[秋乐种业]-(生产)->[玉米种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[荃银高科]-(生产)->[水稻种子]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[秋乐种业]-(生产)->[小麦种子]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药制剂]-(父节点)->[除草剂]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药制剂]-(父节点)->[杀虫剂]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药制剂]-(父节点)->[杀菌剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[浙农股份]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[国光股份]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[中农联合]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[农药制剂]-(原材料)->[农作物]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药原药]-(原材料)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[辉隆股份]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[丰乐种业]-(生产)->[农药制剂]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药制剂]-(父节点)->[调节剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[辉丰股份]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[绿亨科技]-(生产)->[农药制剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[雅本化学]-(生产)->[农药中间体]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[中农联合]-(生产)->[农药中间体]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农药中间体]-(原材料)->[农药原药]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[辉丰股份]-(生产)->[农药中间体]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[海利尔]-(生产)->[农药中间体]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[中农联合]-(生产)->[农药原药]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[蓝丰生化]-(生产)->[农药原药]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[海利尔]-(生产)->[农药原药]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[绿亨科技]-(生产)->[农药原药]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[安道麦A]-(生产)->[除草剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[扬农化工]-(生产)->[除草剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[丰山集团]-(生产)->[除草剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[润丰股份]-(生产)->[除草剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[溴素]-(原材料)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[诺普信]-(生产)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[利民股份]-(生产)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[农心科技]-(生产)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[美邦股份]-(生产)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[丰山集团]-(生产)->[杀虫剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[诺普信]-(生产)->[杀菌剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[利民股份]-(生产)->[杀菌剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[农心科技]-(生产)->[杀菌剂]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[美邦股份]-(生产)->[杀菌剂]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[天然气]-(原材料)->[合成氨]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成橡胶]-(原材料)->[农业机械]
CRITICAL 完成对 “种植”  多维表格进行内部检查

good table

CRITICAL 对 “汽车制造”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 汽车制造
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[动力锂电池]-(原材料)->[电源系统]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[博汇股份]-(生产)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[深中华A]-(生产)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[锂电池正极材料]-(原材料)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[锂电池电解液]-(原材料)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[汽车电池回收服务]-(储运)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[锂电池结构件]-(原材料)->[动力锂电池]
INFO     检查到与“锂离子电池”骨干间的正确星图边界：[锂电池负极材料]-(原材料)->[动力锂电池]
WARNING  检查到本骨干之外的,属于“锂离子电池”骨干的边，该边不参与冲突检查：[锂矿材料价格水平]-(反映)->[动力锂电池]
INFO     检查到与“电力储能”骨干间的正确星图边界：[充电桩]-(储运)->[电力]
INFO     检查到与“电力储能”骨干间的正确星图边界：[电力]-(原材料)->[新能源车出行]
INFO     检查到与“电力储能”骨干间的正确星图边界：[配电网设备]-(储运)->[电力]
INFO     检查到与“工业制造”骨干间的正确星图边界：[数控机床]-(原材料)->[一体化车身]
INFO     检查到与“工业制造”骨干间的正确星图边界：[数控机床]-(原材料)->[汽车骨架]
INFO     检查到与“工业制造”骨干间的正确星图边界：[嵘泰股份]-(生产)->[数控机床]
INFO     检查到与“工业制造”骨干间的正确星图边界：[合锻智能]-(生产)->[数控机床]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[成品油]-(原材料)->[燃油车出行]
INFO     检查到与“钠离子电池”骨干间的正确星图边界：[动力钠电池]-(原材料)->[电源系统]
INFO     检查到与“旅游”骨干间的正确星图边界：[客车]-(原材料)->[景区观光]
INFO     检查到与“陆运”骨干间的正确星图边界：[货车]-(原材料)->[公路货运]
INFO     检查到与“陆运”骨干间的正确星图边界：[三羊马]-(生产)->[公路货运]
INFO     检查到与“陆运”骨干间的正确星图边界：[ST大洲]-(生产)->[公路货运]
INFO     检查到与“海运”骨干间的正确星图边界：[滚装船航运]-(储运)->[汽车]
INFO     检查到与“陆运”骨干间的正确星图边界：[朗博科技]-(生产)->[车用橡胶]
CRITICAL 完成对 “汽车制造”  多维表格进行内部检查

good table

CRITICAL 对 “教育”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 人力资源（教育）
CRITICAL 完成对 “教育”  多维表格进行内部检查

good table

CRITICAL 对 “零售餐饮”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 零售餐饮
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec3f1Oy9N",起点："unknown" 终点:"unknown"
CRITICAL 完成对 “零售餐饮”  多维表格进行内部检查

good table

CRITICAL 对 “广告传媒”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 广告传媒
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[广告渠道]-(父节点)->[信息平台]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[内容]-(父节点)->[广告]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[内容]-(父节点)->[PGC]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[内容]-(父节点)->[AIGC]
ERROR    “在线教育”节点没有找到对应的外部骨干：“人力资源（教育）”
INFO     检查到与“旅游”骨干间的正确星图边界：[米奥会展]-(生产)->[展览会]
INFO     检查到与“旅游”骨干间的正确星图边界：[兰生股份]-(生产)->[展览会]
INFO     检查到与“旅游”骨干间的正确星图边界：[广告渠道]-(父节点)->[展览会]
CRITICAL 完成对 “广告传媒”  多维表格进行内部检查

good table

CRITICAL 对 “石油天然气”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 石油天然气
INFO     检查到与“海运”骨干间的正确星图边界：[成品油航运]-(储运)->[成品油]
INFO     检查到与“海运”骨干间的正确星图边界：[原油航运]-(储运)->[原油]
INFO     检查到与“海运”骨干间的正确星图边界：[液化天然气航运]-(储运)->[液化天然气]
INFO     检查到与“航空航天”骨干间的正确星图边界：[航空汽油]-(原材料)->[航空运输]
INFO     检查到与“电力储能”骨干间的正确星图边界：[天然气]-(原材料)->[热电联产]
INFO     检查到与“电力储能”骨干间的正确星图边界：[廊坊发展]-(生产)->[热电联产]
CRITICAL 完成对 “石油天然气”  多维表格进行内部检查

good table

CRITICAL 对 “银行”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 银行
INFO     检查到与“地产”骨干间的正确星图边界：[个人活期储蓄]-(原材料)->[房地产销售回款]
INFO     检查到与“地产”骨干间的正确星图边界：[个人定期储蓄]-(原材料)->[房地产销售回款]
INFO     检查到与“地产”骨干间的正确星图边界：[个人住房贷款]-(原材料)->[房地产销售回款]
INFO     检查到与“地产”骨干间的正确星图边界：[房地产外部融资]-(父节点)->[房地产开发贷款]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[信息化工程建设]-(原材料)->[银行信息化建设]
CRITICAL 完成对 “银行”  多维表格进行内部检查

good table

CRITICAL 对 “石油化工”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 石油化工
INFO     检查到与“石油天然气”骨干间的正确星图边界：[原油]-(原材料)->[石油轻炼]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[纽约商业交易所轻质低硫原油合约]-(反映)->[原油]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[伦敦国际石油交易所布伦特原油期货合约]-(反映)->[原油]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[INE原油]-(反映)->[原油]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[石油轻炼]-(原材料)->[化工轻油]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[化工轻油]-(原材料)->[芳构化反应]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[化工轻油]-(原材料)->[裂解反应]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[化工轻油]-(原材料)->[石油制甲醇法]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[石脑油现货价(中间价):CFR日本]-(反映)->[化工轻油]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[石脑油基准价-国内-生意社]-(反映)->[化工轻油]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚酯纤维(涤纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[对二甲苯酸PTA]-(原材料)->[聚酯纤维(涤纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[乙二醇]-(原材料)->[聚酯纤维(涤纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[荣盛石化]-(生产)->[聚酯纤维(涤纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚氯乙烯纤维(氯纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[聚氯乙烯PVC]-(原材料)->[聚氯乙烯纤维(氯纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[丙烯腈]-(原材料)->[聚丙烯腈纤维(腈纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚丙烯腈纤维(腈纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[聚烯烃]-(原材料)->[聚烯烃弹力纤维]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚烯烃弹力纤维]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚乙烯醇缩醛纤维(维尼纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[聚乙烯醇PVA]-(原材料)->[聚乙烯醇缩醛纤维(维尼纶)]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[聚酰胺纤维(尼龙/锦纶)]-(父节点)->[尼龙6]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[聚酰胺纤维(尼龙/锦纶)]-(父节点)->[尼龙66]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚酰胺纤维(尼龙/锦纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[聚四氢呋喃PTMG]-(原材料)->[聚氨酯纤维(氨纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[二苯基甲烷二异氰酸酯MDI]-(原材料)->[聚氨酯纤维(氨纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚氨酯纤维(氨纶)]
INFO     检查到与“纺织业”骨干间的正确星图边界：[己内酰胺]-(原材料)->[尼龙6]
INFO     检查到与“纺织业”骨干间的正确星图边界：[乙二胺]-(原材料)->[尼龙66]
INFO     检查到与“纺织业”骨干间的正确星图边界：[己二酸]-(原材料)->[尼龙66]
WARNING  检查到本骨干之外的,属于“煤炭”骨干的边，该边不参与冲突检查：[炼焦煤]-(原材料)->[煤制甲醇法]
INFO     检查到与“煤炭”骨干间的正确星图边界：[江苏国信]-(生产)->[炼焦煤]
ERROR    “轮胎”节点没有找到对应的外部骨干：“汽车”
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成橡胶]-(原材料)->[鞋类原料]
INFO     检查到与“电力储能”骨干间的正确星图边界：[丁苯橡胶]-(原材料)->[电线电缆]
INFO     检查到与“纺织业”骨干间的正确星图边界：[合成纤维]-(原材料)->[化纤面料]
INFO     检查到与“地产”骨干间的正确星图边界：[合成树脂]-(原材料)->[建筑涂料]
INFO     检查到与“光伏”骨干间的正确星图边界：[POE粒子]-(原材料)->[POE胶膜]
INFO     检查到与“煤炭”骨干间的正确星图边界：[煤制乙二醇工艺]-(原材料)->[乙二醇]
INFO     检查到与“煤炭”骨干间的正确星图边界：[合成气]-(原材料)->[煤制乙二醇工艺]
INFO     检查到与“煤炭”骨干间的正确星图边界：[煤制甲醇法]-(原材料)->[合成气]
CRITICAL 完成对 “石油化工”  多维表格进行内部检查

good table

CRITICAL 对 “互联网云计算”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 互联网云计算
WARNING  检查到本骨干之外的,属于“半导体”骨干的边，该边不参与冲突检查：[裕太微-U]-(生产)->[高速有线通信芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[高速有线通信芯片]-(原材料)->[互联网数据中心]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[广告设计策划]-(父节点)->[广告推广平台]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[广告设计策划]-(父节点)->[电商导购平台]
WARNING  检查到本骨干之外的,属于“广告传媒”骨干的边，该边不参与冲突检查：[广告设计策划]-(父节点)->[数字营销]
WARNING  检查到本骨干之外的,属于“广告传媒”骨干的边，该边不参与冲突检查：[广告设计策划]-(父节点)->[大数据营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[广告设计策划]-(原材料)->[广告]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[华媒控股]-(生产)->[广告设计策划]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[优矩控股]-(生产)->[广告设计策划]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[万星控股]-(生产)->[广告设计策划]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[姚记科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[智度股份]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[盛天网络]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[中富通]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[国脉文化]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[网达软件]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[中广天择]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[华扬联众]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[利欧股份]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[创业黑马]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[新华都]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[久其软件]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[因赛集团]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[省广集团]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[易点天下]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[浙江富润]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[恒大高新]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[万润科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[环球印务]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[天地在线]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[同花顺]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[*ST中昌]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[天下秀]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[三六五网]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[引力传媒]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[思美传媒]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[川网传媒]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[汇量科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[秀商时代控股]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[辉煌明天]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[联建光电]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[佳云科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[浙文互联]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[国旅联合]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[旗天科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[云想科技]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[润歌互动]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[乐享集团]-(生产)->[数字营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[福石控股]-(生产)->[大数据营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[人工智能]-(父节点)->[大数据营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[智度股份]-(生产)->[大数据营销]
INFO     检查到与“广告传媒”骨干间的正确星图边界：[中新赛克]-(生产)->[大数据营销]
INFO     检查到与“半导体”骨干间的正确星图边界：[存储芯片]-(父节点)->[DRAM]
WARNING  检查到本骨干之外的,属于“半导体”骨干的边，该边不参与冲突检查：[存储芯片]-(父节点)->[ROM]
WARNING  检查到本骨干之外的,属于“半导体”骨干的边，该边不参与冲突检查：[朗科科技]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[江波龙]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[恒烁股份]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[德明利]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[*ST紫晶]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[东芯股份]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[深科技]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[普冉股份]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[佰维存储]-(生产)->[存储芯片]
INFO     检查到与“半导体”骨干间的正确星图边界：[北京君正]-(生产)->[存储芯片]
WARNING  检查到本骨干之外的,属于“旅游”骨干的边，该边不参与冲突检查：[在线旅行社]-(储运)->[旅行团服务]
INFO     检查到与“旅游”骨干间的正确星图边界：[信息平台]-(父节点)->[在线旅行社]
INFO     检查到与“银行”骨干间的正确星图边界：[信息化工程建设]-(原材料)->[银行IT建设]
INFO     检查到与“银行”骨干间的正确星图边界：[创识科技]-(生产)->[银行IT建设]
INFO     检查到与“银行”骨干间的正确星图边界：[银信科技]-(生产)->[银行IT建设]
INFO     检查到与“半导体”骨干间的正确星图边界：[ROM]-(原材料)->[存储服务器]
ERROR    “金融服务”节点没有找到对应的外部骨干：“券商”
INFO     检查到与“电影”骨干间的正确星图边界：[视频]-(父节点)->[影视剧]
WARNING  检查到本骨干之外的,属于“电影”骨干的边，该边不参与冲突检查：[百纳千成]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[欢瑞世纪]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[奥飞娱乐]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[慈文传媒]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[中南文化]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[捷成股份]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[光迅科技]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[上海电影]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[文投控股]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[光线传媒]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[大晟文化]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[IPTV业务]-(储运)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[浙文影业]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[华策影视]-(生产)->[影视剧]
INFO     检查到与“电影”骨干间的正确星图边界：[唐德影视]-(生产)->[影视剧]
INFO     检查到与“种植”骨干间的正确星图边界：[鸿博股份]-(生产)->[互联网数据中心]
INFO     检查到与“种植”骨干间的正确星图边界：[英伟达]-(供应)->[鸿博股份]
ERROR    “人力资源”节点没有找到对应的外部骨干：“人力资源（教育）”
ERROR    因“人力资源”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[人力资源]-(原材料)->[手工生产]
ERROR    因“人力资源”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[人力资源]-(原材料)->[AIGC]
INFO     检查到与“纺织业”骨干间的正确星图边界：[常山北明]-(生产)->[软件解决方案]
INFO     检查到与“纺织业”骨干间的正确星图边界：[百度集团-SW]-(供应)->[常山北明]
INFO     检查到与“纺织业”骨干间的正确星图边界：[美利云]-(生产)->[互联网数据中心]
INFO     检查到与“地产”骨干间的正确星图边界：[国光电器]-(生产)->[智能音响]
INFO     检查到与“旅游”骨干间的正确星图边界：[石基信息]-(生产)->[软件解决方案]
INFO     检查到与“光伏”骨干间的正确星图边界：[三五互联]-(生产)->[游戏]
INFO     检查到与“半导体”骨干间的正确星图边界：[欧比特]-(生产)->[数据]
INFO     检查到与“半导体”骨干间的正确星图边界：[欧比特]-(生产)->[智能安防]
INFO     检查到与“半导体”骨干间的正确星图边界：[欧比特]-(生产)->[地理信息系统]
INFO     检查到与“电力储能”骨干间的正确星图边界：[麦克奥迪]-(生产)->[医疗平台]
INFO     检查到与“航空航天”骨干间的正确星图边界：[天和防务]-(生产)->[军用信息化软件]
CRITICAL 完成对 “互联网云计算”  多维表格进行内部检查

good table

CRITICAL 对 “家居”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 家居
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec3f1Oy9N",起点："unknown" 终点:"unknown"
ERROR    检查到孤立外骨干节点，该点为内部错误，不参与冲突检查：线下零售店
INFO     检查到与“钢铁”骨干间的正确星图边界：[冷轧钢板]-(原材料)->[家电用复合材料（PCM/VCM）]
INFO     检查到与“钢铁”骨干间的正确星图边界：[镀锌板]-(原材料)->[家电用复合材料（PCM/VCM）]
CRITICAL 完成对 “家居”  多维表格进行内部检查

good table

CRITICAL 对 “环保”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 环保
CRITICAL 完成对 “环保”  多维表格进行内部检查

good table

CRITICAL 对 “矿产”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 矿产
CRITICAL 完成对 “矿产”  多维表格进行内部检查

good table

CRITICAL 对 “电影”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 电影
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[数字娱乐平台]-(父节点)->[视频平台]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[线上销售渠道平台]-(父节点)->[在线票务平台]
INFO     检查到与“地产”骨干间的正确星图边界：[商业房地产]-(原材料)->[院线放映]
CRITICAL 完成对 “电影”  多维表格进行内部检查

good table

CRITICAL 对 “食品饮料”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 食品饮料
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec2GZKsF6",起点："蜡笔小新食品" 终点:"果冻产品"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recPu0jQIj",起点："亲亲食品" 终点:"果冻产品"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recIaUk8M5",起点："休闲零食" 终点:"果冻产品"
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[线下零售店]-(储运)->[食品烟酒]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[文峰股份]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[家家悦]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[良品铺子]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[国光连锁]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[中国北大荒]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[太古股份公司B]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[四洲集团]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[利亚零售]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[联华超市]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[鸿福堂]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[宾仕国际]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[K2 F&B]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[利福中国]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[奈雪的茶]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[优品360]-(生产)->[线下零售店]
INFO     检查到与“零售餐饮”骨干间的正确星图边界：[红旗连锁]-(生产)->[线下零售店]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚乙烯]-(原材料)->[塑料包装]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[大豆]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[玉米]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(原材料)->[粮食作物加工]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[水稻]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[小麦]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[大麦]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[高粱]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物]-(父节点)->[谷子]
INFO     检查到与“种植”骨干间的正确星图边界：[小麦]-(原材料)->[白酒]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[小麦]-(原材料)->[面粉]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[小麦]-(原材料)->[麦芽]
INFO     检查到与“种植”骨干间的正确星图边界：[高粱]-(原材料)->[白酒]
INFO     检查到与“种植”骨干间的正确星图边界：[大豆]-(原材料)->[豆制品]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[大豆榨取]-(原材料)->[大豆油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[油菜籽榨取]-(原材料)->[菜籽油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[玉米]-(原材料)->[玉米油]
INFO     检查到与“种植”骨干间的正确星图边界：[玉米]-(原材料)->[白酒]
INFO     检查到与“种植”骨干间的正确星图边界：[玉米]-(原材料)->[谷氨酸钠]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[大麦]-(原材料)->[麦芽]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[粮食作物加工]-(原材料)->[成品粮食]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[成品粮食]-(父节点)->[大米]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[成品粮食]-(父节点)->[面粉]
INFO     检查到与“种植”骨干间的正确星图边界：[食品烟酒]-(父节点)->[成品粮食]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[成品粮食]-(父节点)->[玉米面]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[成品粮食]-(父节点)->[小米]
INFO     检查到与“种植”骨干间的正确星图边界：[成品粮食]-(父节点)->[玉米淀粉]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[零售价:粮食:小包装面粉]-(反映)->[面粉]
INFO     检查到与“种植”骨干间的正确星图边界：[大米]-(原材料)->[白酒]
INFO     检查到与“种植”骨干间的正确星图边界：[金健米业]-(生产)->[大米]
INFO     检查到与“种植”骨干间的正确星图边界：[东方集团]-(生产)->[大米]
INFO     检查到与“种植”骨干间的正确星图边界：[金源米业]-(生产)->[大米]
INFO     检查到与“种植”骨干间的正确星图边界：[中绿]-(生产)->[大米]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[零售价:粮食:小包装大米]-(反映)->[大米]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[油料作物]-(父节点)->[棕榈树，油棕树]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[棕榈树，油棕树]-(原材料)->[棕榈油]
INFO     检查到与“种植”骨干间的正确星图边界：[咖啡豆]-(原材料)->[咖啡]
INFO     检查到与“种植”骨干间的正确星图边界：[茶叶]-(原材料)->[茶饮料]
INFO     检查到与“种植”骨干间的正确星图边界：[食用酵母]-(原材料)->[啤酒]
INFO     检查到与“种植”骨干间的正确星图边界：[安琪酵母]-(生产)->[食用酵母]
INFO     检查到与“种植”骨干间的正确星图边界：[酒花]-(原材料)->[啤酒]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[糖料作物]-(原材料)->[食糖]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[调味品]-(父节点)->[单味调味品]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[调味品]-(父节点)->[复合调味品]
INFO     检查到与“种植”骨干间的正确星图边界：[调味品]-(父节点)->[味精]
INFO     检查到与“种植”骨干间的正确星图边界：[调味品]-(父节点)->[香料]
INFO     检查到与“种植”骨干间的正确星图边界：[恒顺醋业]-(生产)->[调味品]
INFO     检查到与“种植”骨干间的正确星图边界：[千禾味业]-(生产)->[调味品]
INFO     检查到与“种植”骨干间的正确星图边界：[仲景食品]-(生产)->[调味品]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[单味调味品]-(父节点)->[食糖]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[单味调味品]-(父节点)->[食盐]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[单味调味品]-(父节点)->[醋]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[单味调味品]-(父节点)->[酱油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[单味调味品]-(父节点)->[天然香辛料]
INFO     检查到与“种植”骨干间的正确星图边界：[金丹科技]-(生产)->[单味调味品]
INFO     检查到与“种植”骨干间的正确星图边界：[三元生物]-(生产)->[单味调味品]
INFO     检查到与“种植”骨干间的正确星图边界：[雪天盐业]-(生产)->[食盐]
INFO     检查到与“种植”骨干间的正确星图边界：[N江盐]-(生产)->[食盐]
INFO     检查到与“种植”骨干间的正确星图边界：[云图控股]-(生产)->[食盐]
INFO     检查到与“种植”骨干间的正确星图边界：[海天味业]-(生产)->[酱油]
INFO     检查到与“种植”骨干间的正确星图边界：[中炬高新]-(生产)->[酱油]
INFO     检查到与“种植”骨干间的正确星图边界：[加加食品]-(生产)->[酱油]
INFO     检查到与“种植”骨干间的正确星图边界：[食糖]-(原材料)->[糖果，巧克力]
INFO     检查到与“种植”骨干间的正确星图边界：[南宁糖业]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[中粮糖业]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[广州浪奇]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[华资实业]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[华康股份]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[华联国际]-(生产)->[食糖]
INFO     检查到与“种植”骨干间的正确星图边界：[亚香股份]-(生产)->[天然香辛料]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[复合调味品]-(父节点)->[风味酱料]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[复合调味品]-(父节点)->[汤料]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[复合调味品]-(父节点)->[蘸料涂料]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[复合调味品]-(父节点)->[复合香辛料]
INFO     检查到与“种植”骨干间的正确星图边界：[复合调味品]-(父节点)->[佐餐开味菜]
INFO     检查到与“种植”骨干间的正确星图边界：[天味食品]-(生产)->[风味酱料]
INFO     检查到与“种植”骨干间的正确星图边界：[日辰股份]-(生产)->[风味酱料]
INFO     检查到与“种植”骨干间的正确星图边界：[颐海国际]-(生产)->[风味酱料]
INFO     检查到与“种植”骨干间的正确星图边界：[仲景食品]-(生产)->[风味酱料]
INFO     检查到与“种植”骨干间的正确星图边界：[华宝股份]-(生产)->[复合香辛料]
INFO     检查到与“种植”骨干间的正确星图边界：[食品烟酒]-(父节点)->[食用油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[食用油]-(父节点)->[食用植物油]
INFO     检查到与“种植”骨干间的正确星图边界：[道道全]-(生产)->[食用油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[棕榈油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[大豆油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[玉米油]
INFO     检查到与“种植”骨干间的正确星图边界：[金龙鱼]-(生产)->[食用植物油]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[食用植物油]-(父节点)->[菜籽油]
INFO     检查到与“种植”骨干间的正确星图边界：[湘财股份]-(生产)->[食用植物油]
INFO     检查到与“种植”骨干间的正确星图边界：[中粮科工]-(生产)->[食用植物油]
INFO     检查到与“种植”骨干间的正确星图边界：[京粮控股]-(生产)->[食用植物油]
INFO     检查到与“种植”骨干间的正确星图边界：[棕榈油]-(原材料)->[膨化食品]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[DCE:棕榈油]-(反映)->[棕榈油]
INFO     检查到与“种植”骨干间的正确星图边界：[嘉华股份]-(生产)->[大豆油]
INFO     检查到与“种植”骨干间的正确星图边界：[西王食品]-(生产)->[玉米油]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[牛奶]-(原材料)->[乳制品]
WARNING  检查到本骨干之外的,属于“畜牧业”骨干的边，该边不参与冲突检查：[生鲜牛乳主产区均价]-(反映)->[牛奶]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[商品蛋]-(父节点)->[鲜鸡蛋]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[鲜鸡蛋]-(原材料)->[烘焙食品]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[商品蛋]-(父节点)->[鸭蛋]
INFO     检查到与“种植”骨干间的正确星图边界：[生鲜食品]-(父节点)->[水果]
INFO     检查到与“种植”骨干间的正确星图边界：[水果]-(原材料)->[蜜饯果干]
INFO     检查到与“种植”骨干间的正确星图边界：[食品烟酒]-(父节点)->[水果]
INFO     检查到与“种植”骨干间的正确星图边界：[水果]-(父节点)->[红枣]
INFO     检查到与“种植”骨干间的正确星图边界：[亚洲果业]-(生产)->[水果]
INFO     检查到与“种植”骨干间的正确星图边界：[洪九果品]-(生产)->[水果]
INFO     检查到与“种植”骨干间的正确星图边界：[生鲜食品]-(父节点)->[蔬菜]
INFO     检查到与“种植”骨干间的正确星图边界：[蔬菜]-(父节点)->[番茄制品]
INFO     检查到与“种植”骨干间的正确星图边界：[蔬菜]-(父节点)->[魔芋]
INFO     检查到与“种植”骨干间的正确星图边界：[中国万天控股]-(生产)->[蔬菜]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[肉类]-(父节点)->[冷冻肉]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[肉类]-(父节点)->[冷鲜肉]
CRITICAL 完成对 “食品饮料”  多维表格进行内部检查

good table

CRITICAL 对 “陆运”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 陆运
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢型材]-(父节点)->[钢轨]
ERROR    “整车物流”节点没有找到对应的外部骨干：“汽车”
INFO     检查到与“地产”骨干间的正确星图边界：[沥青]-(原材料)->[公路基础设施]
INFO     检查到与“地产”骨干间的正确星图边界：[水泥]-(原材料)->[公路基础设施]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[石油焦]-(原材料)->[公路基础设施]
INFO     检查到与“地产”骨干间的正确星图边界：[混凝土]-(原材料)->[轨道板]
ERROR    “货车”节点没有找到对应的外部骨干：“汽车”
ERROR    因“货车”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[货车]-(原材料)->[公路货运]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[冷藏车物流]-(储运)->[生鲜食品]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[冷藏车物流]-(储运)->[冷冻食品]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钢带]-(原材料)->[铁路桥梁]
CRITICAL 完成对 “陆运”  多维表格进行内部检查

good table

CRITICAL 对 “地产”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 地产
INFO     检查到与“银行”骨干间的正确星图边界：[个人定期储蓄]-(原材料)->[房地产销售回款]
INFO     检查到与“银行”骨干间的正确星图边界：[房地产外部融资]-(父节点)->[房地产开发贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款]-(父节点)->[长期租赁住房开发贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款]-(父节点)->[住宅开发贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款余额]-(反映)->[房地产开发贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[中长期贷款基准利率:1-3年]-(反映)->[房地产开发贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[个人贷款资金]-(父节点)->[个人住房贷款]
INFO     检查到与“银行”骨干间的正确星图边界：[个人活期储蓄]-(原材料)->[房地产销售回款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[个人住房贷款]-(父节点)->[公积金贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[个人住房贷款]-(父节点)->[个人住房商业性贷款]
INFO     检查到与“银行”骨干间的正确星图边界：[个人住房贷款]-(原材料)->[房地产销售回款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[贷款利率LPR：5年]-(反映)->[个人住房贷款]
WARNING  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[个人住房贷款余额]-(反映)->[个人住房贷款]
INFO     检查到与“钢铁”骨干间的正确星图边界：[建筑材料]-(父节点)->[型钢]
INFO     检查到与“钢铁”骨干间的正确星图边界：[有色金属材料]-(原材料)->[型钢]
INFO     检查到与“钢铁”骨干间的正确星图边界：[建筑材料]-(父节点)->[螺纹钢]
INFO     检查到与“钢铁”骨干间的正确星图边界：[建筑材料]-(父节点)->[结构钢管]
INFO     检查到与“海运”骨干间的正确星图边界：[干散货航运]-(储运)->[水泥]
INFO     检查到与“海运”骨干间的正确星图边界：[物产中大]-(生产)->[干散货航运]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成树脂]-(原材料)->[建筑涂料]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[家电零配件]-(原材料)->[家用电器]
INFO     检查到与“家居”骨干间的正确星图边界：[天银机电]-(生产)->[家电零配件]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[家具机械设备]-(原材料)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[家具]-(原材料)->[住宅装修]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[家具家居零售]-(储运)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[欧派家居]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[顾家家居]-(生产)->[家具]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[木材]-(原材料)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[皮阿诺]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[尚品宅配]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[志邦家居]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[海鸥住工]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[索菲亚]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[瑞尔特]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[帝欧家居]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[海象新材]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[德艺文创]-(生产)->[家具]
INFO     检查到与“家居”骨干间的正确星图边界：[顶固集创]-(生产)->[家具]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[家具家居零售]-(储运)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[美凯龙]-(生产)->[家具家居零售]
INFO     检查到与“家居”骨干间的正确星图边界：[居然之家]-(生产)->[家具家居零售]
INFO     检查到与“家居”骨干间的正确星图边界：[吉宏股份]-(生产)->[家具家居零售]
INFO     检查到与“家居”骨干间的正确星图边界：[富森美]-(生产)->[家具家居零售]
INFO     检查到与“家居”骨干间的正确星图边界：[家具机械设备]-(父节点)->[封边机]
INFO     检查到与“家居”骨干间的正确星图边界：[家具机械设备]-(父节点)->[裁板锯]
INFO     检查到与“家居”骨干间的正确星图边界：[家具机械设备]-(父节点)->[钻孔机]
INFO     检查到与“家居”骨干间的正确星图边界：[弘亚数控]-(生产)->[家具机械设备]
INFO     检查到与“家居”骨干间的正确星图边界：[南兴股份]-(生产)->[家具机械设备]
INFO     检查到与“家居”骨干间的正确星图边界：[家居装饰]-(原材料)->[住宅装修]
WARNING  检查到本骨干之外的,属于“家居”骨干的边，该边不参与冲突检查：[家居装饰]-(父节点)->[智能家居]
INFO     检查到与“家居”骨干间的正确星图边界：[箭牌家居]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[兔宝宝]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[友邦吊顶]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[皮阿诺]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[东鹏控股]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[趣睡科技]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[联翔股份]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[海鸥住工]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[郑中设计]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[名雕股份]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[美芝股份]-(生产)->[家居装饰]
INFO     检查到与“家居”骨干间的正确星图边界：[家用电器]-(原材料)->[住宅装修]
INFO     检查到与“家居”骨干间的正确星图边界：[美的集团]-(生产)->[家用电器]
INFO     检查到与“家居”骨干间的正确星图边界：[格力电器]-(生产)->[家用电器]
INFO     检查到与“家居”骨干间的正确星图边界：[四川长虹]-(生产)->[家用电器]
INFO     检查到与“种植”骨干间的正确星图边界：[永安林业]-(生产)->[木材]
INFO     检查到与“种植”骨干间的正确星图边界：[C森泰股份]-(生产)->[木材]
INFO     检查到与“钢铁”骨干间的正确星图边界：[起重机钢轨]-(原材料)->[起重机]
INFO     检查到与“电影”骨干间的正确星图边界：[商业房地产]-(原材料)->[院线放映]
INFO     检查到与“电影”骨干间的正确星图边界：[华联股份]-(生产)->[院线放映]
INFO     检查到与“电影”骨干间的正确星图边界：[嘉凯城]-(生产)->[院线放映]
INFO     检查到与“家居”骨干间的正确星图边界：[好太太]-(生产)->[智能家居]
INFO     检查到与“旅游”骨干间的正确星图边界：[商业房地产]-(原材料)->[住宿服务]
CRITICAL 完成对 “地产”  多维表格进行内部检查

CRITICAL 对 “区域图”  多维表格进行内部检查
CRITICAL 对 “区域图”  多维表格进行内部检查失败，错误信息：{'code': -1, 'msg': "查多维表格完整性失败，请确认包含节点表/关系表/监测指标表，并且给予星图编辑器可读权限    not all tables found, node,link,indicator :['tblrxmYuYGGHFvks', 'tbl9c8206O2uptEO', None, 'tblNJ40t82QzZtfi']"}

good table

CRITICAL 对 “纺织业”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 纺织业
INFO     检查到与“石油化工”骨干间的正确星图边界：[面料]-(父节点)->[化纤面料]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[化学纤维]-(原材料)->[化纤面料]
INFO     检查到与“石油化工”骨干间的正确星图边界：[常山北明]-(生产)->[化纤面料]
INFO     检查到与“种植”骨干间的正确星图边界：[天然纤维]-(父节点)->[棉]
INFO     检查到与“种植”骨干间的正确星图边界：[棉]-(原材料)->[再生纤维素纤维]
INFO     检查到与“种植”骨干间的正确星图边界：[联发股份]-(生产)->[棉]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[棉花期货价格]-(反映)->[棉]
INFO     检查到与“种植”骨干间的正确星图边界：[麻]-(原材料)->[麻布]
INFO     检查到与“种植”骨干间的正确星图边界：[天然纤维]-(父节点)->[麻]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[羊毛]-(原材料)->[呢绒]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[天然纤维]-(父节点)->[羊毛]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[猪皮]-(原材料)->[天然皮革]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[牛皮]-(原材料)->[天然皮革]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[羊皮]-(原材料)->[天然皮革]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[鸭绒]-(原材料)->[羽绒]
WARNING  检查到本骨干之外的,属于“畜牧业”骨干的边，该边不参与冲突检查：[白鸭绒(90%)价格]-(反映)->[鸭绒]
INFO     检查到与“畜牧业”骨干间的正确星图边界：[鹅绒]-(原材料)->[羽绒]
WARNING  检查到本骨干之外的,属于“畜牧业”骨干的边，该边不参与冲突检查：[白鹅绒(90%)价格]-(反映)->[鹅绒]
INFO     检查到与“石油化工”骨干间的正确星图边界：[化学纤维]-(原材料)->[混纺]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[化学纤维]-(父节点)->[合成纤维]
INFO     检查到与“石油化工”骨干间的正确星图边界：[化学纤维]-(父节点)->[人造纤维]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚酯纤维(涤纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚酰胺纤维(尼龙/锦纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚丙烯腈纤维(腈纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚乙烯醇缩醛纤维(维尼纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚氨酯纤维(氨纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚氯乙烯纤维(氯纶)]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成纤维]-(父节点)->[聚烯烃弹力纤维]
INFO     检查到与“种植”骨干间的正确星图边界：[木材]-(原材料)->[再生纤维素纤维]
INFO     检查到与“种植”骨干间的正确星图边界：[大豆]-(原材料)->[再生蛋白质纤维]
INFO     检查到与“种植”骨干间的正确星图边界：[玉米]-(原材料)->[再生蛋白质纤维]
INFO     检查到与“石油化工”骨干间的正确星图边界：[乙二醇]-(原材料)->[聚酯纤维(涤纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[煤制乙二醇工艺]-(原材料)->[乙二醇]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[乙烯制乙二醇工艺]-(原材料)->[乙二醇]
INFO     检查到与“石油化工”骨干间的正确星图边界：[对苯二甲酸PTA]-(原材料)->[聚酯纤维(涤纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[对二甲苯PX]-(原材料)->[对苯二甲酸PTA]
INFO     检查到与“石油化工”骨干间的正确星图边界：[东方盛虹]-(生产)->[对苯二甲酸PTA]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[对二甲苯酸市场价格]-(反映)->[对苯二甲酸PTA]
INFO     检查到与“石油化工”骨干间的正确星图边界：[己内酰胺]-(原材料)->[尼龙6]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[苯]-(原材料)->[己内酰胺]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[己内酰胺现货价]-(反映)->[己内酰胺]
INFO     检查到与“石油化工”骨干间的正确星图边界：[乙二胺]-(原材料)->[尼龙66]
INFO     检查到与“石油化工”骨干间的正确星图边界：[己二酸]-(原材料)->[尼龙66]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[苯]-(原材料)->[己二酸]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[己二酸现货价]-(反映)->[己二酸]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚四氢呋喃PTMG]-(原材料)->[聚氨酯纤维(氨纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[1,4丁二醇BDO]-(原材料)->[聚四氢呋喃PTMG]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[CCFEI价格指数:聚四亚甲基醚二醇PTMEG]-(反映)->[聚四氢呋喃PTMG]
INFO     检查到与“石油化工”骨干间的正确星图边界：[二苯基甲烷二异氰酸酯MDI]-(原材料)->[聚氨酯纤维(氨纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[苯]-(原材料)->[二苯基甲烷二异氰酸酯MDI]
INFO     检查到与“石油化工”骨干间的正确星图边界：[万华化学]-(生产)->[二苯基甲烷二异氰酸酯MDI]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[市场价:纯MDI:华东地区]-(反映)->[二苯基甲烷二异氰酸酯MDI]
INFO     检查到与“石油化工”骨干间的正确星图边界：[丙烯腈]-(原材料)->[聚丙烯腈纤维(腈纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[丙烯]-(原材料)->[丙烯腈]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[氨气]-(原材料)->[丙烯腈]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[烯烃]-(父节点)->[丙烯]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚氯乙烯]-(原材料)->[聚氯乙烯纤维(氯纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[乙烯]-(原材料)->[聚氯乙烯]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[氯气]-(原材料)->[聚氯乙烯]
INFO     检查到与“石油化工”骨干间的正确星图边界：[中泰化学]-(生产)->[聚氯乙烯]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[乙烯]-(原材料)->[乙烯制乙二醇工艺]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[乙烯]-(原材料)->[石油乙烯直接法]
INFO     检查到与“石油化工”骨干间的正确星图边界：[万华化学]-(生产)->[乙烯]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[烯烃]-(父节点)->[乙烯]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚乙烯醇PVA]-(原材料)->[聚乙烯醇缩醛纤维(维尼纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[石油乙烯直接法]-(原材料)->[聚乙烯醇PVA]
INFO     检查到与“石油化工”骨干间的正确星图边界：[乙炔法]-(原材料)->[聚乙烯醇PVA]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚烯烃]-(原材料)->[聚烯烃弹力纤维]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[烯烃]-(原材料)->[聚烯烃]
INFO     检查到与“石油化工”骨干间的正确星图边界：[甲醇]-(原材料)->[聚乙烯醇缩醛纤维(维尼纶)]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[甲醇]-(原材料)->[1,4丁二醇BDO]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[合成气]-(原材料)->[甲醇]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[乙炔]-(原材料)->[1,4丁二醇BDO]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[煤制苯法]-(原材料)->[苯]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[芳烃]-(父节点)->[苯]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[合成气]-(原材料)->[煤制乙二醇工艺]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[煤制甲醇法]-(原材料)->[合成气]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[石油制甲醇法]-(原材料)->[合成气]
INFO     检查到与“石油化工”骨干间的正确星图边界：[乙炔]-(原材料)->[乙炔法]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[混二甲苯MX]-(原材料)->[对二甲苯PX]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[芳烃]-(父节点)->[混二甲苯MX]
WARNING  检查到本骨干之外的,属于“煤炭”骨干的边，该边不参与冲突检查：[炼焦煤]-(原材料)->[煤制甲醇法]
WARNING  检查到本骨干之外的,属于“煤炭”骨干的边，该边不参与冲突检查：[煤焦油]-(原材料)->[煤制苯法]
INFO     检查到与“石油化工”骨干间的正确星图边界：[华峰化学]-(生产)->[聚氨酯原液]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚氨酯原液]-(原材料)->[鞋类原料]
INFO     检查到与“石油化工”骨干间的正确星图边界：[荣盛石化]-(生产)->[聚氨酯原液]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成橡胶]-(原材料)->[鞋类原料]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[对二甲苯价格]-(反映)->[对二甲苯PX]
INFO     检查到与“石油化工”骨干间的正确星图边界：[EVA]-(原材料)->[鞋类原料]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[原油]-(原材料)->[石油轻炼]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[WTI 原油期货结算价格]-(反映)->[原油]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[石油轻炼]-(原材料)->[化工轻油]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[化工轻油]-(原材料)->[石油制甲醇法]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[化工轻油]-(原材料)->[裂解反应]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[化工轻油]-(原材料)->[芳构化反应]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[芳构化反应]-(原材料)->[芳烃]
WARNING  检查到本骨干之外的,属于“石油化工”骨干的边，该边不参与冲突检查：[裂解反应]-(原材料)->[烯烃]
CRITICAL 完成对 “纺织业”  多维表格进行内部检查

good table

CRITICAL 对 “航空航天”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 航空航天
INFO     检查到与“半导体”骨干间的正确星图边界：[本川智能]-(生产)->[印制电路板]
INFO     检查到与“半导体”骨干间的正确星图边界：[覆铜板]-(原材料)->[印制电路板]
INFO     检查到与“半导体”骨干间的正确星图边界：[协和电子]-(生产)->[印制电路板]
INFO     检查到与“半导体”骨干间的正确星图边界：[印制电路板]-(原材料)->[航空电子]
INFO     检查到与“工业制造”骨干间的正确星图边界：[ST新研]-(生产)->[航空零部件]
INFO     检查到与“半导体”骨干间的正确星图边界：[铖昌科技]-(生产)->[电源管理模块]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[川大智胜]-(生产)->[航空管制系统]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[多伦科技]-(生产)->[通信服务]
INFO     检查到与“地产”骨干间的正确星图边界：[航天工程]-(生产)->[工业压力容器]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[航天科技]-(生产)->[惯性导航]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[航天科技]-(生产)->[加速度传感器]
INFO     检查到与“半导体”骨干间的正确星图边界：[景嘉微]-(生产)->[雷达]
INFO     检查到与“工业制造”骨干间的正确星图边界：[晶品特装]-(生产)->[光电侦察设备]
INFO     检查到与“工业制造”骨干间的正确星图边界：[利君股份]-(生产)->[航空零部件]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[迈信林]-(生产)->[电连接器]
INFO     检查到与“汽车制造”骨干间的正确星图边界：[迈信林]-(生产)->[航空零部件]
INFO     检查到与“电力储能”骨干间的正确星图边界：[四创电子]-(生产)->[雷达]
WARNING  检查到本骨干之外的,属于“地产”骨干的边，该边不参与冲突检查：[万方发展]-(生产)->[铝合金]
INFO     检查到与“半导体”骨干间的正确星图边界：[亚光科技]-(生产)->[射频器件]
INFO     检查到与“电力储能”骨干间的正确星图边界：[中航电测]-(生产)->[飞机]
INFO     检查到与“石油化工”骨干间的正确星图边界：[合成树脂]-(原材料)->[预浸料]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚丙烯腈]-(原材料)->[碳纤维预浸料]
INFO     检查到与“石油化工”骨干间的正确星图边界：[聚氯乙烯]-(原材料)->[隔热材料]
INFO     检查到与“半导体”骨干间的正确星图边界：[逻辑芯片]-(原材料)->[航空电子]
INFO     检查到与“钢铁”骨干间的正确星图边界：[铝合金]-(原材料)->[火箭发动机外壳]
INFO     检查到与“钢铁”骨干间的正确星图边界：[宝钛股份]-(生产)->[钛合金]
INFO     检查到与“钢铁”骨干间的正确星图边界：[钛合金]-(原材料)->[航空器外壳，航空器骨架]
CRITICAL 完成对 “航空航天”  多维表格进行内部检查

good table

CRITICAL 对 “畜牧业”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 畜牧业
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[大豆]-(原材料)->[大豆榨取]
WARNING  检查到本骨干之外的,属于“种植”骨干的边，该边不参与冲突检查：[大豆榨取]-(原材料)->[豆粕]
INFO     检查到与“种植”骨干间的正确星图边界：[玉米]-(原材料)->[能量原材料]
INFO     检查到与“种植”骨干间的正确星图边界：[小麦]-(原材料)->[能量原材料]
INFO     检查到与“种植”骨干间的正确星图边界：[高粱]-(原材料)->[能量原材料]
INFO     检查到与“种植”骨干间的正确星图边界：[豆粕]-(原材料)->[植物性蛋白]
INFO     检查到与“种植”骨干间的正确星图边界：[菜粕]-(原材料)->[植物性蛋白]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[牛奶]-(原材料)->[乳制品]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[伊利股份]-(生产)->[乳制品]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[鹅绒]-(原材料)->[羽绒]
INFO     检查到与“纺织业”骨干间的正确星图边界：[肉鸭]-(原材料)->[鸭绒]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[鸭绒]-(原材料)->[羽绒]
INFO     检查到与“纺织业”骨干间的正确星图边界：[ST华英]-(生产)->[鸭绒]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[牛皮]-(原材料)->[天然皮革]
INFO     检查到与“纺织业”骨干间的正确星图边界：[肉牛商品牛]-(原材料)->[牛皮]
INFO     检查到与“纺织业”骨干间的正确星图边界：[生猪；商品猪]-(原材料)->[猪皮]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[猪皮]-(原材料)->[天然皮革]
INFO     检查到与“纺织业”骨干间的正确星图边界：[巨星农牧]-(生产)->[猪皮]
INFO     检查到与“纺织业”骨干间的正确星图边界：[肉裘商品羊]-(原材料)->[羊皮]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[羊皮]-(原材料)->[天然皮革]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[羊毛]-(原材料)->[呢绒]
WARNING  检查到本骨干之外的,属于“纺织业”骨干的边，该边不参与冲突检查：[天然纤维]-(父节点)->[羊毛]
INFO     检查到与“纺织业”骨干间的正确星图边界：[肉裘商品羊]-(原材料)->[羊毛]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[鲜鸡蛋]-(原材料)->[烘焙食品]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[商品蛋]-(父节点)->[鲜鸡蛋]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[商品蛋]-(父节点)->[鸭蛋]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[晓鸣股份]-(生产)->[商品蛋]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[冷藏车物流]-(储运)->[冷冻肉]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[冷链储存]-(储运)->[冷冻肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[肉类]-(父节点)->[冷冻肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[华统股份]-(生产)->[冷冻肉]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[冷藏车物流]-(储运)->[冷鲜肉]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[冷链储存]-(储运)->[冷鲜肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[肉类]-(父节点)->[冷鲜肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[华统股份]-(生产)->[冷鲜肉]
WARNING  检查到本骨干之外的,属于“食品饮料”骨干的边，该边不参与冲突检查：[农贸市场]-(储运)->[热鲜肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[肉类]-(父节点)->[热鲜肉]
INFO     检查到与“食品饮料”骨干间的正确星图边界：[四方科技]-(生产)->[冷链储存]
WARNING  检查到本骨干之外的,属于“零售餐饮”骨干的边，该边不参与冲突检查：[线下零售渠道]-(父节点)->[农贸市场]
CRITICAL 完成对 “畜牧业”  多维表格进行内部检查

good table

CRITICAL 对 “美妆”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 美妆
CRITICAL 完成对 “美妆”  多维表格进行内部检查

good table

CRITICAL 对 “旅游”  多维表格进行内部检查
CRITICAL 本骨干标记：
CRITICAL 旅游
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"reczR4jhze",起点："游轮服务" 终点:"景区观光"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recb6GCgjC",起点："云顶香港" 终点:"游轮服务"
ERROR    出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"recnEMwED7",起点："休闲船艇" 终点:"游轮服务"
INFO     检查到与“地产”骨干间的正确星图边界：[商业房地产]-(原材料)->[住宿服务]
INFO     检查到与“地产”骨干间的正确星图边界：[华侨城A]-(生产)->[商业房地产]
INFO     检查到与“地产”骨干间的正确星图边界：[三湘印象]-(生产)->[商业房地产]
INFO     检查到与“地产”骨干间的正确星图边界：[新华联]-(生产)->[商业房地产]
INFO     检查到与“地产”骨干间的正确星图边界：[ 海南高速]-(生产)->[商业房地产]
INFO     检查到与“石油天然气”骨干间的正确星图边界：[航空汽油]-(原材料)->[航空运输]
WARNING  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[成品油]-(父节点)->[航空汽油]
ERROR    “客车”节点没有找到对应的外部骨干：“汽车”
ERROR    因“客车”节点没有找到对应外部骨干，与其相连的边也出错,不参与联调：[客车]-(原材料)->[景区观光]
INFO     检查到与“互联网云计算”骨干间的正确星图边界：[中科云网]-(生产)->[游戏]
INFO     检查到与“电影”骨干间的正确星图边界：[中视传媒]-(生产)->[影视制片]
CRITICAL 完成对 “旅游”  多维表格进行内部检查

CRITICAL 内部检查完成，以下表格出现问题不参与联调:['钠离子电池', '区域图']

{'I6SFbcZLnaNP8nscvFCcKDRknqf': {'internal_links': [{'bitapp_id': 'recuBdc461',
    'source': 'rec4F9dJLT',
    'source_name_ref': '原料药',
    'target_name_ref': '化学药',
    'target': 'rec4V0VCNn',
    'category': '原材料',
    'more_info': {},
    'target_name': '化学药',
    'source_name': '原料药'},
   {'bitapp_id': 'recylGEN8f',
    'source': 'rec6yDTGFq',
    'source_name_ref': '医药中间体',
    'target_name_ref': '原料药',
    'target': 'rec4F9dJLT',
    'category': '原材料',
    'more_info': {},
    'target_name': '原料药',
    'source_name': '医药中间体'},
   {'bitapp_id': 'recTXmCnXy',
    'source': 'recGqKtjof',
    'source_name_ref': '化合物研究服务',
    'target_name_ref': '药品配方',
    'target': 'recvrZmGcK',
    'category': '原材料',
    'more_info': {},
    'source_name': '化合物研究服务',
    'target_name': '药品配方'},
   {'bitapp_id': 'receAfFSC9',
    'source': 'rec3idm4QX',
    'source_name_ref': '试验用动物',
    'target_name_ref': '化合物研究服务',
    'target': 'recGqKtjof',
    'category': '原材料',
    'more_info': {},
    'target_name': '化合物研究服务',
    'source_name': '试验用动物'},
   {'bitapp_id': 'recMgxwc7B',
    'source': 'recI4DaBB3',
    'source_name_ref': '中药',
    'target_name_ref': '中成药',
    'target': 'recd9zjo4h',
    'category': '父节点',
    'more_info': {},
    'source_name': '中药',
    'target_name': '中成药'},
   {'bitapp_id': 'rec2zMHHxR',
    'source': 'recKlufH5w',
    'source_name_ref': '中药材',
    'target_name_ref': '中药',
    'target': 'recI4DaBB3',
    'category': '原材料',
    'more_info': {},
    'target_name': '中药',
    'source_name': '中药材'},
   {'bitapp_id': 'rec3A6s5P4',
    'source': 'recQF31lsq',
    'source_name_ref': '成品西药',
    'target_name_ref': '化学药',
    'target': 'rec4V0VCNn',
    'category': '父节点',
    'more_info': {},
    'target_name': '化学药',
    'source_name': '成品西药'},
   {'bitapp_id': 'recrBWGvOg',
    'source': 'recQF31lsq',
    'source_name_ref': '成品西药',
    'target_name_ref': '生物药',
    'target': 'recHgJHPYW',
    'category': '父节点',
    'more_info': {},
    'target_name': '生物药',
    'source_name': '成品西药'},
   {'bitapp_id': 'recbOaqrBy',
    'source': 'recA1cSIFC',
    'source_name_ref': '临床研究服务',
    'target_name_ref': '药品配方',
    'target': 'recvrZmGcK',
    'category': '原材料',
    'more_info': {},
    'source_name': '临床研究服务',
    'target_name': '药品配方'},
   {'bitapp_id': 'recvLeqc0Y',
    'source': 'reciZrgSDQ',
    'source_name_ref': '药品生产服务',
    'target_name_ref': '成品西药',
    'target': 'recQF31lsq',
    'category': '原材料',
    'more_info': {},
    'target_name': '成品西药',
    'source_name': '药品生产服务'},
   {'bitapp_id': 'reczeDqu7Q',
    'source': 'recvrZmGcK',
    'source_name_ref': '药品配方',
    'target_name_ref': '药品生产服务',
    'target': 'reciZrgSDQ',
    'category': '原材料',
    'more_info': {},
    'source_name': '药品配方',
    'target_name': '药品生产服务'},
   {'bitapp_id': 'recyESjWnP',
    'source': 'recGOeQiOx',
    'source_name_ref': 'CRO 服务',
    'target_name_ref': '化合物研究服务',
    'target': 'recGqKtjof',
    'category': '父节点',
    'more_info': {},
    'target_name': '化合物研究服务',
    'source_name': 'CRO 服务'},
   {'bitapp_id': 'recgbA33iw',
    'source': 'recGOeQiOx',
    'source_name_ref': 'CRO 服务',
    'target_name_ref': '临床研究服务',
    'target': 'recA1cSIFC',
    'category': '父节点',
    'more_info': {},
    'target_name': '临床研究服务',
    'source_name': 'CRO 服务'},
   {'bitapp_id': 'rec4HOXbzl',
    'source': 'recOIyyxha',
    'source_name_ref': 'CMO/CDMO 服务',
    'target_name_ref': '化合物研究服务',
    'target': 'recGqKtjof',
    'category': '父节点',
    'more_info': {},
    'target_name': '化合物研究服务',
    'source_name': 'CMO/CDMO 服务'},
   {'bitapp_id': 'rectCEW5G8',
    'source': 'recOIyyxha',
    'source_name_ref': 'CMO/CDMO 服务',
    'target_name_ref': '药品生产服务',
    'target': 'reciZrgSDQ',
    'category': '父节点',
    'more_info': {},
    'target_name': '药品生产服务',
    'source_name': 'CMO/CDMO 服务'},
   {'bitapp_id': 'recfPXTDlF',
    'source': 'recOIyyxha',
    'source_name_ref': 'CMO/CDMO 服务',
    'target_name_ref': '临床研究服务',
    'target': 'recA1cSIFC',
    'category': '父节点',
    'more_info': {},
    'target_name': '临床研究服务',
    'source_name': 'CMO/CDMO 服务'},
   {'bitapp_id': 'recJKHc0PI',
    'source': 'recI4DaBB3',
    'source_name_ref': '中药',
    'target_name_ref': '中药汤剂',
    'target': 'recqIjk1R0',
    'category': '父节点',
    'more_info': {},
    'source_name': '中药',
    'target_name': '中药汤剂'},
   {'bitapp_id': 'recH96Ahti',
    'source': 'recHgJHPYW',
    'source_name_ref': '生物药',
    'target_name_ref': '单克隆抗体',
    'target': 'recWLsQYeD',
    'category': '父节点',
    'more_info': {},
    'source_name': '生物药',
    'target_name': '单克隆抗体'},
   {'bitapp_id': 'recpaB861Z',
    'source': 'recHgJHPYW',
    'source_name_ref': '生物药',
    'target_name_ref': '重组蛋白',
    'target': 'rec4EHZrQC',
    'category': '父节点',
    'more_info': {},
    'source_name': '生物药',
    'target_name': '重组蛋白'},
   {'bitapp_id': 'recgNZwaHS',
    'source': 'recHgJHPYW',
    'source_name_ref': '生物药',
    'target_name_ref': '疫苗',
    'target': 'rec83wOg2I',
    'category': '父节点',
    'more_info': {},
    'source_name': '生物药',
    'target_name': '疫苗'},
   {'bitapp_id': 'rec6ikTaRg',
    'source': 'recHgJHPYW',
    'source_name_ref': '生物药',
    'target_name_ref': '血液制品',
    'target': 'rec4DdZMDw',
    'category': '父节点',
    'more_info': {},
    'source_name': '生物药',
    'target_name': '血液制品'},
   {'bitapp_id': 'recLjwY1WW',
    'source': 'rec83wOg2I',
    'source_name_ref': '疫苗',
    'target_name_ref': 'mRNA 疫苗',
    'target': 'recoEK7gXj',
    'category': '父节点',
    'more_info': {},
    'source_name': '疫苗',
    'target_name': 'mRNA 疫苗'},
   {'bitapp_id': 'recPmWaX7S',
    'source': 'recvrZmGcK',
    'source_name_ref': '药品配方',
    'target_name_ref': '创新药',
    'target': 'rechSpfAYs',
    'category': '原材料',
    'more_info': {},
    'source_name': '药品配方',
    'target_name': '创新药'},
   {'bitapp_id': 'recMyxij5o',
    'source': 'recWLsQYeD',
    'source_name_ref': '单克隆抗体',
    'target_name_ref': '抗体药物偶联物',
    'target': 'rec204jJXN',
    'category': '原材料',
    'more_info': {},
    'source_name': '单克隆抗体',
    'target_name': '抗体药物偶联物'},
   {'bitapp_id': 'recRYRRezO',
    'source': 'rec4EHZrQC',
    'source_name_ref': '重组蛋白',
    'target_name_ref': '酶抑制剂',
    'target': 'reciBik0I4',
    'category': '原材料',
    'more_info': {},
    'source_name': '重组蛋白',
    'target_name': '酶抑制剂'},
   {'bitapp_id': 'recRI7iaY4',
    'source': 'recI4DaBB3',
    'source_name_ref': '中药',
    'target_name_ref': '中药注射剂',
    'target': 'recxyUCKLK',
    'category': '父节点',
    'more_info': {},
    'source_name': '中药',
    'target_name': '中药注射剂'},
   {'bitapp_id': 'recRlaHDvv',
    'source': 'rec4DdZMDw',
    'source_name_ref': '血液制品',
    'target_name_ref': '细胞浓缩悬液',
    'target': 'recJGSZTAa',
    'category': '父节点',
    'more_info': {},
    'source_name': '血液制品',
    'target_name': '细胞浓缩悬液'},
   {'bitapp_id': 'recI2xXm0S',
    'source': 'rec4DdZMDw',
    'source_name_ref': '血液制品',
    'target_name_ref': '红细胞制品',
    'target': 'rec3hadBYo',
    'category': '父节点',
    'more_info': {},
    'source_name': '血液制品',
    'target_name': '红细胞制品'},
   {'bitapp_id': 'recptrX5gX',
    'source': 'rec4DdZMDw',
    'source_name_ref': '血液制品',
    'target_name_ref': '血蛋白制品',
    'target': 'rec02IHDfV',
    'category': '父节点',
    'more_info': {},
    'source_name': '血液制品',
    'target_name': '血蛋白制品'},
   {'bitapp_id': 'recRcLosuW',
    'source': 'recfWmPNug',
    'source_name_ref': '药物',
    'target_name_ref': '成品西药',
    'target': 'recQF31lsq',
    'category': '父节点',
    'more_info': {},
    'target_name': '成品西药',
    'source_name': '药物'},
   {'bitapp_id': 'recbLqabZu',
    'source': 'recfWmPNug',
    'source_name_ref': '药物',
    'target_name_ref': '中药',
    'target': 'recI4DaBB3',
    'category': '父节点',
    'more_info': {},
    'target_name': '中药',
    'source_name': '药物'},
   {'bitapp_id': 'reckVTyfIy',
    'source': 'recAq6vhgY',
    'source_name_ref': '科兴制药',
    'target_name_ref': '灭活疫苗',
    'target': 'reccucqY7W',
    'category': '生产',
    'more_info': {},
    'source_name': '科兴制药',
    'target_name': '灭活疫苗'},
   {'bitapp_id': 'recOxaLLUg',
    'source': 'rec83wOg2I',
    'source_name_ref': '疫苗',
    'target_name_ref': '灭活疫苗',
    'target': 'reccucqY7W',
    'category': '父节点',
    'more_info': {},
    'source_name': '疫苗',
    'target_name': '灭活疫苗'},
   {'bitapp_id': 'recwKetiRi',
    'source': 'rec83wOg2I',
    'source_name_ref': '疫苗',
    'target_name_ref': '腺病毒载体疫苗',
    'target': 'recjR71IG8',
    'category': '父节点',
    'more_info': {},
    'source_name': '疫苗',
    'target_name': '腺病毒载体疫苗'},
   {'bitapp_id': 'rec24vl9jm',
    'source': 'recMTXt6YK',
    'source_name_ref': '康希诺',
    'target_name_ref': '腺病毒载体疫苗',
    'target': 'recjR71IG8',
    'category': '生产',
    'more_info': {},
    'source_name': '康希诺',
    'target_name': '腺病毒载体疫苗'},
   {'bitapp_id': 'recGFoDf09',
    'source': 'recO3kC1y8',
    'source_name_ref': '凯莱英',
    'target_name_ref': 'CMO/CDMO 服务',
    'target': 'recOIyyxha',
    'category': '生产',
    'more_info': {},
    'target_name': 'CMO/CDMO 服务',
    'source_name': '凯莱英'},
   {'bitapp_id': 'rec5lrIRoc',
    'source': 'rec4V0VCNn',
    'source_name_ref': '化学药',
    'target_name_ref': '甾体药物',
    'target': 'rec5fAaoKu',
    'category': '父节点',
    'more_info': {},
    'source_name': '化学药',
    'target_name': '甾体药物'},
   {'bitapp_id': 'recbl0ytua',
    'source': 'reckycYl0C',
    'source_name_ref': '共同药业',
    'target_name_ref': '甾体药物',
    'target': 'rec5fAaoKu',
    'category': '生产',
    'more_info': {},
    'target_name': '甾体药物',
    'source_name': '共同药业'},
   {'bitapp_id': 'recQaJ1bUS',
    'source': 'recNVC2bMY',
    'source_name_ref': '智飞生物',
    'target_name_ref': '灭活疫苗',
    'target': 'reccucqY7W',
    'category': '生产',
    'more_info': {},
    'target_name': '灭活疫苗',
    'source_name': '智飞生物'},
   {'bitapp_id': 'rec0IKu6zp',
    'source': 'recVykFN4b',
    'source_name_ref': '舒泰神',
    'target_name_ref': '生长因子',
    'target': 'recH8xYNH1',
    'category': '生产',
    'more_info': {},
    'source_name': '舒泰神',
    'target_name': '生长因子'},
   {'bitapp_id': 'rech5Cai73',
    'source': 'recHgJHPYW',
    'source_name_ref': '生物药',
    'target_name_ref': '生物制剂',
    'target': 'recvgpyAA0',
    'category': '父节点',
    'more_info': {},
    'source_name': '生物药',
    'target_name': '生物制剂'},
   {'bitapp_id': 'rec3g1uBE5',
    'source': 'recvgpyAA0',
    'source_name_ref': '生物制剂',
    'target_name_ref': '生长因子',
    'target': 'recH8xYNH1',
    'category': '原材料',
    'more_info': {},
    'source_name': '生物制剂',
    'target_name': '生长因子'},
   {'bitapp_id': 'recD7T8UR2',
    'source': 'rec4EHZrQC',
    'source_name_ref': '重组蛋白',
    'target_name_ref': '全能核酸酶',
    'target': 'recROXSRKK',
    'category': '父节点',
    'more_info': {},
    'source_name': '重组蛋白',
    'target_name': '全能核酸酶'},
   {'bitapp_id': 'recau970q4',
    'source': 'recnu3Jd3j',
    'source_name_ref': '近岸蛋白',
    'target_name_ref': '全能核酸酶',
    'target': 'recROXSRKK',
    'category': '生产',
    'more_info': {},
    'target_name': '全能核酸酶',
    'source_name': '近岸蛋白'},
   {'bitapp_id': 'recdfW9ZJ6',
    'source': 'recnu3Jd3j',
    'source_name_ref': '近岸蛋白',
    'target_name_ref': 'mRNA 原料酶',
    'target': 'recJKqacuT',
    'category': '生产',
    'more_info': {},
    'target_name': 'mRNA 原料酶',
    'source_name': '近岸蛋白'},
   {'bitapp_id': 'recDlFwNOH',
    'source': 'rec4EHZrQC',
    'source_name_ref': '重组蛋白',
    'target_name_ref': '多肽',
    'target': 'recksjuVPt',
    'category': '父节点',
    'more_info': {},
    'source_name': '重组蛋白',
    'target_name': '多肽'},
   {'bitapp_id': 'recQXIjnIv',
    'source': 'rec57m0sxo',
    'source_name_ref': '翰宇药业',
    'target_name_ref': '多肽',
    'target': 'recksjuVPt',
    'category': '生产',
    'more_info': {},
    'target_name': '多肽',
    'source_name': '翰宇药业'},
   {'bitapp_id': 'recpKC1mXq',
    'source': 'recqIqnFRT',
    'source_name_ref': '医疗耗材',
    'target_name_ref': '介入学耗材',
    'target': 'recZhMWbVa',
    'category': '父节点',
    'more_info': {},
    'target_name': '介入学耗材',
    'source_name': '医疗耗材'},
   {'bitapp_id': 'recTrQj8xJ',
    'source': 'recZhMWbVa',
    'source_name_ref': '介入学耗材',
    'target_name_ref': '造影剂',
    'target': 'recQulchVv',
    'category': '父节点',
    'more_info': {},
    'source_name': '介入学耗材',
    'target_name': '造影剂'},
   {'bitapp_id': 'recdXUrfIF',
    'source': 'recqIqnFRT',
    'source_name_ref': '医疗耗材',
    'target_name_ref': '植入类耗材',
    'target': 'recCFpjAOU',
    'category': '父节点',
    'more_info': {},
    'target_name': '植入类耗材',
    'source_name': '医疗耗材'},
   {'bitapp_id': 'recIBqnJzV',
    'source': 'recZhMWbVa',
    'source_name_ref': '介入学耗材',
    'target_name_ref': '血管腔扩张用器械',
    'target': 'recrwylQEP',
    'category': '父节点',
    'more_info': {},
    'source_name': '介入学耗材',
    'target_name': '血管腔扩张用器械'},
   {'bitapp_id': 'rece77iLAf',
    'source': 'recrwylQEP',
    'source_name_ref': '血管腔扩张用器械',
    'target_name_ref': '血管内支架',
    'target': 'recdnBhx4u',
    'category': '父节点',
    'more_info': {},
    'source_name': '血管腔扩张用器械',
    'target_name': '血管内支架'},
   {'bitapp_id': 'recPycybN6',
    'source': 'recZhMWbVa',
    'source_name_ref': '介入学耗材',
    'target_name_ref': '穿刺器械',
    'target': 'recQPJLQw6',
    'category': '父节点',
    'more_info': {},
    'source_name': '介入学耗材',
    'target_name': '穿刺器械'},
   {'bitapp_id': 'receJCrXTh',
    'source': 'recrwylQEP',
    'source_name_ref': '血管腔扩张用器械',
    'target_name_ref': '血管内用导管',
    'target': 'recidiJ7Kb',
    'category': '父节点',
    'more_info': {},
    'source_name': '血管腔扩张用器械',
    'target_name': '血管内用导管'},
   {'bitapp_id': 'reciee2bhz',
    'source': 'rec0Tn0Rjh',
    'source_name_ref': '医疗设备',
    'target_name_ref': '医疗监护设备',
    'target': 'recvGeKD0K',
    'category': '父节点',
    'more_info': {},
    'source_name': '医疗设备',
    'target_name': '医疗监护设备'},
   {'bitapp_id': 'rechuCNwRC',
    'source': 'recvGeKD0K',
    'source_name_ref': '医疗监护设备',
    'target_name_ref': '呼吸机',
    'target': 'recDWv7QyH',
    'category': '父节点',
    'more_info': {},
    'source_name': '医疗监护设备',
    'target_name': '呼吸机'},
   {'bitapp_id': 'recEnEVaqG',
    'source': 'rec0Tn0Rjh',
    'source_name_ref': '医疗设备',
    'target_name_ref': '医学检测设备',
    'target': 'recXQqajPC',
    'category': '父节点',
    'more_info': {},
    'source_name': '医疗设备',
    'target_name': '医学检测设备'},
   {'bitapp_id': 'receia83V0',
    'source': 'recXQqajPC',
    'source_name_ref': '医学检测设备',
    'target_name_ref': '基因测序设备',
    'target': 'recwB66uPm',
    'category': '父节点',
    'more_info': {},
    'source_name': '医学检测设备',
    'target_name': '基因测序设备'},
   {'bitapp_id': 'rec1qVNR1S',
    'source': 'rec0Tn0Rjh',
    'source_name_ref': '医疗设备',
    'target_name_ref': '诊疗设备',
    'target': 'recbxUTyEZ',
    'category': '父节点',
    'more_info': {},
    'source_name': '医疗设备',
    'target_name': '诊疗设备'},
   {'bitapp_id': 'recngF83r5',
    'source': 'recbxUTyEZ',
    'source_name_ref': '诊疗设备',
    'target_name_ref': '超声诊疗设备',
    'target': 'recnssTdxh',
    'category': '父节点',
    'more_info': {},
    'source_name': '诊疗设备',
    'target_name': '超声诊疗设备'},
   {'bitapp_id': 'rec8lRdUhO',
    'source': 'recbxUTyEZ',
    'source_name_ref': '诊疗设备',
    'target_name_ref': '光学诊疗设备',
    'target': 'rec27s6X2u',
    'category': '父节点',
    'more_info': {},
    'source_name': '诊疗设备',
    'target_name': '光学诊疗设备'},
   {'bitapp_id': 'rec5Erw7BB',
    'source': 'recC8iuDWr',
    'source_name_ref': '医疗器械',
    'target_name_ref': '医疗设备',
    'target': 'rec0Tn0Rjh',
    'category': '父节点',
    'more_info': {},
    'source_name': '医疗器械',
    'target_name': '医疗设备'},
   {'bitapp_id': 'recN19QjRD',
    'source': 'recqIqnFRT',
    'source_name_ref': '医疗耗材',
    'target_name_ref': '外科常用导管',
    'target': 'recEF6UwtM',
    'category': '父节点',
    'more_info': {},
    'target_name': '外科常用导管',
    'source_name': '医疗耗材'},
   {'bitapp_id': 'recFn0xHrf',
    'source': 'recEF6UwtM',
    'source_name_ref': '外科常用导管',
    'target_name_ref': '导尿管',
    'target': 'recXURq0Vl',
    'category': '父节点',
    'more_info': {},
    'source_name': '外科常用导管',
    'target_name': '导尿管'},
   {'bitapp_id': 'rec2uy4bP4',
    'source': 'recCFpjAOU',
    'source_name_ref': '植入类耗材',
    'target_name_ref': '人工心脏瓣膜',
    'target': 'recKVCQlKP',
    'category': '父节点',
    'more_info': {},
    'source_name': '植入类耗材',
    'target_name': '人工心脏瓣膜'},
   {'bitapp_id': 'recIG4f2MK',
    'source': 'recbxUTyEZ',
    'source_name_ref': '诊疗设备',
    'target_name_ref': '电生理诊疗设备',
    'target': 'recEXpu1iQ',
    'category': '父节点',
    'more_info': {},
    'source_name': '诊疗设备',
    'target_name': '电生理诊疗设备'},
   {'bitapp_id': 'recevTYn6o',
    'source': 'rec27s6X2u',
    'source_name_ref': '光学诊疗设备',
    'target_name_ref': '硬性内窥镜',
    'target': 'rec6x8HhEA',
    'category': '父节点',
    'more_info': {},
    'source_name': '光学诊疗设备',
    'target_name': '硬性内窥镜'},
   {'bitapp_id': 'recIrqDeVk',
    'source': 'rec27s6X2u',
    'source_name_ref': '光学诊疗设备',
    'target_name_ref': '软性内窥镜',
    'target': 'recNtDd1yP',
    'category': '父节点',
    'more_info': {},
    'source_name': '光学诊疗设备',
    'target_name': '软性内窥镜'},
   {'bitapp_id': 'rec8a15okg',
    'source': 'rec9DHNSnT',
    'source_name_ref': '澳华内镜',
    'target_name_ref': '硬性内窥镜',
    'target': 'rec6x8HhEA',
    'category': '生产',
    'more_info': {},
    'target_name': '硬性内窥镜',
    'source_name': '澳华内镜'},
   {'bitapp_id': 'recM7d5lgs',
    'source': 'recrfdelnK',
    'source_name_ref': '开立医疗',
    'target_name_ref': '软性内窥镜',
    'target': 'recNtDd1yP',
    'category': '生产',
    'more_info': {},
    'target_name': '软性内窥镜',
    'source_name': '开立医疗'},
   {'bitapp_id': 'recxMSzt0r',
    'source': 'rec5ZE3vh1',
    'source_name_ref': 'FPGA 芯片',
    'target_name_ref': '光学诊疗设备',
    'target': 'rec27s6X2u',
    'category': '原材料',
    'more_info': {},
    'target_name': '光学诊疗设备',
    'source_name': 'FPGA 芯片'},
   {'bitapp_id': 'recXCnXuSN',
    'source': 'recSSfMWdm',
    'source_name_ref': 'CMOS 芯片',
    'target_name_ref': '光学诊疗设备',
    'target': 'rec27s6X2u',
    'category': '原材料',
    'more_info': {},
    'target_name': '光学诊疗设备',
    'source_name': 'CMOS 芯片'},
   {'bitapp_id': 'recgbPaixk',
    'source': 'recqZTXTdZ',
    'source_name_ref': '微电生理',
    'target_name_ref': '心脏电生理设备',
    'target': 'recDYDloNM',
    'category': '生产',
    'more_info': {},
    'source_name': '微电生理',
    'target_name': '心脏电生理设备'},
   {'bitapp_id': 'recpHxIQEX',
    'source': 'recEXpu1iQ',
    'source_name_ref': '电生理诊疗设备',
    'target_name_ref': '心脏电生理设备',
    'target': 'recDYDloNM',
    'category': '父节点',
    'more_info': {},
    'source_name': '电生理诊疗设备',
    'target_name': '心脏电生理设备'},
   {'bitapp_id': 'recL5m1NXc',
    'source': 'recEXpu1iQ',
    'source_name_ref': '电生理诊疗设备',
    'target_name_ref': '心脏电生理导管',
    'target': 'rec3GI8oOS',
    'category': '父节点',
    'more_info': {},
    'source_name': '电生理诊疗设备',
    'target_name': '心脏电生理导管'},
   {'bitapp_id': 'recf3DJV4h',
    'source': 'recqZTXTdZ',
    'source_name_ref': '微电生理',
    'target_name_ref': '心脏电生理导管',
    'target': 'rec3GI8oOS',
    'category': '生产',
    'more_info': {},
    'source_name': '微电生理',
    'target_name': '心脏电生理导管'},
   {'bitapp_id': 'recLMbCzIm',
    'source': 'recCFpjAOU',
    'source_name_ref': '植入类耗材',
    'target_name_ref': '关节假体',
    'target': 'recGqbbLt9',
    'category': '父节点',
    'more_info': {},
    'source_name': '植入类耗材',
    'target_name': '关节假体'},
   {'bitapp_id': 'recqjhxW4e',
    'source': 'recCFpjAOU',
    'source_name_ref': '植入类耗材',
    'target_name_ref': '脊柱固定器',
    'target': 'rec1ZiNRLm',
    'category': '父节点',
    'more_info': {},
    'source_name': '植入类耗材',
    'target_name': '脊柱固定器'},
   {'bitapp_id': 'rec9b37E4I',
    'source': 'recEYUMVpN',
    'source_name_ref': '春立医疗',
    'target_name_ref': '关节假体',
    'target': 'recGqbbLt9',
    'category': '生产',
    'more_info': {},
    'target_name': '关节假体',
    'source_name': '春立医疗'},
   {'bitapp_id': 'recgwgtd0S',
    'source': 'recEYUMVpN',
    'source_name_ref': '春立医疗',
    'target_name_ref': '脊柱固定器',

In [18]:
result,report_df=work2(internal_result,files,report_df)

CRITICAL 开始外部联调，参与表格为：
CRITICAL ['医药', '钠离子电池', '通信', '半导体', '锂离子电池', '工业制造', '钢铁', '光伏', '煤炭', '电力储能', '风电', '贵金属', '海运', '消费电子', '种植', '汽车制造', '教育', '零售餐饮', '广告传媒', '石油天然气', '银行', '石油化工', '互联网云计算', '家居', '环保', '矿产', '电影', '食品饮料', '陆运', '地产', '区域图', '纺织业', '航空航天', '畜牧业', '美妆', '旅游']

CRITICAL 对标记为"医药"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 医药
CRITICAL 完成对标记为"医药"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"通信"的表格的边界进行检查,该表共有3条外边参与联调
CRITICAL 通信
ERROR    星图边界识别失败，该边："互联网数据中心--原材料->宽带通信服务"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："手机--原材料->移动通信需求"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天线模块--原材料->手机"在对应"消费电子"骨干中没找到对应边界
CRITICAL 完成对标记为"通信"的表格的边界进行检查,该表共有3条外边参与联调，通过边0条，冲突边3条

CRITICAL 对标记为"半导体"的表格的边界进行检查,该表共有73条外边参与联调
CRITICAL 半导体
ERROR    星图边界识别失败，该边："创益通--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电连技术--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中航光电--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天电器--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："维峰电子--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："珠城科技--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："奕东电子--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："胜蓝股份--生产->电连接器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广信材料--生产->涂料"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广信材料--生产->光刻胶"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天长峰--生产->信息安全芯片"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天长峰--生产->通信芯片"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天长峰--生产->电源管理模块"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："明微电子--生产->LED模组"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："明微电子--生产->电源管理芯片，电源管理IC"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："纳睿雷达--生产->通信芯片"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欧比特--生产->通信芯片"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："乾照光电--生产->LED模组"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："石英股份--生产->高纯石英砂"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："苏州固锝--生产->半导体分立器件"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："微导纳米--生产->芯片封装测试设备"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："微导纳米--生产->半导体薄膜沉积设备"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："正帆科技--生产->半导体制造设备"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："正帆科技--生产->电子特种气体"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："臻镭科技--生产->通信芯片"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："臻镭科技--生产->射频模组"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中航电测--生产->半导体传感器"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："AC/DC交流-直流转换器--原材料->充电器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："固德威--生产->储能逆变器"在对应"电力储能"骨干中没找到对应边界
INFO     星图边界识别成功，在"电力储能"骨干中查到对应边："功率模块--原材料->储能逆变器"
INFO     星图边界识别成功，在"互联网云计算"骨干中查到对应边："ROM--原材料->存储服务器"
INFO     星图边界识别成功，在"电力储能"骨干中查到对应边："功率模块--原材料->电力逆变器"
ERROR    星图边界识别失败，该边："有研硅--生产->多晶硅料"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："神工股份--生产->多晶硅料"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中晶科技--生产->多晶硅料"在对应"光伏"骨干中没找到对应边界
INFO     星图边界识别成功，在"光伏"骨干中查到对应边："多晶硅料--原材料->半导体级单晶硅片"
INFO     星图边界识别成功，在"风电"骨干中查到对应边："IGBT模块--原材料->风电变流器"
ERROR    星图边界识别失败，该边："芯片，集成电路，IC--父节点->工业IC"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："东软载波--生产->工业MCU"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："恒烁股份--生产->工业MCU"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："乐鑫科技--生产->工业MCU"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："芯海科技--生产->工业MCU"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中颖电子--生产->工业MCU"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："*ST紫晶--生产->工业存储"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："复旦微电--生产->工业存储"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："佰维存储--生产->工业存储"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："威贸电子--生产->工业生产线"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："至纯科技--生产->光传感器"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："法尔胜--生产->光传感器"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："光莆股份--生产->光传感器"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："南大光电--生产->光传感器"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："固德威--生产->光伏逆变器"在对应"光伏"骨干中没找到对应边界
INFO     星图边界识别成功，在"光伏"骨干中查到对应边："IGBT模块--原材料->光伏逆变器"
INFO     星图边界识别成功，在"航空航天"骨干中查到对应边："逻辑芯片--原材料->航空电子"
ERROR    星图边界识别失败，该边："LDO，低压线性稳压器--原材料->摄像头"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："昀冢科技--生产->摄像头"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："DC/DC直流-直流转换器--原材料->数码相机"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："经纬辉开--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："艾比森--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："清越科技--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："光罩，光掩膜基板--原材料->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："长信科技--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："凯盛科技--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："彩虹股份--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："龙腾光电--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："和辉光电-U--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："深科达--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："冠石科技--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："翰博高新--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："联得装备--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："ST星星--生产->显示器"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："汽车电子--原材料->新能源汽车"在对应"汽车制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："DC/DC直流-直流转换器--原材料->智能手机"在对应"消费电子"骨干中没找到对应边界
CRITICAL 完成对标记为"半导体"的表格的边界进行检查,该表共有73条外边参与联调，通过边7条，冲突边66条

CRITICAL 对标记为"锂离子电池"的表格的边界进行检查,该表共有51条外边参与联调
CRITICAL 锂离子电池
INFO     星图边界识别成功，在"电力储能"骨干中查到对应边："储能电池--父节点->储能锂电池"
ERROR    星图边界识别失败，该边："孚能科技--生产->储能电池"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池后段设备--父节点->化成分容设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池后段设备--父节点->电池组装设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池后段设备--父节点->电池检测设备"在对应"工业制造"骨干中没找到对应边界

{'bitapp_id': 'rectDUbCoD', 'source': 'recOSjwToq', 'source_name_ref': '功率模块', 'target_name_ref': '储能逆变器', 'category': '原材料', 'more_info': {}, 'target_name': '储能逆变器', 'source_name': '功率模块', 'external_backbone_name': '电力储能', 'external_backbone': 'bascnsACceveT2H48fktBz3xK7f'}
{'bitapp_id': 'recDNWOrhe', 'source_name_ref': '功率模块', 'target_name_ref': '储能逆变器', 'target': 'recNYsT9kW', 'category': '原材料', 'more_info': {}, 'target_name': '储能逆变器', 'source_name': '功率模块', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'rec7KW9GWC', 'source': 'rec4i53UgC', 'source_name_ref': 'ROM', 'target_name_ref': '存储服务器', 'category': '原材料', 'more_info': {}, 'source_name': 'ROM', 'target_name': '存储服务器', 'external_backbone_name': '互联网云计算', 'external_backbone': 'bascnX3JNXBB9J428M3qHmJv1Me'}
{'bitapp_id': 'reczzGzIkM', 'source_name_ref': 'ROM', 'target_name_ref': '存储服务器', 'target': 'recqS3IYxB', 'category': '原材料', 'more_info': {}, 'target_name': '存储服务器', 'source_name': 'ROM', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'recXsMNYuB', 'source': 'recOSjwToq', 'source_name_ref': '功率模块', 'target_name_ref': '电力逆变器', 'category': '原材料', 'more_info': {}, 'target_name': '电力逆变器', 'source_name': '功率模块', 'external_backbone_name': '电力储能', 'external_backbone': 'bascnsACceveT2H48fktBz3xK7f'}
{'bitapp_id': 'recFMyeKeu', 'source_name_ref': '功率模块', 'target_name_ref': '电力逆变器', 'target': 'rec2TMDBDy', 'category': '原材料', 'more_info': {}, 'target_name': '电力逆变器', 'source_name': '功率模块', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'rec1n6VR6G', 'source': 'recT1s9Fon', 'source_name_ref': 'IGBT模块', 'target_name_ref': '风电变流器', 'category': '原材料', 'more_info': {}, 'source_name': 'IGBT模块', 'target_name': '风电变流器', 'external_backbone_name': '风电', 'external_backbone': 'bascn5vPLSXteiWCaBOBYxoN8Vh'}
{'bitapp_id': 'recgebUC92', 'source_name_ref': 'IGBT模块', 'target_name_ref': '风电变流器', 'target': 'recnanvQW1', 'category': '原材料', 'more_info': {}, 'source_name': 'IGBT模块', 'target_name': '风电变流器', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'recySgppxm', 'source': 'recT1s9Fon', 'source_name_ref': 'IGBT模块', 'target_name_ref': '光伏逆变器', 'category': '原材料', 'more_info': {}, 'source_name': 'IGBT模块', 'target_name': '光伏逆变器', 'external_backbone_name': '光伏', 'external_backbone': 'bascngo31Pi722JP5rBWEMgQL4e'}
{'bitapp_id': 'recIbvGwCk', 'source_name_ref': 'IGBT模块', 'target_name_ref': '光伏逆变器', 'target': 'recNqvAvzl', 'category': '原材料', 'more_info': {}, 'target_name': '光伏逆变器', 'source_name': 'IGBT模块', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'recCy67ZtB', 'source': 'recwKL6UQI', 'source_name_ref': '逻辑芯片', 'target_name_ref': '航空电子', 'category': '原材料', 'more_info': {}, 'target_name': '航空电子', 'source_name': '逻辑芯片', 'external_backbone_name': '航空航天', 'external_backbone': 'bascn7y2rkPgE6WpXTxT8K93OHb'}
{'bitapp_id': 'rec2zMHHxR', 'source_name_ref': '逻辑芯片', 'target_name_ref': '航空电子', 'target': 'rec2HvUMLw', 'category': '原材料', 'more_info': {}, 'target_name': '航空电子', 'source_name': '逻辑芯片', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}

ERROR    星图边界识别失败，该边："电池后段设备--原材料->锂电池模组"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池后段设备--原材料->锂离子电池"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："杭可科技--生产->电池后段设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华自科技--生产->电池后段设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："星云股份--生产->电池后段设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--原材料->锂电池正极极片"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--原材料->锂电池负极极片"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--父节点->涂布机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--父节点->真空搅拌机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--父节点->辊压机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--父节点->分切机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池前段设备--父节点->制片机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海目星--生产->电池前段设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："金银河--生产->电池前段设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池中段设备--父节点->卷绕机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池中段设备--父节点->叠片机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池中段设备--父节点->电芯入壳机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池中段设备--父节点->注液机"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池中段设备--原材料->锂电池电芯"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海目星--生产->电池中段设备"在对应"工业制造"骨干中没找到对应边界
INFO     星图边界识别成功，在"汽车制造"骨干中查到对应边："动力锂电池--原材料->电源系统"
ERROR    星图边界识别失败，该边："聚丙烯--原材料->干法隔膜"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："聚乙烯--原材料->湿法隔膜"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利元亨--生产->锂电池生产设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："先导智能--生产->锂电池生产设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："星云股份--生产->锂电池生产设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂电池生产设备--父节点->激光焊切设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂精矿--原材料->碳酸锂"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂精矿--原材料->氢氧化锂"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："融捷股份--生产->锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："盛新锂能--生产->锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天齐锂业--生产->锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中矿资源--生产->锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天齐锂业--生产->锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："融捷股份--生产->锂矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："江特电机--生产->锂云母精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂云母精矿--原材料->碳酸锂"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："永兴材料--生产->锂云母精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："隔膜--原材料->钠离子电池电芯"所对应的"钠离子电池"骨干没有经过内部检查，这是对应骨干而非本边的问题
ERROR    星图边界识别失败，该边："隔膜--原材料->钠离子电池电芯"在对应"钠离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："消费电子--父节点->手机、电脑"在对应"消费电子"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："储能锂电池--原材料->通信基站"在对应"通信"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："膜产品--原材料->盐湖锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："提锂剂--原材料->盐湖锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："西藏城投--生产->盐湖锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："西藏矿业--生产->盐湖锂精矿"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："盐湖锂精矿--原材料->碳酸锂"在对应"矿产"骨干中没找到对应边界
CRITICAL 完成对标记为"锂离子电池"的表格的边界进行检查,该表共有51条外边参与联调，通过边2条，冲突边50条

CRITICAL 对标记为"工业制造"的表格的边界进行检查,该表共有1条外边参与联调
CRITICAL 工业制造
ERROR    星图边界识别失败，该边："工业IC--原材料->工业网络设备"在对应"半导体"骨干中没找到对应边界
CRITICAL 完成对标记为"工业制造"的表格的边界进行检查,该表共有1条外边参与联调，通过边0条，冲突边1条

CRITICAL 对标记为"钢铁"的表格的边界进行检查,该表共有28条外边参与联调
CRITICAL 钢铁
INFO     星图边界识别成功，在"陆运"骨干中查到对应边："钢型材--父节点->钢轨"
ERROR    星图边界识别失败，该边："铁路货运--储运->钢材"在对应"陆运"骨干中没找到对应边界
INFO     星图边界识别成功，在"地产"骨干中查到对应边："建筑材料--父节点->型钢"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："建筑材料--父节点->结构钢管"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："建筑材料--父节点->螺纹钢"
ERROR    星图边界识别失败，该边："钢带--原材料->汽车密封条"在对应"汽车制造"骨干中没找到对应边界

{'bitapp_id': 'recOghMvMS', 'source': 'recE3vQsGy', 'source_name_ref': '动力锂电池', 'target_name_ref': '电源系统', 'category': '原材料', 'more_info': {}, 'target_name': '电源系统', 'source_name': '动力锂电池', 'external_backbone_name': '汽车制造', 'external_backbone': 'bascnIRb34I8uajC8l70BZYtrYe'}
{'bitapp_id': 'recJPVmIlE', 'source_name_ref': '动力锂电池', 'target_name_ref': '电源系统', 'target': 'recl9QXaoE', 'category': '原材料', 'more_info': {}, 'target_name': '电源系统', 'source_name': '动力锂电池', 'external_backbone_name': '锂离子电池', 'external_backbone': 'ZG1YbzKjQaPjIpsmk9NcSTBZnag'}
{'bitapp_id': 'recoDDOreA', 'source': 'recSPgKJKd', 'source_name_ref': '钢型材', 'target_name_ref': '钢轨', 'category': '父节点', 'more_info': {}, 'source_name': '钢型材', 'target_name': '钢轨', 'external_backbone_name': '陆运', 'external_backbone': 'bascnipf2OKC7NYIMkWvAe5Fwhf'}
{'bitapp_id': 'recTXmCnXy', 'source_name_ref': '钢型材', 'target_name_ref': '钢轨', 'target': 'recE3vQsGy', 'category': '父节点', 'more_info': {}, 'target_name': '钢轨', 'source_name': '钢型材', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}

INFO     星图边界识别成功，在"陆运"骨干中查到对应边："钢带--原材料->铁路桥梁"
ERROR    星图边界识别失败，该边："轧钢板--原材料->汽车骨架"在对应"汽车制造"骨干中没找到对应边界
INFO     星图边界识别成功，在"海运"骨干中查到对应边："轧钢板--原材料->集装箱"
ERROR    星图边界识别失败，该边："余热锅炉--原材料->电力"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钨铁--原材料->炼钢"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："不锈钢--原材料->医疗器械"在对应"医药"骨干中没找到对应边界
INFO     星图边界识别成功，在"海运"骨干中查到对应边："干散货航运--储运->铁矿石"
ERROR    星图边界识别失败，该边："港口--储运->铁矿石"在对应"海运"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："型钢--原材料->船舶"在对应"海运"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铝合金--原材料->船舶"在对应"海运"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铸件，锻件--父节点->医疗器械零部件"在对应"医药"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铝合金--原材料->高压导线"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铝铜合金--原材料->航天器零部件"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："白铜--原材料->精密机械"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："青铜--原材料->轴承"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铸件，锻件--父节点->航空发动机零部件"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钛合金--原材料->航空发动机零部件"在对应"航空航天"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铝合金--原材料->航空器外壳，航空器骨架"在对应"航空航天"骨干中没找到对应边界
INFO     星图边界识别成功，在"航空航天"骨干中查到对应边："钛合金--原材料->航空器外壳，航空器骨架"
ERROR    星图边界识别失败，该边："钢材--原材料->风塔"在对应"风电"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："无缝钢管--原材料->风电轴承"在对应"风电"骨干中没找到对应边界
INFO     星图边界识别成功，在"煤炭"骨干中查到对应边："焦炭--原材料->高炉炼铁"
CRITICAL 完成对标记为"钢铁"的表格的边界进行检查,该表共有28条外边参与联调，通过边9条，冲突边19条

CRITICAL 对标记为"光伏"的表格的边界进行检查,该表共有5条外边参与联调
CRITICAL 光伏
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："IGBT模块--原材料->光伏逆变器"
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："多晶硅料--原材料->半导体级单晶硅片"
ERROR    星图边界识别失败，该边："电化学储能站--原材料->光伏电站"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："科士达--生产->光伏逆变器"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："逆变器--父节点->储能逆变器"在对应"电力储能"骨干中没找到对应边界
CRITICAL 完成对标记为"光伏"的表格的边界进行检查,该表共有5条外边参与联调，通过边2条，冲突边3条

{'bitapp_id': 'recWVoT1Lz', 'source': 'recd8HFblF', 'source_name_ref': '钢带', 'target_name_ref': '铁路桥梁', 'category': '原材料', 'more_info': {}, 'source_name': '钢带', 'target_name': '铁路桥梁', 'external_backbone_name': '陆运', 'external_backbone': 'bascnipf2OKC7NYIMkWvAe5Fwhf'}
{'bitapp_id': 'recVTeHAc1', 'source_name_ref': '钢带', 'target_name_ref': '铁路桥梁', 'target': 'recoBIz2VC', 'category': '原材料', 'more_info': {}, 'target_name': '铁路桥梁', 'source_name': '钢带', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'recy1MoRyQ', 'source': 'recGQWRrVP', 'source_name_ref': '轧钢板', 'target_name_ref': '集装箱', 'category': '原材料', 'more_info': {}, 'source_name': '轧钢板', 'target_name': '集装箱', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recDULHoC4', 'source_name_ref': '轧钢板', 'target_name_ref': '集装箱', 'target': 'recKryF5cq', 'category': '原材料', 'more_info': {}, 'target_name': '集装箱', 'source_name': '轧钢板', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'recf05mhzs', 'source': 'rec5rUIomn', 'source_name_ref': '钛合金', 'target_name_ref': '航空器外壳，航空器骨架', 'category': '原材料', 'more_info': {}, 'source_name': '钛合金', 'target_name': '航空器外壳，航空器骨架', 'external_backbone_name': '航空航天', 'external_backbone': 'bascn7y2rkPgE6WpXTxT8K93OHb'}
{'bitapp_id': 'rec5lrIRoc', 'source_name_ref': '钛合金', 'target_name_ref': '航空器外壳，航空器骨架', 'target': 'recPFDoCFu', 'category': '原材料', 'more_info': {}, 'target_name': '航空器外壳，航空器骨架', 'source_name': '钛合金', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'rechn9iuVq', 'source': 'recoBIz2VC', 'source_name_ref': '多晶硅料', 'target_name_ref': '半导体级单晶硅片', 'category': '原材料', 'more_info': {}, 'source_name': '多晶硅料', 'target_name': '半导体级单晶硅片', 'external_backbone_name': '半导体', 'external_backbone': 'bascnbzucap8DFko3LgSLe0q1Kd'}
{'bitapp_id': 'receAfFSC9', 'source_name_ref': '多晶硅料', 'target_name_ref': '半导体级单晶硅片', 'target': 'recOD7q2E9', 'category': '原材料', 'more_info': {}, 'target_name': '半导体级单晶硅片', 'source_name': '多晶硅料', 'external_backbone_name': '光伏', 'external_backbone': 'bascngo31Pi722JP5rBWEMgQL4e'}

CRITICAL 对标记为"煤炭"的表格的边界进行检查,该表共有4条外边参与联调
CRITICAL 煤炭
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："焦炭--原材料->高炉炼铁"
ERROR    星图边界识别失败，该边："广汇能源--生产->液化天然气LNG"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："煤制天然气--原材料->液化天然气LNG"在对应"石油天然气"骨干中没找到对应边界
INFO     星图边界识别成功，在"电力储能"骨干中查到对应边："动力煤--原材料->火力发电"
CRITICAL 完成对标记为"煤炭"的表格的边界进行检查,该表共有4条外边参与联调，通过边2条，冲突边2条

CRITICAL 对标记为"电力储能"的表格的边界进行检查,该表共有23条外边参与联调
CRITICAL 电力储能
INFO     星图边界识别成功，在"锂离子电池"骨干中查到对应边："储能电池--父节点->储能锂电池"
ERROR    星图边界识别失败，该边："电池测试设备--原材料->储能锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："豪鹏科技--生产->储能锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："*ST雪莱--生产->储能锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："超威动力--生产->储能锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铁空气电池--同位->储能钠电池"所对应的"钠离子电池"骨干没有经过内部检查，这是对应骨干而非本边的问题
ERROR    星图边界识别失败，该边："铁空气电池--同位->储能钠电池"在对应"钠离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："储能电池--父节点->储能钠电池"所对应的"钠离子电池"骨干没有经过内部检查，这是对应骨干而非本边的问题
ERROR    星图边界识别失败，该边："储能电池--父节点->储能钠电池"在对应"钠离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："永兴材料--生产->电池级碳酸锂"在对应"矿产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电池测试设备--原材料->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钠离子电池模组--原材料->钠离子电池"所对应的"钠离子电池"骨干没有经过内部检查，这是对应骨干而非本边的问题
ERROR    星图边界识别失败，该边："钠离子电池模组--原材料->钠离子电池"在对应"钠离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："煤--原材料->火力发电"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："苏能股份--生产->煤"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："恒源煤电--生产->煤"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华电重工--储运->煤"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："皖能电力--生产->煤"在对应"煤炭"骨干中没找到对应边界
INFO     星图边界识别成功，在"煤炭"骨干中查到对应边："动力煤--原材料->火力发电"
INFO     星图边界识别成功，在"石油天然气"骨干中查到对应边："天然气--原材料->热电联产"
ERROR    星图边界识别失败，该边："美能能源--生产->天然气"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天富能源--生产->天然气"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："赛晶科技--生产->半导体"在对应"半导体"骨干中没找到对应边界
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："功率模块--原材料->储能逆变器"
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："功率模块--原材料->电力逆变器"
ERROR    星图边界识别失败，该边："博菲电气--生产->光伏组件边框"在对应"光伏"骨干中没找到对应边界
CRITICAL 完成对标记为"电力储能"的表格的边界进行检查,该表共有23条外边参与联调，通过边5条，冲突边21条

CRITICAL 对标记为"风电"的表格的边界进行检查,该表共有7条外边参与联调
CRITICAL 风电
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："IGBT模块--原材料->风电变流器"
ERROR    星图边界识别失败，该边："钢材--原材料->风电塔筒"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钢材--父节点->特种钢"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钢材--父节点->钢锭"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钢材--父节点->无缝钢管"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钢材--父节点->硅钢"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："钢材--父节点->硼钢"在对应"钢铁"骨干中没找到对应边界
CRITICAL 完成对标记为"风电"的表格的边界进行检查,该表共有7条外边参与联调，通过边1条，冲突边6条

CRITICAL 对标记为"贵金属"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 贵金属
CRITICAL 完成对标记为"贵金属"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"海运"的表格的边界进行检查,该表共有10条外边参与联调
CRITICAL 海运
INFO     星图边界识别成功，在"石油天然气"骨干中查到对应边："原油航运--储运->原油"
INFO     星图边界识别成功，在"石油天然气"骨干中查到对应边："成品油航运--储运->成品油"
INFO     星图边界识别成功，在"石油天然气"骨干中查到对应边："液化天然气航运--储运->液化天然气"
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："干散货航运--储运->铁矿石"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："干散货航运--储运->纸浆"
ERROR    星图边界识别失败，该边："纸浆船运输--储运->纸浆"在对应"种植"骨干中没找到对应边界
INFO     星图边界识别成功，在"种植"骨干中查到对应边："干散货航运--储运->粮食作物"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："干散货航运--储运->水泥"

{'bitapp_id': 'recTDgpvxI', 'source': 'recgmAQUmw', 'source_name_ref': '焦炭', 'target_name_ref': '高炉炼铁', 'category': '原材料', 'more_info': {}, 'source_name': '焦炭', 'target_name': '高炉炼铁', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'recCAvyAu5', 'source_name_ref': '焦炭', 'target_name_ref': '高炉炼铁', 'target': 'rec5SKu1XF', 'category': '原材料', 'more_info': {}, 'target_name': '高炉炼铁', 'source_name': '焦炭', 'external_backbone_name': '煤炭', 'external_backbone': 'bascnTB3mCMQdzSb3kJ37ATgQyg'}
{'bitapp_id': 'recljETBAn', 'source': 'rec0VruDBc', 'source_name_ref': '动力煤', 'target_name_ref': '火力发电', 'category': '原材料', 'more_info': {}, 'source_name': '动力煤', 'target_name': '火力发电', 'external_backbone_name': '电力储能', 'external_backbone': 'bascnsACceveT2H48fktBz3xK7f'}
{'bitapp_id': 'rectz3zp6i', 'source_name_ref': '动力煤', 'target_name_ref': '火力发电', 'target': 'recjTLfnmq', 'category': '原材料', 'more_info': {}, 'source_name': '动力煤', 'target_name': '火力发电', 'external_backbone_name': '煤炭', 'external_backbone': 'bascnTB3mCMQdzSb3kJ37ATgQyg'}
{'bitapp_id': 'recJzfhsTB', 'source': 'rectJnewZG', 'source_name_ref': '储能电池', 'target_name_ref': '储能锂电池', 'category': '父节点', 'more_info': {}, 'target_name': '储能锂电池', 'source_name': '储能电池', 'external_backbone_name': '锂离子电池', 'external_backbone': 'ZG1YbzKjQaPjIpsmk9NcSTBZnag'}
{'bitapp_id': 'rec193V9JG', 'source_name_ref': '储能电池', 'target_name_ref': '储能锂电池', 'target': 'rec9KgK3RV', 'category': '父节点', 'more_info': {}, 'source_name': '储能电池', 'target_name': '储能锂电池', 'external_backbone_name': '电力储能', 'external_backbone': 'bascnsACceveT2H48fktBz3xK7f'}
{'bitapp_id': 'recVYQrqqD', 'source': 'recG30My0A', 'source_name_ref': '原油航运', 'target_name_ref': '原油', 'category': '储运', 'more_info': {}, 'source_name': '原油航运', 'target_name': '原油', 'external_backbone_name': '石油天然气', 'external_backbone': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g'}
{'bitapp_id': 'recVAOPVrM', 'source_name_ref': '原油航运', 'target_name_ref': '原油', 'target': 'rec9KgK3RV', 'category': '储运', 'more_info': {}, 'target_name': '原油', 'source_name': '原油航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recLgPL7hl', 'source': 'recIO97lru', 'source_name_ref': '成品油航运', 'target_name_ref': '成品油', 'category': '储运', 'more_info': {}, 'source_name': '成品油航运', 'target_name': '成品油', 'external_backbone_name': '石油天然气', 'external_backbone': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g'}
{'bitapp_id': 'recw8P2Six', 'source_name_ref': '成品油航运', 'target_name_ref': '成品油', 'target': 'reczIOnccd', 'category': '储运', 'more_info': {}, 'target_name': '成品油', 'source_name': '成品油航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recv3xGKEo', 'source': 'recmXfVmSs', 'source_name_ref': '液化天然气航运', 'target_name_ref': '液化天然气', 'category': '储运', 'more_info': {}, 'source_name': '液化天然气航运', 'target_name': '液化天然气', 'external_backbone_name': '石油天然气', 'external_backbone': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g'}
{'bitapp_id': 'recwmp2Dyp', 'source_name_ref': '液化天然气航运', 'target_name_ref': '液化天然气', 'target': 'rec46sHbR2', 'category': '储运', 'more_info': {}, 'target_name': '液化天然气', 'source_name': '液化天然气航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'rec1oGrj1Z', 'source': 'rec8VfqE22', 'source_name_ref': '干散货航运', 'target_name_ref': '铁矿石', 'category': '储运', 'more_info': {}, 'source_name': '干散货航运', 'target_name': '铁矿石', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'recwALixWw', 'source_name_ref': '干散货航运', 'target_name_ref': '铁矿石', 'target': 'recjKJWcPd', 'category': '储运', 'more_info': {}, 'target_name': '铁矿石', 'source_name': '干散货航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recrXidlN7', 'source': 'rec8VfqE22', 'source_name_ref': '干散货航运', 'target_name_ref': '纸浆', 'category': '储运', 'more_info': {}, 'source_name': '干散货航运', 'target_name': '纸浆', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recQ0pc0Nm', 'source_name_ref': '干散货航运', 'target_name_ref': '纸浆', 'target': 'rectO6cXli', 'category': '储运', 'more_info': {}, 'source_name': '干散货航运', 'target_name': '纸浆', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recDAc1NKn', 'source': 'rec8VfqE22', 'source_name_ref': '干散货航运', 'target_name_ref': '粮食作物', 'category': '储运', 'more_info': {}, 'source_name': '干散货航运', 'target_name': '粮食作物', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recWQHrHrd', 'source_name_ref': '干散货航运', 'target_name_ref': '粮食作物', 'target': 'recV96vgmB', 'category': '储运', 'more_info': {}, 'target_name': '粮食作物', 'source_name': '干散货航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'rec30k8Uzo', 'source': 'rec8VfqE22', 'source_name_ref': '干散货航运', 'target_name_ref': '水泥', 'category': '储运', 'more_info': {}, 'source_name': '干散货航运', 'target_name': '水泥', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recpnzCFMR', 'source_name_ref': '干散货航运', 'target_name_ref': '水泥', 'target': 'recACSM6Jx', 'category': '储运', 'more_info': {}, 'target_name': '水泥', 'source_name': '干散货航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}

INFO     星图边界识别成功，在"汽车制造"骨干中查到对应边："滚装船航运--储运->汽车"
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："轧钢板--原材料->集装箱"
CRITICAL 完成对标记为"海运"的表格的边界进行检查,该表共有10条外边参与联调，通过边9条，冲突边1条

CRITICAL 对标记为"消费电子"的表格的边界进行检查,该表共有6条外边参与联调
CRITICAL 消费电子
ERROR    星图边界识别失败，该边："存储芯片--原材料->消费电子"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："芯片--父节点->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："GPU--原材料->消费电子"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："GPU--原材料->手机"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："CPU--原材料->消费电子"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："CPU--原材料->手机"在对应"半导体"骨干中没找到对应边界
CRITICAL 完成对标记为"消费电子"的表格的边界进行检查,该表共有6条外边参与联调，通过边0条，冲突边6条

CRITICAL 对标记为"种植"的表格的边界进行检查,该表共有80条外边参与联调
CRITICAL 种植
ERROR    星图边界识别失败，该边："粮食作物--原材料->粮食作物加工"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："粮食作物--原材料->粮食作物加工"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"海运"骨干中查到对应边："干散货航运--储运->粮食作物"
INFO     星图边界识别成功，在"海运"骨干中查到对应边："干散货航运--储运->纸浆"
ERROR    星图边界识别失败，该边："苏垦农发--生产->大米"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："小麦--原材料->面粉"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："小麦--原材料->能量原材料"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："玉米--原材料->能量原材料"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："高粱--原材料->能量原材料"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："玉米--原材料->再生蛋白质纤维"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："大豆--原材料->再生蛋白质纤维"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："小麦--原材料->白酒"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："高粱--原材料->白酒"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："玉米--原材料->白酒"
ERROR    星图边界识别失败，该边："麦芽--原材料->啤酒"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："大豆榨取--原材料->大豆油"在对应"食品饮料"骨干中没找到对应边界
ERROR    找到文本相同的星图边界但起终点有问题，可能是方向写反了或者外骨干标重了，如无法解决联系王之霖。边信息：嘉华股份--生产->大豆油
ERROR    星图边界识别失败，该边："玉米--原材料->玉米油"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："木材--原材料->家具"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："纸浆--原材料->纸质包装"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美盈森--生产->纸质包装"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："棕榈树，油棕树--原材料->棕榈油"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："油菜籽榨取--原材料->菜籽油"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："菜粕--原材料->植物性蛋白"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："豆粕--原材料->植物性蛋白"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："天然纤维--父节点->棉"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："天然纤维--父节点->麻"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："棉--原材料->再生纤维素纤维"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："木材--原材料->再生纤维素纤维"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："麻--原材料->麻布"
ERROR    星图边界识别失败，该边："经济作物--父节点->饮料作物"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："英记茶庄集团--储运->茶叶"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："经济作物--父节点->水果"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："宏辉果蔬--生产->水果"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："丝路能源--生产->水果"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："经济作物--父节点->蔬菜"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："经济作物--父节点->糖料作物"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："种子--原材料->农作物"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："敦煌种业--生产->种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："丰乐种业--生产->种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："隆平高科--生产->种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："绿亨科技--生产->种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："登海种业--生产->玉米种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："万向德农--生产->玉米种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："荃银高科--生产->玉米种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："秋乐种业--生产->玉米种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："荃银高科--生产->水稻种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："秋乐种业--生产->小麦种子"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："浙农股份--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："国光股份--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中农联合--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："农药制剂--原材料->农作物"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："辉隆股份--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："丰乐种业--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："辉丰股份--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："绿亨科技--生产->农药制剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："雅本化学--生产->农药中间体"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中农联合--生产->农药中间体"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："辉丰股份--生产->农药中间体"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海利尔--生产->农药中间体"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中农联合--生产->农药原药"在对应"食品饮料"骨干中没找到对应边界

{'bitapp_id': 'rec5eDqKQX', 'source': 'recTloD5YD', 'source_name_ref': '滚装船航运', 'target_name_ref': '汽车', 'category': '储运', 'more_info': {}, 'source_name': '滚装船航运', 'target_name': '汽车', 'external_backbone_name': '汽车制造', 'external_backbone': 'bascnIRb34I8uajC8l70BZYtrYe'}
{'bitapp_id': 'recFr8DPqn', 'source_name_ref': '滚装船航运', 'target_name_ref': '汽车', 'target': 'recV96vgmB', 'category': '储运', 'more_info': {}, 'target_name': '汽车', 'source_name': '滚装船航运', 'external_backbone_name': '海运', 'external_backbone': 'BfmAbCOziaY61NsAFk6cMa7Ynvc'}
{'bitapp_id': 'recWmQO5Ux', 'source': 'rec9KgK3RV', 'source_name_ref': '小麦', 'target_name_ref': '能量原材料', 'category': '原材料', 'more_info': {}, 'source_name': '小麦', 'target_name': '能量原材料', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recuqtprON', 'source_name_ref': '小麦', 'target_name_ref': '能量原材料', 'target': 'recGrmZvEs', 'category': '原材料', 'more_info': {}, 'target_name': '能量原材料', 'source_name': '小麦', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recY5HAjPi', 'source': 'recoH0xpBJ', 'source_name_ref': '玉米', 'target_name_ref': '能量原材料', 'category': '原材料', 'more_info': {}, 'source_name': '玉米', 'target_name': '能量原材料', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recaiga0G6', 'source_name_ref': '玉米', 'target_name_ref': '能量原材料', 'target': 'recGrmZvEs', 'category': '原材料', 'more_info': {}, 'target_name': '能量原材料', 'source_name': '玉米', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recKS8hcJt', 'source': 'rec2HvUMLw', 'source_name_ref': '高粱', 'target_name_ref': '能量原材料', 'category': '原材料', 'more_info': {}, 'source_name': '高粱', 'target_name': '能量原材料', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recN8zEobe', 'source_name_ref': '高粱', 'target_name_ref': '能量原材料', 'target': 'recGrmZvEs', 'category': '原材料', 'more_info': {}, 'target_name': '能量原材料', 'source_name': '高粱', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recnfzvO3Y', 'source': 'recoH0xpBJ', 'source_name_ref': '玉米', 'target_name_ref': '再生蛋白质纤维', 'category': '原材料', 'more_info': {}, 'source_name': '玉米', 'target_name': '再生蛋白质纤维', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recfegHUFD', 'source_name_ref': '玉米', 'target_name_ref': '再生蛋白质纤维', 'target': 'recr8m09eu', 'category': '原材料', 'more_info': {}, 'target_name': '再生蛋白质纤维', 'source_name': '玉米', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recRTGh8iM', 'source': 'recoBIz2VC', 'source_name_ref': '大豆', 'target_name_ref': '再生蛋白质纤维', 'category': '原材料', 'more_info': {}, 'source_name': '大豆', 'target_name': '再生蛋白质纤维', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recI8ZKp1c', 'source_name_ref': '大豆', 'target_name_ref': '再生蛋白质纤维', 'target': 'recr8m09eu', 'category': '原材料', 'more_info': {}, 'target_name': '再生蛋白质纤维', 'source_name': '大豆', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recrUZlRNu', 'source': 'rec9KgK3RV', 'source_name_ref': '小麦', 'target_name_ref': '白酒', 'category': '原材料', 'more_info': {}, 'source_name': '小麦', 'target_name': '白酒', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recLCAwQ4K', 'source_name_ref': '小麦', 'target_name_ref': '白酒', 'target': 'recvdlnBq6', 'category': '原材料', 'more_info': {}, 'source_name': '小麦', 'target_name': '白酒', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'rec2uX2g5q', 'source': 'rec2HvUMLw', 'source_name_ref': '高粱', 'target_name_ref': '白酒', 'category': '原材料', 'more_info': {}, 'source_name': '高粱', 'target_name': '白酒', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'rec80NgVJ8', 'source_name_ref': '高粱', 'target_name_ref': '白酒', 'target': 'recvdlnBq6', 'category': '原材料', 'more_info': {}, 'source_name': '高粱', 'target_name': '白酒', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recWAstUzW', 'source': 'recoH0xpBJ', 'source_name_ref': '玉米', 'target_name_ref': '白酒', 'category': '原材料', 'more_info': {}, 'source_name': '玉米', 'target_name': '白酒', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recVgWark5', 'source_name_ref': '玉米', 'target_name_ref': '白酒', 'target': 'recvdlnBq6', 'category': '原材料', 'more_info': {}, 'source_name': '玉米', 'target_name': '白酒', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'reciU8qqFN', 'source': 'reciUbnYLh', 'source_name_ref': '嘉华股份', 'target_name_ref': '大豆油', 'category': '生产', 'more_info': {}, 'target_name': '大豆油', 'source_name': '嘉华股份', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recsodarpl', 'source': 'reckYl1q4C', 'source_name_ref': '嘉华股份', 'target_name_ref': '大豆油', 'category': '生产', 'more_info': {}, 'target_name': '大豆油', 'source_name': '嘉华股份', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recBNWxjgr', 'source': 'recwgzwYx5', 'source_name_ref': '菜粕', 'target_name_ref': '植物性蛋白', 'category': '原材料', 'more_info': {}, 'source_name': '菜粕', 'target_name': '植物性蛋白', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recUT2PdfA', 'source_name_ref': '菜粕', 'target_name_ref': '植物性蛋白', 'target': 'recJGm1w7l', 'category': '原材料', 'more_info': {}, 'target_name': '植物性蛋白', 'source_name': '菜粕', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recepnfxUy', 'source': 'reciqtrz6f', 'source_name_ref': '豆粕', 'target_name_ref': '植物性蛋白', 'category': '原材料', 'more_info': {}, 'source_name': '豆粕', 'target_name': '植物性蛋白', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recjqIN7Cv', 'source_name_ref': '豆粕', 'target_name_ref': '植物性蛋白', 'target': 'recJGm1w7l', 'category': '原材料', 'more_info': {}, 'target_name': '植物性蛋白', 'source_name': '豆粕', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recBXqGARt', 'source': 'recEwBBl2m', 'source_name_ref': '棉', 'target_name_ref': '再生纤维素纤维', 'category': '原材料', 'more_info': {}, 'target_name': '再生纤维素纤维', 'source_name': '棉', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recErDvf84', 'source_name_ref': '棉', 'target_name_ref': '再生纤维素纤维', 'target': 'recFP3Bx44', 'category': '原材料', 'more_info': {}, 'source_name': '棉', 'target_name': '再生纤维素纤维', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recMIJyRF4', 'source': 'recYrzfC2M', 'source_name_ref': '木材', 'target_name_ref': '再生纤维素纤维', 'category': '原材料', 'more_info': {}, 'source_name': '木材', 'target_name': '再生纤维素纤维', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recOmYAMVH', 'source_name_ref': '木材', 'target_name_ref': '再生纤维素纤维', 'target': 'recFP3Bx44', 'category': '原材料', 'more_info': {}, 'target_name': '再生纤维素纤维', 'source_name': '木材', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recQXLNj2s', 'source': 'recksqMkxW', 'source_name_ref': '麻', 'target_name_ref': '麻布', 'category': '原材料', 'more_info': {}, 'source_name': '麻', 'target_name': '麻布', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recl9c2rsp', 'source_name_ref': '麻', 'target_name_ref': '麻布', 'target': 'reckwhR45N', 'category': '原材料', 'more_info': {}, 'target_name': '麻布', 'source_name': '麻', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}

ERROR    星图边界识别失败，该边："蓝丰生化--生产->农药原药"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海利尔--生产->农药原药"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："绿亨科技--生产->农药原药"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："安道麦A--生产->除草剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："扬农化工--生产->除草剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："丰山集团--生产->除草剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："润丰股份--生产->除草剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："溴素--原材料->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："诺普信--生产->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利民股份--生产->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："农心科技--生产->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美邦股份--生产->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："丰山集团--生产->杀虫剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："诺普信--生产->杀菌剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利民股份--生产->杀菌剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："农心科技--生产->杀菌剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美邦股份--生产->杀菌剂"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天然气--原材料->合成氨"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："合成橡胶--原材料->农业机械"在对应"石油化工"骨干中没找到对应边界
CRITICAL 完成对标记为"种植"的表格的边界进行检查,该表共有80条外边参与联调，通过边17条，冲突边63条

CRITICAL 对标记为"汽车制造"的表格的边界进行检查,该表共有23条外边参与联调
CRITICAL 汽车制造
INFO     星图边界识别成功，在"锂离子电池"骨干中查到对应边："动力锂电池--原材料->电源系统"
ERROR    星图边界识别失败，该边："博汇股份--生产->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："深中华A--生产->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂电池正极材料--原材料->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂电池电解液--原材料->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："汽车电池回收服务--储运->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂电池结构件--原材料->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："锂电池负极材料--原材料->动力锂电池"在对应"锂离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："充电桩--储运->电力"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："电力--原材料->新能源车出行"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："配电网设备--储运->电力"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："数控机床--原材料->一体化车身"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："数控机床--原材料->汽车骨架"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："嵘泰股份--生产->数控机床"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："合锻智能--生产->数控机床"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："成品油--原材料->燃油车出行"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："动力钠电池--原材料->电源系统"所对应的"钠离子电池"骨干没有经过内部检查，这是对应骨干而非本边的问题
ERROR    星图边界识别失败，该边："动力钠电池--原材料->电源系统"在对应"钠离子电池"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："客车--原材料->景区观光"在对应"旅游"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："货车--原材料->公路货运"在对应"陆运"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："三羊马--生产->公路货运"在对应"陆运"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："ST大洲--生产->公路货运"在对应"陆运"骨干中没找到对应边界
INFO     星图边界识别成功，在"海运"骨干中查到对应边："滚装船航运--储运->汽车"
ERROR    星图边界识别失败，该边："朗博科技--生产->车用橡胶"在对应"陆运"骨干中没找到对应边界
CRITICAL 完成对标记为"汽车制造"的表格的边界进行检查,该表共有23条外边参与联调，通过边2条，冲突边22条

CRITICAL 对标记为"人力资源（教育）"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 人力资源（教育）
CRITICAL 完成对标记为"人力资源（教育）"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"零售餐饮"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 零售餐饮
CRITICAL 完成对标记为"零售餐饮"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"广告传媒"的表格的边界进行检查,该表共有7条外边参与联调
CRITICAL 广告传媒
ERROR    星图边界识别失败，该边："广告渠道--父节点->信息平台"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："内容--父节点->广告"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："内容--父节点->PGC"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："内容--父节点->AIGC"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："米奥会展--生产->展览会"在对应"旅游"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："兰生股份--生产->展览会"在对应"旅游"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广告渠道--父节点->展览会"在对应"旅游"骨干中没找到对应边界
CRITICAL 完成对标记为"广告传媒"的表格的边界进行检查,该表共有7条外边参与联调，通过边0条，冲突边7条

CRITICAL 对标记为"石油天然气"的表格的边界进行检查,该表共有6条外边参与联调
CRITICAL 石油天然气
INFO     星图边界识别成功，在"海运"骨干中查到对应边："成品油航运--储运->成品油"
INFO     星图边界识别成功，在"海运"骨干中查到对应边："原油航运--储运->原油"
INFO     星图边界识别成功，在"海运"骨干中查到对应边："液化天然气航运--储运->液化天然气"
ERROR    星图边界识别失败，该边："航空汽油--原材料->航空运输"在对应"航空航天"骨干中没找到对应边界
INFO     星图边界识别成功，在"电力储能"骨干中查到对应边："天然气--原材料->热电联产"
ERROR    星图边界识别失败，该边："廊坊发展--生产->热电联产"在对应"电力储能"骨干中没找到对应边界
CRITICAL 完成对标记为"石油天然气"的表格的边界进行检查,该表共有6条外边参与联调，通过边4条，冲突边2条

CRITICAL 对标记为"银行"的表格的边界进行检查,该表共有5条外边参与联调
CRITICAL 银行
INFO     星图边界识别成功，在"地产"骨干中查到对应边："个人活期储蓄--原材料->房地产销售回款"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："个人定期储蓄--原材料->房地产销售回款"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："个人住房贷款--原材料->房地产销售回款"
INFO     星图边界识别成功，在"地产"骨干中查到对应边："房地产外部融资--父节点->房地产开发贷款"
ERROR    星图边界识别失败，该边："信息化工程建设--原材料->银行信息化建设"在对应"互联网云计算"骨干中没找到对应边界
CRITICAL 完成对标记为"银行"的表格的边界进行检查,该表共有5条外边参与联调，通过边4条，冲突边1条

CRITICAL 对标记为"石油化工"的表格的边界进行检查,该表共有33条外边参与联调
CRITICAL 石油化工
ERROR    星图边界识别失败，该边："原油--原材料->石油轻炼"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："石油轻炼--原材料->化工轻油"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："化工轻油--原材料->芳构化反应"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："化工轻油--原材料->裂解反应"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："化工轻油--原材料->石油制甲醇法"在对应"石油天然气"骨干中没找到对应边界
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚酯纤维(涤纶)"
ERROR    星图边界识别失败，该边："对二甲苯酸PTA--原材料->聚酯纤维(涤纶)"在对应"纺织业"骨干中没找到对应边界
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："乙二醇--原材料->聚酯纤维(涤纶)"
ERROR    星图边界识别失败，该边："荣盛石化--生产->聚酯纤维(涤纶)"在对应"纺织业"骨干中没找到对应边界
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚氯乙烯纤维(氯纶)"
ERROR    星图边界识别失败，该边："聚氯乙烯PVC--原材料->聚氯乙烯纤维(氯纶)"在对应"纺织业"骨干中没找到对应边界
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："丙烯腈--原材料->聚丙烯腈纤维(腈纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚丙烯腈纤维(腈纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："聚烯烃--原材料->聚烯烃弹力纤维"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚烯烃弹力纤维"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚乙烯醇缩醛纤维(维尼纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："聚乙烯醇PVA--原材料->聚乙烯醇缩醛纤维(维尼纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚酰胺纤维(尼龙/锦纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："聚四氢呋喃PTMG--原材料->聚氨酯纤维(氨纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："二苯基甲烷二异氰酸酯MDI--原材料->聚氨酯纤维(氨纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成纤维--父节点->聚氨酯纤维(氨纶)"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："己内酰胺--原材料->尼龙6"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："乙二胺--原材料->尼龙66"
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："己二酸--原材料->尼龙66"
ERROR    星图边界识别失败，该边："江苏国信--生产->炼焦煤"在对应"煤炭"骨干中没找到对应边界
INFO     星图边界识别成功，在"纺织业"骨干中查到对应边："合成橡胶--原材料->鞋类原料"
ERROR    星图边界识别失败，该边："丁苯橡胶--原材料->电线电缆"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："合成纤维--原材料->化纤面料"在对应"纺织业"骨干中没找到对应边界
INFO     星图边界识别成功，在"地产"骨干中查到对应边："合成树脂--原材料->建筑涂料"
ERROR    星图边界识别失败，该边："POE粒子--原材料->POE胶膜"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："煤制乙二醇工艺--原材料->乙二醇"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："合成气--原材料->煤制乙二醇工艺"在对应"煤炭"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："煤制甲醇法--原材料->合成气"在对应"煤炭"骨干中没找到对应边界
CRITICAL 完成对标记为"石油化工"的表格的边界进行检查,该表共有33条外边参与联调，通过边18条，冲突边15条

CRITICAL 对标记为"互联网云计算"的表格的边界进行检查,该表共有92条外边参与联调
CRITICAL 互联网云计算
ERROR    星图边界识别失败，该边："高速有线通信芯片--原材料->互联网数据中心"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广告设计策划--父节点->广告推广平台"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广告设计策划--父节点->电商导购平台"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广告设计策划--原材料->广告"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华媒控股--生产->广告设计策划"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："优矩控股--生产->广告设计策划"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："万星控股--生产->广告设计策划"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："姚记科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："智度股份--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："盛天网络--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中富通--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："国脉文化--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："网达软件--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中广天择--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华扬联众--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利欧股份--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："创业黑马--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："新华都--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："久其软件--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："因赛集团--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："省广集团--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："易点天下--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："浙江富润--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："恒大高新--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："万润科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："环球印务--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天地在线--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："同花顺--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："*ST中昌--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天下秀--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界

{'bitapp_id': 'recYUG6DEA', 'source': 'recJ1kQx2a', 'source_name_ref': '天然气', 'target_name_ref': '热电联产', 'category': '原材料', 'more_info': {}, 'source_name': '天然气', 'target_name': '热电联产', 'external_backbone_name': '电力储能', 'external_backbone': 'bascnsACceveT2H48fktBz3xK7f'}
{'bitapp_id': 'recccnEclX', 'source_name_ref': '天然气', 'target_name_ref': '热电联产', 'target': 'recCeyFPiq', 'category': '原材料', 'more_info': {}, 'source_name': '天然气', 'target_name': '热电联产', 'external_backbone_name': '石油天然气', 'external_backbone': 'JGUEbKc6WaLUF3sj10ZcgRhdn7g'}
{'bitapp_id': 'recMkEVWF7', 'source': 'rec2Af8KSz', 'source_name_ref': '个人活期储蓄', 'target_name_ref': '房地产销售回款', 'category': '原材料', 'more_info': {}, 'source_name': '个人活期储蓄', 'target_name': '房地产销售回款', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recrgTqr0r', 'source_name_ref': '个人活期储蓄', 'target_name_ref': '房地产销售回款', 'target': 'recCpUsZmI', 'category': '原材料', 'more_info': {}, 'source_name': '个人活期储蓄', 'target_name': '房地产销售回款', 'external_backbone_name': '银行', 'external_backbone': 'NQX9b6UZ6astfrsthMac8fcgnTb'}
{'bitapp_id': 'recvUrKnEq', 'source': 'recOD7q2E9', 'source_name_ref': '个人定期储蓄', 'target_name_ref': '房地产销售回款', 'category': '原材料', 'more_info': {}, 'source_name': '个人定期储蓄', 'target_name': '房地产销售回款', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'reckl3DTfq', 'source_name_ref': '个人定期储蓄', 'target_name_ref': '房地产销售回款', 'target': 'recCpUsZmI', 'category': '原材料', 'more_info': {}, 'source_name': '个人定期储蓄', 'target_name': '房地产销售回款', 'external_backbone_name': '银行', 'external_backbone': 'NQX9b6UZ6astfrsthMac8fcgnTb'}
{'bitapp_id': 'recTIHKIow', 'source': 'recBy6bHQ8', 'source_name_ref': '个人住房贷款', 'target_name_ref': '房地产销售回款', 'category': '原材料', 'more_info': {}, 'source_name': '个人住房贷款', 'target_name': '房地产销售回款', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recpXqcBPi', 'source_name_ref': '个人住房贷款', 'target_name_ref': '房地产销售回款', 'target': 'recCpUsZmI', 'category': '原材料', 'more_info': {}, 'source_name': '个人住房贷款', 'target_name': '房地产销售回款', 'external_backbone_name': '银行', 'external_backbone': 'NQX9b6UZ6astfrsthMac8fcgnTb'}
{'bitapp_id': 'recI5E85KM', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚酯纤维(涤纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚酯纤维(涤纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recHru7Eqy', 'source_name_ref': '合成纤维', 'target_name_ref': '聚酯纤维(涤纶)', 'target': 'recocvGIZE', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚酯纤维(涤纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recloayazH', 'source': 'recc5yhkvy', 'source_name_ref': '乙二醇', 'target_name_ref': '聚酯纤维(涤纶)', 'category': '原材料', 'more_info': {}, 'source_name': '乙二醇', 'target_name': '聚酯纤维(涤纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recPELPXE3', 'source_name_ref': '乙二醇', 'target_name_ref': '聚酯纤维(涤纶)', 'target': 'recocvGIZE', 'category': '原材料', 'more_info': {}, 'target_name': '聚酯纤维(涤纶)', 'source_name': '乙二醇', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recVe0el1u', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚氯乙烯纤维(氯纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚氯乙烯纤维(氯纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recOcIhHDO', 'source_name_ref': '合成纤维', 'target_name_ref': '聚氯乙烯纤维(氯纶)', 'target': 'reczjwZq8v', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚氯乙烯纤维(氯纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recyXtrTl2', 'source': 'recqVjFgkT', 'source_name_ref': '丙烯腈', 'target_name_ref': '聚丙烯腈纤维(腈纶)', 'category': '原材料', 'more_info': {}, 'source_name': '丙烯腈', 'target_name': '聚丙烯腈纤维(腈纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recgrzShn4', 'source_name_ref': '丙烯腈', 'target_name_ref': '聚丙烯腈纤维(腈纶)', 'target': 'recFGeL8oR', 'category': '原材料', 'more_info': {}, 'target_name': '聚丙烯腈纤维(腈纶)', 'source_name': '丙烯腈', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'rec8Wt5HFZ', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚丙烯腈纤维(腈纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚丙烯腈纤维(腈纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recPZMrXZH', 'source_name_ref': '合成纤维', 'target_name_ref': '聚丙烯腈纤维(腈纶)', 'target': 'recFGeL8oR', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚丙烯腈纤维(腈纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recnIbf54n', 'source': 'rec2DxsbzA', 'source_name_ref': '聚烯烃', 'target_name_ref': '聚烯烃弹力纤维', 'category': '原材料', 'more_info': {}, 'target_name': '聚烯烃弹力纤维', 'source_name': '聚烯烃', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'rec3HfIiWJ', 'source_name_ref': '聚烯烃', 'target_name_ref': '聚烯烃弹力纤维', 'target': 'recYx8vrjY', 'category': '原材料', 'more_info': {}, 'target_name': '聚烯烃弹力纤维', 'source_name': '聚烯烃', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recwyofOW8', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚烯烃弹力纤维', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚烯烃弹力纤维', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recqcBfBP8', 'source_name_ref': '合成纤维', 'target_name_ref': '聚烯烃弹力纤维', 'target': 'recYx8vrjY', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚烯烃弹力纤维', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recvtitfRD', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚乙烯醇缩醛纤维(维尼纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚乙烯醇缩醛纤维(维尼纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recNQh5tzv', 'source_name_ref': '合成纤维', 'target_name_ref': '聚乙烯醇缩醛纤维(维尼纶)', 'target': 'rec3lGWKKN', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚乙烯醇缩醛纤维(维尼纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'rec2SfbnRM', 'source': 'recSnZbNQ1', 'source_name_ref': '聚乙烯醇PVA', 'target_name_ref': '聚乙烯醇缩醛纤维(维尼纶)', 'category': '原材料', 'more_info': {}, 'target_name': '聚乙烯醇缩醛纤维(维尼纶)', 'source_name': '聚乙烯醇PVA', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'rec3skDAjH', 'source_name_ref': '聚乙烯醇PVA', 'target_name_ref': '聚乙烯醇缩醛纤维(维尼纶)', 'target': 'rec3lGWKKN', 'category': '原材料', 'more_info': {}, 'target_name': '聚乙烯醇缩醛纤维(维尼纶)', 'source_name': '聚乙烯醇PVA', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'rec7oObxrG', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚酰胺纤维(尼龙/锦纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚酰胺纤维(尼龙/锦纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recJAF6ZPO', 'source_name_ref': '合成纤维', 'target_name_ref': '聚酰胺纤维(尼龙/锦纶)', 'target': 'recB486bSV', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚酰胺纤维(尼龙/锦纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recUfgcejz', 'source': 'recpi13b6r', 'source_name_ref': '聚四氢呋喃PTMG', 'target_name_ref': '聚氨酯纤维(氨纶)', 'category': '原材料', 'more_info': {}, 'target_name': '聚氨酯纤维(氨纶)', 'source_name': '聚四氢呋喃PTMG', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recMbLt1rP', 'source_name_ref': '聚四氢呋喃PTMG', 'target_name_ref': '聚氨酯纤维(氨纶)', 'target': 'recuFDtGfl', 'category': '原材料', 'more_info': {}, 'target_name': '聚氨酯纤维(氨纶)', 'source_name': '聚四氢呋喃PTMG', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'rec2JCo0NN', 'source': 'recLnnhOWg', 'source_name_ref': '二苯基甲烷二异氰酸酯MDI', 'target_name_ref': '聚氨酯纤维(氨纶)', 'category': '原材料', 'more_info': {}, 'target_name': '聚氨酯纤维(氨纶)', 'source_name': '二苯基甲烷二异氰酸酯MDI', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recezkTk6T', 'source_name_ref': '二苯基甲烷二异氰酸酯MDI', 'target_name_ref': '聚氨酯纤维(氨纶)', 'target': 'recuFDtGfl', 'category': '原材料', 'more_info': {}, 'target_name': '聚氨酯纤维(氨纶)', 'source_name': '二苯基甲烷二异氰酸酯MDI', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recXDBZo49', 'source': 'recviMEnOn', 'source_name_ref': '合成纤维', 'target_name_ref': '聚氨酯纤维(氨纶)', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚氨酯纤维(氨纶)', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'reclVWGv0E', 'source_name_ref': '合成纤维', 'target_name_ref': '聚氨酯纤维(氨纶)', 'target': 'recuFDtGfl', 'category': '父节点', 'more_info': {}, 'source_name': '合成纤维', 'target_name': '聚氨酯纤维(氨纶)', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'reclQrWAcc', 'source': 'rec6XMNebu', 'source_name_ref': '己内酰胺', 'target_name_ref': '尼龙6', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙6', 'source_name': '己内酰胺', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'rec3r0zuiH', 'source_name_ref': '己内酰胺', 'target_name_ref': '尼龙6', 'target': 'recGIbMs1t', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙6', 'source_name': '己内酰胺', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recWenqDdN', 'source': 'rec18YmPYg', 'source_name_ref': '乙二胺', 'target_name_ref': '尼龙66', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙66', 'source_name': '乙二胺', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recuYdkTJf', 'source_name_ref': '乙二胺', 'target_name_ref': '尼龙66', 'target': 'recx2Xr9yE', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙66', 'source_name': '乙二胺', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recUENK8Xw', 'source': 'rectfCshbc', 'source_name_ref': '己二酸', 'target_name_ref': '尼龙66', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙66', 'source_name': '己二酸', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recul8W1n8', 'source_name_ref': '己二酸', 'target_name_ref': '尼龙66', 'target': 'recx2Xr9yE', 'category': '原材料', 'more_info': {}, 'target_name': '尼龙66', 'source_name': '己二酸', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recoSfxuCW', 'source': 'rectG2Tf5U', 'source_name_ref': '合成橡胶', 'target_name_ref': '鞋类原料', 'category': '原材料', 'more_info': {}, 'source_name': '合成橡胶', 'target_name': '鞋类原料', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recobj93wL', 'source_name_ref': '合成橡胶', 'target_name_ref': '鞋类原料', 'target': 'rec75lHjxw', 'category': '原材料', 'more_info': {}, 'source_name': '合成橡胶', 'target_name': '鞋类原料', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}
{'bitapp_id': 'recTEEAnj6', 'source': 'recsWywCuS', 'source_name_ref': '合成树脂', 'target_name_ref': '建筑涂料', 'category': '原材料', 'more_info': {}, 'source_name': '合成树脂', 'target_name': '建筑涂料', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'reczP0DxID', 'source_name_ref': '合成树脂', 'target_name_ref': '建筑涂料', 'target': 'recfua03rV', 'category': '原材料', 'more_info': {}, 'target_name': '建筑涂料', 'source_name': '合成树脂', 'external_backbone_name': '石油化工', 'external_backbone': 'YwFYbfJs8asYqIs2IdscNjUHn0c'}

ERROR    星图边界识别失败，该边："三六五网--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："引力传媒--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："思美传媒--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："川网传媒--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："汇量科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："秀商时代控股--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："辉煌明天--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："联建光电--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："佳云科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："浙文互联--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："国旅联合--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："旗天科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："云想科技--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："润歌互动--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："乐享集团--生产->数字营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："福石控股--生产->大数据营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："人工智能--父节点->大数据营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："智度股份--生产->大数据营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中新赛克--生产->大数据营销"在对应"广告传媒"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："存储芯片--父节点->DRAM"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："江波龙--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："恒烁股份--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："德明利--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："*ST紫晶--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："东芯股份--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："深科技--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："普冉股份--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："佰维存储--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："北京君正--生产->存储芯片"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："信息平台--父节点->在线旅行社"在对应"旅游"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："信息化工程建设--原材料->银行IT建设"在对应"银行"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："创识科技--生产->银行IT建设"在对应"银行"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："银信科技--生产->银行IT建设"在对应"银行"骨干中没找到对应边界
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："ROM--原材料->存储服务器"
ERROR    星图边界识别失败，该边："视频--父节点->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欢瑞世纪--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："奥飞娱乐--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："慈文传媒--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中南文化--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："捷成股份--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："光迅科技--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："上海电影--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："文投控股--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："光线传媒--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："大晟文化--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："IPTV业务--储运->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："浙文影业--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华策影视--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："唐德影视--生产->影视剧"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："鸿博股份--生产->互联网数据中心"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："英伟达--供应->鸿博股份"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："常山北明--生产->软件解决方案"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："百度集团-SW--供应->常山北明"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美利云--生产->互联网数据中心"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："国光电器--生产->智能音响"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："石基信息--生产->软件解决方案"在对应"旅游"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："三五互联--生产->游戏"在对应"光伏"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欧比特--生产->数据"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欧比特--生产->智能安防"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欧比特--生产->地理信息系统"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："麦克奥迪--生产->医疗平台"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天和防务--生产->军用信息化软件"在对应"航空航天"骨干中没找到对应边界
CRITICAL 完成对标记为"互联网云计算"的表格的边界进行检查,该表共有92条外边参与联调，通过边1条，冲突边91条

CRITICAL 对标记为"家居"的表格的边界进行检查,该表共有2条外边参与联调
CRITICAL 家居
ERROR    星图边界识别失败，该边："冷轧钢板--原材料->家电用复合材料（PCM/VCM）"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："镀锌板--原材料->家电用复合材料（PCM/VCM）"在对应"钢铁"骨干中没找到对应边界
CRITICAL 完成对标记为"家居"的表格的边界进行检查,该表共有2条外边参与联调，通过边0条，冲突边2条

CRITICAL 对标记为"环保"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 环保
CRITICAL 完成对标记为"环保"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"矿产"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 矿产
CRITICAL 完成对标记为"矿产"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"电影"的表格的边界进行检查,该表共有3条外边参与联调
CRITICAL 电影
ERROR    星图边界识别失败，该边："数字娱乐平台--父节点->视频平台"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："线上销售渠道平台--父节点->在线票务平台"在对应"互联网云计算"骨干中没找到对应边界
INFO     星图边界识别成功，在"地产"骨干中查到对应边："商业房地产--原材料->院线放映"
CRITICAL 完成对标记为"电影"的表格的边界进行检查,该表共有3条外边参与联调，通过边1条，冲突边2条

CRITICAL 对标记为"食品饮料"的表格的边界进行检查,该表共有87条外边参与联调
CRITICAL 食品饮料
ERROR    星图边界识别失败，该边："线下零售店--储运->食品烟酒"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："文峰股份--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家家悦--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："良品铺子--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："国光连锁--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中国北大荒--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："太古股份公司B--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："四洲集团--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利亚零售--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："联华超市--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："鸿福堂--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："宾仕国际--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："K2 F&B--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利福中国--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："奈雪的茶--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："优品360--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："红旗连锁--生产->线下零售店"在对应"零售餐饮"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："聚乙烯--原材料->塑料包装"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"种植"骨干中查到对应边："小麦--原材料->白酒"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："高粱--原材料->白酒"
ERROR    星图边界识别失败，该边："大豆--原材料->豆制品"在对应"种植"骨干中没找到对应边界
INFO     星图边界识别成功，在"种植"骨干中查到对应边："玉米--原材料->白酒"
ERROR    星图边界识别失败，该边："玉米--原材料->谷氨酸钠"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："食品烟酒--父节点->成品粮食"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："成品粮食--父节点->玉米淀粉"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："大米--原材料->白酒"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："金健米业--生产->大米"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："东方集团--生产->大米"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："金源米业--生产->大米"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中绿--生产->大米"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："咖啡豆--原材料->咖啡"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："茶叶--原材料->茶饮料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："食用酵母--原材料->啤酒"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："安琪酵母--生产->食用酵母"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："酒花--原材料->啤酒"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："调味品--父节点->味精"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："调味品--父节点->香料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："恒顺醋业--生产->调味品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："千禾味业--生产->调味品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："仲景食品--生产->调味品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："金丹科技--生产->单味调味品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："三元生物--生产->单味调味品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："雪天盐业--生产->食盐"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："N江盐--生产->食盐"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："云图控股--生产->食盐"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海天味业--生产->酱油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中炬高新--生产->酱油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："加加食品--生产->酱油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："食糖--原材料->糖果，巧克力"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："南宁糖业--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中粮糖业--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："广州浪奇--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华资实业--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华康股份--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华联国际--生产->食糖"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："亚香股份--生产->天然香辛料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："复合调味品--父节点->佐餐开味菜"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天味食品--生产->风味酱料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："日辰股份--生产->风味酱料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："颐海国际--生产->风味酱料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："仲景食品--生产->风味酱料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华宝股份--生产->复合香辛料"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："食品烟酒--父节点->食用油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："道道全--生产->食用油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："金龙鱼--生产->食用植物油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："湘财股份--生产->食用植物油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中粮科工--生产->食用植物油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："京粮控股--生产->食用植物油"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："棕榈油--原材料->膨化食品"在对应"种植"骨干中没找到对应边界
ERROR    找到文本相同的星图边界但起终点有问题，可能是方向写反了或者外骨干标重了，如无法解决联系王之霖。边信息：嘉华股份--生产->大豆油
ERROR    星图边界识别失败，该边："西王食品--生产->玉米油"在对应"种植"骨干中没找到对应边界
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："牛奶--原材料->乳制品"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："商品蛋--父节点->鲜鸡蛋"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："鲜鸡蛋--原材料->烘焙食品"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："商品蛋--父节点->鸭蛋"
ERROR    星图边界识别失败，该边："生鲜食品--父节点->水果"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："水果--原材料->蜜饯果干"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："食品烟酒--父节点->水果"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："水果--父节点->红枣"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："亚洲果业--生产->水果"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："洪九果品--生产->水果"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："生鲜食品--父节点->蔬菜"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："蔬菜--父节点->番茄制品"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："蔬菜--父节点->魔芋"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中国万天控股--生产->蔬菜"在对应"种植"骨干中没找到对应边界
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："肉类--父节点->冷冻肉"
INFO     星图边界识别成功，在"畜牧业"骨干中查到对应边："肉类--父节点->冷鲜肉"
CRITICAL 完成对标记为"食品饮料"的表格的边界进行检查,该表共有87条外边参与联调，通过边9条，冲突边78条

CRITICAL 对标记为"陆运"的表格的边界进行检查,该表共有8条外边参与联调
CRITICAL 陆运
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："钢型材--父节点->钢轨"
ERROR    星图边界识别失败，该边："沥青--原材料->公路基础设施"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："水泥--原材料->公路基础设施"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："石油焦--原材料->公路基础设施"在对应"石油天然气"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："混凝土--原材料->轨道板"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："冷藏车物流--储运->生鲜食品"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："冷藏车物流--储运->冷冻食品"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："钢带--原材料->铁路桥梁"
CRITICAL 完成对标记为"陆运"的表格的边界进行检查,该表共有8条外边参与联调，通过边2条，冲突边6条

CRITICAL 对标记为"地产"的表格的边界进行检查,该表共有58条外边参与联调
CRITICAL 地产
INFO     星图边界识别成功，在"银行"骨干中查到对应边："个人定期储蓄--原材料->房地产销售回款"
INFO     星图边界识别成功，在"银行"骨干中查到对应边："房地产外部融资--父节点->房地产开发贷款"
INFO     星图边界识别成功，在"银行"骨干中查到对应边："个人活期储蓄--原材料->房地产销售回款"
INFO     星图边界识别成功，在"银行"骨干中查到对应边："个人住房贷款--原材料->房地产销售回款"
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："建筑材料--父节点->型钢"
ERROR    星图边界识别失败，该边："有色金属材料--原材料->型钢"在对应"钢铁"骨干中没找到对应边界
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："建筑材料--父节点->螺纹钢"
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："建筑材料--父节点->结构钢管"
INFO     星图边界识别成功，在"海运"骨干中查到对应边："干散货航运--储运->水泥"
ERROR    星图边界识别失败，该边："物产中大--生产->干散货航运"在对应"海运"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成树脂--原材料->建筑涂料"
ERROR    星图边界识别失败，该边："天银机电--生产->家电零配件"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家具--原材料->住宅装修"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："欧派家居--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："顾家家居--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："皮阿诺--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："尚品宅配--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："志邦家居--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海鸥住工--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："索菲亚--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："瑞尔特--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："帝欧家居--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海象新材--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："德艺文创--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："顶固集创--生产->家具"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美凯龙--生产->家具家居零售"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："居然之家--生产->家具家居零售"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："吉宏股份--生产->家具家居零售"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："富森美--生产->家具家居零售"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家具机械设备--父节点->封边机"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家具机械设备--父节点->裁板锯"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家具机械设备--父节点->钻孔机"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："弘亚数控--生产->家具机械设备"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："南兴股份--生产->家具机械设备"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："家居装饰--原材料->住宅装修"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："箭牌家居--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："兔宝宝--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："友邦吊顶--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："皮阿诺--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："东鹏控股--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："趣睡科技--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："联翔股份--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："海鸥住工--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："郑中设计--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："名雕股份--生产->家居装饰"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美芝股份--生产->家居装饰"在对应"家居"骨干中没找到对应边界

{'bitapp_id': 'recsodarpl', 'source': 'reckYl1q4C', 'source_name_ref': '嘉华股份', 'target_name_ref': '大豆油', 'category': '生产', 'more_info': {}, 'target_name': '大豆油', 'source_name': '嘉华股份', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'reciU8qqFN', 'source': 'reciUbnYLh', 'source_name_ref': '嘉华股份', 'target_name_ref': '大豆油', 'category': '生产', 'more_info': {}, 'target_name': '大豆油', 'source_name': '嘉华股份', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recrBWGvOg', 'source': 'recJKHzh9I', 'source_name_ref': '商品蛋', 'target_name_ref': '鲜鸡蛋', 'category': '父节点', 'more_info': {}, 'source_name': '商品蛋', 'target_name': '鲜鸡蛋', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recgLBNlns', 'source_name_ref': '商品蛋', 'target_name_ref': '鲜鸡蛋', 'target': 'recpcDStt8', 'category': '父节点', 'more_info': {}, 'target_name': '鲜鸡蛋', 'source_name': '商品蛋', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recga1qkf6', 'source': 'recJKHzh9I', 'source_name_ref': '商品蛋', 'target_name_ref': '鸭蛋', 'category': '父节点', 'more_info': {}, 'source_name': '商品蛋', 'target_name': '鸭蛋', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recCHzA4Ti', 'source_name_ref': '商品蛋', 'target_name_ref': '鸭蛋', 'target': 'recz7a9pN4', 'category': '父节点', 'more_info': {}, 'target_name': '鸭蛋', 'source_name': '商品蛋', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recHzUBRYP', 'source': 'recAhDtuwO', 'source_name_ref': '房地产外部融资', 'target_name_ref': '房地产开发贷款', 'category': '父节点', 'more_info': {}, 'target_name': '房地产开发贷款', 'source_name': '房地产外部融资', 'external_backbone_name': '银行', 'external_backbone': 'NQX9b6UZ6astfrsthMac8fcgnTb'}
{'bitapp_id': 'recKPPuCIh', 'source_name_ref': '房地产外部融资', 'target_name_ref': '房地产开发贷款', 'target': 'rec0z3PAUQ', 'category': '父节点', 'more_info': {}, 'target_name': '房地产开发贷款', 'source_name': '房地产外部融资', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'receAfFSC9', 'source': 'recWH3lg8K', 'source_name_ref': '建筑材料', 'target_name_ref': '型钢', 'category': '父节点', 'more_info': {}, 'target_name': '型钢', 'source_name': '建筑材料', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'reczDE9lDM', 'source_name_ref': '建筑材料', 'target_name_ref': '型钢', 'target': 'recy7nZD3E', 'category': '父节点', 'more_info': {}, 'target_name': '型钢', 'source_name': '建筑材料', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'rec96Qtno7', 'source': 'recWH3lg8K', 'source_name_ref': '建筑材料', 'target_name_ref': '螺纹钢', 'category': '父节点', 'more_info': {}, 'target_name': '螺纹钢', 'source_name': '建筑材料', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'recm7cgsf4', 'source_name_ref': '建筑材料', 'target_name_ref': '螺纹钢', 'target': 'rec7TE938b', 'category': '父节点', 'more_info': {}, 'target_name': '螺纹钢', 'source_name': '建筑材料', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recU3Qyvb8', 'source': 'recWH3lg8K', 'source_name_ref': '建筑材料', 'target_name_ref': '结构钢管', 'category': '父节点', 'more_info': {}, 'target_name': '结构钢管', 'source_name': '建筑材料', 'external_backbone_name': '钢铁', 'external_backbone': 'IEWKbVaDLayP0Bskj6ucfJB8nGc'}
{'bitapp_id': 'reczSIE7KP', 'source_name_ref': '建筑材料', 'target_name_ref': '结构钢管', 'target': 'recAQAwBQt', 'category': '父节点', 'more_info': {}, 'source_name': '建筑材料', 'target_name': '结构钢管', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}

ERROR    星图边界识别失败，该边："家用电器--原材料->住宅装修"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："美的集团--生产->家用电器"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："格力电器--生产->家用电器"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："四川长虹--生产->家用电器"在对应"家居"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："永安林业--生产->木材"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："C森泰股份--生产->木材"在对应"种植"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："起重机钢轨--原材料->起重机"在对应"钢铁"骨干中没找到对应边界
INFO     星图边界识别成功，在"电影"骨干中查到对应边："商业房地产--原材料->院线放映"
ERROR    星图边界识别失败，该边："华联股份--生产->院线放映"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："嘉凯城--生产->院线放映"在对应"电影"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："好太太--生产->智能家居"在对应"家居"骨干中没找到对应边界
INFO     星图边界识别成功，在"旅游"骨干中查到对应边："商业房地产--原材料->住宿服务"
CRITICAL 完成对标记为"地产"的表格的边界进行检查,该表共有58条外边参与联调，通过边11条，冲突边47条

CRITICAL 对标记为"纺织业"的表格的边界进行检查,该表共有49条外边参与联调
CRITICAL 纺织业
ERROR    星图边界识别失败，该边："面料--父节点->化纤面料"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："常山北明--生产->化纤面料"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"种植"骨干中查到对应边："天然纤维--父节点->棉"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："棉--原材料->再生纤维素纤维"
ERROR    星图边界识别失败，该边："联发股份--生产->棉"在对应"种植"骨干中没找到对应边界
INFO     星图边界识别成功，在"种植"骨干中查到对应边："麻--原材料->麻布"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："天然纤维--父节点->麻"
ERROR    星图边界识别失败，该边："羊毛--原材料->呢绒"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："天然纤维--父节点->羊毛"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："猪皮--原材料->天然皮革"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："牛皮--原材料->天然皮革"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："羊皮--原材料->天然皮革"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："鸭绒--原材料->羽绒"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："鹅绒--原材料->羽绒"在对应"畜牧业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："化学纤维--原材料->混纺"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："化学纤维--父节点->人造纤维"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚酯纤维(涤纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚酰胺纤维(尼龙/锦纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚丙烯腈纤维(腈纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚乙烯醇缩醛纤维(维尼纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚氨酯纤维(氨纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚氯乙烯纤维(氯纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成纤维--父节点->聚烯烃弹力纤维"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："木材--原材料->再生纤维素纤维"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："大豆--原材料->再生蛋白质纤维"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："玉米--原材料->再生蛋白质纤维"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："乙二醇--原材料->聚酯纤维(涤纶)"
ERROR    星图边界识别失败，该边："对苯二甲酸PTA--原材料->聚酯纤维(涤纶)"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："东方盛虹--生产->对苯二甲酸PTA"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："己内酰胺--原材料->尼龙6"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："乙二胺--原材料->尼龙66"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："己二酸--原材料->尼龙66"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："聚四氢呋喃PTMG--原材料->聚氨酯纤维(氨纶)"
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："二苯基甲烷二异氰酸酯MDI--原材料->聚氨酯纤维(氨纶)"
ERROR    星图边界识别失败，该边："万华化学--生产->二苯基甲烷二异氰酸酯MDI"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："丙烯腈--原材料->聚丙烯腈纤维(腈纶)"
ERROR    星图边界识别失败，该边："聚氯乙烯--原材料->聚氯乙烯纤维(氯纶)"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中泰化学--生产->聚氯乙烯"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："万华化学--生产->乙烯"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："聚乙烯醇PVA--原材料->聚乙烯醇缩醛纤维(维尼纶)"
ERROR    星图边界识别失败，该边："乙炔法--原材料->聚乙烯醇PVA"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："聚烯烃--原材料->聚烯烃弹力纤维"
ERROR    星图边界识别失败，该边："甲醇--原材料->聚乙烯醇缩醛纤维(维尼纶)"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："乙炔--原材料->乙炔法"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："华峰化学--生产->聚氨酯原液"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："聚氨酯原液--原材料->鞋类原料"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："荣盛石化--生产->聚氨酯原液"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"石油化工"骨干中查到对应边："合成橡胶--原材料->鞋类原料"
ERROR    星图边界识别失败，该边："EVA--原材料->鞋类原料"在对应"石油化工"骨干中没找到对应边界
CRITICAL 完成对标记为"纺织业"的表格的边界进行检查,该表共有49条外边参与联调，通过边24条，冲突边25条

CRITICAL 对标记为"航空航天"的表格的边界进行检查,该表共有26条外边参与联调
CRITICAL 航空航天
ERROR    星图边界识别失败，该边："本川智能--生产->印制电路板"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："覆铜板--原材料->印制电路板"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："协和电子--生产->印制电路板"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："印制电路板--原材料->航空电子"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："ST新研--生产->航空零部件"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："铖昌科技--生产->电源管理模块"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："川大智胜--生产->航空管制系统"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："多伦科技--生产->通信服务"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天工程--生产->工业压力容器"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天科技--生产->惯性导航"在对应"汽车制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："航天科技--生产->加速度传感器"在对应"汽车制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："景嘉微--生产->雷达"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："晶品特装--生产->光电侦察设备"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："利君股份--生产->航空零部件"在对应"工业制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："迈信林--生产->电连接器"在对应"汽车制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："迈信林--生产->航空零部件"在对应"汽车制造"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："四创电子--生产->雷达"在对应"电力储能"骨干中没找到对应边界

{'bitapp_id': 'rec7boTbMB', 'source': 'rec3C33UU3', 'source_name_ref': '商业房地产', 'target_name_ref': '院线放映', 'category': '原材料', 'more_info': {}, 'source_name': '商业房地产', 'target_name': '院线放映', 'external_backbone_name': '电影', 'external_backbone': 'bascnCFrkVGczkkyWTXqAdLTLqe'}
{'bitapp_id': 'recNyxhy9w', 'source_name_ref': '商业房地产', 'target_name_ref': '院线放映', 'target': 'recRamnp5z', 'category': '原材料', 'more_info': {}, 'target_name': '院线放映', 'source_name': '商业房地产', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recaFvjhdY', 'source': 'rec3C33UU3', 'source_name_ref': '商业房地产', 'target_name_ref': '住宿服务', 'category': '原材料', 'more_info': {}, 'source_name': '商业房地产', 'target_name': '住宿服务', 'external_backbone_name': '旅游', 'external_backbone': 'bascnoh0v8aKAFhMqihl6dxxTdf'}
{'bitapp_id': 'recscetuwn', 'source_name_ref': '商业房地产', 'target_name_ref': '住宿服务', 'target': 'recoBIz2VC', 'category': '原材料', 'more_info': {'pro_line': '主营'}, 'target_name': '住宿服务', 'source_name': '商业房地产', 'external_backbone_name': '地产', 'external_backbone': 'HRwdbhrmTaAOBws3hLhcKhKbnlh'}
{'bitapp_id': 'recvb41AqG', 'source': 'recKLrj75S', 'source_name_ref': '天然纤维', 'target_name_ref': '棉', 'category': '父节点', 'more_info': {}, 'target_name': '棉', 'source_name': '天然纤维', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'rechYj1XlC', 'source_name_ref': '天然纤维', 'target_name_ref': '棉', 'target': 'recEwBBl2m', 'category': '父节点', 'more_info': {}, 'source_name': '天然纤维', 'target_name': '棉', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}
{'bitapp_id': 'recDUEZPdC', 'source': 'recKLrj75S', 'source_name_ref': '天然纤维', 'target_name_ref': '麻', 'category': '父节点', 'more_info': {}, 'target_name': '麻', 'source_name': '天然纤维', 'external_backbone_name': '种植', 'external_backbone': 'Rr4XbrLEzaargtsgfF1c9ppxnsc'}
{'bitapp_id': 'recK8EkCRY', 'source_name_ref': '天然纤维', 'target_name_ref': '麻', 'target': 'recksqMkxW', 'category': '父节点', 'more_info': {}, 'source_name': '天然纤维', 'target_name': '麻', 'external_backbone_name': '纺织业', 'external_backbone': 'KfNAbDo9GaFPWusomZgck7Zeneh'}

ERROR    星图边界识别失败，该边："亚光科技--生产->射频器件"在对应"半导体"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中航电测--生产->飞机"在对应"电力储能"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："合成树脂--原材料->预浸料"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："聚丙烯腈--原材料->碳纤维预浸料"在对应"石油化工"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："聚氯乙烯--原材料->隔热材料"在对应"石油化工"骨干中没找到对应边界
INFO     星图边界识别成功，在"半导体"骨干中查到对应边："逻辑芯片--原材料->航空电子"
ERROR    星图边界识别失败，该边："铝合金--原材料->火箭发动机外壳"在对应"钢铁"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："宝钛股份--生产->钛合金"在对应"钢铁"骨干中没找到对应边界
INFO     星图边界识别成功，在"钢铁"骨干中查到对应边："钛合金--原材料->航空器外壳，航空器骨架"
CRITICAL 完成对标记为"航空航天"的表格的边界进行检查,该表共有26条外边参与联调，通过边2条，冲突边24条

CRITICAL 对标记为"畜牧业"的表格的边界进行检查,该表共有24条外边参与联调
CRITICAL 畜牧业
INFO     星图边界识别成功，在"种植"骨干中查到对应边："玉米--原材料->能量原材料"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："小麦--原材料->能量原材料"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："高粱--原材料->能量原材料"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："豆粕--原材料->植物性蛋白"
INFO     星图边界识别成功，在"种植"骨干中查到对应边："菜粕--原材料->植物性蛋白"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："牛奶--原材料->乳制品"
ERROR    星图边界识别失败，该边："伊利股份--生产->乳制品"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："肉鸭--原材料->鸭绒"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："ST华英--生产->鸭绒"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："肉牛商品牛--原材料->牛皮"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："生猪；商品猪--原材料->猪皮"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："巨星农牧--生产->猪皮"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："肉裘商品羊--原材料->羊皮"在对应"纺织业"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："肉裘商品羊--原材料->羊毛"在对应"纺织业"骨干中没找到对应边界
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："鲜鸡蛋--原材料->烘焙食品"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："商品蛋--父节点->鲜鸡蛋"
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："商品蛋--父节点->鸭蛋"
ERROR    星图边界识别失败，该边："晓鸣股份--生产->商品蛋"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："肉类--父节点->冷冻肉"
ERROR    星图边界识别失败，该边："华统股份--生产->冷冻肉"在对应"食品饮料"骨干中没找到对应边界
INFO     星图边界识别成功，在"食品饮料"骨干中查到对应边："肉类--父节点->冷鲜肉"
ERROR    星图边界识别失败，该边："华统股份--生产->冷鲜肉"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："肉类--父节点->热鲜肉"在对应"食品饮料"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："四方科技--生产->冷链储存"在对应"食品饮料"骨干中没找到对应边界
CRITICAL 完成对标记为"畜牧业"的表格的边界进行检查,该表共有24条外边参与联调，通过边11条，冲突边13条

CRITICAL 对标记为"美妆"的表格的边界进行检查,该表共有0条外边参与联调
CRITICAL 美妆
CRITICAL 完成对标记为"美妆"的表格的边界进行检查,该表共有0条外边参与联调，通过边0条，冲突边0条

CRITICAL 对标记为"旅游"的表格的边界进行检查,该表共有8条外边参与联调
CRITICAL 旅游
INFO     星图边界识别成功，在"地产"骨干中查到对应边："商业房地产--原材料->住宿服务"
ERROR    星图边界识别失败，该边："华侨城A--生产->商业房地产"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："三湘印象--生产->商业房地产"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："新华联--生产->商业房地产"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别失败，该边：" 海南高速--生产->商业房地产"在对应"地产"骨干中没找到对应边界
ERROR    星图边界识别到对应的边，但对应边的外骨干标记与本骨干不符，对应边的外骨干标记为："石油天然气"，对应边为："航空汽油--原材料->航空运输"
ERROR    星图边界识别失败，该边："中科云网--生产->游戏"在对应"互联网云计算"骨干中没找到对应边界
ERROR    星图边界识别失败，该边："中视传媒--生产->影视制片"在对应"电影"骨干中没找到对应边界
CRITICAL 完成对标记为"旅游"的表格的边界进行检查,该表共有8条外边参与联调，通过边1条，冲突边7条

{'bitapp_id': 'recmOTfpwV', 'source': 'recvVidZzf', 'source_name_ref': '牛奶', 'target_name_ref': '乳制品', 'category': '原材料', 'more_info': {}, 'source_name': '牛奶', 'target_name': '乳制品', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recpjqBpj3', 'source_name_ref': '牛奶', 'target_name_ref': '乳制品', 'target': 'rec8OHrc2n', 'category': '原材料', 'more_info': {}, 'source_name': '牛奶', 'target_name': '乳制品', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recKurD4j9', 'source': 'recpcDStt8', 'source_name_ref': '鲜鸡蛋', 'target_name_ref': '烘焙食品', 'category': '原材料', 'more_info': {}, 'source_name': '鲜鸡蛋', 'target_name': '烘焙食品', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'rec4q4VAzE', 'source_name_ref': '鲜鸡蛋', 'target_name_ref': '烘焙食品', 'target': 'recsouIpQc', 'category': '原材料', 'more_info': {}, 'source_name': '鲜鸡蛋', 'target_name': '烘焙食品', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'recNA7d4Rz', 'source': 'recoBIz2VC', 'source_name_ref': '肉类', 'target_name_ref': '冷冻肉', 'category': '父节点', 'more_info': {}, 'source_name': '肉类', 'target_name': '冷冻肉', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'rechrxdtGW', 'source_name_ref': '肉类', 'target_name_ref': '冷冻肉', 'target': 'recNvaXbHb', 'category': '父节点', 'more_info': {}, 'target_name': '冷冻肉', 'source_name': '肉类', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}
{'bitapp_id': 'rec2py92uG', 'source': 'recoBIz2VC', 'source_name_ref': '肉类', 'target_name_ref': '冷鲜肉', 'category': '父节点', 'more_info': {}, 'source_name': '肉类', 'target_name': '冷鲜肉', 'external_backbone_name': '食品饮料', 'external_backbone': 'BQfjb41pka6j8os5iIZcqCpjnV1'}
{'bitapp_id': 'recfkiRzzG', 'source_name_ref': '肉类', 'target_name_ref': '冷鲜肉', 'target': 'recfRjBoUi', 'category': '父节点', 'more_info': {}, 'target_name': '冷鲜肉', 'source_name': '肉类', 'external_backbone_name': '畜牧业', 'external_backbone': 'HmoFbzbXNakHFpsyCDUctlOTnIb'}

In [48]:
report_df

      level                                               body backbone  rough
0     error  出现边没有找到对应的起/终点，可能是因为起终点没有勾选粗骨干权限。id:"rec3f1Oy9...     零售餐饮   True
0   warning  检查到本骨干之外的,属于“石油天然气”骨干的边，该边不参与冲突检查：[英国布伦特原油]-(反...       海运   True
0   warning  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款]-(父节点)...       地产   True
0   warning  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款]-(父节点)...       地产   True
0   warning  检查到本骨干之外的,属于“银行”骨干的边，该边不参与冲突检查：[房地产开发贷款余额]-(反映...       地产   True
..      ...                                                ...      ...    ...
0     error   星图边界识别失败，该边："丁苯橡胶--原材料->电线电缆"在对应"电力储能"骨干中没找到对应边界     石油化工   True
0     error   星图边界识别失败，该边："POE粒子--原材料->POE胶膜"在对应"光伏"骨干中没找到对应边界     石油化工   True
0     error   星图边界识别失败，该边："煤制乙二醇工艺--原材料->乙二醇"在对应"煤炭"骨干中没找到对应边界     石油化工   True
0     error   星图边界识别失败，该边："合成气--原材料->煤制乙二醇工艺"在对应"煤炭"骨干中没找到对应边界     石油化工   True
0     error     星图边界识别失败，该边："煤制甲醇法--原材料->合成气"在对应"煤炭"骨干中没找到对应边界     石油化工   True

[306 rows x 4 columns]

In [19]:
from datetime import datetime
d=datetime.today().__format__("%Y%m%d")
report_df.to_csv(r'E:\wangzhilin\QuantumGalaxy\opt\combine_check\report-%s.csv'%d)

In [20]:
dup=find_common_elements(result,files)
dup=[[d[0],d[1][0],d[1][1]] for d in dup]
dup
import pandas as pd
dupdf=pd.DataFrame(data=dup,columns=['节点名','所属骨干1','所属骨干2'])
dupdf.sort_values('节点名')

dupdf.to_csv(r'E:\wangzhilin\QuantumGalaxy\opt\combine_check\dupnames.csv')
dupdf

       节点名 所属骨干1  所属骨干2
0       氩气    医药     钢铁
1       淀粉    医药     种植
2       玉米    医药     种植
3      天然气    医药  石油天然气
4       丙烯    医药   石油化工
..     ...   ...    ...
201     肉鸭  食品饮料    畜牧业
202  饮食类需求  食品饮料    畜牧业
203     牛肉  食品饮料    畜牧业
204     肉牛  食品饮料    畜牧业
205     猪肉  食品饮料    畜牧业

[206 rows x 3 columns]

In [21]:
def save_json(result):
    import json
    
    d=datetime.today().__format__("%Y%m%d")
    b = json.dumps(result)
    f2 = open(r'E:\wangzhilin\QuantumGalaxy\opt\combine_check\results\result-%s.json'%d, 'w')
    f2.write(b)
    f2.close()
save_json(result)

# result2cypher

对所有表格里的internalnodes internallinks+ good_external_links就ok？（goodexternallink 有两组,可能moreinfo还不相同,用merge？不相同时会有重边。需要提前融合外边

重名内部节点处理？ 公司名字有唯一性约束，其他没有。merge会对{}内的项进行完全匹配，内部重名和连线不会出错（需要联调时检查并warning）。只需要把公司做更新backbone和code
连边的时候需要对点明确骨干？bitappid！

node的数据项 backbone，配图（地址，后续做,backbonetoken+bitappid，后续每次刷库时可以用md5验证图片之后再下到本地？api没有md5，必须要下载吧），code,category,（x,y）

link的数据项 sourcename type targetname (产线地位)， 只用名字匹配？？

其他信息及其结构要改82的bitablework和81的飞书接口

In [22]:

vertexs=[]
links={}


nodedic={'产品':'Product','企业':'Company','指标':'Indicator','工艺':'Technique','需求':'Demand'}
linkdic={'原材料':'compose','供应':'supply','父节点':'parent','储运':'carry','生产':'produce','同位':'peer','反映':'measure'}
for file_token,data in result.items():
    print(data['backbone_mark'])
    print('内部节点:%s'%len(data['internal_nodes']))
    print('内部边:%s'%len(data['internal_links']))
    print('外部节点:%s'%len(data['external_nodes']))
    print('外部边:%s'%len(data['good_external_links']))
    for node in data['internal_nodes']:
        post_node=deepcopy(node)
        cate=post_node.pop('category')
        cate_new=nodedic.get(cate,cate)
        post_node['category']=cate_new
        more=post_node.pop('more_info')
        post_node['file_token']=file_token
        post_node['backbone']=data['backbone_mark']
        if more:
            post_node.update(more)
        vertexs.append(post_node)
    for link in data['internal_links']:
        post_link={}
        post_link['source']=link['source']
        post_link['target']=link['target']
        post_link['target_name']=link['target_name']
        post_link['source_name']=link['source_name']
        post_link['category']=linkdic.get(link['category'],link['category'])
        if link.get('more_info'):
            
            post_link.update(link['more_info'])
        key=link['source_name']+'--'+link['category']+'->'+link['target_name']
        if key not in links.keys():
            links[key]=post_link
        else:
            body="“%s”骨干内部重复的边:'%s'"%(data['backbone_mark'],key)
            logger.warning(body)
            report_df=append_df(report_df,['warning',body,data['backbone_mark'],True])
            links[key].update(post_link)
    for link in data['good_external_links']:
        #要找到其节点所在本骨干的recordid，不能直接用link里的id。。
        post_link={}
        post_link['source']=link['source']
        post_link['target']=link['target']
        post_link['target_name']=link['target_name']
        post_link['source_name']=link['source_name']
        post_link['category']=linkdic.get(link['category'],link['category'])
        if link.get('more_info'):
            post_link.update(link['more_info'])
        key=link['source_name']+'--'+link['category']+'->'+link['target_name']
        if key not in links.keys():
            links[key]=post_link
        else:
            #print("dup!:'%s'"%key)
            links[key].update(post_link)
post_result={'vertex':vertexs,'link':list(links.values())}
print(len(post_result['vertex']))
print(len(post_result['link']))

WARNING  “半导体”骨干内部重复的边:'华兴源创--生产->芯片封装测试设备'
WARNING  “半导体”骨干内部重复的边:'朗科科技--生产->内存'
WARNING  “半导体”骨干内部重复的边:'北方华创--生产->半导体薄膜沉积设备'
WARNING  “半导体”骨干内部重复的边:'北方华创--生产->刻蚀机'
WARNING  “半导体”骨干内部重复的边:'北方华创--生产->半导体清洗设备'
WARNING  “半导体”骨干内部重复的边:'澜起科技--生产->电源管理芯片，电源管理IC'
WARNING  “半导体”骨干内部重复的边:'澜起科技--生产->存储芯片'
WARNING  “半导体”骨干内部重复的边:'润欣科技--生产->电子元器件分销服务'
WARNING  “半导体”骨干内部重复的边:'力源信息--生产->电子元器件分销服务'
WARNING  “半导体”骨干内部重复的边:'雅创电子--生产->电子元器件分销服务'
WARNING  “锂离子电池”骨干内部重复的边:'赣锋锂业--生产->电池级碳酸锂'
WARNING  “锂离子电池”骨干内部重复的边:'赣锋锂业--生产->氢氧化锂'
WARNING  “锂离子电池”骨干内部重复的边:'天齐锂业--生产->电池级碳酸锂'
WARNING  “锂离子电池”骨干内部重复的边:'天齐锂业--生产->氢氧化锂'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'传动类装置--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'传感类装置--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'伺服电机--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'磁材--原材料->伺服电机'
WARNING  “工业制造”骨干内部重复的边:'滚珠丝杠--原材料->执行器'
WARNING  “工业制造”骨干内部重复的边:'步进电机--原材料->步进系统'
WARNING  “工业制造”骨干内部重复的边:'编码器--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'高温合金--原材料->发动机'
WARNING  “工业制造”骨干内部重复的边:'主轴箱--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'执行器--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'辅助系统--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'液压系统--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'伺服驱动器--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'橡胶软管--原材料->液压系统'
WARNING  “工业制造”骨干内部重复的边:'工业互联网--原材料->工业网络设备'
WARNING  “工业制造”骨干内部重复的边:'工业软件--原材料->工业网络设备'
WARNING  “工业制造”骨干内部重复的边:'机器视觉（智能视觉装备）--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'外部传感器--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'仪表--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'工业机器人--原材料->工业机器人系统集成'
WARNING  “工业制造”骨干内部重复的边:'工程机械设备--原材料->工程承包'
WARNING  “工业制造”骨干内部重复的边:'立方氮化硼--原材料->加工中心'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--原材料->执行层'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->控制器'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->HMI人机界面接口'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->变频器'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'传动类装置--父节点->减速器'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用电气部件'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->步进系统'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用机械部件'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用设备'
WARNING  “工业制造”骨干内部重复的边:'微特电机--父节点->伺服电机'
WARNING  “工业制造”骨干内部重复的边:'微特电机--父节点->步进电机'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->断路器'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->发动机'
WARNING  “工业制造”骨干内部重复的边:'机器人--父节点->特种机器人'
WARNING  “工业制造”骨干内部重复的边:'机器人--父节点->工业机器人'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->锂电设备'

医药
内部节点:328
内部边:270
外部节点:0
外部边:0
通信
内部节点:205
内部边:101
外部节点:4
外部边:0
半导体
内部节点:488
内部边:586
外部节点:37
外部边:7
锂离子电池
内部节点:306
内部边:426
外部节点:18
外部边:2
工业制造
内部节点:566
内部边:636
外部节点:2
外部边:0

WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->半导体设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->工程机械设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->光伏设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->高端仪器'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->3C产品生产设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->汽车生产设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->其他行业生产设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->石化行业设备'
WARNING  “工业制造”骨干内部重复的边:'执行层--父节点->机器人'
WARNING  “工业制造”骨干内部重复的边:'执行层--父节点->数控机床'
WARNING  “工业制造”骨干内部重复的边:'机床主体--原材料->模具'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->空气分离设备'
WARNING  “工业制造”骨干内部重复的边:'空气分离设备--原材料->工业气体'
WARNING  “工业制造”骨干内部重复的边:'液压密封产品--原材料->液压系统'
WARNING  “工业制造”骨干内部重复的边:'其他工业原材料--原材料->通用部件与服务'
WARNING  “工业制造”骨干内部重复的边:'其他行业生产设备--父节点->核工业设备'
WARNING  “工业制造”骨干内部重复的边:'工程设计与咨询--原材料->工程承包'
WARNING  “工业制造”骨干内部重复的边:'工业网络设备--原材料->智能工厂'
WARNING  “工业制造”骨干内部重复的边:'感知设备--原材料->智能工厂'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'传动类装置--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'机床主体--原材料->数控机床'
WARNING  “工业制造”骨干内部重复的边:'数控系统--原材料->数控机床'
WARNING  “工业制造”骨干内部重复的边:'工业互联网--父节点->工业以太网'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->控制器'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->HMI人机界面接口'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->变频器'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'传动类装置--父节点->减速器'
WARNING  “工业制造”骨干内部重复的边:'工业互联网--原材料->工业网络设备'
WARNING  “工业制造”骨干内部重复的边:'工业软件--原材料->工业网络设备'
WARNING  “工业制造”骨干内部重复的边:'机器视觉（智能视觉装备）--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'外部传感器--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'机器人--父节点->特种机器人'
WARNING  “工业制造”骨干内部重复的边:'机器人--父节点->工业机器人'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用电气部件'
WARNING  “工业制造”骨干内部重复的边:'传感类装置--原材料->通用自动化控制系统'
WARNING  “工业制造”骨干内部重复的边:'伺服电机--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->步进系统'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用机械部件'
WARNING  “工业制造”骨干内部重复的边:'磁材--原材料->伺服电机'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->锂电设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->半导体设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->工程机械设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->光伏设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->高端仪器'
WARNING  “工业制造”骨干内部重复的边:'滚珠丝杠--原材料->执行器'
WARNING  “工业制造”骨干内部重复的边:'工业机器人--原材料->工业机器人系统集成'
WARNING  “工业制造”骨干内部重复的边:'通用部件与服务--父节点->通用设备'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->3C产品生产设备'
WARNING  “工业制造”骨干内部重复的边:'步进电机--原材料->步进系统'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->汽车生产设备'
WARNING  “工业制造”骨干内部重复的边:'工程机械设备--原材料->工程承包'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->其他行业生产设备'
WARNING  “工业制造”骨干内部重复的边:'编码器--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->石化行业设备'
WARNING  “工业制造”骨干内部重复的边:'微特电机--父节点->伺服电机'
WARNING  “工业制造”骨干内部重复的边:'微特电机--父节点->步进电机'
WARNING  “工业制造”骨干内部重复的边:'控制类设备--父节点->断路器'
WARNING  “工业制造”骨干内部重复的边:'仪表--原材料->感知设备'
WARNING  “工业制造”骨干内部重复的边:'驱动类设备--父节点->发动机'
WARNING  “工业制造”骨干内部重复的边:'高温合金--原材料->发动机'
WARNING  “工业制造”骨干内部重复的边:'主轴箱--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'执行器--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'辅助系统--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'液压系统--原材料->传动类装置'
WARNING  “工业制造”骨干内部重复的边:'机床主体--原材料->模具'
WARNING  “工业制造”骨干内部重复的边:'伺服驱动器--原材料->伺服系统'
WARNING  “工业制造”骨干内部重复的边:'碳化钨--原材料->硬质合金'
WARNING  “工业制造”骨干内部重复的边:'硬质合金--原材料->机床刀具'
WARNING  “工业制造”骨干内部重复的边:'人造金刚石--原材料->机床刀具'
WARNING  “工业制造”骨干内部重复的边:'特种机器人--原材料->核反应堆'
WARNING  “工业制造”骨干内部重复的边:'橡胶软管--原材料->液压系统'
WARNING  “工业制造”骨干内部重复的边:'工业IC--原材料->工业网络设备'
WARNING  “工业制造”骨干内部重复的边:'钨粉--原材料->碳化钨'
WARNING  “工业制造”骨干内部重复的边:'碳粉--原材料->碳化钨'
WARNING  “工业制造”骨干内部重复的边:'空气分离设备--原材料->工业气体'
WARNING  “工业制造”骨干内部重复的边:'行业专用设备--父节点->空气分离设备'
WARNING  “工业制造”骨干内部重复的边:'液压密封产品--原材料->液压系统'
WARNING  “工业制造”骨干内部重复的边:'模块化建设--原材料->工程承包'
WARNING  “光伏”骨干内部重复的边:'横店东磁--生产->HJT电池'
WARNING  “光伏”骨干内部重复的边:'横店东磁--生产->PERC电池'
WARNING  “光伏”骨干内部重复的边:'横店东磁--生产->TOPCon电池'
WARNING  “光伏”骨干内部重复的边:'珈伟新能--生产->光伏发电'
WARNING  “光伏”骨干内部重复的边:'晶澳科技--生产->光伏组件'
WARNING  “光伏”骨干内部重复的边:'天合光能--生产->光伏组件'
WARNING  “光伏”骨干内部重复的边:'罗博特科--生产->电镀设备'
WARNING  “电力储能”骨干内部重复的边:'光伏电站--原材料->光伏发电'
WARNING  “电力储能”骨干内部重复的边:'发电站--父节点->光伏电站'
WARNING  “电力储能”骨干内部重复的边:'好利科技--生产->熔断器'
WARNING  “电力储能”骨干内部重复的边:'朗新科技--生产->智慧能源服务平台'
WARNING  “电力储能”骨干内部重复的边:'东方电气--生产->电站工程建设'
WARNING  “电力储能”骨干内部重复的边:'上海电气--生产->发电机组'
WARNING  “风电”骨干内部重复的边:'金龙羽--生产->电缆'
WARNING  “风电”骨干内部重复的边:'日丰股份--生产->电缆'
WARNING  “风电”骨干内部重复的边:'中广核新能源--生产->风力发电'

钢铁
内部节点:136
内部边:141
外部节点:45
外部边:9
光伏
内部节点:232
内部边:276
外部节点:6
外部边:2
煤炭
内部节点:106
内部边:108
外部节点:5
外部边:2
电力储能
内部节点:498
内部边:578
外部节点:15
外部边:5
风电
内部节点:135
内部边:156
外部节点:2
外部边:1

WARNING  “风电”骨干内部重复的边:'龙源电力--生产->风力发电'
WARNING  “风电”骨干内部重复的边:'金风科技--生产->风电整机'
WARNING  “风电”骨干内部重复的边:'金风科技--生产->风电发电机组'
WARNING  “风电”骨干内部重复的边:'金风科技--生产->风电场'
WARNING  “贵金属”骨干内部重复的边:'豫光金铅--生产->标准银'
WARNING  “海运”骨干内部重复的边:'青岛港--生产->码头运营'
WARNING  “海运”骨干内部重复的边:'秦港股份--生产->码头运营'
WARNING  “海运”骨干内部重复的边:'中船防务--生产->舰船维修'
WARNING  “海运”骨干内部重复的边:'中国外运--生产->物流服务'
WARNING  “海运”骨干内部重复的边:'中远海控--生产->集装箱航运'
WARNING  “海运”骨干内部重复的边:'中远海能--生产->原油航运'
WARNING  “汽车制造”骨干内部重复的边:'双环传动--生产->传动系统'
WARNING  “汽车制造”骨干内部重复的边:'征和工业--生产->传动系统'
WARNING  “汽车制造”骨干内部重复的边:'科达利--生产->锂电池结构件'
WARNING  “汽车制造”骨干内部重复的边:'新宙邦--生产->锂电池电解液'
WARNING  “汽车制造”骨干内部重复的边:'轮胎--原材料->车轮'
WARNING  “汽车制造”骨干内部重复的边:'汽车内饰--原材料->汽车车身'
WARNING  “汽车制造”骨干内部重复的边:'上汽集团--生产->汽车'
WARNING  “人力资源（教育）”骨干内部重复的边:'新华文轩--生产->图书期刊出版'
WARNING  “人力资源（教育）”骨干内部重复的边:'新华文轩--生产->图书期刊发行'
WARNING  “广告传媒”骨干内部重复的边:'芒果超媒--生产->广播电视媒体'
WARNING  “广告传媒”骨干内部重复的边:'城市传媒--生产->出版物'
WARNING  “广告传媒”骨干内部重复的边:'分众传媒--生产->场景媒体'
WARNING  “广告传媒”骨干内部重复的边:'易点天下--生产->广告营销'
WARNING  “石油化工”骨干内部重复的边:'苯--原材料->己二酸'
WARNING  “石油化工”骨干内部重复的边:'万华化学--生产->二苯基甲烷二异氰酸酯MDI'

贵金属
内部节点:102
内部边:119
外部节点:0
外部边:0
海运
内部节点:186
内部边:207
外部节点:9
外部边:9
消费电子
内部节点:143
内部边:194
外部节点:3
外部边:0
种植
内部节点:300
内部边:207
外部节点:48
外部边:17
汽车制造
内部节点:433
内部边:432
外部节点:9
外部边:2
人力资源（教育）
内部节点:237
内部边:326
外部节点:0
外部边:0
零售餐饮
内部节点:58
内部边:66
外部节点:0
外部边:0
广告传媒
内部节点:110
内部边:124
外部节点:3
外部边:0
石油天然气
内部节点:61
内部边:68
外部节点:5
外部边:4
银行
内部节点:203
内部边:278
外部节点:3
外部边:4
石油化工
内部节点:137
内部边:125
外部节点:19
外部边:18

WARNING  “互联网云计算”骨干内部重复的边:'剑桥科技--生产->光模块'
WARNING  “互联网云计算”骨干内部重复的边:'联特科技--生产->光模块'
WARNING  “互联网云计算”骨干内部重复的边:'博创科技--生产->光模块'
WARNING  “互联网云计算”骨干内部重复的边:'地基网络--父节点->宽带网络'
WARNING  “互联网云计算”骨干内部重复的边:'德科立--生产->光模块'
WARNING  “互联网云计算”骨干内部重复的边:'光芯片--原材料->光模块'
WARNING  “环保”骨干内部重复的边:'无机废气治理--父节点->脱硝'
WARNING  “环保”骨干内部重复的边:'无机废气治理--父节点->除尘'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->水治理'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->大气治理'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->固废治理'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->噪声控制'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->土壤修复'
WARNING  “环保”骨干内部重复的边:'水治理--父节点->工业废水治理'
WARNING  “环保”骨干内部重复的边:'水治理--父节点->生活污水治理'
WARNING  “环保”骨干内部重复的边:'水治理--父节点->地下水治理'
WARNING  “环保”骨干内部重复的边:'固废治理--父节点->危废治理'
WARNING  “环保”骨干内部重复的边:'固废治理--父节点->工业废弃物治理'
WARNING  “环保”骨干内部重复的边:'固废治理--父节点->生活垃圾治理'
WARNING  “环保”骨干内部重复的边:'土壤修复--父节点->污染耕地修复'
WARNING  “环保”骨干内部重复的边:'土壤修复--父节点->工矿废地修复'
WARNING  “环保”骨干内部重复的边:'土壤修复--父节点->盐碱地修复'
WARNING  “环保”骨干内部重复的边:'工业废气治理--父节点->无机废气治理'
WARNING  “环保”骨干内部重复的边:'反渗透法--原材料->地下水治理'
WARNING  “环保”骨干内部重复的边:'还原沉淀法--原材料->地下水治理'
WARNING  “环保”骨干内部重复的边:'自然净化法--原材料->地下水治理'
WARNING  “环保”骨干内部重复的边:'垃圾焚烧--原材料->危废治理'
WARNING  “环保”骨干内部重复的边:'垃圾焚烧--原材料->工业废弃物治理'
WARNING  “环保”骨干内部重复的边:'垃圾焚烧--原材料->生活垃圾治理'
WARNING  “环保”骨干内部重复的边:'垃圾焚烧--原材料->炉渣'
WARNING  “环保”骨干内部重复的边:'炉渣--原材料->砖'
WARNING  “环保”骨干内部重复的边:'化学法--原材料->生活污水治理'
WARNING  “环保”骨干内部重复的边:'光大环境--生产->垃圾焚烧'
WARNING  “环保”骨干内部重复的边:'东方园林--生产->工业废弃物治理'
WARNING  “环保”骨干内部重复的边:'环保服务--父节点->环境监测'
WARNING  “环保”骨干内部重复的边:'南大环境--生产->环境监测'
WARNING  “环保”骨干内部重复的边:'京蓝科技--生产->土壤修复'
WARNING  “环保”骨干内部重复的边:'德创环保--生产->除尘设备'
WARNING  “环保”骨干内部重复的边:'卓锦股份--生产->土壤修复'
WARNING  “环保”骨干内部重复的边:'卓锦股份--生产->固废治理'
WARNING  “环保”骨干内部重复的边:'卓锦股份--生产->大气治理'
WARNING  “环保”骨干内部重复的边:'脱硝设备--原材料->脱硝'
WARNING  “环保”骨干内部重复的边:'除尘设备--原材料->除尘'
WARNING  “环保”骨干内部重复的边:'脱硝设备--父节点->全负荷脱硝设备'
WARNING  “环保”骨干内部重复的边:'青达环保--生产->全负荷脱硝设备'
WARNING  “环保”骨干内部重复的边:'土壤修复--父节点->生态湿地修复'
WARNING  “环保”骨干内部重复的边:'东珠生态--生产->生态湿地修复'
WARNING  “环保”骨干内部重复的边:'工业废气治理--父节点->有机废气治理（VOCs）'
WARNING  “环保”骨干内部重复的边:'川润股份--生产->无机废气治理'

互联网云计算
内部节点:889
内部边:969
外部节点:22
外部边:1
家居
内部节点:38
内部边:29
外部节点:3
外部边:0
环保
内部节点:79
内部边:178
外部节点:0
外部边:0

WARNING  “环保”骨干内部重复的边:'锅炉烟气在线监测仪--原材料->无机废气治理'
WARNING  “环保”骨干内部重复的边:'雪迪龙--生产->锅炉烟气在线监测仪'
WARNING  “环保”骨干内部重复的边:'大气治理--父节点->工业废气治理'
WARNING  “环保”骨干内部重复的边:'龙源技术--生产->工业废气治理'
WARNING  “环保”骨干内部重复的边:'化学修复--原材料->土壤修复'
WARNING  “环保”骨干内部重复的边:'物理修复--原材料->土壤修复'
WARNING  “环保”骨干内部重复的边:'生物修复--原材料->土壤修复'
WARNING  “环保”骨干内部重复的边:'天华超净--生产->静电及微污染消除与监控系统'
WARNING  “环保”骨干内部重复的边:'静电及微污染消除与监控系统--原材料->环境监测'
WARNING  “环保”骨干内部重复的边:'启迪环境--生产->水治理'
WARNING  “环保”骨干内部重复的边:'中持股份--生产->生活污水治理'
WARNING  “环保”骨干内部重复的边:'启迪环境--生产->固废治理'
WARNING  “环保”骨干内部重复的边:'中国天楹--生产->垃圾焚烧'
WARNING  “环保”骨干内部重复的边:'环卫保洁--原材料->生活垃圾治理'
WARNING  “环保”骨干内部重复的边:'中国天楹--生产->垃圾智慧分类'
WARNING  “环保”骨干内部重复的边:'智慧水务平台--原材料->水治理'
WARNING  “环保”骨干内部重复的边:'华控赛格--生产->水治理'
WARNING  “环保”骨干内部重复的边:'华控赛格--生产->智慧水务平台'
WARNING  “环保”骨干内部重复的边:'空气净化设备--原材料->大气治理'
WARNING  “环保”骨干内部重复的边:'污水处理设备--原材料->水治理'
WARNING  “环保”骨干内部重复的边:'创元科技--生产->空气净化设备'
WARNING  “环保”骨干内部重复的边:'创元科技--生产->污水处理设备'
WARNING  “环保”骨干内部重复的边:'垃圾智慧分类--原材料->环卫保洁'
WARNING  “环保”骨干内部重复的边:'浙富控股--生产->危废治理'
WARNING  “环保”骨干内部重复的边:'地表水监测装置--原材料->环境监测'
WARNING  “环保”骨干内部重复的边:'变压器油溶解气体监测装置--原材料->环境监测'
WARNING  “环保”骨干内部重复的边:'理工能科--生产->地表水监测装置'
WARNING  “环保”骨干内部重复的边:'理工能科--生产->变压器油溶解气体监测装置'
WARNING  “环保”骨干内部重复的边:'理工能科--生产->土壤修复'
WARNING  “环保”骨干内部重复的边:'土壤修复--父节点->城市绿化'
WARNING  “环保”骨干内部重复的边:'绿茵生态--生产->城市绿化'
WARNING  “环保”骨干内部重复的边:'绿茵生态--生产->工矿废地修复'
WARNING  “环保”骨干内部重复的边:'绿茵生态--生产->盐碱地修复'
WARNING  “环保”骨干内部重复的边:'侨银股份--生产->生活垃圾治理'
WARNING  “环保”骨干内部重复的边:'万邦达--生产->固废治理'
WARNING  “环保”骨干内部重复的边:'过滤材料--原材料->污水处理设备'
WARNING  “环保”骨干内部重复的边:'过滤材料--原材料->空气净化设备'
WARNING  “环保”骨干内部重复的边:'新动力--生产->水治理'
WARNING  “环保”骨干内部重复的边:'新动力--生产->垃圾焚烧'
WARNING  “环保”骨干内部重复的边:'中电环保--生产->工业水处理系统'
WARNING  “环保”骨干内部重复的边:'工业水处理系统--原材料->工业废水治理'
WARNING  “矿产”骨干内部重复的边:'老凤祥--生产->黄金首饰'
WARNING  “矿产”骨干内部重复的边:'磷酸--原材料->磷肥'
WARNING  “矿产”骨干内部重复的边:'磷矿石--原材料->黄磷'
WARNING  “矿产”骨干内部重复的边:'热法磷酸--原材料->磷酸'
WARNING  “矿产”骨干内部重复的边:'化肥--父节点->磷肥'
WARNING  “矿产”骨干内部重复的边:'黄磷--原材料->热法磷酸'
WARNING  “矿产”骨干内部重复的边:'湿法磷酸--原材料->磷酸'
WARNING  “矿产”骨干内部重复的边:'钾矿石--原材料->钾矿石制钾肥'
WARNING  “矿产”骨干内部重复的边:'钾矿石制钾肥--原材料->钾肥'
WARNING  “矿产”骨干内部重复的边:'化肥--父节点->钾肥'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->煤炭'
WARNING  “矿产”骨干内部重复的边:'有色金属--父节点->精铜矿'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->稀土元素'
WARNING  “矿产”骨干内部重复的边:'有色金属--父节点->矿产银'
WARNING  “矿产”骨干内部重复的边:'有色金属--父节点->矿产金'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->锂矿石'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->铁矿石'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->天然石墨'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->磷矿石'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->天然开采钻石'
WARNING  “矿产”骨干内部重复的边:'矿产金--原材料->合质金锭'
WARNING  “矿产”骨干内部重复的边:'矿产--父节点->有色金属'
WARNING  “矿产”骨干内部重复的边:'中国黄金国际--生产->有色金属'
WARNING  “矿产”骨干内部重复的边:'中国有色矿业--生产->有色金属'
WARNING  “矿产”骨干内部重复的边:'白银有色--生产->有色金属'
WARNING  “矿产”骨干内部重复的边:'兴业矿业--生产->有色金属'
WARNING  “矿产”骨干内部重复的边:'合质金锭--原材料->黄金首饰'
WARNING  “矿产”骨干内部重复的边:'老凤祥--生产->黄金首饰'
WARNING  “矿产”骨干内部重复的边:'珠宝设计加工--原材料->黄金首饰'
WARNING  “矿产”骨干内部重复的边:'矿产银--原材料->合质银锭'
WARNING  “矿产”骨干内部重复的边:'合质银锭--原材料->白银首饰'
WARNING  “矿产”骨干内部重复的边:'珠宝设计加工--原材料->白银首饰'
WARNING  “矿产”骨干内部重复的边:'精铜矿--原材料->熔炼'
WARNING  “矿产”骨干内部重复的边:'煤炭--父节点->动力煤'
WARNING  “矿产”骨干内部重复的边:'煤炭--父节点->炼焦煤'
WARNING  “矿产”骨干内部重复的边:'熔炼--原材料->粗铜'
WARNING  “矿产”骨干内部重复的边:'粗铜--原材料->阳极铜'
WARNING  “矿产”骨干内部重复的边:'阴极铜--原材料->铜产品'
WARNING  “矿产”骨干内部重复的边:'云南铜业--生产->阴极铜'
WARNING  “矿产”骨干内部重复的边:'江西铜矿--生产->阴极铜'
WARNING  “矿产”骨干内部重复的边:'锂矿石--原材料->碳酸锂'
WARNING  “矿产”骨干内部重复的边:'赣锋锂业--生产->锂矿石'
WARNING  “矿产”骨干内部重复的边:'天齐锂业--生产->锂矿石'

矿产
内部节点:99
内部边:171
外部节点:0
外部边:0

WARNING  “矿产”骨干内部重复的边:'碳酸锂--原材料->磷酸铁锂'
WARNING  “矿产”骨干内部重复的边:'磷酸铁锂--原材料->锂电池'
WARNING  “矿产”骨干内部重复的边:'西部矿业--生产->锂矿石'
WARNING  “矿产”骨干内部重复的边:'磷酸--原材料->磷肥'
WARNING  “矿产”骨干内部重复的边:'磷矿石--原材料->磷酸盐'
WARNING  “矿产”骨干内部重复的边:'磷矿石--原材料->黄磷'
WARNING  “矿产”骨干内部重复的边:'磷酸盐--原材料->磷酸铁锂'
WARNING  “矿产”骨干内部重复的边:'黄磷--原材料->草甘膦'
WARNING  “矿产”骨干内部重复的边:'热法磷酸--原材料->磷酸'
WARNING  “矿产”骨干内部重复的边:'黄磷--原材料->三氯化磷'
WARNING  “矿产”骨干内部重复的边:'湖北宜化--生产->磷矿石'
WARNING  “矿产”骨干内部重复的边:'云天化--生产->磷矿石'
WARNING  “矿产”骨干内部重复的边:'兴发集团--生产->磷矿石'
WARNING  “矿产”骨干内部重复的边:'化肥--父节点->磷肥'
WARNING  “矿产”骨干内部重复的边:'钻石--父节点->天然开采钻石'
WARNING  “矿产”骨干内部重复的边:'钻石--父节点->培育钻石'
WARNING  “矿产”骨干内部重复的边:'钻石--原材料->钻石首饰'
WARNING  “矿产”骨干内部重复的边:'珠宝设计加工--原材料->钻石首饰'
WARNING  “矿产”骨干内部重复的边:'中兵红箭--生产->培育钻石'
WARNING  “矿产”骨干内部重复的边:'黄河旋风--生产->培育钻石'
WARNING  “矿产”骨干内部重复的边:'力量钻石--生产->培育钻石'
WARNING  “矿产”骨干内部重复的边:'钻石--原材料->切削刀具'
WARNING  “矿产”骨干内部重复的边:'天然石墨--父节点->石墨'
WARNING  “矿产”骨干内部重复的边:'石墨--父节点->人造石墨'
WARNING  “矿产”骨干内部重复的边:'石墨--原材料->高纯度石墨'
WARNING  “矿产”骨干内部重复的边:'石墨--原材料->石墨烯'
WARNING  “矿产”骨干内部重复的边:'高纯度石墨--原材料->培育钻石'
WARNING  “矿产”骨干内部重复的边:'方大炭素--生产->人造石墨'
WARNING  “矿产”骨干内部重复的边:'厦门钨业--生产->稀土元素'
WARNING  “矿产”骨干内部重复的边:'五矿稀土--生产->稀土元素'
WARNING  “电影”骨干内部重复的边:'视频平台--父节点->流媒体视频平台'
WARNING  “电影”骨干内部重复的边:'芒果超媒--生产->流媒体视频平台'
WARNING  “食品饮料”骨干内部重复的边:'食品烟酒--父节点->香烟'
WARNING  “食品饮料”骨干内部重复的边:'食品烟酒--父节点->酒水'
WARNING  “食品饮料”骨干内部重复的边:'香飘飘--生产->固体饮料'
WARNING  “陆运”骨干内部重复的边:'供应链服务--父节点->有色金属运输'
WARNING  “地产”骨干内部重复的边:'新城市--生产->土地规划'
WARNING  “地产”骨干内部重复的边:'新城市--生产->工程设计'
WARNING  “地产”骨干内部重复的边:'蕾奥规划--生产->土地规划'
WARNING  “地产”骨干内部重复的边:'正平股份--生产->基础设施'
WARNING  “地产”骨干内部重复的边:'全筑股份--生产->建筑装修'
WARNING  “航空航天”骨干内部重复的边:'中国联通--生产->通信服务'
WARNING  “航空航天”骨干内部重复的边:'阿莱德--生产->射频器件'
WARNING  “航空航天”骨干内部重复的边:'中英科技--生产->覆铜板'
WARNING  “航空航天”骨干内部重复的边:'铜箔--原材料->覆铜板'
WARNING  “航空航天”骨干内部重复的边:'通信芯片--父节点->射频芯片'
WARNING  “航空航天”骨干内部重复的边:'世嘉科技--生产->射频器件'
WARNING  “畜牧业”骨干内部重复的边:'福成股份--生产->牛肉'
WARNING  “畜牧业”骨干内部重复的边:'福成股份--生产->肉牛'

电影
内部节点:107
内部边:141
外部节点:3
外部边:1
食品饮料
内部节点:434
内部边:361
外部节点:50
外部边:9
陆运
内部节点:102
内部边:104
外部节点:8
外部边:2
地产
内部节点:521
内部边:602
外部节点:25
外部边:11
纺织业
内部节点:110
内部边:89
外部节点:54
外部边:24
航空航天
内部节点:199
内部边:204
外部节点:21
外部边:2
畜牧业
内部节点:185
内部边:205
外部节点:27
外部边:11

WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--父节点->彩妆类'
WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--父节点->护肤品类'
WARNING  “美妆”骨干内部重复的边:'护肤品类--父节点->面霜'
WARNING  “美妆”骨干内部重复的边:'护肤品类--父节点->护肤乳液'
WARNING  “美妆”骨干内部重复的边:'护肤品类--父节点->精华类产品'
WARNING  “美妆”骨干内部重复的边:'精华类产品--父节点->次抛精华'
WARNING  “美妆”骨干内部重复的边:'精华类产品--父节点->普通精华'
WARNING  “美妆”骨干内部重复的边:'活性成分--原材料->护肤品类'
WARNING  “美妆”骨干内部重复的边:'护肤品类--父节点->面膜类产品'
WARNING  “美妆”骨干内部重复的边:'面膜类产品--父节点->片状面膜'
WARNING  “美妆”骨干内部重复的边:'面膜类产品--父节点->涂抹式面膜'
WARNING  “美妆”骨干内部重复的边:'无纺布--原材料->片状面膜'
WARNING  “美妆”骨干内部重复的边:'片状面膜--父节点->冻干面膜'
WARNING  “美妆”骨干内部重复的边:'低温冻干技术--原材料->冻干面膜'
WARNING  “美妆”骨干内部重复的边:'护肤品类--父节点->清洁类产品'
WARNING  “美妆”骨干内部重复的边:'清洁类产品--父节点->卸妆产品'
WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--父节点->工具类'
WARNING  “美妆”骨干内部重复的边:'工具类--父节点->化妆刷'
WARNING  “美妆”骨干内部重复的边:'工具类--父节点->美妆蛋'
WARNING  “美妆”骨干内部重复的边:'乳胶--原材料->美妆蛋'
WARNING  “美妆”骨干内部重复的边:'亲水性聚氨酯（PU）--原材料->美妆蛋'
WARNING  “美妆”骨干内部重复的边:'保湿剂--原材料->护肤品类'
WARNING  “美妆”骨干内部重复的边:'工具类--父节点->化妆棉'
WARNING  “美妆”骨干内部重复的边:'棉--原材料->化妆棉'
WARNING  “美妆”骨干内部重复的边:'聚丙烯纤维（丙纶）--原材料->无纺布'
WARNING  “美妆”骨干内部重复的边:'工具类--父节点->睫毛夹'
WARNING  “美妆”骨干内部重复的边:'酰基氨基酸盐--原材料->氨基酸洗面奶'
WARNING  “美妆”骨干内部重复的边:'氢氧化钾--原材料->皂基洗面奶'
WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--父节点->头发护理产品'
WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--父节点->化妆品包材'
WARNING  “美妆”骨干内部重复的边:'塑料--原材料->化妆品包材'
WARNING  “美妆”骨干内部重复的边:'美妆产品（化妆品）--原材料->美容护肤需求'
WARNING  “美妆”骨干内部重复的边:'保湿剂--父节点->化妆品级透明质酸（玻尿酸）'
WARNING  “美妆”骨干内部重复的边:'华熙生物--生产->透明质酸'
WARNING  “美妆”骨干内部重复的边:'华熙生物--生产->护肤品类'
WARNING  “美妆”骨干内部重复的边:'乳化剂--原材料->护肤乳液'
WARNING  “旅游”骨干内部重复的边:'西安饮食--生产->餐饮服务'
WARNING  “旅游”骨干内部重复的边:'力盛体育--生产->体育赛事'
WARNING  “旅游”骨干内部重复的边:'同庆楼--生产->餐饮服务'
WARNING  “旅游”骨干内部重复的边:'西域旅游--生产->景区观光'
WARNING  “旅游”骨干内部重复的边:'西安旅游--生产->景区观光'

美妆
内部节点:61
内部边:102
外部节点:0
外部边:0
旅游
内部节点:189
内部边:187
外部节点:5
外部边:1

WARNING  “旅游”骨干内部重复的边:'曲江文旅--生产->景区观光'
WARNING  “旅游”骨干内部重复的边:'金陵饭店--生产->餐饮服务'
WARNING  “旅游”骨干内部重复的边:'西藏旅游--生产->景区观光'

7983
8434

In [23]:
from QGI.neoapi import Neo4j
#neo4j+ssc://534ea9b7.databases.neo4j.io:7687
#QuantumGalaxy
#atlas
uri = "neo4j+ssc://08ef0a79.databases.neo4j.io"
user = "QG_Editor"
password = "editor"
#neo1=Neo4j(uri,user,password)
#nova
uri = "neo4j+ssc://534ea9b7.databases.neo4j.io:7687"
user = "neo4j"
password = "QuantumGalaxy"

neo=Neo4j(uri,user,password)
#neo.simple_query('match (n) detach delete n')

In [24]:

def data2cypher(data):
    cyphers=['match (n) detach delete n']
    from copy import deepcopy
    d=deepcopy(data)
    for v in d['vertex']:
        #merge 应该只有名字？和骨干？公司怎么办
        cate=v.pop('category')
        if cate=='Company' or cate=='Indicator':
            name=v.pop('name')
            backbone=v.pop('backbone')
            
            cypher='merge(n:%s {name:"%s"}) \
                on match set n.backbone=n.backbone+",%s" \
                on create set n.backbone="%s" \
                '%(cate,name,backbone,backbone)
            if v:
                other='with n set '
                
                for key,value in v.items():
                    if type(value)==str:
                        value=value.replace('"', '\\\"').replace("'", "\\\'")
                    other+='n.%s="%s",'%(key,value)
                other=other[:-1]
                cypher+=other
            cyphers.append(cypher)
        else:
            s='{'
            for key,value in v.items():
                s+=key+':'+'"%s",'%value
            s=s[:-1]
            s+='}'
            cypher='merge (n:%s %s)'%(cate,s)
            #print(cypher)
            cyphers.append(cypher)

            
            #cypher='merge (n:%s {name:"%s"}) set n.backbone=n.backbone+",%s"'%(cate,v['name'],v['backbone'])
            #print('try this instead:"%s"'%cypher)
            #try:neo.simple_query(cypher)
            #except:print('failed! pass')
    for l in d['link']:
        #link表中对name和bitapp同时匹配 match (n {name:"",bitapp_id:""})
        #边界是不是不对？eg 畜牧业 牛奶- 食品饮料-乳制品
        sourcename,source,targetname,target,cate=l.pop('source_name'),l.pop('source'),l.pop('target_name'),l.pop('target'),l.pop('category')
        more=''
        if l:
            for k,v in l.items():
                more+=k+':'+'"%s",'%v
            more=more[:-1]
        if cate=='produce':
            cypher='match (n {name:"%s"}),(n1 {name:"%s",bitapp_id:"%s"}) create (n)-[r:%s {%s}]->(n1)'%(sourcename,targetname,target,cate,more) 
        else:
            cypher='match (n {name:"%s",bitapp_id:"%s"}),(n1 {name:"%s",bitapp_id:"%s"}) create (n)-[r:%s {%s}]->(n1)'%(sourcename,source,targetname,target,cate,more)          
        '''                                                                                                                                                                                   -------------------------------------+'
        s=deepcopy(data['vertex'][e['source']])
        s_cate=s.pop('category')
        s1='{'
        for key,value in s.items():
            s1+=key+':'+'"%s",'%value
        s1=s1[:-1]
        s1+='}'
        
        t=deepcopy(data['vertex'][e['target']])
        t_cate=t.pop('category')
        s2='{'
        for key,value in t.items():
            s2+=key+':'+'"%s",'%value
        s2=s2[:-1]
        s2+='}'
        cypher='match (n:%s %s),(n1:%s %s) create (n)-[r:%s]->(n1)'%(s_cate,s1,t_cate,s2,e["rela"])
        '''
        cyphers.append(cypher)
        #print(cypher)
        #neo.simple_query(cypher)
    return cyphers
cyphers=data2cypher(post_result)
print(len(cyphers))

16418

In [25]:
r=neo.multi_cypher(cyphers)
r

16418

In [ ]:
r'20	112.81 \
400	-170'

In [ ]:
data=bitable_works('bascnzsAjUXwr4gUkaIpqi8BBaf',subgraph_name='粗骨干图')
data

In [ ]:
from copy import deepcopy
#data1=deepcopy(data)

In [ ]:
import time

In [ ]:
s=time.time()
time.sleep(5)
e=time.time()-s
e

In [ ]:
fold='fldcn2VlYvt8Efb9PqZwO51GWud'

In [ ]:

r=requests.get('http://82.156.248.152:81/fs/fold_meta?token=%s'%fold).json()
r

In [ ]:
r=requests.get('http://82.156.248.152:81/fs/fold_children?fld_token=%s'%fold).json()
r

In [ ]:
r.json()

In [ ]:
import simplejson
with open(r'E:\wangzhilin\QuantumGalaxy\opt\combine_check\results\result-20230404.json','r') as file:
    data=simplejson.load(file)

In [ ]:
web=result['bascnX3JNXBB9J428M3qHmJv1Me']
web

In [ ]:
json.dumps('键桥科技')

### 多维表格附件图片的相关杂务

将所有多维表格中的配图列按照appid/tblid/recid的路径保存二进制文件（需要格式？）到8383/static/img下，将路径保存到哪里？（neo，则需要维护所有文件的node表，包括node表token

多为表格存的是图片。。neo要存路径，联调需要对所有节点存路径

In [ ]:
from html import escape
import json
from urllib.parse import quote
import requests,json

In [ ]:
bitapp_auth={'app_id':'cli_a1fc0a192db8100c','app_secret':'nNk1fT8h2eVi8B2ymIFangHTpYrOAJTD'}
def build_headers():
    
    token=fetch_tenant_token(bitapp_auth)
    #token='u-3atGsodiN9391_BlvmfeZh1kkwt5hlQxo0G0hgew2Ijc'
    headers = {
        'Authorization':
        'Bearer ' + token,  # your access token
        #'Content-Type': 'application/json; charset=utf-8'
    }
    return headers

In [ ]:
def download(url):
    url=url
    headers=build_headers()
    payload = ''
    #print(headers)
    file_token='bascnzsAjUXwr4gUkaIpqi8BBaf'
    table_token='tbl0Ko7cxJaGwUnh'
    record_id="recV96vgmB"
    save_path=os.path.join(r'E:\wangzhilin\QuantumGalaxy\pics',file_token)
    save_path=os.path.json(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\pic\static',file_token)
    #save_file=os.path.join(save_path,record_id)
    res=  requests.request("GET", url, headers=headers, data=payload,stream=True)
    if res.headers['Content-Type'] in ['image/gif', 'image/png', 'image/jpeg', 'image/bmp', 'image/webp']:
        post=res.headers['Content-Type'].split('/')[1]
        #post=res.headers['Content-Disposition'].split('.')[-1]
        name=record_id+'.'+post
        save_file=os.path.join(save_path,name)
        #return res.headers
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        with  open(save_file, "wb") as f:
            # 下载文件大小
            total_size = int(res.headers["content-length"])
            content_size = 0
            for content in res.iter_content(chunk_size=1024):
                f.write(content)
                content_size += len(content)

        data = {"recv_size": content_size, "total_size": total_size}
        if content_size == total_size:
            return ("接收成功")
        return ("接收失败")
    else:return('wrong type, got "%s"'%res.headers['Content-Type'])

r=download(r"https://open.feishu.cn/open-apis/drive/v1/medias/boxcnyh7dn98QVYTIGQZI4hPCOc/download?extra=%7B%22bitablePerm%22%3A%7B%22tableId%22%3A%22tbl0Ko7cxJaGwUnh%22%2C%22rev%22%3A77%7D%7D")
r

In [ ]:
def upload(file):
    UPDATE_PACKAGE_PATH = '/tools/package/'
    out = os.path.join(UPDATE_PACKAGE_PATH, params.get("filename"))
    if not os.path.isfile(out):
        return None
    # 文件大小
    fsize = os.path.getsize(out)

    def send_file_fp():
        store_path = out
        send_size = 0
        with open(store_path, "rb") as target_file:
            while 1:
                data = target_file.read(2 * 1024 * 1024)  # 每次读取2M
                if not data:
                    break
                yield data
    #content_type='multipart/form-data; boundary=something'
    content_type='image/'+name.split('.')[1]
    response = Response(send_file_fp(), )
    response.headers["Content-disposition"] = 'attachment; filename={}'.format(params.get("filename"))
    response.headers["Content-length"] = fsize
    return response

In [ ]:
def find_file(token,id):
    import os
    root_dir=r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\pic\static'
    file_dir=os.path.join(root_dir,token)
    files=os.listdir(file_dir)
    file_name=None
    for file in files:
        name=os.path.splitext(file)
        if name[0]==id:
            file_name=name[0]+name[1]
    return  file_dir,file_name
   
file_token='bascnzsAjUXwr4gUkaIpqi8BBaf'
table_token='tbl0Ko7cxJaGwUnh'
record_id="recV96vgmB"
r=find_file(file_token,record_id)

In [ ]:
from flask import Response
import os
def test():
    file_token='bascnzsAjUXwr4gUkaIpqi8BBaf'
    table_token='tbl0Ko7cxJaGwUnh'
    record_id="recV96vgmB"
    file_dir,file_name=find_file(file_token,record_id)
    if file_name:
        out=os.path.join(file_dir,file_name)
        fsize = os.path.getsize(out)

        def send_file_fp():
            store_path = out
            send_size = 0
            with open(store_path, "rb") as target_file:
                while 1:
                    data = target_file.read(2 * 1024 * 1024)  # 每次读取2M
                    if not data:
                        break
                    yield data
        #content_type='multipart/form-data; boundary=something'
        content_type='image/'+out.split('.')[1]
        response = Response(send_file_fp(),content_type=content_type )
        response.headers["Content-disposition"] = 'attachment; filename={}'.format(file_name)
        response.headers["Content-length"] = fsize
        return response
r=test()
r

In [ ]:
r.headers

In [ ]:
r.content

In [ ]:
imagebyte=r.content

In [ ]:
import cv2
import numpy as np

def read2byte(path):
    '''
    图片转二进制
    path：图片路径
    byte_data：二进制数据
    '''
    with open(path,"rb") as f:
        byte_data = f.read()
    return byte_data

def byte2numpy(byte_data):
    '''
    byte转numpy矩阵/cv格式
    byte_data：二进制数据
    image : numpy矩阵/cv格式图片
    '''
    image = np.asarray(bytearray(byte_data), dtype="uint8")
    image = cv2.imdecode(image, cv2.IMREAD_COLOR)
    return image

整合部分
对各个表格data进行整合（排除其中error的部分？）