# 星图映射

A股公司->从简介提取主营产品/业务->所属骨干；市值（分级？）；
1. 如果已经在图里了，gpt从主营产品/业务到板块名，对比已经在的骨干名
2. 主营产品和星图产品的相关度打分


已经定出关键词，从关键词映射到字不一样的星图词

In [1]:
import requests,json,re
from functools import wraps
from datetime import datetime
import sys
sys.path.append('E:\wangzhilin\QuantumGalaxy')
import re


from QGI.feishu import *
from QGI.mysql import MYSQL
from QGI.neoapi import Neo4j
MYSQL_HOST='localhost'
MYSQL_USER='Local_Editor'
MYSQL_PASSWORD='QuantumGalaxy'
NOVA_URI = "neo4j+ssc://534ea9b7.databases.neo4j.io:7687"
NOVA_USER = "neo4j"
NOVA_PASSWORD = "QuantumGalaxy"
ATLAS_URI = "neo4j+ssc://08ef0a79.databases.neo4j.io"
ATLAS_USER = "QG_Editor"
ATLAS_PASSWORD = "editor"
def get_mysql(database='qgdbs'):

    
    #database='qgdbs'
    mysql=MYSQL(MYSQL_HOST,MYSQL_USER,MYSQL_PASSWORD,database)

    return mysql
def get_neo(database='nova'):
    if database=='nova':
        neo=Neo4j(NOVA_URI,NOVA_USER,NOVA_PASSWORD)
    else:
        neo=Neo4j(ATLAS_URI,ATLAS_USER,ATLAS_PASSWORD)
    return neo

In [2]:

def handle_res(res_func):
    @wraps(res_func)
    def wrapper(*args,**kwargs):
        
        #res={code=0,res=something}
        res=res_func(*args,**kwargs)
        if  res.status_code==200:
            if res.json().get('code')==0 :
                
                
                #code=0,tokens,res
                return res.json()['res']
            else:
                return {'code':-1,'msg':'没有您想要的结果'}
        else:
            return {'code':-2,'msg':'后台gpt服务器返回出错：%s'%res.status_code}
    return wrapper
@handle_res
def base_gpt(message):
    
    r=requests.post('http://43.153.23.232:81/chat',json=json.dumps({'message':message}))
    return r

@handle_res
def cust_gpt(messages):        
    r=requests.post('http://43.153.23.232:81/cust_chat',json=json.dumps({'messages':messages}))
    return r

@handle_res
def compltion(prompt):
    r=requests.post('http://43.153.23.232:81/completion',json=json.dumps({'prompt':prompt}))
    return r

def prod_extraction(brief):
    message=f'从下面描述中，找到公司的主营产品或业务。只回答产品/业务名\n'+brief
    r=base_gpt(message)
    return r
def guess_backbone(prod):
    messages=[{"role":'system',"content":"完成相似度选择任务。从下面的关键词表中选出与用户输入最相关的五个，然后再从选出的五个中选出与用户输入最相关的一个词。关键词表：{航空航天\n煤炭\n畜牧业\n旅游\n地产\n石油化工\n石油天然气\n钠离子电池\n半导体\n工业制造\n陆运\n海运\n电力储能\n教育\n钢铁\n锂离子电池\n风电\n消费电子\n汽车\n种植\n通信\n电影\n医药\n光伏\n互联网云计算\n纺织业\n美妆\n食品饮料\n银行\n贵金属\n}"},
        {'role':'user','content':f"{prod}与哪个关键词最相关？只回答关键词，用[]框出"}]
    r=cust_gpt(messages)
    return r
def similarity(prod_group):
    message=f'对[{prod_group[0]}]，和[{prod_group[1]}]这两组产品/业务的相关性进行评价，等级包括，几乎一致；比较相关；有些交集；毫无关系。只用回答等级'
    r=base_gpt(message)
    return r

In [ ]:
similarity(["'户外鞋靴', '运动休闲鞋'","运动鞋履的开发设计、生产与销售"])

In [3]:
s='航空航天\n煤炭\n畜牧业\n旅游\n地产\n石油化工\n石油天然气\n钠离子电池\n半导体\n工业制造\n陆运\n海运\n电力储能\n教育\n钢铁\n锂离子电池\n风电\n消费电子\n汽车\n种植\n通信\n电影\n医药\n光伏\n互联网云计算\n纺织业\n美妆\n食品饮料\n银行\n贵金属'
backbones=s.split('\n')
backbones

['航空航天',
 '煤炭',
 '畜牧业',
 '旅游',
 '地产',
 '石油化工',
 '石油天然气',
 '钠离子电池',
 '半导体',
 '工业制造',
 '陆运',
 '海运',
 '电力储能',
 '教育',
 '钢铁',
 '锂离子电池',
 '风电',
 '消费电子',
 '汽车',
 '种植',
 '通信',
 '电影',
 '医药',
 '光伏',
 '互联网云计算',
 '纺织业',
 '美妆',
 '食品饮料',
 '银行',
 '贵金属']

In [4]:
len(backbones)

30

In [5]:
def guess_backbone(prod):
    #messages=[{"role":'system',"content":"给出用户提供产品所属的产业分类。从下面的关键词表中选出与用户输入最相关的五个，然后再从选出的五个中选出与用户输入最相关的一个词。关键词表：{航空航天\n煤炭\n畜牧业\n旅游\n地产\n石油化工\n石油天然气\n钠离子电池\n半导体\n工业制造\n陆运\n海运\n电力储能\n教育\n钢铁\n锂离子电池\n风电\n消费电子\n汽车\n种植\n通信\n电影\n医药\n光伏\n互联网云计算\n纺织业\n美妆\n食品饮料\n银行\n贵金属\n}"},
    #    {'role':'user','content':f"{prod}与哪个关键词最相关？只回答关键词，用[]框出"}]
    messages=[{"role":'system',"content":"给出用户提供产品所属的产业分类class。然后，从下面的板块列表中选出与该class最接近的一个板块名，用[]框出该板块名，注意必须从列表中选择。板块列表：{航空航天\n煤炭\n畜牧业\n旅游\n地产\n石油化工\n石油天然气\n钠离子电池\n半导体\n工业制造\n陆运\n海运\n电力储能\n教育\n钢铁\n锂离子电池\n风电\n消费电子\n汽车\n种植\n通信\n电影\n医药\n光伏\n互联网云计算\n纺织业\n美妆\n食品饮料\n银行\n贵金属\n}"},
    #messages=[{"role":'system',"content":"Provide the industry classification class to which the user's product belongs. Then, select the keyword from the following keyword table that is closest in meaning to the classification, and enclose the keyword in square brackets. Keyword table:{航空航天\n煤炭\n畜牧业\n旅游\n地产\n石油化工\n石油天然气\n钠离子电池\n半导体\n工业制造\n陆运\n海运\n电力储能\n教育\n钢铁\n锂离子电池\n风电\n消费电子\n汽车\n种植\n通信\n电影\n医药\n光伏\n互联网云计算\n纺织业\n美妆\n食品饮料\n银行\n贵金属\n}"},
        {'role':'user','content':f"{prod}"}]
    r=cust_gpt(messages)
    return r
r=guess_backbone("数据服务、线上广告服务、电子产品之企业对企业、企业对客户零售业务、企业对企业交易平台、防伪产品和服务、供应链管理服务、营销服务、融资服务")
r

'[互联网云计算]'

In [ ]:
match=re.findall('\[(.*?)\]',r)

In [ ]:
match[0]

In [ ]:
re.findall('.*/[.*?/]',r)

In [ ]:
neo.close()

In [ ]:
mysql.close()

In [6]:
neo=get_neo()
mysql=get_mysql()

In [ ]:
cypher='match (c:Company)-[:produce]->(p:Product) where c.code is not null and c.code <>"无" return c.code as code,collect(p.name) as prod,c.backbone as backbone limit 100'
records=neo.read_query(cypher)
records

In [ ]:
data=[]
for r in records:
    raw=(r.get('code'),str(r.get('prod'))[1:-1],r.get('backbone'))
    data.append(raw)

In [7]:
mysql=get_mysql()
data=mysql.read_query('select code,sec_name,briefing from ticker_brief')
data

(('000001.SZ',
  '平安银行',
  '公司是深圳发展银行股份有限公司以吸收合并原平安银行股份有限公司的方式完成两行整合并更名后的银行，是全国性股份制商业银行。公司自2016年开始全面向零售银行转型，全力打造智能化零售银行，大力推进精品公司银行双轻化.综合金融是公司的特色优势，公司依托庞大的个人客户基础、强大的品牌影响力、广泛的分销网络和完备的综合金融产品体系，为全面推进零售转型、打造领先的智能化零售银行提供了强大的核心竞争力支持。在对公业务领域，公司利用大数据技术打造领先的中小企业数据征信平台，利用先进的IT系统打造橙e网、行E通、黄金银行等传统业务的新优势，提升对公司客户的数字化服务能力。'),
 ('000002.SZ',
  '万科A',
  '公司成立于1984年，1988年进入房地产行业，经过三十余年的发展，已成为国内领先的城市配套服务商，公司业务聚焦全国经济最具活力的三大经济圈及中西部重点城市。2014年万科第四个十年发展规划，已经把“三好住宅供应商”的定位延展为“城市配套服务商”。2018年万科将这一定位进一步迭代升级为“城乡建设与生活服务商”，并具体细化为四个角色：美好生活场景师，实体经济生力军，创新探索试验田，和谐生态建设者。2017年，深圳地铁集团成为本集团第一大股东，始终支持万科的混合所有制结构，支持万科城市配套服务商战略和事业合伙人机制，支持万科管理团队按照既定战略目标，实施运营和管理，支持深化“轨道+物业”发展模式。公司核心业务包括住宅开发、物业服务、长租公寓。2018年，公司将自身定位进一步迭代升级为“城乡建设与生活服务商”，所搭建的生态体系已初具规模，在巩固住宅开发和物业服务固有优势的基础上，业务已延伸至商业开发和运营、物流仓储服务、租赁住宅、产业城镇、冰雪度假、养老、教育等领域，为更好的服务人民美好生活需要、实现可持续发展奠定了良好基础。'),
 ('000004.SZ',
  'ST国华',
  '公司创立于1981年，1990年12月1日起在深圳证券交易所挂牌交易，是深交所首家挂牌的上市公司。上市之初，公司主营业务为汽车货运及旅客运输，兼营汽车修理、汽车配件零售等。2000年、2001年期间，公司完成全面资产重组，调整主营业务方向，剥离了原上市公司体内所有资产及负债，并注入了全新的生物指纹识别和生物制药产业。2005年，为了优化上市公司资产质量，提高盈利能力，公司新增房地产开发与销售业务，并退出生物指纹识别行业。近年来，受国家宏观政策调整及上市公司自身发展规划调整影响，为盘活公司存量资产，优化公司资产结构，推动公司转型升级，公司先后剥离了房地产开发业务和生物医药业务。基于移动互联网产业良好的市场前景，上市公司通过内生式增长与外延式发展并举的手段加快发展移动互联网业务。一方面，公司通过投资设立移动互联网游戏企业开拓移动互联网领域业务，另一方面，公司利用上市平台优势进行外延式整合，并购移动应用安全行业优质资产。目前，公司以移动互联网服务为主营业务，旗下拥有北京智游网安科技有限公司、广州国科互娱网络科技有限公司等子公司。'),
 ('000005.SZ',
  'ST星源',
  '公司是中国早期大规模介入酒店式公寓服务业的公司之一，中国早期上市的公司之一。公司从事的主要业务为交通、清洁能源、水资源基础设施经营性项目的开发投资；低碳技术集成、水处理设备销售和环境处理成套设备销售和环境工程服务；不动产项目、水电项目的开发管理、工程监理和建筑、工程设计服务；酒店经营、物管服务和“智慧空间水管理”的物业管理服务；不动产项目权益投资组合管理和大型工业园区开发投资管理服务。公司1990年最初设立时的主营业务是与纺织、印染、时装相关的行业，但经过二十多年的市场洗练，主营业务的发展近年来逐渐转向以发展绿色低碳城市社区建设相关的服务业务为经营方向，即逐步地重构以城市清洁能源基础设施经营、可持续发展的清洁环境的营造、绿色住宅社区开发建设。尤其是2008年以来致力于以深圳特区为辐射中心向北即广东珠三角、上海、长沙、重庆等地区对交通基础设施建设经营、不动产开发服务、环境营造相关的综合服务业务的重构发展。公司将企业的发展和社会责任相结合，实施了可持续的绿色低碳发展战略，将围绕绿色低碳不动产上下相关产业作为主要业务发展目标，致力成为绿色低碳社区的开发者。'),
 ('000006.SZ',
  '深振业A',
  '公司是深圳市国有资产监督管理委员会直管的国有上市公司，公司以房地产开发经营为主营业务，具备国家一级开发资质。自公司成立以来，发展迅速，资产规模与开发规模不断壮大，先后开发了振业花园、振业大厦、星海名城、翠海花园、振业城、峦山谷、振业国际商务中心、惠阳振业城、西安振业·泊墅、南宁振业·青秀山1号、天津振业·城中央等代表性项目，产品类别涉及普通居民住宅、商用物业、Townhouse、别墅等多种类型。公司先后被授予中国房地产百强、中国上市公司百强，广东地产三十强、深圳房地产十强、深圳市首届发展循环经济十佳企业、特区建立30年——深圳企业文化建设功勋企业等称号。开发的星海名城、翠海花园分别荣获国家建设部颁发的“人居经典综合奖”、“规划环境金质奖”；振业城以A级住宅性能认证有史以来最高分899分顺利通过建设部3A终审，被列为“国家建筑节能示范小区”。'),
 ('000007.SZ',
  '全新好',
  '公司是中国最早上市的公司之一,目前公司的主营业务为物业管理和房屋租赁业，原有的主营业务如商品贸易业(矿产品)、旅游饮食业已全面退出。公司物业管理(含停车场经营)和房屋租赁业的主要经营区域位于深圳市最为繁华的金融商业区之一——华强北，凭借华强北活跃的商业氛围和旺盛的人气，公司该块业务经营业绩一直较为稳定，是公司经营工作的有益补充。公司投资控股的公司分别有深圳市零七物业管理有限公司、深圳德福联合金融控股有限公司、上海量宽信息技术有限公司等公司。公司正逐步形成具有金融信息咨询、创业投资、金融投资、股权投资、投资管理等多元化信息技术服务平台，为各类投资者提供优质的金融信息及投资服务，实现公司与客户的共赢。'),
 ('000008.SZ',
  '神州高铁',
  '公司创建于1997年，2014年重组上市后更名为神州高铁技术股份有限公司。在自身发展的基础上，通过并购线路、信号、供电、站场等多家创办20余年的公司，共同组成了轨道交通运营检修维护装备领域一家涵盖全产业链的上市公司，是中国高铁及城轨运营检修维护装备制造产业的领军供应商。拥有核心产品400余项，其中26项处于国内、国际领先地位，多项核心技术填补了国际空白。通过运营维护智能装备、大数据系统研发，致力于轨道交通云运营及智能检修维护体系的搭建和复制推广。逐渐形成了独有的轨道交通运维产业板块，与轨道交通另外两大产业板块协同互补并构成差异化的产业格局，成为轨道交通产业新的一极。在大铁领域，业绩覆盖18个铁路局、7个主机厂、7个动车基地、7个大功率机车基地、13个焊轨基地、76个机务段、54个车辆段、15个工务段、36个供电段、54个动车所、16个货运站场、2000余个车站；在城市轨道交通领域，为42座城市提供了车辆检修工艺系统、为长沙、北京中低速磁浮提供了车辆检修工艺系统、为北京地铁、重庆城市轨道交通提供了信号集成系统；公司不断拓展海外业务版图，并与中国铁建、中国交建等央企深入合作，在东南亚、非洲、东欧、拉美等地区取得了稳健业绩。'),
 ('000009.SZ',
  '中国宝安',
  '公司是一家综合类股份制集团公司，主营业务是高新技术产业、房地产业、生物医药业，曾连创“新中国第一家股份制企业、发行新中国第一张股票、第一张可转换债券、第一张中长期认股权证、成功策划武汉商场成为深交所第一家异地上市公司、首次通过证券二级市场收购上市公司上海延中实业、分拆马应龙并在上海证券交易所上市，成为中国境内首例分拆企业上市的上市公司、开办新中国第一个财务顾问公司安信财务，协助川盐化、甘长风等20多家国企改制上市”等多项新中国第一。公司连年获得资本市场各种荣誉：中国资本市场高峰论坛“最佳持续投资价值奖”、中国证券市场年会“金凤凰奖”、“金鼎奖”；在广东省企业联合会组织的评选活动中，中国宝安集团连续多年分别获评“推动广东发展杰出贡献企业”、“广东上市公司最具竞争力10强”“广东上市公司综合实力10强”、“广东上市公司最具投资价值10强”、“中国上市公司百佳行业领军企业”、“中国上市公司诚信示范标杆企业”等荣誉称号。'),
 ('000010.SZ',
  '美丽生态',
  '公司是中国最早的上市公司之一，公司主营业务为园林绿化，主要从事园林绿化工程施工、园林景观设计、园林养护及绿化苗木种植等,市政景观建设、河道治理、园林生态景观建设、市政道路、乡村生态旅游等公用工程业务方面进行了积极拓展，并取得相关进展。公司资质可比肩国内一线企业，综合竞争显著，为公司可持续发展打下了坚实基础。'),
 ('000011.SZ',
  '深物业A',
  '公司经过多年发展，已形成了以房地产开发为主业，物业管理、物业租赁、出租汽车营运、餐饮服务、物流仓储、工程监理等为辅的跨行业、多元化的经营格局。先后开发了深圳国际贸易中心大厦、国贸商业大厦、皇城广场等高层商务建筑群及皇御苑、俊峰丽舍花园、风和日丽花园、物业时代新居等一大批高中档住宅小区；总承包建设了我国最大的对外陆路口岸皇岗口岸；合作开发了天安国际大厦、罗湖商业城等知名商务楼宇。公司总承包建设的深圳国际贸易中心大厦，被誉为神州第一楼并创造了三天一层楼的奇迹，国贸大厦成为“深圳速度”的象征和改革开放的标志性建筑。公司负责开发建设的房地产项目以其卓越的品质和专业化的服务赢得社会的广泛赞誉。公司已连续多年荣获“中国房地产开发企业500强”、“广东省企业500强”等诸多荣誉称号。'),
 ('000012.SZ',
  '南玻A',
  '公司是一家中外合资企业，是中国玻璃行业最具竞争力和影响力的大型企业。公司致力于节能和可再生能源事业。其主营业务为平板玻璃、工程玻璃等节能建筑材料，硅材料、光伏组件等可再生能源产品及精细玻璃等新型材料和高科技产品的生产、制造和销售。公司培育和引导了中国节能玻璃市场，参与多项节能建筑、节能产品的国家标准和行业标准的制定与修订。随着人类节能减排、发展低碳经济的潮流，公司开始全面实施产业升级和战略调整，斥巨资进入太阳能产业领域，并战略性地构建了多晶硅—硅片—电池片—太阳能电池产业链。公司以完善的法人治理结构为基础，以规范的管理制度为手段，以“为社会提供节能玻璃及可再生能源产品”为长期发展战略与企业经营理念，不断创新运行机制，严格控制经营风险，为公司持续快速发展奠定了坚实的基础。'),
 ('000014.SZ',
  '沙河股份',
  '公司主要从事房地产开发以及配套工程开发建设、新型建材的生产与建设、物业租赁与管理、物资供销、国内外商业、及投资兴办实业等。公司已成功开发出荔园新村、祥祺花园、鹿鸣园、宝瑞轩、世纪村、世纪假日广场等多个住宅、商务项目。其中，世纪村通过国家建设部“3A”性能住宅认定，荣获“全国人居优秀推荐楼盘”称号。公司以深圳为依托，积极寻求对外扩张，并在湖南长沙、河南新乡等地开发新项目。公司拥有丰富的土地储备，曾在全国率先实行住宅质量保证书和住宅使用说明制度。连续多年被深圳权威资信机构评为“AAA”级信誉企业和深圳市守法纳税大户，曾获深圳市“文明企业”等多种殊荣。公司着力实施名牌精品战略，致力于全方位开拓和多元化发展，企业资产质量和盈利水平得以迅速提升，进而为社会提供更多优质产品服务和高额投资回报，确保了公司的可持续发展。'),
 ('000016.SZ',
  '深康佳A',
  '公司主要从事彩色电视机、手机、白色家电、厨卫电器，净水系列、日用生活电器、LED、机顶盒及相关产品的研发、制造和销售，兼及精密模具、注塑件、高频头、印制板、变压器及手机电池等配套业务，是中国领先的电子信息企业。公司拥有覆盖面广、服务完善的营销服务网络，在国内建立了多个营销分公司、数百个销售经营部及多个维修服务网点，海外业务也已拓展到世界多个国家和地区。公司按照“科技+产业+城镇化”的发展方向和“硬件+软件、终端+用户、科技+投控”的发展模式，以消费电子业务为基础，以“科技+投控”复合能力为支撑，向战略性新兴产业升级、向产业地产业务拓展、向互联网及供应链服务业务延伸，形成科技园区业务群、产业产品业务群、平台服务业务群和投资金融业务群四大业务群协同发展的全新局面。'),
 ('000017.SZ',
  '深中华A',
  '公司是以生产自行车、电动自行车产品为核心的多元化、集团化的上市公司。公司从事的主要业务为自行车业务以及锂电池材料业务，自行车业务包括生产、装配、采购、销售自行车及电动自行车等。公司有严格的质量保证体系，产品通过了ISO9001质量认证体系。公司为进一步适应市场环境的变化，积极调整经营策略和产品结构，采取多种经营策略，加强网络建设和售后服务工作，健全服务体系，同时加大产品研发力度，合理布局生产基地等经营策略，努力发展经营业务，大力拓展电动自行车主业。'),
 ('000019.SZ',
  '深粮控股',
  '公司是中国食品饮料行业首家上市公司，是中国大陆最早生产利乐软包饮料、发酵型乳酸菌饮料的企业之一，公司拥有“深宝”、“三井”、“金雕”等品牌，确立了“天然、绿色、健康”的茶产业为未来发展方向，公司将以茶叶精深加工为核心，以建设天然健康产品和服务一体化的产业链为目标，积极向茶园种植和体验基地以及终端产品两头延伸。公司将集中资源大力发展茶产业，加强在技术研发、市场网络建设、产业链运营和人才聚集等方面的投入和积累，通过建立一支专业化、职业化、高素质的运营团队，提升公司产业运营水平，构建领先于未来的核心能力，巩固和提升行业地位。2018年公司通过重大资产重组收购深粮集团100%股权,公司的主营业务在原有业务基础上增加粮油储备、粮油贸易、粮油加工等粮油流通及粮油储备服务业务，深粮集团在粮油行业深耕数十年，具有一定的品牌和规模优势。'),
 ('000020.SZ',
  '深华发A',
  '公司是深圳证券交易所早期上市的公司之一，是全国外商投资双优企业。公司经营业务主要分为液晶显示器整机业务、注塑件生产业务、保丽龙(轻型材料包装)生产业务、物业租赁业务。公司拥有三间大型工厂，国内多家知名大型生产企业云集周边，基于加工配套服务业的辐射半径要求，客户资源优质稳定，已形成良好的长期合作关系,尤其注塑业务与保丽龙业务迄今经营多年，年产能力及规模居华中地区前列;在深圳市福田区华强北商圈及光明新区公明街道均拥有数万平方米的大型物业，每年物业租赁收入可观。公司未来自有土地资源的开发与经营将成为公司循序渐进式的长期稳定的收入来源和新的利润增长点。'),
 ('000021.SZ',
  '深科技',
  '公司是中国先进的通讯电子产品制造企业之一，为全球多家一线品牌提供技术制造服务。致力于提供计算机与存储、通讯与消费电子、半导体、医疗器械、汽车电子、商业与工业产品的制造服务和自动化设备、计量系统及物联网系统的研发生产服务。公司拥有深圳、苏州、惠州、东莞、成都、重庆、桂林、马来西亚、泰国、菲律宾等多个研发制造基地，同时公司在美国、英国、荷兰、印度、新加坡、中国香港等多个国家或地区设有分支机构或拥有研发团队。公司是中国知名的智能电表及控制系统出口企业，是中国知名的半导体存储模组制造企业和中国先进的DRAM/flash封装测试企业。公司是国家高新技术企业，拥有中国国家认可委员会(CNAS)认可的专业实验室，具备优秀的可靠性、材料分析、先进机械、热仿真、表面贴装(SMT)、以及静电防护等工程技术能力，被认定为广东省工程技术中心和深圳市公共技术平台。'),
 ('000023.SZ',
  '深天地A',
  '公司是全国第一家以商品混凝土为主业的上市公司，主要业务涉及商品混凝土、房地产开发及物业管理等，目前业务已扩展至湖南、陕西、江苏等地。公司在深圳和湖南均建有专业商品混凝土生产基地，可生产各种强度等级的普通混凝土和特种混凝土以及预拌砂浆，其中在预拌砂浆技术方面位居领先地位。长期以来，为深圳许多重点工程、地标建筑提供了大量优质商品混凝土，产品已覆盖整个深圳市，进入湖南株洲市场后，为当地的重点和样板工程提供了优质混凝土。市场占有率居深圳、株洲地区前列。公司秉承“一流的产品质量，一流的服务水平”的宗旨，规范和加强内部管理，培育优秀的企业文化，充分发挥资源、设备、技术、品牌共享的优势，进一步拓展新的生产基地，扩大市场占有率，拓展房地产开发项目，步入了良性、稳健发展的快车道。'),
 ('000025.SZ',
  '特力A',
  '公司是一家以汽车后市场服务和房地产物业经营管理为主营业务的大型集团。近年来，公司通过重组、资产整合、投资新项目，逐步形成了适应市场的经营模式，成为深圳市汽车行业的知名企业。拥有7家控股企业和多家参股企业，是深圳市汽车行业的知名企业。在汽车市场服务上，公司有一套完整的产业链，产品畅销全国各地、东南亚及非洲。物业经营管理方面，公司重点致力于产业园区建设，重点围绕特力吉盟黄金首饰产业园和布心汽车配件产业园建设，对产业园的部分项目进行投资开发、物业经营管理。'),
 ('000026.SZ',
  '飞亚达',
  '公司是中国钟表行业的旗舰企业，中国境内表业上市公司，系中航工业集团下属中航国际深圳公司的主要投资企业之一。公司以品牌战略为统领，专注于钟表行业，主要从事世界名表零售和自有品牌钟表的研发、设计、制造和销售业务。名表零售业务方面，旗下的“亨吉利世界名表中心”是国内统一商号名表连锁网络，已发展为高端钟表零售业务的领军品牌之一。自有产品品牌方面，已形成飞亚达表、高端品牌、时尚品牌为主的“三色堇”产品品牌构架，基本完成了在研发、设计、关键零部件生产制造、分销、零售等重要价值环节的全产业链布局。公司长期致力于精密计时腕表技术研发与应用，拥有先进的研发生产技术和制造工艺平台。'),
 ('000027.SZ',
  '深圳能源',
  '公司是全国电力行业第一家在深圳上市的大型股份制企业，也是深圳市第一家上市的公用事业股份公司。公司所从事的主要业务是各种常规能源和新能源的开发、生产、购销，以及城市固体废物处理、城市燃气供应和废水处理等。公司通过引进、消化、吸收和自主创新，掌握了具有国际领先水平的垃圾焚烧发电自主知识产权，拥有多项技术发明专利，拥有设计、投资、建设、运营和管理全过程运作能力。依托科技创新成果，公司具备含盐废水(脱硫废水、煤化工废水)、高浓度有机废水(垃圾沥滤液)等环保项目产业化运用的能力。在大力拓展电力主业的同时，公司坚持最高环保标准，以垃圾处理产业为依托，积极发展能源环保产业，初步形成以电为主，能源环保等相关产业综合发展的战略格局，在深圳市国有企业综合实力排名中位居第一，连续多年入选中国工业企业500强，在产业市场和资本市场上树立起“诚信、绩优、规范、环保”的良好形象。'),
 ('000028.SZ',
  '国药一致',
  '公司是集医药研发、制药工业、药品分销、医药物流为一体的综合性医药上市公司承担着国家、省、市政府药品特储任务。公司制药工业集产品研发、原料与制剂生产、市场营销于一体，产品主要覆盖头孢抗菌素、呼吸系统用药、消化系统用药、心脑血管用药以及抗肿瘤药等领域。公司药品分销业务位居广东、广西两省前茅，名列中国医药商业20强，拥有完善的全国商业网络和深度渗透的南区终端市场网络，拥有华南地区自动化程度最高、服务能力最强的专业医药物流中心，也是华南地区首家获批第三方医药物流资质的企业。未来的公司坚持内生性增长与外延式扩张并重，借助资本运作、实施兼并收购、联合重组，创新盈利模式，积极发展新业务，致力成为具有国际竞争力的医药健康产品和服务提供商。'),
 ('000029.SZ',
  '深深房A',
  '公司是深圳经济特区最早成立的房地产开发公司，公司曾在房地产开发史上创造了多个“第一”，包括：第一个有偿使用国有土地；第一个引入外资合作开发土地；第一个采用楼宇预售手段筹集开发资金；第一个按国际惯例实行建设工程公开招标；第一个成立物业管理公司对开发的楼宇、住宅进行全方位管理；在深圳经济特区举行的第一次土地使用权拍卖会上夺标等等。公司已发展成为一家以房地产开发与经营为主业，集物业管理与经营、建筑工程设计、施工与管理、旅游开发与经营等多元化经营于一体的企业集团。'),
 ('000030.SZ',
  '富奥股份',
  '公司是中国知名的汽车零部件制造业集团企业，主要从事汽车零部件的研发、生产和销售，是国内在生产规模、产品系列、客户覆盖均具有一定优势的汽车零部件上市公司。公司自成立以来，始终以市场为导向，坚持走技术发展之路，通过市场结构调整、产品结构调整和企业结构调整，形成了以底盘业务、空调业务、汽车电子及新能源为主导核心产品的产业格局。目前，公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列，产品品种覆盖重、中、轻、微型商用车和高、中、低档乘用车等系列车型；公司产品为众多国内整车/整机企业配套，部分产品远销海外。公司进一步深化自主研发机制，建立两级研发模式，研发中心及下属多家分公司、控股子公司被评为“省级企业技术中心”，公司及下属十余家企业被认定为高新技术企业。'),
 ('000031.SZ',
  '大悦城',
  '公司是一家全国性、综合性的房地产开发上市企业，总部位于深圳市。公司从事的主要业务包括：房地产开发、经营、销售、出租及管理住宅、商用物业，经营业态以住宅为主。公司立足环北京、环上海、环深圳三大核心城市群，重点关注以长江中游城市群、成渝城市群、一带一路沿线为主的中心城市及高潜力城市，打造了壹号、祥云、锦云、鸿云四条品牌住宅产品线，细分产品类型，实现区位、规模、定位上的互补。'),
 ('000032.SZ',
  '深桑达A',
  '公司是一家以电子整机产品、新兴电子元器件等电子高新技术产品为主导的上市公司。公司主要经营以电子整机产品、新兴电子元器件等电子高新技术产品为主导，兼及房地产、商贸等多个领域。公司在坚持科技创新，不断开发新技术和新产品的同时，努力拓展发展空间，现已与国外多家知名企业开展广泛的技术交流与合作；以诚信为基础，以共赢为目标，公司业已建立良好的市场信誉，实现了集研发、生产、销售与售后服务于一体的战略体系；公司通过多年的发展，培养和锻炼了一支敬业、奉献、高素质的专业人才队伍，成为公司各项事业持续向前推进的有力保障。'),
 ('000034.SZ',
  '神州数码',
  '公司原为神州控股，2015年出售分销和系统业务，迎击“互联网+”时代浪潮，2016年4月于A股上市。公司先后荣获国家级火炬计划重点高新技术企业称号、北京市高新技术企业称号、中关村高新技术企业称号，软件开发获得CMMI4级认证，软件服务水平通过ISO20000和ISO27001认证，并在北京和武汉建成两个大型研发中心，是北京市“十百千工程”中，四家千亿核心企业之一。公司一直是国内外产品技术以及服务的提供商在中国首选的合作伙伴，与300余家国际顶尖供应商展开精诚合作，市场份额稳居第一，并建成覆盖全国860个城市、30000余家渠道伙伴的中国最大的IT营销网络，在为广大的消费者用户提供丰富的电子产品的同时，神州数码集团已累计为超过100万家中国企业提供信息化所需的产品、解决方案和服务。面向未来，公司将继续通过专业化与多元化的IT产品和服务，释放信息技术的力量，把信息技术价值转化为客户价值，推动中国信息化建设进程。'),
 ('000035.SZ',
  '中国天楹',
  '公司是一家环保新能源上市公司，主要业务包括投资、建设、运营、维护环保基础设施项目和环保设备的研发、生产、销售；业务范围覆盖生活垃圾焚烧发电及蒸汽生产、污泥处理、餐厨垃圾处理、危险废弃物处理、建筑垃圾处理、污水处理、填埋气开发与利用、垃圾分类收运体系投资与运营等领域。公司坚守生活垃圾焚烧发电主营产业，围绕垃圾处理无害化、减量化、资源化，从末端处置向上游的分类、收运、中转和综合环卫方向拓展，延伸固废产业链，打造以生活垃圾处理为主线的城市环境服务综合运营商。公司项目荣获众多荣誉，特别是海安垃圾焚烧发电项目荣获了“2014-2015年度中国建设工程鲁班奖”，通过了江苏省“AAA”级城市生活垃圾处理设施无害化等级评定，为垃圾焚烧发电行业建设管理工作树立了标杆。公司在引进、消化、吸收国外先进技术的基础上，尤为注重提升自主创新水平，在垃圾焚烧发电领域拥有多项发明专利及实用新型专利，充分实现了该领域核心设备和关键设备的国产化，关键技术研究被国家科技部列入国家火炬计划项目。同时，公司致力于打造环保治理精品工程和以污水处理、烟气净化、垃圾压缩、垃圾焚烧设备为主导产品的国内领先环保装备制造基地。'),
 ('000036.SZ',
  '华联控股',
  '公司原是深圳市最早从事专业化纤产品生产与经营的国营内联企业，目前公司主营业务为房地产开发和自有物业租赁管理业务。房地产开发业务主要集中在深圳、杭州、千岛湖等城市，物业资产及物业经营管理业务主要集中深圳、杭州、上海、千岛湖等区域。从事房地产开发的实体主要包括：公司本部、深圳华联置业公司、杭州华联置业公司、浙江兴财公司、上海申冠置业公司等五家企业。从事物业经营管理业务的实体为华联物业集团，负责统筹、运营和管理本公司和华联集团的物业资产出租及住宅地产项目、商业地产项目等运营与服务管理。'),
 ('000037.SZ',
  '深南电A',
  '公司是以生产经营供电、供热，从事发电厂(站)建设工程总承包，提供技术咨询和技术服务为主营业务的中外合资股份制企业。自创立以来，公司坚持燃机发电及上下游产业并举的发展战略，在不断提高管理水平、扩大发电生产规模的同时，通过参股、控股等形式，先后涉足燃机电站工程建设、油品贸易、燃机发电技术培训等相关领域，努力朝着多元化和跨区域的方向迈进。公司主营业务为生产经营供电供热、从事发电厂(站)的相关技术咨询和技术服务，下属深南电工程公司不断开拓国内外燃机电站建设工程的技术咨询和技术服务业务，下属深南电环保公司利用燃机发电的余热从事污水处理厂湿污泥的干化处理业务，实现污泥的减量化、无害化处理和资源的综合利用。经过多年努力，公司先后获得“中国工业企业500强”、“中国最大500家外商投资企业”、“国家循环经济试点”等荣誉称号；连续数年被评为广东省、深圳市先进模范单位及保供电先进单位。'),
 ('000038.SZ',
  '*ST大通',
  '公司致力于发展成集新媒体传播、金融服务、大数据服务、数字娱乐、物联网等为一体的“科技”+“文化”产业集团，构建“内容”+“平台”+“服务”的企业生态系统。拥有成熟的技术服务团队，技术人员覆盖了前期的需求沟通、用户界面设计，中期HTML5技术以及后期的广告效果跟踪。深大通可以全方位满足客户品牌传播和产品推广的需求，配合客户整体宣传策略，深入了解客户、了解市场、了解消费者，结合渠道资源、技术，帮助客户寻找广告信息传播的目标受众群，以适当的媒介及广告位置组合、恰当的互动形式为客户量身定制整合营销宣传策略。依托碎片化的沟通和互动，实现广告投放精准性、高效性品牌传播，让客户的营销更有价值。公司将将持续关注行业内优质资源，加大在互联网广告、户外广告等新媒体传媒领域的投入，未来公司将通过并购的方式，加大在传媒、数字娱乐、数字内容、大数据服务、金融服务等产业的布局，实现公司整体转型及跨越式发展。'),
 ('000039.SZ',
  '中集集团',
  '公司是世界领先的物流装备和能源装备供应商，总部位于中国深圳。公司致力于在如下主要业务领域：集装箱、道路运输车辆、能源化工及食品装备、海洋工程、物流服务、空港设备等，提供高品质与可信赖的装备和服务。支持这些业务蓬勃发展的有：提供专业资金管理的财务公司，以及提供金融解决方案的融资租赁公司。作为一家为全球市场服务的多元化跨国产业集团，中集在亚洲、北美、欧洲、澳洲等地区拥有300余家成员企业及2家上市公司，客户和销售网络分布在全球100多个国家和地区。'),
 ('000040.SZ',
  '东旭蓝天',
  '公司是国内A股主板上市公司，主营业务包括新能源和生态环保。公司致力于成为国内领先的环保新能源综合服务商，在特定区域内打造优质生态环境，并提供多能互补、发配售一体、冷热电联供的智慧能源，通过环保、新能源两个绿色产业协同开发带动，提供一揽子绿色发展解决方案。在新能源领域，公司的重点发展方向是智慧能源。以东旭蓝天私有云为依托，实现对电站的全生命周期智能化管理，公司从上游的核心设备、规模化储能布局到下游的新能源电站发配售一体化、智能微网齐头并进，为用户提供系统的“一站式”新能源解决方案。在生态环保领域，公司业务范围涉及生态综合治理、水环境修复及运营、土壤及矿山修复、危废/固废处理四大领域，为地方政府提供基础建设和生态环保等领域的规划、设计、投资、建设、运营、管理等全生命周期的解决方案。作为对新能源产业产业链的补充和完善，公司积极布局新材料，组件生产已成功销往海外；公司旗下有自主研发的安轩智能运维机器人已实现量产，运行效果获玖龙纸业、上海宝钢、浙江正泰等大型企业客户好评。'),
 ('000042.SZ',
  '中洲控股',
  '公司前身是深圳市长城投资控股股份有限公司，创立于1984年，1994年经股份制改造成为公众上市公司，为首批获得国家房地产开发一级资质企业。公司以房地产开发业务为主，范围涉及酒店经营、资产管理、物业管理、商业管理、投资等多个领域。近年来，公司继续扎根于主流的经济区域，多渠道、多方式取地，扩大区域影响范围，逐渐实现“专注区域、深耕城市、多盘联动”的战略布局。'),
 ('000045.SZ',
  '深纺织A',
  '公司是由深圳市投资控股有限公司控股的国有上市公司，成立于1984年。主要从事纺织、服装及相关产品的生产与进出口贸易，兼营物业租赁、仓储、房地产开发、酒店等业务。公司重要的业务有：以LCD用偏光片为代表的高新技术产业；以海外服装加工及高档无缝内衣为代表的纺织服装产业；以地处深圳华强北繁华商业区的深纺大厦为代表的物业租赁业。公司立足企业实际，主动进行产业结构调整，积极推进产业转型升级，集中精力发展LCD用偏光片这一具有自主知识产权、市场前景广阔的高新技术产业，从传统的纺织服装加工业成功转型进入平板显示产业领域，被评为“深圳市国有企业产业转型升级的典范企业”、“广东省优势产业转型升级的企业”及“国家高新技术企业”。'),
 ('000046.SZ',
  '泛海控股',
  '公司成立于1989年，于1994年在深圳证券交易所挂牌上市。面对中国经济结构转型的历史性机遇，泛海控股敏锐感知宏观经济和行业市场的变化，重新规划了产业发展方向，在继续发挥房地产业务优势的基础上，融合具有较大发展潜力的金融、战略投资等业务板块，将公司打造成涵盖金融、房地产、战略投资等业务的综合性控股上市公司。在金融业务领域，泛海控股围绕构筑完整的金融服务体系，业务已涵盖证券、信托、保险、期货、基金、资产管理、互联网金融等领域，形成了以民生证券、民生信托、亚太财险为核心的金融布局和业态分布。在地产业务领域，泛海控股涉及规划设计、开发建设、商业管理及物业服务等，具备大体量、多业态综合开发能力，项目布局已从北京、上海、武汉等国内一、二线城市延伸至美国洛杉矶、旧金山、纽约等海外市场。在战略投资领域，泛海控股已形成境内以“泛海投资”、境外以“中泛集团”、“中泛控股”为核心的战略布局，以期与公司现有业务形成互补和平衡。'),
 ('000048.SZ',
  '京基智农',
  '公司前身为深圳市养鸡公司。公司发展至今已形成集低碳都市农业、公用事业、房地产、金融投资等多种产业于一体的多元化集团公司，业务内容包括：种猪、肉猪养殖与销售，种鸡、肉鸡养殖与销售，中高端品牌猪肉与鸡蛋等生鲜农产品销售，饲料生产与销售，交通运输，自来水供应，房地产开发，物业管理、金融投资等。公司养猪业以技术为依托，以种猪繁殖为中心，大力培育新品种，实现农业的科技化，在农业部种猪质量检测中心测定评比中多次获得好成绩，公司养猪场连年被评为健康与合格猪场、原种猪场合格单位、重点生猪养殖场、先进养猪企业。'),
 ('000049.SZ',
  '德赛电池',
  '公司为控股型企业，主要围绕锂电池产业链进行业务布局，其中惠州电池主营中小型锂电池封装集成业务，惠州蓝微主营中小型移动电源管理系统业务，二级子公司惠州市蓝微新源技术有限公司主营大型动力电池、储能电池等电源管理系统及封装集成业务。公司已经成为全球中小型移动电源领域的领导厂商之一，与全球主要电芯厂开展合作，服务于全球顶级消费电子厂商。作为国内锂电池制造领域的先行者，经过多年的发展，尤其是近年来，通过持续加大研发投入、打造高效制造平台、搭建品质控制预防体系、优化业务结构等举措，公司积累了雄厚的技术优势，品质保证及技术开发能力处于国际领先地位，拥有了优质的高端客户资源、先进的自动化水平和领先的制造水平，具有较强的综合竞争优势。在智能手机、电动工具等中小型移动电源管理系统暨封装领域处于全球领先地位。公司的电池产品获得了“国家免检产品”、“中国名牌产品”、“广东省名牌产品”等称号。'),
 ('000050.SZ',
  '深天马A',
  '公司是一家在全球范围内提供显示解决方案和快速服务支持的创新型科技企业，主要经营液晶显示器(LCD)及液晶显示模块(LCM)。公司聚焦于移动终端消费类显示市场和车载、医疗、工控等专业类显示市场，这两大类产品广泛应用于智能手机、平板电脑、车载显示、医疗显示、工业仪表、智能穿戴和智能家居等众多领域。公司是国内规模最大的液晶显示器及模块制造商之一。2018年公司通过重大资产重组拥有厦门天马100%股权以及天马有机发光60%股权,有利于上市公司充分发挥协同效应及规模优势，提升市场综合竞争力，提高上市公司盈利能力和可持续发展能力。'),
 ('000055.SZ',
  '方大集团',
  '公司业务范围涵盖高端幕墙系统及材料、轨道交通设备及系统、太阳能光伏发电、房地产和金融等板块，主要产品为节能幕墙、光电幕墙、LED彩显幕墙等各类建筑幕墙及铝板材料、轨道交通屏蔽门系统。公司秉承“科技为本，创新为源”的经营理念，坚持自主创新，以“方大工匠”精神发展“节能、环保、低碳”产业。公司先后荣获“亚太地区100家最佳管理公司”、“建设创新型国家杰出企业”、“中国建设科技自主创新优势企业”、“全国质量效益型先进企业”、“中国工业行业状元”、“国家863计划CIMS应用示范企业”、“全国CAD应用工程示范企业”、“全国建设信用AAA级诚信企业”、“广东省知识产权优势企业”、“广东省诚信守法示范企业”、“广东省守合同重信用企业”、“深圳市民营领军骨干企业”、“深圳市制造业信息化重点示范企业”、以及世界质量大奖——“白金明星奖”、“国家级重点新产品”、“中国建筑工程鲁班奖(国家优质工程)”、“詹天佑土木工程奖”、“全国建筑工程装饰奖”、“白玉兰”奖、“用户满意工程”等诸多荣誉。“方大FANGDA”被评为“中国驰名商标”。'),
 ('000056.SZ',
  '皇庭国际',
  '公司是一家集商业、地产、物业、林业为一体的集团化上市公司。公司坚持以市场为导向，注重夯实企业根基，并结合企业经营优势及商业发展趋势，勾勒出以商业地产为核心的战略发展蓝图。公司先后开发出国企大厦、港逸豪庭、榭丽花园、惠州阳光100等系列优质楼盘，积累了丰富的地产开发经验。公司融合中国国际化进程的思路及历史性机遇，坚持以品牌制胜的理念，立足高端品牌路线和精品路线，重视以人的美好品质感受与企业的持续性发展为归依，致力于成为行业顶尖的商业地产开发商和运营商，为消费者带来先进的生活品质体验，为城市的战略升级创造有价值的贡献。'),
 ('000058.SZ',
  '深赛格',
  '公司的主营业务是电子专业市场及其配套项目的开发及经营、物业租赁服务业务、贸易及渠道业务、电子商务、小额贷款增值业务以及酒店业务等。“赛格电子市场”已成为将自建发展IT综合体、租赁与委托管理相结合，市场服务与金融增值服务相结合，专业市场与渠道分销相结合，线上交易与线下交易相结合的国内乃至亚洲规模最大的涵盖电子元器件、数码IT、通讯产品等在内的综合类专业电子市场，在国内外拥有较高的品牌影响力。先后荣获了“中国电子产品五星级市场”、“深圳特区三十年最具影响力的专业市场”、“影响中国”的深圳十大品牌专业市场等荣誉称号。'),
 ('000059.SZ',
  '华锦股份',
  '公司是国内特大型炼油化工一体化综合性石油化工企业之一，具有较强的整体规模实力，是国内重要的成品油、中间石化产品、ABS合成树脂和尿素生产企业，并拥有独立的公用工程、环境保护系统，及铁路运输、公路运输配套设施。公司拥有40多年的尿素生产经营和管理经验，积累有深厚的资源；公司曾多次获全国和地方政府的优质产品奖。公司主要业务包括石油化工产品、化学肥料的生产与销售。石化板块产品包括柴油、聚乙烯、聚丙烯、聚苯乙烯、ABS、船用燃料油、工业硫磺、石油甲苯、石油混合二甲苯等；化肥板块产品包括尿素、甲醇、液氨等。'),
 ('000060.SZ',
  '中金岭南',
  '公司是一家主要是从事铅锌铜等有色金属的采矿、选矿、冶炼和深加工一体化生产的企业。公司通过一系列收购兼并、资源整合，直接掌控的已探明的铅锌铜等有色金属资源总量近千万吨，逐步成长为具有一定影响力的跨国矿业企业。公司主要产品有铅锭、锌锭及锌合金、白银、黄金、镉锭、锗锭、铟锭、工业硫酸、硫磺等产品。公司主要的生产活动为铅锌矿的开采、选矿以及铅锌金属的冶炼。公司产品质量均达到国际先进水平，公司拥有国家级技术中心，设立了“博士后科研工作站”。多年来，共获得省部级以上科技奖励近100项。公司秉承“做不到，没有理由”的企业核心价值观，以铅、锌、铜为主，坚持多金属、国际化、一体化、集约化的经营理念，努力打造国际矿业旗舰企业。'),
 ('000061.SZ',
  '农产品',
  '公司是一家以投资、开发、建设、经营和管理农产品批发市场为核心业务的大型现代化农产品流通企业集团。公司肩负使命、情系民生，始终致力于中国农产品流通领域的发展与进步。率先开创农批市场网络化经营模式，在深圳、北京、上海、天津、成都、西安、长沙、武汉等多个大中城市经营管理了多家综合批发市场和网上交易市场，形成国内最具规模的基于供应链管理的新型农产品流通生态圈。公司率先创导绿色交易，精心打造以保障食品安全、提高流通效率、综合利用资源为核心的海吉星品牌，使得海吉星市场汇集了公司在工程建设、食品安全、信息科技、电子商务、物流管理、金融服务、综合环保等领域的创新性成果，成为农产品流通行业转型升级的典范之作；率先探索以农产品交易所为龙头，依托辐射全国的实体市场与电商平台的产业版图，发挥线上线下网络优势和规模效应，构建行业内具有重要影响力的多品种、多层次、多模式的农产品绿色交易新体系。'),
 ('000062.SZ',
  '深圳华强',
  '公司的主营业务为面向电子信息产业链的现代高端服务业，为产业链上的各环节提供线上线下交易服务、产品服务、技术服务、交易信息服务和创新创业配套服务，打造面向电子信息产业的国内一流交易服务和创新创业服务双平台。具体业务环节包括电子元器件线下分销、电子元器件线上交易平台、电子元器件及电子终端产品线下交易平台、品牌终端产品线上分销、硬件+互联网的创新创业服务、其他物业经营等。经过在电子信息行业多年的精耕细作，公司品牌优势明显，打造并拥有了“华强电子世界”、“华强电子网”、“华强北·中国电子市场价格指数”、“IT市场指数”、“华强北国际创客中心”、“湘海电子”、“捷扬讯科”、“鹏源电子”、“淇诺科技”、“芯斐电子”等业内知名品牌，累积了独树一帜、无可复制的电子产业链数据库资源，包括线上线下平台聚集的百万级大中小企业客户及中小贸易商资源、数百万电子工程师资源、数亿条供求信息资源、海量的交易数据资源、高端的国际原厂资源、众多的国内大中小原厂资源以及齐备的电商、融资、物流等配套资源。'),
 ('000063.SZ',
  '中兴通讯',
  '公司是全球领先的综合性通信制造业上市公司，是近年全球增长快速的通信解决方案提供商。公司拥有通信业界完整的、端到端的产品线和融合解决方案，通过全系列的无线、有线、业务、终端产品和专业通信服务，灵活满足全球不同运营商和企业网客户的差异化需求以及快速创新的追求。公司通过为全球多个国家和地区的电信运营商和企业网客户提供创新技术与产品解决方案，让全世界用户享有语音、数据、多媒体、无线宽带等全方位沟通。公司坚持以持续技术创新为客户不断创造价值。公司在美国、加拿大、瑞典、中国等地设立全球研发机构，凭借不断增强的创新能力、突出的灵活定制能力、日趋完善的交付能力赢得全球客户的信任与合作。公司在全球范围内开展社区公益和救助行动，参加了印尼海啸、海地及汶川地震等重大自然灾害救助，并成立了中国规模最大的“关爱儿童专项基金”。'),
 ('000065.SZ',
  '北方国际',
  '公司专注于国际市场的经营，多年来建立了遍布全球的营销网络，培育了强大的国际化经营能力和投融资能力，具有优秀的全球资源配置能力和项目管理能力。公司实现了国际工程与专业化产品贸易的有机融合，充分发挥投资的驱动作用，在轨道交通、电力工程、石油矿产设施建设、市政房建、房地产开发、重型车辆与装备、包装容器研发与生产、物流一体化服务、太阳能产品应用等方面具有优秀业绩与较强竞争力。公司业务范围广泛、专业能力突出，并具有强大的系统集成能力，可以为业主提供一体化和全方位的服务。公司高度重视企业信誉和企业社会责任，连续多年被中国对外承包工程商会和中国机电产品进出口商会评为“AAA级信用企业”。公司还通过了质量(GB/T19001-2008)、环境(GB/T24001-2004)、职业健康(GB/T28001-2011)管理体系认证、工程建设施工企业质量管理规范(GB/T50430-2007)认证。'),
 ('000066.SZ',
  '中国长城',
  '公司是中国电子网络安全与信息化的专业子集团，核心业务覆盖自主可控关键基础设施及解决方案、军工电子、重要行业信息化等领域，能够做到从芯片、整机、操作系统、中间件、数据库、安全产品到应用系统等计算机信息技术各方面完全自主可控且产品线完整的上市公司。公司相关业务水平处于国内领先地位，掌握众多自主可控和信息安全的核心技术，在军队国防、党政等关键领域和重要行业具有深厚的行业理解、丰富的服务经验、稳定良好的合作关系。公司在中国深圳、长沙、武汉、北京、株洲以及海外设有研发中心和生产基地。'),
 ('000068.SZ',
  '华控赛格',
  '公司是清华控股旗下节能环保业务的资本运作平台。公司旗下北京清控人居环境研究院有限公司为清华控股人居环境产业板块核心研发及建设运营平台，在城市水系统工程研发及建设运营领域处于国内领先水平。公司依托清华大学的品牌优势及研发能力，依托清控人居环境研究院后在城市水系统规划设计、市政及环保规划设计、环保基础设施建设投资及运营等领域形成的行业优势，依托上市公司平台与股权基金、资产证券化、信用贷款等其他金融工具组合培育的全方位融资渠道，将在环保基础设施投资、建设、运营服务领域形成系统全面的竞争力。'),
 ('000069.SZ',
  '华侨城A',
  '公司是华侨城集团旗下旅游及房地产板块的上市公司，致力于成为国内主题公园的领导者、旅游产业的领军者、城镇化价值的实现者。经过近二十年的探索与升级，华侨城A以旅游综合、房地产为主营业务，构筑了成熟的成片综合开发模式。各业务板块相互融合，文化旅游景区、酒店、住宅和商业类地产以多种形式组成有机整体，成为公司有别于一般旅游、地产开发模式的独特优势，并实现了1+1>2的效用，在业态布局、产品功能、盈利与资金回收等方面形成紧密联系和相互补充，产生明显的协同效应和集群优势。近年来，公司在业务创新上不断进行探索实践，在探索文化旅游发展新模式、房地产综合业务体系的构造、旅游互联网业务研发等方面进行了探索与实践。'),
 ('000070.SZ',
  '特发信息',
  '公司是国内最早开拓并一直专注于光纤、光缆及光通讯设备开发、生产的国家级高科技企业之一，主要经营光纤光缆、电子元器件、光通讯设备，公司产品广泛应用于电信、移动、联通、广电、电力、石油、矿山、城域网、交通、航空、军工、智能建筑以及消费类和工业电子等领域。公司作为光纤光缆通信行业国家标准及行业标准的制订者之一，产品先后荣获国家级、省部级、地市级的科技进步奖、重点新产品、科技创新奖、科技成果奖、优秀产品奖等荣誉，还率先创造了多项全国第一：国内最早研发出ADSS光缆并保持最大使用跨距纪录；国内第一条OPPC光缆；国内最大芯数光缆-1000芯骨架式光缆；国内第一条实用的OPPC光缆线路，国内第一条12芯带骨架式光缆；国内最早的新型概念SST系列产品等。'),
 ('000078.SZ',
  '海王生物',
  '公司是一家致力于医药制造、商业流通和零售连锁的医药类上市公司，公司的医药制造和医药商业流通业务稳步增长，渠道和终端体系建设稳步推进，医药商业流通系统继续保持健康快速发展，“阳光集中配送”业务不断深化和完善，对公司的业绩贡献有了明显的提升。公司作为国内专业从事医药商业流通的药品服务商，根据国家产业政策和行业整合趋势，科学规划发展布局，加强上下游渠道开拓的同时充分利用资本市场提高自身经营发展水平，实现规模、效益的稳步提升。同时，在新版GMP认证、药品招标采购、药品成本及人力资源成本上升等条件下，公司医药工业体系内各公司坚持专业化、规范化的发展思路，稳步推进生产运营，医药工业体系业务维持平稳增长。'),
 ('000088.SZ',
  '盐田港',
  '公司经营范围为码头的开发和经营，货物装卸与运输，港口配套交通设施建设与经营，港口配套仓储及工业设施建设与经营，港口配套生活服务设施的建设与经营，集装箱修理，转口贸易，货物及技术进出口。公司先后荣获“中国25家最受尊敬上市公司”、“中国十佳最重分红回报上市公司”、“德勤中国风险智能榜优秀企业”称号，近6年连续获深交所信息披露优秀表彰。'),
 ('000089.SZ',
  '深圳机场',
  '公司是国内最早由地方政府自主投资建设管理的机场，也是中国最大的航空运输市场之一。公司作为深圳宝安国际机场管理公司，主要经营航空主业以及航空主业延伸出的非航空业务。航空主业主要包括飞机起降及停场保障，机场飞行控制区的维护与运营管理，旅客的乘机、候机及进出港服务，航站楼商业及物业租赁业务、航空器的维护及辅助服务，航空货物的地面处理服务等，航空主业是机场作为民航运输基础设施固有承担的业务。非航空业务包括航空物流业务和航空增值业务。公司始终坚持打造科学高效的管理体系和市场化机制，致力于成为航空运输安全运行秩序的管理者、优质服务的提供者、社会效益的创造者。公司积极落实民航强国战略，携手国际一流合作伙伴，深度参与“未来机场”建设；与互联网领军企业加强战略合作，大力推进“数字化转型”，着力提升旅客体验和运营效率，更好保障机场公共安全和运营安全，力争成为行业发展的引领者。'),
 ('000090.SZ',
  '天健集团',

In [8]:
brief_dict={}
for row in data:
    brief_dict[row[0]]=row[2]
brief_dict

{'000001.SZ': '公司是深圳发展银行股份有限公司以吸收合并原平安银行股份有限公司的方式完成两行整合并更名后的银行，是全国性股份制商业银行。公司自2016年开始全面向零售银行转型，全力打造智能化零售银行，大力推进精品公司银行双轻化.综合金融是公司的特色优势，公司依托庞大的个人客户基础、强大的品牌影响力、广泛的分销网络和完备的综合金融产品体系，为全面推进零售转型、打造领先的智能化零售银行提供了强大的核心竞争力支持。在对公业务领域，公司利用大数据技术打造领先的中小企业数据征信平台，利用先进的IT系统打造橙e网、行E通、黄金银行等传统业务的新优势，提升对公司客户的数字化服务能力。',
 '000002.SZ': '公司成立于1984年，1988年进入房地产行业，经过三十余年的发展，已成为国内领先的城市配套服务商，公司业务聚焦全国经济最具活力的三大经济圈及中西部重点城市。2014年万科第四个十年发展规划，已经把“三好住宅供应商”的定位延展为“城市配套服务商”。2018年万科将这一定位进一步迭代升级为“城乡建设与生活服务商”，并具体细化为四个角色：美好生活场景师，实体经济生力军，创新探索试验田，和谐生态建设者。2017年，深圳地铁集团成为本集团第一大股东，始终支持万科的混合所有制结构，支持万科城市配套服务商战略和事业合伙人机制，支持万科管理团队按照既定战略目标，实施运营和管理，支持深化“轨道+物业”发展模式。公司核心业务包括住宅开发、物业服务、长租公寓。2018年，公司将自身定位进一步迭代升级为“城乡建设与生活服务商”，所搭建的生态体系已初具规模，在巩固住宅开发和物业服务固有优势的基础上，业务已延伸至商业开发和运营、物流仓储服务、租赁住宅、产业城镇、冰雪度假、养老、教育等领域，为更好的服务人民美好生活需要、实现可持续发展奠定了良好基础。',
 '000004.SZ': '公司创立于1981年，1990年12月1日起在深圳证券交易所挂牌交易，是深交所首家挂牌的上市公司。上市之初，公司主营业务为汽车货运及旅客运输，兼营汽车修理、汽车配件零售等。2000年、2001年期间，公司完成全面资产重组，调整主营业务方向，剥离了原上市公司体内所有资产及负债，并注入了全新的生物指纹识别和生物制药产业。2005年，为了优化上市公司资产质量，提高盈利能力，公司新增房地产开发与销售业务，并退出生物指纹识别行业。近年来，受国家宏观政策调整及上市公司自身发展规划调整影响，为盘活公司存量资产，优化公司资产结构，推动公司转型升级，公司先后剥离了房地产开发业务和生物医药业务。基于移动互联网产业良好的市场前景，上市公司通过内生式增长与外延式发展并举的手段加快发展移动互联网业务。一方面，公司通过投资设立移动互联网游戏企业开拓移动互联网领域业务，另一方面，公司利用上市平台优势进行外延式整合，并购移动应用安全行业优质资产。目前，公司以移动互联网服务为主营业务，旗下拥有北京智游网安科技有限公司、广州国科互娱网络科技有限公司等子公司。',
 '000005.SZ': '公司是中国早期大规模介入酒店式公寓服务业的公司之一，中国早期上市的公司之一。公司从事的主要业务为交通、清洁能源、水资源基础设施经营性项目的开发投资；低碳技术集成、水处理设备销售和环境处理成套设备销售和环境工程服务；不动产项目、水电项目的开发管理、工程监理和建筑、工程设计服务；酒店经营、物管服务和“智慧空间水管理”的物业管理服务；不动产项目权益投资组合管理和大型工业园区开发投资管理服务。公司1990年最初设立时的主营业务是与纺织、印染、时装相关的行业，但经过二十多年的市场洗练，主营业务的发展近年来逐渐转向以发展绿色低碳城市社区建设相关的服务业务为经营方向，即逐步地重构以城市清洁能源基础设施经营、可持续发展的清洁环境的营造、绿色住宅社区开发建设。尤其是2008年以来致力于以深圳特区为辐射中心向北即广东珠三角、上海、长沙、重庆等地区对交通基础设施建设经营、不动产开发服务、环境营造相关的综合服务业务的重构发展。公司将企业的发展和社会责任相结合，实施了可持续的绿色低碳发展战略，将围绕绿色低碳不动产上下相关产业作为主要业务发展目标，致力成为绿色低碳社区的开发者。',
 '000006.SZ': '公司是深圳市国有资产监督管理委员会直管的国有上市公司，公司以房地产开发经营为主营业务，具备国家一级开发资质。自公司成立以来，发展迅速，资产规模与开发规模不断壮大，先后开发了振业花园、振业大厦、星海名城、翠海花园、振业城、峦山谷、振业国际商务中心、惠阳振业城、西安振业·泊墅、南宁振业·青秀山1号、天津振业·城中央等代表性项目，产品类别涉及普通居民住宅、商用物业、Townhouse、别墅等多种类型。公司先后被授予中国房地产百强、中国上市公司百强，广东地产三十强、深圳房地产十强、深圳市首届发展循环经济十佳企业、特区建立30年——深圳企业文化建设功勋企业等称号。开发的星海名城、翠海花园分别荣获国家建设部颁发的“人居经典综合奖”、“规划环境金质奖”；振业城以A级住宅性能认证有史以来最高分899分顺利通过建设部3A终审，被列为“国家建筑节能示范小区”。',
 '000007.SZ': '公司是中国最早上市的公司之一,目前公司的主营业务为物业管理和房屋租赁业，原有的主营业务如商品贸易业(矿产品)、旅游饮食业已全面退出。公司物业管理(含停车场经营)和房屋租赁业的主要经营区域位于深圳市最为繁华的金融商业区之一——华强北，凭借华强北活跃的商业氛围和旺盛的人气，公司该块业务经营业绩一直较为稳定，是公司经营工作的有益补充。公司投资控股的公司分别有深圳市零七物业管理有限公司、深圳德福联合金融控股有限公司、上海量宽信息技术有限公司等公司。公司正逐步形成具有金融信息咨询、创业投资、金融投资、股权投资、投资管理等多元化信息技术服务平台，为各类投资者提供优质的金融信息及投资服务，实现公司与客户的共赢。',
 '000008.SZ': '公司创建于1997年，2014年重组上市后更名为神州高铁技术股份有限公司。在自身发展的基础上，通过并购线路、信号、供电、站场等多家创办20余年的公司，共同组成了轨道交通运营检修维护装备领域一家涵盖全产业链的上市公司，是中国高铁及城轨运营检修维护装备制造产业的领军供应商。拥有核心产品400余项，其中26项处于国内、国际领先地位，多项核心技术填补了国际空白。通过运营维护智能装备、大数据系统研发，致力于轨道交通云运营及智能检修维护体系的搭建和复制推广。逐渐形成了独有的轨道交通运维产业板块，与轨道交通另外两大产业板块协同互补并构成差异化的产业格局，成为轨道交通产业新的一极。在大铁领域，业绩覆盖18个铁路局、7个主机厂、7个动车基地、7个大功率机车基地、13个焊轨基地、76个机务段、54个车辆段、15个工务段、36个供电段、54个动车所、16个货运站场、2000余个车站；在城市轨道交通领域，为42座城市提供了车辆检修工艺系统、为长沙、北京中低速磁浮提供了车辆检修工艺系统、为北京地铁、重庆城市轨道交通提供了信号集成系统；公司不断拓展海外业务版图，并与中国铁建、中国交建等央企深入合作，在东南亚、非洲、东欧、拉美等地区取得了稳健业绩。',
 '000009.SZ': '公司是一家综合类股份制集团公司，主营业务是高新技术产业、房地产业、生物医药业，曾连创“新中国第一家股份制企业、发行新中国第一张股票、第一张可转换债券、第一张中长期认股权证、成功策划武汉商场成为深交所第一家异地上市公司、首次通过证券二级市场收购上市公司上海延中实业、分拆马应龙并在上海证券交易所上市，成为中国境内首例分拆企业上市的上市公司、开办新中国第一个财务顾问公司安信财务，协助川盐化、甘长风等20多家国企改制上市”等多项新中国第一。公司连年获得资本市场各种荣誉：中国资本市场高峰论坛“最佳持续投资价值奖”、中国证券市场年会“金凤凰奖”、“金鼎奖”；在广东省企业联合会组织的评选活动中，中国宝安集团连续多年分别获评“推动广东发展杰出贡献企业”、“广东上市公司最具竞争力10强”“广东上市公司综合实力10强”、“广东上市公司最具投资价值10强”、“中国上市公司百佳行业领军企业”、“中国上市公司诚信示范标杆企业”等荣誉称号。',
 '000010.SZ': '公司是中国最早的上市公司之一，公司主营业务为园林绿化，主要从事园林绿化工程施工、园林景观设计、园林养护及绿化苗木种植等,市政景观建设、河道治理、园林生态景观建设、市政道路、乡村生态旅游等公用工程业务方面进行了积极拓展，并取得相关进展。公司资质可比肩国内一线企业，综合竞争显著，为公司可持续发展打下了坚实基础。',
 '000011.SZ': '公司经过多年发展，已形成了以房地产开发为主业，物业管理、物业租赁、出租汽车营运、餐饮服务、物流仓储、工程监理等为辅的跨行业、多元化的经营格局。先后开发了深圳国际贸易中心大厦、国贸商业大厦、皇城广场等高层商务建筑群及皇御苑、俊峰丽舍花园、风和日丽花园、物业时代新居等一大批高中档住宅小区；总承包建设了我国最大的对外陆路口岸皇岗口岸；合作开发了天安国际大厦、罗湖商业城等知名商务楼宇。公司总承包建设的深圳国际贸易中心大厦，被誉为神州第一楼并创造了三天一层楼的奇迹，国贸大厦成为“深圳速度”的象征和改革开放的标志性建筑。公司负责开发建设的房地产项目以其卓越的品质和专业化的服务赢得社会的广泛赞誉。公司已连续多年荣获“中国房地产开发企业500强”、“广东省企业500强”等诸多荣誉称号。',
 '000012.SZ': '公司是一家中外合资企业，是中国玻璃行业最具竞争力和影响力的大型企业。公司致力于节能和可再生能源事业。其主营业务为平板玻璃、工程玻璃等节能建筑材料，硅材料、光伏组件等可再生能源产品及精细玻璃等新型材料和高科技产品的生产、制造和销售。公司培育和引导了中国节能玻璃市场，参与多项节能建筑、节能产品的国家标准和行业标准的制定与修订。随着人类节能减排、发展低碳经济的潮流，公司开始全面实施产业升级和战略调整，斥巨资进入太阳能产业领域，并战略性地构建了多晶硅—硅片—电池片—太阳能电池产业链。公司以完善的法人治理结构为基础，以规范的管理制度为手段，以“为社会提供节能玻璃及可再生能源产品”为长期发展战略与企业经营理念，不断创新运行机制，严格控制经营风险，为公司持续快速发展奠定了坚实的基础。',
 '000014.SZ': '公司主要从事房地产开发以及配套工程开发建设、新型建材的生产与建设、物业租赁与管理、物资供销、国内外商业、及投资兴办实业等。公司已成功开发出荔园新村、祥祺花园、鹿鸣园、宝瑞轩、世纪村、世纪假日广场等多个住宅、商务项目。其中，世纪村通过国家建设部“3A”性能住宅认定，荣获“全国人居优秀推荐楼盘”称号。公司以深圳为依托，积极寻求对外扩张，并在湖南长沙、河南新乡等地开发新项目。公司拥有丰富的土地储备，曾在全国率先实行住宅质量保证书和住宅使用说明制度。连续多年被深圳权威资信机构评为“AAA”级信誉企业和深圳市守法纳税大户，曾获深圳市“文明企业”等多种殊荣。公司着力实施名牌精品战略，致力于全方位开拓和多元化发展，企业资产质量和盈利水平得以迅速提升，进而为社会提供更多优质产品服务和高额投资回报，确保了公司的可持续发展。',
 '000016.SZ': '公司主要从事彩色电视机、手机、白色家电、厨卫电器，净水系列、日用生活电器、LED、机顶盒及相关产品的研发、制造和销售，兼及精密模具、注塑件、高频头、印制板、变压器及手机电池等配套业务，是中国领先的电子信息企业。公司拥有覆盖面广、服务完善的营销服务网络，在国内建立了多个营销分公司、数百个销售经营部及多个维修服务网点，海外业务也已拓展到世界多个国家和地区。公司按照“科技+产业+城镇化”的发展方向和“硬件+软件、终端+用户、科技+投控”的发展模式，以消费电子业务为基础，以“科技+投控”复合能力为支撑，向战略性新兴产业升级、向产业地产业务拓展、向互联网及供应链服务业务延伸，形成科技园区业务群、产业产品业务群、平台服务业务群和投资金融业务群四大业务群协同发展的全新局面。',
 '000017.SZ': '公司是以生产自行车、电动自行车产品为核心的多元化、集团化的上市公司。公司从事的主要业务为自行车业务以及锂电池材料业务，自行车业务包括生产、装配、采购、销售自行车及电动自行车等。公司有严格的质量保证体系，产品通过了ISO9001质量认证体系。公司为进一步适应市场环境的变化，积极调整经营策略和产品结构，采取多种经营策略，加强网络建设和售后服务工作，健全服务体系，同时加大产品研发力度，合理布局生产基地等经营策略，努力发展经营业务，大力拓展电动自行车主业。',
 '000019.SZ': '公司是中国食品饮料行业首家上市公司，是中国大陆最早生产利乐软包饮料、发酵型乳酸菌饮料的企业之一，公司拥有“深宝”、“三井”、“金雕”等品牌，确立了“天然、绿色、健康”的茶产业为未来发展方向，公司将以茶叶精深加工为核心，以建设天然健康产品和服务一体化的产业链为目标，积极向茶园种植和体验基地以及终端产品两头延伸。公司将集中资源大力发展茶产业，加强在技术研发、市场网络建设、产业链运营和人才聚集等方面的投入和积累，通过建立一支专业化、职业化、高素质的运营团队，提升公司产业运营水平，构建领先于未来的核心能力，巩固和提升行业地位。2018年公司通过重大资产重组收购深粮集团100%股权,公司的主营业务在原有业务基础上增加粮油储备、粮油贸易、粮油加工等粮油流通及粮油储备服务业务，深粮集团在粮油行业深耕数十年，具有一定的品牌和规模优势。',
 '000020.SZ': '公司是深圳证券交易所早期上市的公司之一，是全国外商投资双优企业。公司经营业务主要分为液晶显示器整机业务、注塑件生产业务、保丽龙(轻型材料包装)生产业务、物业租赁业务。公司拥有三间大型工厂，国内多家知名大型生产企业云集周边，基于加工配套服务业的辐射半径要求，客户资源优质稳定，已形成良好的长期合作关系,尤其注塑业务与保丽龙业务迄今经营多年，年产能力及规模居华中地区前列;在深圳市福田区华强北商圈及光明新区公明街道均拥有数万平方米的大型物业，每年物业租赁收入可观。公司未来自有土地资源的开发与经营将成为公司循序渐进式的长期稳定的收入来源和新的利润增长点。',
 '000021.SZ': '公司是中国先进的通讯电子产品制造企业之一，为全球多家一线品牌提供技术制造服务。致力于提供计算机与存储、通讯与消费电子、半导体、医疗器械、汽车电子、商业与工业产品的制造服务和自动化设备、计量系统及物联网系统的研发生产服务。公司拥有深圳、苏州、惠州、东莞、成都、重庆、桂林、马来西亚、泰国、菲律宾等多个研发制造基地，同时公司在美国、英国、荷兰、印度、新加坡、中国香港等多个国家或地区设有分支机构或拥有研发团队。公司是中国知名的智能电表及控制系统出口企业，是中国知名的半导体存储模组制造企业和中国先进的DRAM/flash封装测试企业。公司是国家高新技术企业，拥有中国国家认可委员会(CNAS)认可的专业实验室，具备优秀的可靠性、材料分析、先进机械、热仿真、表面贴装(SMT)、以及静电防护等工程技术能力，被认定为广东省工程技术中心和深圳市公共技术平台。',
 '000023.SZ': '公司是全国第一家以商品混凝土为主业的上市公司，主要业务涉及商品混凝土、房地产开发及物业管理等，目前业务已扩展至湖南、陕西、江苏等地。公司在深圳和湖南均建有专业商品混凝土生产基地，可生产各种强度等级的普通混凝土和特种混凝土以及预拌砂浆，其中在预拌砂浆技术方面位居领先地位。长期以来，为深圳许多重点工程、地标建筑提供了大量优质商品混凝土，产品已覆盖整个深圳市，进入湖南株洲市场后，为当地的重点和样板工程提供了优质混凝土。市场占有率居深圳、株洲地区前列。公司秉承“一流的产品质量，一流的服务水平”的宗旨，规范和加强内部管理，培育优秀的企业文化，充分发挥资源、设备、技术、品牌共享的优势，进一步拓展新的生产基地，扩大市场占有率，拓展房地产开发项目，步入了良性、稳健发展的快车道。',
 '000025.SZ': '公司是一家以汽车后市场服务和房地产物业经营管理为主营业务的大型集团。近年来，公司通过重组、资产整合、投资新项目，逐步形成了适应市场的经营模式，成为深圳市汽车行业的知名企业。拥有7家控股企业和多家参股企业，是深圳市汽车行业的知名企业。在汽车市场服务上，公司有一套完整的产业链，产品畅销全国各地、东南亚及非洲。物业经营管理方面，公司重点致力于产业园区建设，重点围绕特力吉盟黄金首饰产业园和布心汽车配件产业园建设，对产业园的部分项目进行投资开发、物业经营管理。',
 '000026.SZ': '公司是中国钟表行业的旗舰企业，中国境内表业上市公司，系中航工业集团下属中航国际深圳公司的主要投资企业之一。公司以品牌战略为统领，专注于钟表行业，主要从事世界名表零售和自有品牌钟表的研发、设计、制造和销售业务。名表零售业务方面，旗下的“亨吉利世界名表中心”是国内统一商号名表连锁网络，已发展为高端钟表零售业务的领军品牌之一。自有产品品牌方面，已形成飞亚达表、高端品牌、时尚品牌为主的“三色堇”产品品牌构架，基本完成了在研发、设计、关键零部件生产制造、分销、零售等重要价值环节的全产业链布局。公司长期致力于精密计时腕表技术研发与应用，拥有先进的研发生产技术和制造工艺平台。',
 '000027.SZ': '公司是全国电力行业第一家在深圳上市的大型股份制企业，也是深圳市第一家上市的公用事业股份公司。公司所从事的主要业务是各种常规能源和新能源的开发、生产、购销，以及城市固体废物处理、城市燃气供应和废水处理等。公司通过引进、消化、吸收和自主创新，掌握了具有国际领先水平的垃圾焚烧发电自主知识产权，拥有多项技术发明专利，拥有设计、投资、建设、运营和管理全过程运作能力。依托科技创新成果，公司具备含盐废水(脱硫废水、煤化工废水)、高浓度有机废水(垃圾沥滤液)等环保项目产业化运用的能力。在大力拓展电力主业的同时，公司坚持最高环保标准，以垃圾处理产业为依托，积极发展能源环保产业，初步形成以电为主，能源环保等相关产业综合发展的战略格局，在深圳市国有企业综合实力排名中位居第一，连续多年入选中国工业企业500强，在产业市场和资本市场上树立起“诚信、绩优、规范、环保”的良好形象。',
 '000028.SZ': '公司是集医药研发、制药工业、药品分销、医药物流为一体的综合性医药上市公司承担着国家、省、市政府药品特储任务。公司制药工业集产品研发、原料与制剂生产、市场营销于一体，产品主要覆盖头孢抗菌素、呼吸系统用药、消化系统用药、心脑血管用药以及抗肿瘤药等领域。公司药品分销业务位居广东、广西两省前茅，名列中国医药商业20强，拥有完善的全国商业网络和深度渗透的南区终端市场网络，拥有华南地区自动化程度最高、服务能力最强的专业医药物流中心，也是华南地区首家获批第三方医药物流资质的企业。未来的公司坚持内生性增长与外延式扩张并重，借助资本运作、实施兼并收购、联合重组，创新盈利模式，积极发展新业务，致力成为具有国际竞争力的医药健康产品和服务提供商。',
 '000029.SZ': '公司是深圳经济特区最早成立的房地产开发公司，公司曾在房地产开发史上创造了多个“第一”，包括：第一个有偿使用国有土地；第一个引入外资合作开发土地；第一个采用楼宇预售手段筹集开发资金；第一个按国际惯例实行建设工程公开招标；第一个成立物业管理公司对开发的楼宇、住宅进行全方位管理；在深圳经济特区举行的第一次土地使用权拍卖会上夺标等等。公司已发展成为一家以房地产开发与经营为主业，集物业管理与经营、建筑工程设计、施工与管理、旅游开发与经营等多元化经营于一体的企业集团。',
 '000030.SZ': '公司是中国知名的汽车零部件制造业集团企业，主要从事汽车零部件的研发、生产和销售，是国内在生产规模、产品系列、客户覆盖均具有一定优势的汽车零部件上市公司。公司自成立以来，始终以市场为导向，坚持走技术发展之路，通过市场结构调整、产品结构调整和企业结构调整，形成了以底盘业务、空调业务、汽车电子及新能源为主导核心产品的产业格局。目前，公司主要产品包括底盘系统、环境系统、制动和传动系统、转向及安全系统、电子电器系统、发动机附件系统等六大系列，产品品种覆盖重、中、轻、微型商用车和高、中、低档乘用车等系列车型；公司产品为众多国内整车/整机企业配套，部分产品远销海外。公司进一步深化自主研发机制，建立两级研发模式，研发中心及下属多家分公司、控股子公司被评为“省级企业技术中心”，公司及下属十余家企业被认定为高新技术企业。',
 '000031.SZ': '公司是一家全国性、综合性的房地产开发上市企业，总部位于深圳市。公司从事的主要业务包括：房地产开发、经营、销售、出租及管理住宅、商用物业，经营业态以住宅为主。公司立足环北京、环上海、环深圳三大核心城市群，重点关注以长江中游城市群、成渝城市群、一带一路沿线为主的中心城市及高潜力城市，打造了壹号、祥云、锦云、鸿云四条品牌住宅产品线，细分产品类型，实现区位、规模、定位上的互补。',
 '000032.SZ': '公司是一家以电子整机产品、新兴电子元器件等电子高新技术产品为主导的上市公司。公司主要经营以电子整机产品、新兴电子元器件等电子高新技术产品为主导，兼及房地产、商贸等多个领域。公司在坚持科技创新，不断开发新技术和新产品的同时，努力拓展发展空间，现已与国外多家知名企业开展广泛的技术交流与合作；以诚信为基础，以共赢为目标，公司业已建立良好的市场信誉，实现了集研发、生产、销售与售后服务于一体的战略体系；公司通过多年的发展，培养和锻炼了一支敬业、奉献、高素质的专业人才队伍，成为公司各项事业持续向前推进的有力保障。',
 '000034.SZ': '公司原为神州控股，2015年出售分销和系统业务，迎击“互联网+”时代浪潮，2016年4月于A股上市。公司先后荣获国家级火炬计划重点高新技术企业称号、北京市高新技术企业称号、中关村高新技术企业称号，软件开发获得CMMI4级认证，软件服务水平通过ISO20000和ISO27001认证，并在北京和武汉建成两个大型研发中心，是北京市“十百千工程”中，四家千亿核心企业之一。公司一直是国内外产品技术以及服务的提供商在中国首选的合作伙伴，与300余家国际顶尖供应商展开精诚合作，市场份额稳居第一，并建成覆盖全国860个城市、30000余家渠道伙伴的中国最大的IT营销网络，在为广大的消费者用户提供丰富的电子产品的同时，神州数码集团已累计为超过100万家中国企业提供信息化所需的产品、解决方案和服务。面向未来，公司将继续通过专业化与多元化的IT产品和服务，释放信息技术的力量，把信息技术价值转化为客户价值，推动中国信息化建设进程。',
 '000035.SZ': '公司是一家环保新能源上市公司，主要业务包括投资、建设、运营、维护环保基础设施项目和环保设备的研发、生产、销售；业务范围覆盖生活垃圾焚烧发电及蒸汽生产、污泥处理、餐厨垃圾处理、危险废弃物处理、建筑垃圾处理、污水处理、填埋气开发与利用、垃圾分类收运体系投资与运营等领域。公司坚守生活垃圾焚烧发电主营产业，围绕垃圾处理无害化、减量化、资源化，从末端处置向上游的分类、收运、中转和综合环卫方向拓展，延伸固废产业链，打造以生活垃圾处理为主线的城市环境服务综合运营商。公司项目荣获众多荣誉，特别是海安垃圾焚烧发电项目荣获了“2014-2015年度中国建设工程鲁班奖”，通过了江苏省“AAA”级城市生活垃圾处理设施无害化等级评定，为垃圾焚烧发电行业建设管理工作树立了标杆。公司在引进、消化、吸收国外先进技术的基础上，尤为注重提升自主创新水平，在垃圾焚烧发电领域拥有多项发明专利及实用新型专利，充分实现了该领域核心设备和关键设备的国产化，关键技术研究被国家科技部列入国家火炬计划项目。同时，公司致力于打造环保治理精品工程和以污水处理、烟气净化、垃圾压缩、垃圾焚烧设备为主导产品的国内领先环保装备制造基地。',
 '000036.SZ': '公司原是深圳市最早从事专业化纤产品生产与经营的国营内联企业，目前公司主营业务为房地产开发和自有物业租赁管理业务。房地产开发业务主要集中在深圳、杭州、千岛湖等城市，物业资产及物业经营管理业务主要集中深圳、杭州、上海、千岛湖等区域。从事房地产开发的实体主要包括：公司本部、深圳华联置业公司、杭州华联置业公司、浙江兴财公司、上海申冠置业公司等五家企业。从事物业经营管理业务的实体为华联物业集团，负责统筹、运营和管理本公司和华联集团的物业资产出租及住宅地产项目、商业地产项目等运营与服务管理。',
 '000037.SZ': '公司是以生产经营供电、供热，从事发电厂(站)建设工程总承包，提供技术咨询和技术服务为主营业务的中外合资股份制企业。自创立以来，公司坚持燃机发电及上下游产业并举的发展战略，在不断提高管理水平、扩大发电生产规模的同时，通过参股、控股等形式，先后涉足燃机电站工程建设、油品贸易、燃机发电技术培训等相关领域，努力朝着多元化和跨区域的方向迈进。公司主营业务为生产经营供电供热、从事发电厂(站)的相关技术咨询和技术服务，下属深南电工程公司不断开拓国内外燃机电站建设工程的技术咨询和技术服务业务，下属深南电环保公司利用燃机发电的余热从事污水处理厂湿污泥的干化处理业务，实现污泥的减量化、无害化处理和资源的综合利用。经过多年努力，公司先后获得“中国工业企业500强”、“中国最大500家外商投资企业”、“国家循环经济试点”等荣誉称号；连续数年被评为广东省、深圳市先进模范单位及保供电先进单位。',
 '000038.SZ': '公司致力于发展成集新媒体传播、金融服务、大数据服务、数字娱乐、物联网等为一体的“科技”+“文化”产业集团，构建“内容”+“平台”+“服务”的企业生态系统。拥有成熟的技术服务团队，技术人员覆盖了前期的需求沟通、用户界面设计，中期HTML5技术以及后期的广告效果跟踪。深大通可以全方位满足客户品牌传播和产品推广的需求，配合客户整体宣传策略，深入了解客户、了解市场、了解消费者，结合渠道资源、技术，帮助客户寻找广告信息传播的目标受众群，以适当的媒介及广告位置组合、恰当的互动形式为客户量身定制整合营销宣传策略。依托碎片化的沟通和互动，实现广告投放精准性、高效性品牌传播，让客户的营销更有价值。公司将将持续关注行业内优质资源，加大在互联网广告、户外广告等新媒体传媒领域的投入，未来公司将通过并购的方式，加大在传媒、数字娱乐、数字内容、大数据服务、金融服务等产业的布局，实现公司整体转型及跨越式发展。',
 '000039.SZ': '公司是世界领先的物流装备和能源装备供应商，总部位于中国深圳。公司致力于在如下主要业务领域：集装箱、道路运输车辆、能源化工及食品装备、海洋工程、物流服务、空港设备等，提供高品质与可信赖的装备和服务。支持这些业务蓬勃发展的有：提供专业资金管理的财务公司，以及提供金融解决方案的融资租赁公司。作为一家为全球市场服务的多元化跨国产业集团，中集在亚洲、北美、欧洲、澳洲等地区拥有300余家成员企业及2家上市公司，客户和销售网络分布在全球100多个国家和地区。',
 '000040.SZ': '公司是国内A股主板上市公司，主营业务包括新能源和生态环保。公司致力于成为国内领先的环保新能源综合服务商，在特定区域内打造优质生态环境，并提供多能互补、发配售一体、冷热电联供的智慧能源，通过环保、新能源两个绿色产业协同开发带动，提供一揽子绿色发展解决方案。在新能源领域，公司的重点发展方向是智慧能源。以东旭蓝天私有云为依托，实现对电站的全生命周期智能化管理，公司从上游的核心设备、规模化储能布局到下游的新能源电站发配售一体化、智能微网齐头并进，为用户提供系统的“一站式”新能源解决方案。在生态环保领域，公司业务范围涉及生态综合治理、水环境修复及运营、土壤及矿山修复、危废/固废处理四大领域，为地方政府提供基础建设和生态环保等领域的规划、设计、投资、建设、运营、管理等全生命周期的解决方案。作为对新能源产业产业链的补充和完善，公司积极布局新材料，组件生产已成功销往海外；公司旗下有自主研发的安轩智能运维机器人已实现量产，运行效果获玖龙纸业、上海宝钢、浙江正泰等大型企业客户好评。',
 '000042.SZ': '公司前身是深圳市长城投资控股股份有限公司，创立于1984年，1994年经股份制改造成为公众上市公司，为首批获得国家房地产开发一级资质企业。公司以房地产开发业务为主，范围涉及酒店经营、资产管理、物业管理、商业管理、投资等多个领域。近年来，公司继续扎根于主流的经济区域，多渠道、多方式取地，扩大区域影响范围，逐渐实现“专注区域、深耕城市、多盘联动”的战略布局。',
 '000045.SZ': '公司是由深圳市投资控股有限公司控股的国有上市公司，成立于1984年。主要从事纺织、服装及相关产品的生产与进出口贸易，兼营物业租赁、仓储、房地产开发、酒店等业务。公司重要的业务有：以LCD用偏光片为代表的高新技术产业；以海外服装加工及高档无缝内衣为代表的纺织服装产业；以地处深圳华强北繁华商业区的深纺大厦为代表的物业租赁业。公司立足企业实际，主动进行产业结构调整，积极推进产业转型升级，集中精力发展LCD用偏光片这一具有自主知识产权、市场前景广阔的高新技术产业，从传统的纺织服装加工业成功转型进入平板显示产业领域，被评为“深圳市国有企业产业转型升级的典范企业”、“广东省优势产业转型升级的企业”及“国家高新技术企业”。',
 '000046.SZ': '公司成立于1989年，于1994年在深圳证券交易所挂牌上市。面对中国经济结构转型的历史性机遇，泛海控股敏锐感知宏观经济和行业市场的变化，重新规划了产业发展方向，在继续发挥房地产业务优势的基础上，融合具有较大发展潜力的金融、战略投资等业务板块，将公司打造成涵盖金融、房地产、战略投资等业务的综合性控股上市公司。在金融业务领域，泛海控股围绕构筑完整的金融服务体系，业务已涵盖证券、信托、保险、期货、基金、资产管理、互联网金融等领域，形成了以民生证券、民生信托、亚太财险为核心的金融布局和业态分布。在地产业务领域，泛海控股涉及规划设计、开发建设、商业管理及物业服务等，具备大体量、多业态综合开发能力，项目布局已从北京、上海、武汉等国内一、二线城市延伸至美国洛杉矶、旧金山、纽约等海外市场。在战略投资领域，泛海控股已形成境内以“泛海投资”、境外以“中泛集团”、“中泛控股”为核心的战略布局，以期与公司现有业务形成互补和平衡。',
 '000048.SZ': '公司前身为深圳市养鸡公司。公司发展至今已形成集低碳都市农业、公用事业、房地产、金融投资等多种产业于一体的多元化集团公司，业务内容包括：种猪、肉猪养殖与销售，种鸡、肉鸡养殖与销售，中高端品牌猪肉与鸡蛋等生鲜农产品销售，饲料生产与销售，交通运输，自来水供应，房地产开发，物业管理、金融投资等。公司养猪业以技术为依托，以种猪繁殖为中心，大力培育新品种，实现农业的科技化，在农业部种猪质量检测中心测定评比中多次获得好成绩，公司养猪场连年被评为健康与合格猪场、原种猪场合格单位、重点生猪养殖场、先进养猪企业。',
 '000049.SZ': '公司为控股型企业，主要围绕锂电池产业链进行业务布局，其中惠州电池主营中小型锂电池封装集成业务，惠州蓝微主营中小型移动电源管理系统业务，二级子公司惠州市蓝微新源技术有限公司主营大型动力电池、储能电池等电源管理系统及封装集成业务。公司已经成为全球中小型移动电源领域的领导厂商之一，与全球主要电芯厂开展合作，服务于全球顶级消费电子厂商。作为国内锂电池制造领域的先行者，经过多年的发展，尤其是近年来，通过持续加大研发投入、打造高效制造平台、搭建品质控制预防体系、优化业务结构等举措，公司积累了雄厚的技术优势，品质保证及技术开发能力处于国际领先地位，拥有了优质的高端客户资源、先进的自动化水平和领先的制造水平，具有较强的综合竞争优势。在智能手机、电动工具等中小型移动电源管理系统暨封装领域处于全球领先地位。公司的电池产品获得了“国家免检产品”、“中国名牌产品”、“广东省名牌产品”等称号。',
 '000050.SZ': '公司是一家在全球范围内提供显示解决方案和快速服务支持的创新型科技企业，主要经营液晶显示器(LCD)及液晶显示模块(LCM)。公司聚焦于移动终端消费类显示市场和车载、医疗、工控等专业类显示市场，这两大类产品广泛应用于智能手机、平板电脑、车载显示、医疗显示、工业仪表、智能穿戴和智能家居等众多领域。公司是国内规模最大的液晶显示器及模块制造商之一。2018年公司通过重大资产重组拥有厦门天马100%股权以及天马有机发光60%股权,有利于上市公司充分发挥协同效应及规模优势，提升市场综合竞争力，提高上市公司盈利能力和可持续发展能力。',
 '000055.SZ': '公司业务范围涵盖高端幕墙系统及材料、轨道交通设备及系统、太阳能光伏发电、房地产和金融等板块，主要产品为节能幕墙、光电幕墙、LED彩显幕墙等各类建筑幕墙及铝板材料、轨道交通屏蔽门系统。公司秉承“科技为本，创新为源”的经营理念，坚持自主创新，以“方大工匠”精神发展“节能、环保、低碳”产业。公司先后荣获“亚太地区100家最佳管理公司”、“建设创新型国家杰出企业”、“中国建设科技自主创新优势企业”、“全国质量效益型先进企业”、“中国工业行业状元”、“国家863计划CIMS应用示范企业”、“全国CAD应用工程示范企业”、“全国建设信用AAA级诚信企业”、“广东省知识产权优势企业”、“广东省诚信守法示范企业”、“广东省守合同重信用企业”、“深圳市民营领军骨干企业”、“深圳市制造业信息化重点示范企业”、以及世界质量大奖——“白金明星奖”、“国家级重点新产品”、“中国建筑工程鲁班奖(国家优质工程)”、“詹天佑土木工程奖”、“全国建筑工程装饰奖”、“白玉兰”奖、“用户满意工程”等诸多荣誉。“方大FANGDA”被评为“中国驰名商标”。',
 '000056.SZ': '公司是一家集商业、地产、物业、林业为一体的集团化上市公司。公司坚持以市场为导向，注重夯实企业根基，并结合企业经营优势及商业发展趋势，勾勒出以商业地产为核心的战略发展蓝图。公司先后开发出国企大厦、港逸豪庭、榭丽花园、惠州阳光100等系列优质楼盘，积累了丰富的地产开发经验。公司融合中国国际化进程的思路及历史性机遇，坚持以品牌制胜的理念，立足高端品牌路线和精品路线，重视以人的美好品质感受与企业的持续性发展为归依，致力于成为行业顶尖的商业地产开发商和运营商，为消费者带来先进的生活品质体验，为城市的战略升级创造有价值的贡献。',
 '000058.SZ': '公司的主营业务是电子专业市场及其配套项目的开发及经营、物业租赁服务业务、贸易及渠道业务、电子商务、小额贷款增值业务以及酒店业务等。“赛格电子市场”已成为将自建发展IT综合体、租赁与委托管理相结合，市场服务与金融增值服务相结合，专业市场与渠道分销相结合，线上交易与线下交易相结合的国内乃至亚洲规模最大的涵盖电子元器件、数码IT、通讯产品等在内的综合类专业电子市场，在国内外拥有较高的品牌影响力。先后荣获了“中国电子产品五星级市场”、“深圳特区三十年最具影响力的专业市场”、“影响中国”的深圳十大品牌专业市场等荣誉称号。',
 '000059.SZ': '公司是国内特大型炼油化工一体化综合性石油化工企业之一，具有较强的整体规模实力，是国内重要的成品油、中间石化产品、ABS合成树脂和尿素生产企业，并拥有独立的公用工程、环境保护系统，及铁路运输、公路运输配套设施。公司拥有40多年的尿素生产经营和管理经验，积累有深厚的资源；公司曾多次获全国和地方政府的优质产品奖。公司主要业务包括石油化工产品、化学肥料的生产与销售。石化板块产品包括柴油、聚乙烯、聚丙烯、聚苯乙烯、ABS、船用燃料油、工业硫磺、石油甲苯、石油混合二甲苯等；化肥板块产品包括尿素、甲醇、液氨等。',
 '000060.SZ': '公司是一家主要是从事铅锌铜等有色金属的采矿、选矿、冶炼和深加工一体化生产的企业。公司通过一系列收购兼并、资源整合，直接掌控的已探明的铅锌铜等有色金属资源总量近千万吨，逐步成长为具有一定影响力的跨国矿业企业。公司主要产品有铅锭、锌锭及锌合金、白银、黄金、镉锭、锗锭、铟锭、工业硫酸、硫磺等产品。公司主要的生产活动为铅锌矿的开采、选矿以及铅锌金属的冶炼。公司产品质量均达到国际先进水平，公司拥有国家级技术中心，设立了“博士后科研工作站”。多年来，共获得省部级以上科技奖励近100项。公司秉承“做不到，没有理由”的企业核心价值观，以铅、锌、铜为主，坚持多金属、国际化、一体化、集约化的经营理念，努力打造国际矿业旗舰企业。',
 '000061.SZ': '公司是一家以投资、开发、建设、经营和管理农产品批发市场为核心业务的大型现代化农产品流通企业集团。公司肩负使命、情系民生，始终致力于中国农产品流通领域的发展与进步。率先开创农批市场网络化经营模式，在深圳、北京、上海、天津、成都、西安、长沙、武汉等多个大中城市经营管理了多家综合批发市场和网上交易市场，形成国内最具规模的基于供应链管理的新型农产品流通生态圈。公司率先创导绿色交易，精心打造以保障食品安全、提高流通效率、综合利用资源为核心的海吉星品牌，使得海吉星市场汇集了公司在工程建设、食品安全、信息科技、电子商务、物流管理、金融服务、综合环保等领域的创新性成果，成为农产品流通行业转型升级的典范之作；率先探索以农产品交易所为龙头，依托辐射全国的实体市场与电商平台的产业版图，发挥线上线下网络优势和规模效应，构建行业内具有重要影响力的多品种、多层次、多模式的农产品绿色交易新体系。',
 '000062.SZ': '公司的主营业务为面向电子信息产业链的现代高端服务业，为产业链上的各环节提供线上线下交易服务、产品服务、技术服务、交易信息服务和创新创业配套服务，打造面向电子信息产业的国内一流交易服务和创新创业服务双平台。具体业务环节包括电子元器件线下分销、电子元器件线上交易平台、电子元器件及电子终端产品线下交易平台、品牌终端产品线上分销、硬件+互联网的创新创业服务、其他物业经营等。经过在电子信息行业多年的精耕细作，公司品牌优势明显，打造并拥有了“华强电子世界”、“华强电子网”、“华强北·中国电子市场价格指数”、“IT市场指数”、“华强北国际创客中心”、“湘海电子”、“捷扬讯科”、“鹏源电子”、“淇诺科技”、“芯斐电子”等业内知名品牌，累积了独树一帜、无可复制的电子产业链数据库资源，包括线上线下平台聚集的百万级大中小企业客户及中小贸易商资源、数百万电子工程师资源、数亿条供求信息资源、海量的交易数据资源、高端的国际原厂资源、众多的国内大中小原厂资源以及齐备的电商、融资、物流等配套资源。',
 '000063.SZ': '公司是全球领先的综合性通信制造业上市公司，是近年全球增长快速的通信解决方案提供商。公司拥有通信业界完整的、端到端的产品线和融合解决方案，通过全系列的无线、有线、业务、终端产品和专业通信服务，灵活满足全球不同运营商和企业网客户的差异化需求以及快速创新的追求。公司通过为全球多个国家和地区的电信运营商和企业网客户提供创新技术与产品解决方案，让全世界用户享有语音、数据、多媒体、无线宽带等全方位沟通。公司坚持以持续技术创新为客户不断创造价值。公司在美国、加拿大、瑞典、中国等地设立全球研发机构，凭借不断增强的创新能力、突出的灵活定制能力、日趋完善的交付能力赢得全球客户的信任与合作。公司在全球范围内开展社区公益和救助行动，参加了印尼海啸、海地及汶川地震等重大自然灾害救助，并成立了中国规模最大的“关爱儿童专项基金”。',
 '000065.SZ': '公司专注于国际市场的经营，多年来建立了遍布全球的营销网络，培育了强大的国际化经营能力和投融资能力，具有优秀的全球资源配置能力和项目管理能力。公司实现了国际工程与专业化产品贸易的有机融合，充分发挥投资的驱动作用，在轨道交通、电力工程、石油矿产设施建设、市政房建、房地产开发、重型车辆与装备、包装容器研发与生产、物流一体化服务、太阳能产品应用等方面具有优秀业绩与较强竞争力。公司业务范围广泛、专业能力突出，并具有强大的系统集成能力，可以为业主提供一体化和全方位的服务。公司高度重视企业信誉和企业社会责任，连续多年被中国对外承包工程商会和中国机电产品进出口商会评为“AAA级信用企业”。公司还通过了质量(GB/T19001-2008)、环境(GB/T24001-2004)、职业健康(GB/T28001-2011)管理体系认证、工程建设施工企业质量管理规范(GB/T50430-2007)认证。',
 '000066.SZ': '公司是中国电子网络安全与信息化的专业子集团，核心业务覆盖自主可控关键基础设施及解决方案、军工电子、重要行业信息化等领域，能够做到从芯片、整机、操作系统、中间件、数据库、安全产品到应用系统等计算机信息技术各方面完全自主可控且产品线完整的上市公司。公司相关业务水平处于国内领先地位，掌握众多自主可控和信息安全的核心技术，在军队国防、党政等关键领域和重要行业具有深厚的行业理解、丰富的服务经验、稳定良好的合作关系。公司在中国深圳、长沙、武汉、北京、株洲以及海外设有研发中心和生产基地。',
 '000068.SZ': '公司是清华控股旗下节能环保业务的资本运作平台。公司旗下北京清控人居环境研究院有限公司为清华控股人居环境产业板块核心研发及建设运营平台，在城市水系统工程研发及建设运营领域处于国内领先水平。公司依托清华大学的品牌优势及研发能力，依托清控人居环境研究院后在城市水系统规划设计、市政及环保规划设计、环保基础设施建设投资及运营等领域形成的行业优势，依托上市公司平台与股权基金、资产证券化、信用贷款等其他金融工具组合培育的全方位融资渠道，将在环保基础设施投资、建设、运营服务领域形成系统全面的竞争力。',
 '000069.SZ': '公司是华侨城集团旗下旅游及房地产板块的上市公司，致力于成为国内主题公园的领导者、旅游产业的领军者、城镇化价值的实现者。经过近二十年的探索与升级，华侨城A以旅游综合、房地产为主营业务，构筑了成熟的成片综合开发模式。各业务板块相互融合，文化旅游景区、酒店、住宅和商业类地产以多种形式组成有机整体，成为公司有别于一般旅游、地产开发模式的独特优势，并实现了1+1>2的效用，在业态布局、产品功能、盈利与资金回收等方面形成紧密联系和相互补充，产生明显的协同效应和集群优势。近年来，公司在业务创新上不断进行探索实践，在探索文化旅游发展新模式、房地产综合业务体系的构造、旅游互联网业务研发等方面进行了探索与实践。',
 '000070.SZ': '公司是国内最早开拓并一直专注于光纤、光缆及光通讯设备开发、生产的国家级高科技企业之一，主要经营光纤光缆、电子元器件、光通讯设备，公司产品广泛应用于电信、移动、联通、广电、电力、石油、矿山、城域网、交通、航空、军工、智能建筑以及消费类和工业电子等领域。公司作为光纤光缆通信行业国家标准及行业标准的制订者之一，产品先后荣获国家级、省部级、地市级的科技进步奖、重点新产品、科技创新奖、科技成果奖、优秀产品奖等荣誉，还率先创造了多项全国第一：国内最早研发出ADSS光缆并保持最大使用跨距纪录；国内第一条OPPC光缆；国内最大芯数光缆-1000芯骨架式光缆；国内第一条实用的OPPC光缆线路，国内第一条12芯带骨架式光缆；国内最早的新型概念SST系列产品等。',
 '000078.SZ': '公司是一家致力于医药制造、商业流通和零售连锁的医药类上市公司，公司的医药制造和医药商业流通业务稳步增长，渠道和终端体系建设稳步推进，医药商业流通系统继续保持健康快速发展，“阳光集中配送”业务不断深化和完善，对公司的业绩贡献有了明显的提升。公司作为国内专业从事医药商业流通的药品服务商，根据国家产业政策和行业整合趋势，科学规划发展布局，加强上下游渠道开拓的同时充分利用资本市场提高自身经营发展水平，实现规模、效益的稳步提升。同时，在新版GMP认证、药品招标采购、药品成本及人力资源成本上升等条件下，公司医药工业体系内各公司坚持专业化、规范化的发展思路，稳步推进生产运营，医药工业体系业务维持平稳增长。',
 '000088.SZ': '公司经营范围为码头的开发和经营，货物装卸与运输，港口配套交通设施建设与经营，港口配套仓储及工业设施建设与经营，港口配套生活服务设施的建设与经营，集装箱修理，转口贸易，货物及技术进出口。公司先后荣获“中国25家最受尊敬上市公司”、“中国十佳最重分红回报上市公司”、“德勤中国风险智能榜优秀企业”称号，近6年连续获深交所信息披露优秀表彰。',
 '000089.SZ': '公司是国内最早由地方政府自主投资建设管理的机场，也是中国最大的航空运输市场之一。公司作为深圳宝安国际机场管理公司，主要经营航空主业以及航空主业延伸出的非航空业务。航空主业主要包括飞机起降及停场保障，机场飞行控制区的维护与运营管理，旅客的乘机、候机及进出港服务，航站楼商业及物业租赁业务、航空器的维护及辅助服务，航空货物的地面处理服务等，航空主业是机场作为民航运输基础设施固有承担的业务。非航空业务包括航空物流业务和航空增值业务。公司始终坚持打造科学高效的管理体系和市场化机制，致力于成为航空运输安全运行秩序的管理者、优质服务的提供者、社会效益的创造者。公司积极落实民航强国战略，携手国际一流合作伙伴，深度参与“未来机场”建设；与互联网领军企业加强战略合作，大力推进“数字化转型”，着力提升旅客体验和运营效率，更好保障机场公共安全和运营安全，力争成为行业发展的引领者。',
 '000090.SZ': '公司系深圳市国资委控股企业，主营业务集建筑施工、地产开发、城市服务于一体的城市综合运营商，致力于为客户提供优质的产品和服务，建设宜居、生态、环保、智慧城市。公司旗下有多家知名企业，其中深圳市市政工程总公司拥有完备的建筑企业资质，涉及市政、公路、房建、机电安装、轨道交通、水利水电等专业领域，其中包括市政公用工程施工总承包特级、公路工程施工总承包壹级和房屋建筑工程施工总承包壹级；深圳市天健房地产开发实业有限公司拥有房地产开发一级资质，已开发项目总建筑面积300多万平方米，集中在深圳、上海、广州、南宁、长沙、惠州等地。深圳市天健置业有限公司融合多年本土商业运营和酒店管理经验，为工业园区、酒店、写字楼、购物中心、公寓、餐饮等商用物业和提供专业化的商业运营与管理服务。',
 '000096.SZ': '公司是一家集成品油、液体化工储运、危化品储运和贸易、液化石油气经营、电力投资、房地产经营为一体的综合性能源类国有控股上市公司，属于深圳市一类企业。公司以能源投资和经营为主业，扎根深圳，辐射华南，通过投资兴建和收购兼并，获得了石油化工仓库、油库、汽车加油站、液化气储配站等优质资产，以及南山热电、深南燃气、妈湾电力、协孚能源、宝生银行等企业股权。公司目前拥有南山石油、广聚亿升、广聚亿达、广聚实业、广聚房地产、广聚香港6家控股子公司。公司身处石化行业，始终把安全工作看作重中之重，公司系统建立了一整套比较完善的安全管理体系，各个危险化学品经营单位均严格执行有关安全管理规定，实现多年的安全运营。',

In [9]:
import pandas as pd
df=pd.DataFrame(data=data,columns=['code','prod','backbone'])
df=df.set_index('code')
df['gpt_prod']=None
df['gpt_backbone']=None
df['similarity']=None
backbone_pattern=re.compile('\[(.*?)\]')
num=0
for code,r in df.iterrows():
    sql=f'select briefing from ticker_brief where code="{code}"'
    brief=mysql.read_query(sql)
    if brief:
        brief=brief[0][0]
        
    else:
        print(code+' has no brief in mysql\n')
        
        continue
    
    gpt_prod=prod_extraction(brief)
    df.loc[code,'gpt_prod']=gpt_prod
    gpt_backbone=guess_backbone(gpt_prod)
    find=backbone_pattern.findall(gpt_backbone)
    if find:
        gpt_backbone=find[0]
        df.loc[code,'gpt_backbone']=gpt_backbone
    gpt_similarity=similarity([r['prod'],gpt_prod])
    df.loc[code,'similarity']=gpt_similarity
    num+=1
    print(num)
    
df

1

KeyboardInterrupt:

In [10]:
import pandas as pd
df=pd.DataFrame(data=data,columns=['code','name','briefing'])
df=df.set_index('code')
df['gpt_prod']=None
df['gpt_backbone']=None
#df['similarity']=None
backbone_pattern=re.compile('\[(.*?)\]')
df

,name,briefing,gpt_prod,gpt_backbone
code,,,,
000001.SZ,平安银行,公司是深圳发展银行股份有限公司以吸收合并原平安银行股份有限公司的方式完成两行整合并更名后的银...,None,None
000002.SZ,万科A,公司成立于1984年，1988年进入房地产行业，经过三十余年的发展，已成为国内领先的城市配套...,None,None
000004.SZ,ST国华,公司创立于1981年，1990年12月1日起在深圳证券交易所挂牌交易，是深交所首家挂牌的上市...,None,None
000005.SZ,ST星源,公司是中国早期大规模介入酒店式公寓服务业的公司之一，中国早期上市的公司之一。公司从事的主要业...,None,None
000006.SZ,深振业A,公司是深圳市国有资产监督管理委员会直管的国有上市公司，公司以房地产开发经营为主营业务，具备国...,None,None
...,...,...,...,...
YZCF.HK,兖州煤业股期,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,None,None
ZAOF.HK,HKEX众安在线财产保险股份有限公司股票期货,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,None,None
ZC.CZC,CZCE动力煤,郑州商品交易所成立于1990年10月12日，是经国务院批准成立的国内首家期货市场试点单位，于...,None,None
ZJMF.HK,紫金矿业集团股期,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,None,None
ZN.SHF,SHFE锌,上海期货交易所是依照有关法规设立的，履行有关法规规定的职能，按照其章程实行自律性管理的法人，...,None,None

In [ ]:
df['gpt_prod']=None
df['gpt_backbone']=None
#df['similarity']=None
backbone_pattern=re.compile('\[(.*?)\]')
num=0
for code,r in df.iterrows():
    sql=f'select briefing from ticker_brief where code="{code}"'
    brief=mysql.read_query(sql)
    if brief:
        brief=brief[0][0]
        
    else:
        print(code+' has no brief in mysql\n')
        
        continue
    
    gpt_prod=prod_extraction(brief)
    df.loc[code,'gpt_prod']=gpt_prod
    gpt_backbone=guess_backbone(gpt_prod)
    find=backbone_pattern.findall(gpt_backbone)
    if find:
        gpt_backbone=find[0]
        if gpt_backbone in backbones:
            df.loc[code,'gpt_backbone']=gpt_backbone
        else:
            print(gpt_backbone)
            df.loc[code,'gpt_backbone']='未找到分类'
    #gpt_similarity=similarity([r['prod'],gpt_prod])
    #df.loc[code,'similarity']=gpt_similarity
    num+=1
    print(num)
    if num==1:
        break
    
df

In [11]:
codelist=df.index.tolist()
len(codelist)

8180

In [12]:
len(codelist)/5

1636.0

In [13]:
5%100

5

In [14]:
from tqdm import tqdm
import time

for i in tqdm(range(100)):
    time.sleep(0.1)

100%|██████████| 100/100 [00:10<00:00,  9.84it/s]

In [15]:


import threading

# 定义一个处理列表的函数
def process_list(lst):
    num=0
    for code in lst:
        #code=lst[i]
        try:
            brief=brief_dict[code]
            gpt_prod=prod_extraction(brief)
            df.loc[code,'gpt_prod']=gpt_prod
            gpt_backbone=guess_backbone(gpt_prod)
            find=backbone_pattern.findall(gpt_backbone)
            if find:
                gpt_backbone=find[0]
                if gpt_backbone in backbones:

                    df.loc[code,'gpt_backbone']=gpt_backbone
                else:

                    print('内容不在范围内：'+code+','+gpt_prod+":"+gpt_backbone)
                    df.loc[code,'gpt_backbone']='未找到分类'
            else:
                print('格式不对：'+code+','+gpt_prod+":"+gpt_backbone)
            num+=1
            if num%100==0:
                print(num)
        except:
            pass
        

# 定义一个线程类
class ListThread(threading.Thread):
    def __init__(self, lst):
        threading.Thread.__init__(self)
        self.lst = lst

    def run(self):
        # 在线程中调用处理列表的函数
        process_list(self.lst)

# 创建一个列表
codelist=df.index.tolist()

# 定义线程数
num_threads = 5

# 计算每个线程需要处理的列表长度
chunk_size = len(codelist) // num_threads

# 创建线程列表
threads = []

# 将列表分成多个块，并为每个块创建一个线程
for i in range(num_threads):
    start = i * chunk_size
    end = start + chunk_size
    if i == num_threads - 1:
        end = len(codelist)
    thread = ListThread(codelist[start:end])
    threads.append(thread)

# 启动所有线程
for thread in threads:
    thread.start()

# 等待所有线程完成
for thread in threads:
    thread.join()

格式不对：2280.HK,数据服务、线上广告服务、电子产品之企业对企业、企业对客户零售业务、企业对企业交易平台、防伪产品和服务、供应链管理服务、营销服务、融资服务。:互联网云计算
内容不在范围内：0122.HK,鳄鱼恤、鳄鱼恤女装、鳄鱼仔、Lacoste:时尚服装
内容不在范围内：0128.HK,主营业务为投资控股及证券买卖。:证券
内容不在范围内：000010.SZ,园林绿化工程施工、园林景观设计、园林养护及绿化苗木种植。:园林
内容不在范围内：600055.SH,医用X射线诊断设备、磁共振成像设备、齿科诊断和治疗设备、血液健康产品:"医药"
内容不在范围内：600057.SH,公司主营产品/业务为商品采购供应及综合物流服务、物流园区平台开发运营。:商品采购供应
格式不对：2297.HK,caFFR系统和caIMR系统:由于没有明确的上下文和相关信息，无法确定caFFR系统和caIMR系统的具体含义和指代。请提供更多背景信息或上下文，以便更好地回答您的问题。
格式不对：605377.SH,可印刷装饰原纸和素色装饰原纸:工业制造
内容不在范围内：2306.HK,艺人管理、音乐IP制作及运营及泛娱乐业务:音乐
格式不对：600058.SH,冶金原材料和钢材的国内外贸易。:根据题目，我们可以将该问题分成两个部分来回答。

1. 冶金原材料的国内外贸易：

我国的冶金原材料主要包括铁矿石、铜矿石、铝土矿等。根据中国海关统计，2019年我国进口的铁矿石总量为10.39亿吨，同比增长0.5%。其中，澳大利亚、巴西和南非是我国的三大铁矿石进口国。而我国的铜矿石主要进口自智利、秘鲁、澳大利亚等国家。此外，我国的铝土矿主要来自澳大利亚、几内亚等国家。

2. 钢材的国内外贸易：

我国是全球最大的钢铁生产和消费国之一。根据中国海关统计，2019年我国的钢材出口量为6426万吨，同比下降7.3%，而钢材进口量为12230万吨，同比下降7.8%。我国的钢材进口主要来自于日本、韩国、东南亚等国家和地区，而钢材出口则主要流向东南亚、美国、欧洲等地。受到新冠疫情和国际贸易摩擦等因素的影响，我国的钢材进出口总量在近两年出现了一定程度的下降。
格式不对：2309.HK,彩票系统及在线付款系统服务解决方案。:该产品属于互联网云计算板块。
格式不对：2310.HK,电子组件制造及销售、物业投资、酒店营运。:从描述中无法确定所属的产业分类，需要更多信息来判断。
内容不在范围内：605398.SH,智慧运维管理平台(SIOPS)、应用性能管理平台(APM)、数据库性能管理平台(DPM)、SQL审核管理平台、大数据日志分析管理平台(IVORY)、数据治理及资产管理平台(DAMS)、敏捷开发与持续交付管理平台(GDEVOPS)等产品。:IVORY
内容不在范围内：2314.HK,箱板原纸及纸浆生产:纸浆生产
内容不在范围内：600063.SH,主营业务：化工、化纤、建材、新材料联合制造。主营产品：PVA光学薄膜。:化工
内容不在范围内：6055.HK,烟叶类产品和捲烟。:烟草业
格式不对：2315.HK,生物制药及临床前研究服务，YH003，YH001，其他管线候选产品。其中，YH003是一种重组人源化激动性抗细胞分化簇40(CD40)免疫球蛋白G2(IgG2)单克隆抗体，YH001是一种重组人源化抗CTLA-4免疫球蛋白G1(IgG1)单克隆抗体。公司的核心产品YH003主要开发用于胰腺导管腺癌、黑色素瘤及其他晚期实体瘤。公司的其他核心产品YH001主要开发用于肝细胞癌(HCC)、非小细胞肺癌(NSCLC)及其他实体瘤。:医药板块。
内容不在范围内：605500.SH,主营产品：原纸、瓦楞纸板、瓦楞纸箱。:瓦楞纸板
内容不在范围内：605555.SH,电机产品线、小家电产品线、EPS电机产品线。:EPS电机产品线
格式不对：600071.SH,光学镜片、光学镜头、光电模组、电池、科学仪器。:工业制造。
内容不在范围内：605566.SH,中高端涤纶分散染料产品及应用服务。:化工
格式不对：605567.SH,鸡肉调理品和生鲜品。:畜牧业。
格式不对：0154.HK,垃圾焚烧发电厂、废物处理及出售垃圾焚烧所产生之电力及蒸气。:工业制造。
格式不对：2318.HK,保险、银行、资产管理、互联网金融四大板块的产品和服务。:保险板块：提供各种保险产品，包括人寿保险、财产保险、医疗保险等。保险公司还会提供理赔服务、风险评估等服务。

银行板块：提供各种金融服务，包括存款、贷款、信用卡、国际结算等。银行还会提供投资理财、保险、外汇交易等服务。

资产管理板块：提供各种投资管理服务，包括股票、债券、基金、证券等。资产管理公司还会提供资产配置、风险管理、投资建议等服务。

互联网金融板块：将金融服务与互联网技术相结合的新型金融服务。包括网上银行、第三方支付、P2P借贷、股权众筹等，也包括新兴的比特币、区块链等技术的应用。互联网金融公司还会提供资产配置、理财产品、财务咨询等服务。
内容不在范围内：600075.SH,塑料制品、节水器材、热电、化工、电石、水泥、矿业、建材、物流、对外贸易、建筑、安装与房地产等多个领域的产品/业务。同时也包括电力、农业节水、物流商贸、食品加工、塑料包装等为一体的多元化综合类产品/业务。:化工
内容不在范围内：2322.HK,食品及电子产品贸易业务。:贸易
内容不在范围内：0159.HK,铁矿、铜矿等矿产资源开发和运营。:矿业
内容不在范围内：2324.HK,主营业务：投资于香港及中国之上市及非上市公司，专注于香港上市证券及以中国为目标之叧类投资机会，如私募资产及以专营行业为目标之基金等。:金融
内容不在范围内：600080.SH,人工虎骨粉/金天格胶囊、金花牌转移因子系列药、金花牌儿童系列药:注：由于其中涉及到不同种类的药品，可能还可以细分为更具体的医药板块
内容不在范围内：2326.HK,采购及销售金属矿物及相关工业原料业务。:矿业
内容不在范围内：0165.HK,资产管理、直接投资、产业投资、投资银行、经纪业务、证券经纪、财富管理。:投资银行
格式不对：6066.HK,证券承销与保荐、证券经纪、证券自营、证券资产管理、证券投资基金代销、融资融券业务、代销金融产品业务、保险兼业代理业务、期权做市业务、证券投资基金托管、销售贵金属制品。:证券资产管理
格式不对：2330.HK,物业发展、物业投资、原糖贸易、电子相关组件、手机组件、自动化产品贸易。:这些类别没有与板块列表中的任何一个板块名相对应。建议重新确定所属的产业分类class并再次查询。
内容不在范围内：2331.HK,李宁牌、KAPPA牌、AIGLE户外运动用品、新动(Z-DO)牌运动鞋、服装和配件。:运动服饰
格式不对：600089.SH,变压器、电线电缆、高压电子铝箔新材料、太阳能系统工程实施及太阳能核心控制部件的研发、制造和出口。:电力储能 【注】虽然太阳能也可以归为光伏板块，但是由于该企业涉及到多个电力领域，因此综合考虑后选用电力储能板块。
内容不在范围内：600091.SH,山泉、双环、云杉等品牌化工产品，电石出口。计算机软硬件开发、生产、销售，系统集成、网络设计与咨询、电子商务等服务。:化工产品
内容不在范围内：600095.SH,湘财证券股份有限公司:证券
格式不对：600096.SH,磷肥、氮肥、共聚甲醛:工业制造。
格式不对：600098.SH,电力、燃料、天然气、能源物流、新能源、财务公司。:石油化工
内容不在范围内：6116.HK,主营产品：大众女性休闲服装，大众时尚男装，童装，以及多个品牌的时尚服装产品。:class
格式不对：6119.HK,散货装卸服务、油罐及粮仓的储存服务、铲车租赁。:工业制造。
内容不在范围内：0188.HK,证券、期权、基金、期货和商品经纪服务、孖展及其他融资服务以及其他相关服务。:证券
格式不对：600107.SH,美尔雅西服:从问题描述中未能判断该产品所属的产业分类class，无法给出与该class最接近的板块名。请您提供更多相关信息，以便我能为您提供更准确的答案。
格式不对：0191.HK,丽新制衣国际有限公司没有主营产品或业务，而是通过五大分部运营，包括物业发展及销售、物业投资、酒店经营、餐厅经营和其他服务。:该公司的产业分类不明确，无法从中选出最接近的板块名。
内容不在范围内：0195.HK,澳大利亚锡矿及铜矿的勘探、开发及开采。:矿业
内容不在范围内：2362.HK,开发及管理海外矿产资源项目，以及镍、铜、钴及其他有色金属原料和产品的贸易。:矿产资源
格式不对：0202.HK,物业投资业务、酒店业务、农业业务、证券投资及融资业务。:从提供的信息中没有明确给出产业分类，无法与板块列表进行匹配，建议提供更详细的信息。
内容不在范围内：2372.HK,卷烟包装纸制造业务。:烟草
格式不对：600119.SH,现代综合物流服务、国际货运、公共信息平台、国内快件、市内货运、陆上货运交易中心、长江现代物流服务平台、气象仪器高科技产品、BT项目。:工业制造。
内容不在范围内：0206.HK,集团的主营产品为与陆上及海洋钻探行业有关的多种产品及相关服务。:class = 石油化工
格式不对：2377.HK,烟气处理服务、脱硫及脱硝服务。:石油化工。
内容不在范围内：2378.HK,人寿保险、医疗及保障、个人财产及伤亡事故保险、团体保险、机构基金管理。:保险
格式不对：000020.SZ,液晶显示器整机业务、注塑件生产业务、保丽龙(轻型材料包装)生产业务、物业租赁业务。:工业制造。
内容不在范围内：600125.SH,特种集装箱运输、铁路货运与临港物流和房地产开发。:特种集装箱运输、铁路货运与临港物流
格式不对：6190.HK,九江银行的主营业务为城市商业银行业务，包括存款、贷款、信用卡、票据承兑与贴现、外汇兑换、结算等金融服务。此外，九江银行还设立了普惠金融总部、金融市场管理总部、票据中心、贸易金融部、金融股权管理部、汽车金融事业部、直销银行事业部、信用卡中心、绿色金融事业部等事业部管理机构，发起设立了修水九银、广东中山小榄等20家村镇银行。:银行。
内容不在范围内：2381.HK,电动工具、电风扇、工作灯、吸尘机。其中，集团自有品牌为「SMC」。:SMC
内容不在范围内：000023.SZ,商品混凝土、预拌砂浆:建材
格式不对：0215.HK,流动通讯服务和固网服务。:由于提供的分类不够具体，不能确定应该从哪个板块进行选择。建议提供更具体的产品信息或者描述，以便能够更准确地进行分类。
格式不对：6600.HK,日达仙:很遗憾，无法确定日达仙的产业分类，无法根据此给出最接近的板块名。
格式不对：6606.HK,常卫清、噗噗管及其他产品。:抱歉，您的问题并没有提供所属的产业分类class，无法回答与之最接近的板块名。请提供更多信息。
格式不对：2390.HK,知乎没有明确的主营产品或业务，而是提供一个问答类网络社区平台，让用户可以分享、探索和享受各种各样的内容。:由于知乎没有明确的主营产品或业务，因此无法将其归类到上述板块中。知乎可以被归为互联网云计算板块，但这也不完全准确。综合来讲，知乎可视为一个互联网社交平台。
内容不在范围内：600135.SH,彩色感光材料和照相化学材料，膜及带涂层的膜类加工产品。:化学制品
内容不在范围内：6616.HK,珠光颜料产品:化学制品
内容不在范围内：2393.HK,彩色相纸、未曝光彩色胶片、医用干式胶片、牙科胶片、印刷电路板胶片、医用湿式胶片等。:印刷电路板胶片
内容不在范围内：600136.SH,影视制作、体育营销、体育版权。:影视
100
100
内容不在范围内：600143.SH,改性塑料、完全生物降解塑料、高性能碳纤维及复合材料、特种工程塑料和环保高性能再生塑料等五大类自主知识产权产品。:塑料
格式不对：000039.SZ,集装箱、道路运输车辆、能源化工及食品装备、海洋工程、物流服务、空港设备。:工业制造。
内容不在范围内：600146.SH,塑料板材、碳纤维制品、苹果酸、防老剂、服装设计销售、高端运动服饰代工、供应链管理、Oneworld、Rules of Etiquette、Weavers等多个自有品牌。:工业制造可能包含塑料板材、碳纤维制品的生产
格式不对：000040.SZ,智慧能源、生态综合治理、水环境修复及运营、土壤及矿山修复、危废/固废处理、新材料、安轩智能运维机器人。:石油化工
100
格式不对：0239.HK,和兴产品的制造及销售。:该描述缺乏足够的信息来确定产业分类class，因此无法选择最接近的板块名。请提供更多细节或背景。
格式不对：2440.HK,物联网解决方案及通信设备供应商:根据提供的信息，无法确定其所属的产业分类class，因此无法给出最接近的板块名。请提供更具体的信息或分类class。对于物联网解决方案及通信设备供应商，可能属于通信、半导体、工业制造、互联网云计算等板块。
格式不对：0243.HK,引线框产品:该产品所属的产业分类没有给出，无法选择最接近的板块名。
格式不对：0244.HK,先施百货:先施百货属于消费电子板块。
内容不在范围内：6680.HK,高性能钕铁硼永磁材料:磁性材料
内容不在范围内：2450.HK,骨料产品和混凝土产品。:骨料产品
内容不在范围内：6696.HK,整合营销解决方案服务，包括内容营销、SaaS互动营销、数字营销、公关活动策划和媒介广告。其中，活动内容营销是公司的主营业务之一。:数字营销
格式不对：0252.HK,物业投资、发展及出租、塑胶包装材料生产及分销、经纪服务及证券保证金融资。:地产
100
内容不在范围内：6805.HK,废水处理及公用事业服务、工业园区物业发展及管理业务、货品销售及配套业务。:公用事业服务
格式不对：0254.HK,媒体广告业务、资源贸易业务、贵金属贸易业务。:根据提供的信息，无法确定具体产业分类，建议提供更详细的信息。
内容不在范围内：600165.SH,活性炭制品的生产及销售:活性炭制品属于一种工业制造产品
内容不在范围内：2528.HK,国际品牌时尚服装零售，包括知名设计师品牌、流行环球品牌、新进品牌，品牌组合包括113个品牌，其中自营品牌包括UM、UM·IXOX及IXOX。单一品牌店铺的品牌包括BLACKBARRETT、CK CALVIN KLEIN、Calvin Klein Jeans、Calvin Klein Performance、CalvinKlein Underwear、EA7、Ed Hardy、Hogan、Moschino、Neil Barrett、Philipp Plein、TommyHilfiger及Under Armour等。:时尚服装
内容不在范围内：000062.SZ,电子元器件线下分销、电子元器件线上交易平台、电子元器件及电子终端产品线下交易平台、品牌终端产品线上分销、硬件+互联网的创新创业服务、其他物业经营等。:电子元器件线下分销、电子元器件线上交易平台、电子元器件及电子终端产品线下交易平台、品牌终端产品线上分销、硬件+互联网的创新创业服务、其他物业经营等
格式不对：6811.HK,多元品牌休闲餐饮。旗舰品牌「太兴」，自创、收购及授权成功壮大品牌组合包括「茶木」、「靠得住」、「敏华冰厅」、「锦丽」、「东京筑地食堂」、「渔牧」及「饭规」。提供琳琅满目的菜式。:食品饮料
内容不在范围内：2600.HK,铝土矿、氧化铝、原铝和铝合金产品生产、销售、技术研发。:铝产业
内容不在范围内：6820.HK,女性向中国古风手机游戏:游戏
格式不对：0261.HK,没有具体提到公司的主营产品或业务。:如果没有具体提到公司的主营产品或业务，无法准确地确定其所属的产业分类。建议您再调查一下该公司的业务范围和主营产品，以确定其应属于哪个产业分类。
内容不在范围内：2628.HK,个人人寿保险、团体人寿保险、意外险和健康险等产品与服务。:保险
内容不在范围内：6826.HK,医用透明质酸钠/玻璃酸钠、医用几丁糖、基因工程药物重组人表皮生长因子、人工晶状体。:注：虽然题目里提到了“钠离子电池”和“玻璃酸钠”，但是这两个板块不适用于该产品分类，医药是最符合的选择
格式不对：600179.SH,集装箱物流服务、大宗商品物流、冷链物流、快拼箱服务、国际物流、金融物流、供应链整合、船舶服务。:由于缺少具体的产业分类class，无法判断最接近的板块名是什么。请提供产业分类class以便答案更准确。
内容不在范围内：6839.HK,污水处理、供水、建造及设备销售以及其他(包括O&M污水处理及市政垃圾处理项目)。:环保工程及服务
内容不在范围内：6855.HK,新型疗法，包括八项处于临床阶段的小分子候选药物，PPI候选药物和下一代酪氨酸激酶抑制剂(TKI)。:注：该题可能存在歧义，因为新型疗法属于医药行业，但是具体从描述来看，可能与生物技术或生命科学更为相关。
内容不在范围内：0270.HK,水资源、基建、物业投资及发展、百货零售、酒店经营及管理。具体产品/业务名包括原水供应、自来水供应、污水处理、水利工程、电力业务、收费道路业务、广东天河城项目、天津天河城项目、番禺万博中央商务区项目、七间酒店（香港华美粤海酒店、香港粤海酒店、粤海喜来登酒店等）。:基建
内容不在范围内：000155.SZ,化工产品的国内贸易及电力设备、机电产品等机电物资的国内贸易业务，风力发电、光伏发电。:class: 石油化工
格式不对：600186.SH,调味品系列，植物蛋白系列，小麦面粉系列，小麦淀粉系列，味精，鸡精，谷朊粉。:该产品属于食品饮料产业。
格式不对：2688.HK,清洁能源分销和非管输能源配送业务。:从给出的信息中无法确定其所属的产业分类，建议提供更多细节或背景信息。
内容不在范围内：2689.HK,包装纸板产品、环保型文化用纸、特种纸、高强瓦楞芯纸、涂布灰底白板纸、色牛皮纸浆生产业务。:包装纸板
内容不在范围内：600189.SH,主营产品/业务：木材、木制品、人造板、林化产品、食用菌、动植物、林副土特产品、机械电子、建材、保健品加工和销售、进出口贸易、园林景观设计、园林工程施工、绿化苗木种植销售和天然饮用矿泉水的生产、销售。其中最具特色的是绿色人造板为主的“露水河”牌刨花板系列产品。:木材
格式不对：000166.SZ,证券业务、银行业务、保险业务、信托业务、租赁业务、资本市场、投资银行。:抱歉，以上提供的分类不在板块列表中，无法回答。请提供在板块列表中的产业分类。
内容不在范围内：0282.HK,印刷传媒出版，刊物出版，手机应用程序，动画剧目，网上游戏。:媒体
格式不对：000300.SH,无。:抱歉，我无法判断应该选取哪个产业分类。请提供更具体的信息，以便我能够帮助您。
内容不在范围内：600191.SH,甜菜制糖业、电子业，主要产品包括“草原”牌糖产品和“包糖”牌食用酒精、“BY”牌石英晶体谐振器等电子元器件，计算机的研制、开发、生产和售后服务以及糖机设备的制造与销售。其中“草原”牌幼砂精糖、颗粒粕及“BY”牌石英晶体谐振器均为国家级新产品。:电子业产品为主要依据
内容不在范围内：000338.SZ,动力总成、整车整机、液压控制和汽车零部件。具体产品包括全系列发动机、重型汽车、轻微型车、工程机械、液压产品、汽车电子及零部件等。:class: 汽车
内容不在范围内：688010.SH,光学镜头、光电系统及光学元组件，包括定制产品和非定制产品，其中非定制产品包含民用安防镜头、车载镜头、红外镜头、物联网镜头、AI镜头等激光、紫外、可见光、红外全光谱镜头。:光学元件
内容不在范围内：0291.HK,华润集团的主营产品或业务包括零售、啤酒、食品及饮品业务。其中，集团零售业务的知名品牌包括「华润万家CR Vanguard」、「苏果Suguo」、「欢乐颂Fun2」、「Ole'」、「blt」、「V>nGO」、「Voi_la!」、「中艺Chinese Arts&Crafts」、「华润堂CRCare」、「采活VIVO」及「太平洋咖啡Pacific Coffee」等；啤酒业务的主要品牌为「雪花Snow」；食品业务主要包括大米、果蔬、肉食、冷冻食品及现代农业产业，以「五丰Ng Fung」品牌的优质食品形象拓展国内市场；饮品业务的主要品牌为纯净水品牌「怡宝C'estbon」，并与「麒麟Kirin」系列饮品发挥协同效益。:五丰Ng Fung
格式不对：600198.SH,可信识别芯片、汽车电子芯片、融合通信芯片、专用终端产品和应用平台、智慧城市、行业信息化、信息安全、电信运营支撑、IT分销、网络游戏等产品和解决方案。:从上述提供的描述中，无法准确判断该产品所属的产业分类。请提供更多相关信息进行判断。
内容不在范围内：688015.SH,城市轨道交通信号系统的研发、关键设备的研制、系统集成以及信号系统总承包，主要产品包括基础CBTC系统、CBTC互联互通列车运行控制系统(I-CBTC系统)、全自动运行系统(FAO系统)。:地铁
格式不对：600202.SH,石化空冷器、电站空冷器和空调暖通设备:工业制造。
格式不对：000409.SZ,公司的主营业务涵盖黑色金属采选、贵金属采选、生物医药、清洁能源、特种轮胎、房地产开发、商品贸易等多个行业。没有明确的单一主营产品或业务。:根据提供的信息，该公司没有明确的单一主营产品或业务，无法准确地给出其所属的产业分类class，因此无法从板块列表中选出与其最接近的一个板块名。
内容不在范围内：688016.SH,主动脉覆膜支架系统、外周血管支架系统、外周血管球囊扩张导管等产品。:class
内容不在范围内：0297.HK,化肥生产、进出口、分销、零售，与化肥相关的业务和产品的技术研发与服务。:化学制品
格式不对：000416.SZ,典当和保险经纪。:抱歉，该产业分类不在板块列表中，无法进行匹配。请提供其他产业分类。
内容不在范围内：000420.SZ,粘胶纤维的生产和销售，醋酐的生产和研发，包括粘胶短纤维、粘胶长丝、腈纶纤维、化纤浆粕、纱线和纸制品六大系列450多个品种。:化纤
格式不对：0309.HK,电视屏幕播放业务、清洁及相关服务、医疗废物处理服务、废物处理服务。:该class可能属于消费电子板块。
格式不对：0310.HK,投资控股、持有股本、投资、管理服务。:根据提供的信息无法确定所属产业分类class，因为该描述比较抽象，没有具体的业务描述。
格式不对：000421.SZ,出租汽车、房地产开发、电力能源、国内国际旅游、汽车销售、客运大巴、小额贷款、驾校培训。:出租汽车、汽车销售属于汽车板块；房地产开发属于地产板块；电力能源属于电力储能板块；国内国际旅游属于旅游板块；客运大巴属于陆运板块；小额贷款属于银行板块；驾校培训可以归为教育板块。
内容不在范围内：2899.HK,金、铜、锌等金属矿产资源勘查和开发。:矿业采掘
格式不对：300001.SZ,箱式电力设备、新能源汽车充电网、新能源微网系统。:钢铁。
格式不对：0312.HK,岁宝百货:根据信息不足，无法确定该产品所属的产业分类class，无法选择对应的板块名。
内容不在范围内：688031.SH,大数据基础软件及服务，大数据与云基础平台、分布式关系型数据库、数据开发与智能分析工具的软件产品矩阵。:class
内容不在范围内：600217.SH,废弃电器电子产品的回收与拆解处理。:环保
内容不在范围内：300003.SZ,冠脉支架、PTCA球囊导管、中心静脉导管、压力传感器、心血管介入、麻醉监护产品、药物支架。:冠脉支架、PTCA球囊导管、中心静脉导管、心血管介入、药物支架
100
内容不在范围内：000488.SZ,造纸、金融、浆纤、地产、矿业五大产业板块，以及林业、物流、建材等领域。主营产品包括高档胶版纸、铜版纸、白卡纸、轻涂纸、生活纸、静电复印纸、热敏纸、格拉辛纸等系列产品。:造纸
内容不在范围内：688038.SH,公共安全管理信息化系统、公安交通综合管控平台、公安大数据综合应用平台、智慧警务全方位服务平台、车联网环境下道路交通信号协调控制技术及应用。:公共安全
内容不在范围内：0318.HK,智能卡金融服务业务、消费者金融、票务网、证券投资、物业投资、酒楼业务。:金融
格式不对：688039.SH,智能视频处理软件、视频云服务、视频内容采集、生产、传输分发和终端播放、人像大数据实战应用平台、移动视频警务、视频编解码软件、4K超高清实时编码器产品。:工业制造。
内容不在范围内：000501.SZ,摩尔商业城、购物中心和超市连锁三大业态。:超市
格式不对：300011.SZ,轨道交通地面电气装备解决方案、车辆电气装备解决方案、信息化与安全检测解决方案、售后维修及运营维护解决方案。:工业制造。
内容不在范围内：600227.SH,尿素的生产和销售，氮肥、磷肥、复合肥、化工产品(不含化学危险品)的生产、销售，生物工程制品(不含预防用生物制品)及生物制药的研究、开发、生产、销售，健康食品、功能性食品、绿色环保产品的研究、开发、生产、销售。:化工
内容不在范围内：300013.SZ,电子元器件保税仓储及配套物流服务。:电子元器件
内容不在范围内：600229.SH,图书、期刊、电子音像等出版物的出版发行业务以及新兴媒体的开发运营业务。:图书期刊出版发行业务
内容不在范围内：0326.HK,电影制作、发行电影及电视连续剧、销售保健产品、投资于自博彩推广业务收取溢利之业务、物业与酒店投资以及物业开发。:影视娱乐
格式不对：600234.SH,自有房屋租赁业务、高端红酒贸易业务、广告传媒业务。:该企业暂未提供产品所属的产业分类class，无法选择最接近的板块名。
格式不对：300018.SZ,智能电网、医疗信息化及临床体外诊断相关产品及服务。:电力储能。
格式不对：600235.SH,卷烟纸、描图纸、电容器纸、格拉辛纸、真空喷铝原纸、热升华数码转印纸。:工业制造。
内容不在范围内：300019.SZ,有机硅室温胶和制胶专用设备的研发、生产和销售。:化工
格式不对：0331.HK,丰盛服务集团有限公司的主营业务包括机电工程服务、环境工程服务、建材贸易及零售，以及设施服务，包括清洁及洗衣服务。其中，机电工程服务包括空调及机械通风系统、消防系统、给排水系统、电气及超低压系统等。:工业制造。
格式不对：300020.SZ,城市交通智能化、医疗信息化和建筑智能化三类产品/业务。其中包括“银江视频监控存储与管理系统”、“基于UNIX平台的视频监控与管理系统”、“BRT嵌入式优先控制系统”、“面向BRT的嵌入式优先信号控制器”、“BRT嵌入式优先信号控制系统”等。:工业制造【注：该题目中的产品/业务涉及城市交通、医疗和建筑等多个领域，但题目要求要从给定的板块列表中选择与其最接近的一个板块，因此选择了工业制造板块作为最接近的板块】。
内容不在范围内：300021.SZ,大禹节水的主营业务是解决农业、农村和水资源问题，包括全产业链业务、研究、资本、设计、工程、制造、智慧水务和环保等领域。:水务
内容不在范围内：0336.HK,香精香料、烟草薄片、烟草新材料以及新型烟草制品的研发、生产和销售。:烟草
格式不对：0337.HK,无法确定公司的主营产品或业务。:如果无法确定公司的主营产品或业务，那么无法确定该公司所属的产业分类class，因此无法选择与其最接近的板块名。建议再进行深入了解该公司的业务和产品，或者重新选择其他可以确定产业分类的公司进行研究。
内容不在范围内：0339.HK,投资及买卖上市及非上市证券。:证券投资
格式不对：000519.SZ,大口径炮弹、火箭弹、导弹、子弹药、超硬材料、飞机零部件、反恐防暴产品、非金属材料及其制品、专用汽车、汽车配件。:工业制造。
200
内容不在范围内：688056.SH,实验分析仪器，包括全自动多功能高通量热裂解仪器、全自动高通量固相萃取系列仪器、全自动和高通量压力萃取系列仪器、全自动和高通量凝胶净化仪器、全自动高通量多功能组合仪器系列、全自动和高通量样品消解仪器系列、全自动和高通量浓缩产品系列、全自动紫外可见分光光谱仪系列、全自动液相色谱仪系列、全自动核素分离仪器系列、放射性元素富集系列、循环水冷却设备、制冷加热循环器(RH40-25A)、微控数显电热板(EG系列)等。:实验分析仪器属于实验设备，涵盖的应用范围较广
内容不在范围内：0343.HK,漫画出版和动漫版权授权，以及文化科技业务。:文化科技业务
内容不在范围内：600249.SH,两面针中药牙膏、个人及家居护理用品、植物药、纸制品等产品。:纸制品
格式不对：688057.SH,FMBR污水处理新工艺和JDL重金属废水处理新工艺:FMBR污水处理新工艺和JDL重金属废水处理新工艺的所属产业分类class未提供，无法选择最接近的板块名。
格式不对：0345.HK,维他奶集团的主营产品包括大豆营养饮料、豆腐产品、茶类、果汁、健怡饮品、蒸馏水、牛奶类饮料、豆类产品、甜品、意大利粉及面食等。:工业制造。
200
内容不在范围内：688058.SH,公司的主营产品包括应用服务器BES Application Server、消息中间件BESMQ、交易中间件BES VBroker、云管理平台BES CloudLink Ops、容器管理平台BES CloudLink CMP、应用性能管理软件BES WebGate等多款产品。:
200
内容不在范围内：300030.SZ,真空采血系统、医学实验室诊断、医疗信息化建设、临床实验室标本解决方案、临床实验室诊断、影像学诊断、临床护理与麻醉、健康管理、医院数字化整体解决方案。:医学实验室诊断、临床实验室标本解决方案、临床实验室诊断、影像学诊断、临床护理与麻醉、健康管理、医院数字化整体解决方案
格式不对：600255.SH,公司的主营产品为铜及铜合金带材、线材、辐照交联电缆、特种电缆等产品，以及影视制作和发行、版权开发与转让、影视投资、衍生品销售及再授权业务等。其中，铜加工板块的主要产品有高精度铜带材、铜合金线材、光亮铜杆、电线电缆等。影视板块的主要产品有电影、电视剧等。:工业制造
内容不在范围内：600257.SH,水产品、体育文化产业、大湖泊水环境治理、渔光一体化、湖面生态旅游、体育赛事、产业链金融、酒业、医药贸易、食品加工。:水产品
内容不在范围内：300035.SZ,电磁冶金专用设备、工业磁力设备、锂电专用设备。:工业磁力设备
内容不在范围内：600259.SH,稀土和钨业:矿业采掘
内容不在范围内：000532.SZ,华金创新投资、华金资产管理、华冠科技、华冠电容器、力合环保等实体产业。在创投方面，重点布局互联网、生物医药、高端制造、新能源、节能环保、文化传媒等领域，已成功投资博纳影业、优必选、和力辰光等众多优质项目。:文化传媒
格式不对：688068.SH,体外诊断试剂及仪器。肝脏疾病、心脑血管类疾病以及感染炎症类疾病检测三大系列试剂产品。肝癌早诊三联检产品，包括甲胎蛋白异质体(AFP-L3%)、异常凝血酶原(DCP)，以及高尔基体蛋白73(GP73)化学发光检测产品。:医药。
内容不在范围内：688069.SH,蓝藻治理业务:水处理
内容不在范围内：300041.SZ,胶粘剂和新材料:化工
格式不对：600265.SH,林化产品、人造板、集装箱地板、松节油精馏。:工业制造。
格式不对：0362.HK,热能及电力、碳化钙和石灰粉。:根据提供的信息无法确定该产品所属的产业分类，无法选择最接近的板块名。建议提供更详细的产品信息和背景资料。
内容不在范围内：300043.SZ,游戏业务、玩具业务、足球俱乐部业务。在游戏业务方面，包括移动游戏、网页游戏、H5游戏的研发、发行和运营。在玩具业务方面，主要专注于动态车模、静态车模、收藏型车模和电动童车、儿童自行车等重点婴童产品的生产、研发及销售。:玩具业务
内容不在范围内：300044.SZ,智慧城市、大数据、人工智能、文化教育。具体产品包括智慧交通、智慧建筑、智慧医疗、智慧教育、大数据运营服务、服务机器人、四足机器人、巡检机器人、无人机、无人机平台、人脸识别和智能视频分析。:智慧城市
内容不在范围内：0366.HK,水泥制造和销售，物业投资和发展，中成药产品制造和销售，电子产品销售，夹板和其他木制产品制造和销售。:建筑材料
内容不在范围内：000544.SZ,公司的主营业务包括供水、污水处理、污泥处置、中水利用、集中供热、固废处置、环保设备制造、新能源利用、市政建设、园林绿化及水环境综合治理等方面。:环保设备制造
内容不在范围内：688077.SH,烧结钕铁硼永磁材料的研发、生产和销售。:钕铁硼磁体
格式不对：688078.SH,龙软专业地理信息系统、LongRuan GIS、LongRuan GIS“一张图”、LongRuan安全云服务三大基础技术平台及在其基础上开发的系列专业应用软件。:工业制造。
格式不对：688081.SH,视频指挥控制系统、视频预警控制系统、编码设备、解码设备、服务设备、终端设备等。:工业制造
格式不对：0372.HK,该公司主营业务包括提供融资、物业投资和库务投资。没有明确提到主营产品。:根据所提供的信息，无法确定该公司所属的产业分类。无法选择最接近的板块名。
200
内容不在范围内：0376.HK,瑞东集团有限公司的主营业务包括证券经纪、证券包销及配售、顾问及咨询服务，以及瑞东金融市场有限公司提供的全面金融服务，包括机构证券交易/买卖、高净值和零售交易服务、投资咨询、企业融资顾问、重组和资产管理服务。此外，公司还进行长期保险业务的核保。:class：证券
内容不在范围内：0377.HK,彩色包装产品、瓦通盒、图书、小册子及各项纸制品:纸制品
格式不对：600287.SH,公司主营产品或业务：进出口贸易、国内贸易、服装生产、化工仓储、股权投资。:工业制造。
内容不在范围内：688089.SH,多不饱和脂肪酸ARA、藻油DHA及SA、发酵来源β-胡萝卜素等多个生物合成营养素产品的研发、生产与销售。:生物技术
内容不在范围内：000564.SZ,百货零售业、航空货运、城乡实体经销网、城乡电子商务网、城乡物流配送网、中国集、酷铺商贸、掌合天下、大集供销链、大集金服、民生百货。:百货零售业
内容不在范围内：300056.SZ,公司的主营产品或业务包括袋式除尘器核心部件高性能高温滤料、烟气脱硝核心部件、环保行业烟气综合治理BOT、BT业务、清洁能源投资运营与散物料输储系统、大供应链贸易金融平台等。:环保
内容不在范围内：688091.SH,紫杉醇胶束:生物医药
内容不在范围内：688095.SH,PDF电子文档核心技术与应用服务。:电子出版
格式不对：000566.SZ,海南海药股份有限公司的主营产品包括枫蓼肠胃康颗粒、特素(紫杉醇注射液)、注射用头孢西丁钠、头孢唑肟钠、美罗培南、氨曲南、头孢克洛等抗生素系列、注射用维生素C等。:医药。
内容不在范围内：600293.SH,浮法玻璃、玻璃深加工制品、新型建材产品、移动互联网终端业务。:新型建材产品
内容不在范围内：600298.SH,面包酵母、酿酒酵母、酵母抽提物、营养健康产品、生物饲料添加剂等。:生物技术
内容不在范围内：300066.SZ,智能水表、物联网水表、水务管理应用系统、水务投资运营、供水企业产销差与DMA分区管理、健康饮水服务、智慧水务数据云平台建设。:水务投资运营
内容不在范围内：300067.SZ,纺织用染料和助剂:化学原料
内容不在范围内：688101.SH,先进膜材料及设备的研发、生产和销售，以及提供膜应用综合解决方案。:化工
格式不对：000582.SZ,集装箱业务、散杂货业务。:工业制造。
内容不在范围内：600303.SH,黄海汽车、曙光车桥、黄海客车、黄海乘用车、黄海特种车、曙光零部件。:曙光车桥、曙光零部件
格式不对：600306.SH,百货业经营、超市、餐饮、酒店、滑冰场、物流配送。:从提供的信息中无法确定所属产业分类class，请提供更多信息。
内容不在范围内：300070.SZ,膜设备制造、膜工艺应用、市政污水和工业废水处理、自来水处理、海水淡化、民用净水、湿地保护与重建、海绵城市建设、河流综合治理、黑臭水体治理、市政景观建设、城市光环境设计建设、固废危废处理、生态农业和循环经济等全业务链的高科技环保企业。同时生产和销售家用及商用净水器产品。:自来水处理
内容不在范围内：688108.SH,冠状动脉支架系统和球囊扩张导管，其中主打产品为生物降解药物涂层冠脉支架BuMA和Neuro RX颅内球囊导管。:生物医药
内容不在范围内：0403.HK,纸品包装、儿童书籍、特殊印刷:纸品包装
内容不在范围内：000591.SZ,太阳能光伏电站投资运营和太阳能电池组件生产销售。:class: 光伏
内容不在范围内：688114.SH,基因测序仪业务和实验室自动化业务:基因测序仪业务
格式不对：000592.SZ,中高密度纤维板、烟草化肥:这两个产品都没有提供足够的信息来确定其所属的产业分类class，无法选择最接近的板块名。建议提供更详细的产品信息。
格式不对：0411.HK,南顺集团的主营产品或业务包括食油、食米、干椰、油脂加工处理、铝罐制造、易开盖制造等。:工业制造。
内容不在范围内：300081.SZ,公司的主营业务包括CG/VR内容生产、儿童产业链开发运营、LBE城市新娱乐、互联网视频应用产品及服务、移动信息产品的销售与服务业务。:class
内容不在范围内：600319.SH,氯化聚乙烯(CPE)、离子膜烧碱、水合肼、ADC发泡剂等产品:注：氯化聚乙烯(CPE)和离子膜烧碱属于石油化工领域，水合肼和ADC发泡剂涉及的产业比较广泛，但也与石油化工有关联。
格式不对：000599.SZ,轮胎业务、智能装备业务、工业智能物流业务。:工业制造。
内容不在范围内：000603.SZ,含银铅精粉、锌精粉、含银铅精矿、锌精矿。:矿产
内容不在范围内：600323.SH,公司的主营业务包括自来水供应、污水处理和固废处理。:环保
格式不对：0422.HK,速克达和国民车。:抱歉，未提供产品所属的产业分类class，无法回答与该class最接近的板块名。
格式不对：688123.SH,EEPROM、音圈马达驱动芯片和智能卡芯片。:半导体
内容不在范围内：000605.SZ,公司主营产品/业务：水务类业务，包括原水开发供应、区域间调水、粗质水、自来水生产及输送、优质地下水高附加值经营、直饮水、海水淡化利用、水环境治理、河道水资源化、城镇集中式供水、水务新技术研发应用、水务基础设施投资建设及运营管理等。其中污水处理业务主要分布在天津、河北和广西等地。:水务
格式不对：600327.SH,主营产品/业务：百货零售、汽车销售与服务、食品与餐饮。:该公司属于【食品饮料】板块。
内容不在范围内：0426.HK,万华媒体集团的主营业务是出版媒体，旗下产品包括《明报周刊》、《MING明日风尚》、《TopGear汽车测试报告》和《Popular Science科技新时代》等杂志。:传媒
格式不对：300097.SZ,成套自动化装备方案解决。:从给出的信息无法确定具体的产业分类，建议提供更为精确的分类信息。
内容不在范围内：600338.SH,矿产资源勘探、开采、矿石加工、金属冶炼、矿产品贸易、矿产资源及相关产业投资运作。其中，塔中矿业有限公司主要从事多金属矿山资源开采。:矿产资源
格式不对：000622.SZ,制冷空调设备、汽车、机械设备、房地产经营、物业管理、实业投资。:工业制造。
200
格式不对：688151.SH,个体防护装备、集体防护装备。:个体防护装备属于工业制造板块，集体防护装备则属于石油化工板块。
内容不在范围内：0444.HK,华贵品牌手表、时计及配件之分销业务:钟表配件
格式不对：0450.HK,彩盒和瓦通纸箱的印刷及制造，纸张生产制造。:工业制造。
格式不对：688152.SH,公司的主营产品包括信息安全产品和云计算产品。其中，信息安全产品以数据安全存储为主，包括操作系统技术、密码服务、存取控制技术等，已成为新一代基础安全设施；云计算产品以云桌面及轻量级云平台为主，包括桌面虚拟化和服务器虚拟化技术，可提供全栈国产自主“云+端”解决方案。:该公司主营产品属于互联网云计算板块。
内容不在范围内：300107.SZ,主营苯系中间体产品的生产，包括染料中间体、纤维中间体和医药中间体产品。同时也生产新型功能性染料及其配套产品。:化学制品
格式不对：000628.SZ,该公司的主营业务不明确，包括建筑施工、期货、厨柜制造等多元化业务。:无法确定产品所属的产业分类class，无法选出最接近的板块名。
内容不在范围内：000629.SZ,钒钛系列产品:矿业采选
格式不对：688155.SH,动力电池模组/电池包(PACK)、电动汽车动力总成(EDS)、动力电池测试和检测系统、燃料电池电堆/系统生产线、变速器、底盘系统智能制造装备。:钠离子电池。
格式不对：300109.SZ,PVP系列产品和精准医疗服务。:医药-->精准医疗
内容不在范围内：688156.SH,泥浆脱水固结一体化、有机糟渣微生物固态发酵等高含水废弃物处理技术及装备系统。:环保工程
格式不对：000635.SZ,电石、聚氯乙烯（PVC）、烧碱、特种树脂。:石油化工。
格式不对：0456.HK,写字楼和酒店物业的兴建和发展。:该题目未提供产业分类class，因此无法根据板块列表进行选择。以下为一般性的回答：

写字楼和酒店物业的兴建和发展，通常受到市场需求、土地资源和政策支持等因素的影响。在经济快速发展的城市，商务活动逐渐增多，办公需求逐渐增加，同时旅游和会展业也逐渐兴起，这些都会带动写字楼和酒店物业的兴建和发展。此外，政府也会通过相关政策和规划来引导和支持写字楼和酒店物业的发展，比如给予税收和用地方面的优惠政策等。值得注意的是，在兴建和发展过程中，还需要关注环保要求、消防安全要求等相关标准和要求，以确保建筑的质量和安全性。
内容不在范围内：300110.SZ,输液产品、血液净化产品、医疗器械、配套医药包材、大健康产品及原料药。其中现有输液产品86个品种191个品规，涵盖非PVC双管双阀、单管单阀、单管双阀、直立式软袋、塑瓶及玻瓶全部包材类别，覆盖从50ml到4000ml的全部规格。公司推出的腹膜透析液是国内首家批量上市的非PVC包材产品。:原料药
内容不在范围内：600356.SH,卷烟纸、滤嘴棒成型纸、滤嘴棒接装原纸、铝箔衬纸、无碳复写原纸等。:烟草
格式不对：0471.HK,印刷线路板制造、移动多媒体技术及服务供应、移动电视多媒体服务。:从提供的信息中无法直接得知产品所属的产业分类class，需要更多信息。
格式不对：600365.SH,果露酒、葡萄酒、干酒、冰酒、甜酒、葡萄烈酒、白酒、红梅山葡萄酒、通化山葡萄酒、雅士樽山葡萄酒、天池山葡萄酒。:这些属于食品饮料板块。
内容不在范围内：000651.SZ,空调、高端装备、生活品类、通信设备、智能装备、模具。:智能装备
格式不对：688168.SH,ABT SPOS网络安全系统平台及相关技术服务。:工业制造。
格式不对：000652.SZ,垃圾焚烧发电、生态环保、区域开发、能源贸易、洁净材料、股权投资。:给出的行业分类涉及多个领域，无法精确匹配到一个板块，需要更具体的信息才能进行分类。建议提供更详细的产品信息、所在地等信息，以便更准确地进行分类。
300
内容不在范围内：600367.SH,电子磁性材料、橡胶塑料助剂、天然植物提取等系列多个品种，主要产品有碳酸钡、碳酸锶、电解二氧化锰、不溶性硫磺、硫脲、硫磺、硫酸钡、硝酸锶、氯化锶、万寿菊等。:电解二氧化锰、碳酸锶、碳酸钡、硬脂酸锶、硝酸锶、硫脲、硫磺、不溶性硫磺、氯化锶、硫酸钡等属于工业化学品，可归为工业制造板块；天然植物提取属于化妆品原料，可归为美妆板块中。
内容不在范围内：000657.SZ,钨产业集团的主营产品为钨及其相关产品，包括硬质合金、钨钢、钨粉等。同时，公司还涉及硬质合金切削刀具、精密微型钻头、刀具和高精密级进模具等产品。:钨业
内容不在范围内：600369.SH,证券经纪、证券投资咨询、证券承销与保荐、证券自营、证券资产管理、融资融券、证券投资基金代销、代销金融产品、股票期权做市。:证券业
格式不对：600370.SH,印染整理、PBT树脂、电、蒸气、瓶级聚酯切片、PTA:工业制造。
300
格式不对：300122.SZ,人用疫苗，包括AC群脑膜炎球菌(结合)b型流感嗜血杆菌(结合)联合疫苗(喜贝康)、b型流感嗜血杆菌结合疫苗(喜菲贝)、A、C、Y、W135群脑膜炎球菌多糖疫苗(盟威克)、注射用母牛分枝杆菌(微卡)、A群C群脑膜炎球菌多糖结合疫苗(盟纳康)等自主产品及统一销售默沙东授权的23价肺炎球菌多糖疫苗、甲型肝炎灭活疫苗(人二倍体细胞)、四价人乳头瘤病毒疫苗(酿酒酵母)、九价人乳头瘤病毒疫苗(酿酒酵母)、口服五价重配轮状病毒减毒活疫苗(Vero细胞)等所有进口疫苗。:医药
内容不在范围内：688179.SH,科研试剂制造和销售，实验耗材配套。主要品牌为“阿拉丁”和“芯硅谷”。涵盖高端化学、生命科学、分析色谱及材料科学四大领域。:化学
内容不在范围内：600373.SH,出版业务、贸易和供应链业务、物流和物联网技术应用、新媒体、在线教育、互联网游戏、数字出版、影视剧生产、艺术品经营、文化综合体和投融资。:文化综合体和投融资
内容不在范围内：300127.SZ,粘结钕铁硼磁体元件及部件:磁性材料
格式不对：0493.HK,无法确定公司的主营产品或业务。:如果无法确定公司的主营产品或业务，那么无法将其归类于特定的产业分类。建议查阅公司的官方网站、年报、新闻报道等信息，以了解其业务范围和市场定位，从而判断其所属的产业分类。
内容不在范围内：000673.SZ,电视剧、电影、综艺节目、影院运营、广告。:文化传媒
300
格式不对：300132.SZ,松节油深加工、合成樟脑及其中间产品的生产、方音化学品、中药次片、药用料、医5中间体的生产、研发和销售。:石油化工。
内容不在范围内：300133.SZ,华策影视的主营业务是电视剧、电影、综艺节目的制作和出品。:影视娱乐
格式不对：000677.SZ,粘胶纤维、帘帆布。:从提供的信息中无法确定产品所属的产业分类class，请提供更多相关信息或描述。
格式不对：0500.HK,航空及物流服务、广告代理服务、在线金融市场信息、物流、航空及风险管理服务、地面运输、海事服务、保安服务、探索支持服务、在线游戏。:陆运
格式不对：0503.HK,该公司的主营产品包括治疗风湿疾病的专科处方西药，其中核心产品为帕夫林。同时还涉及皮肤科、医学美容、诊断试剂、OTC(非处方药)、植物提取等领域。:医药。
格式不对：600382.SH,大宗商品贸易、实业投资、PPP模式项目合作、出租物业。:工业制造。
格式不对：0505.HK,高精度铜板带生产、销售，网页游戏研发和发行，IP运营，影视投资，新技术研发，融资并购等。:工业制造。
内容不在范围内：300137.SZ,环境监测仪器及相关服务。具体产品包括空气质量连续自动监测系统、水质连续自动监测系统、污水在线自动监测系统、烟气在线自动监测系统、酸雨自动监测系统等五大在线监测系统以及数字应急监测车等。:环保工程及服务
格式不对：000683.SZ,天然气化工、煤化工、天然碱化工、新能源化工、精细化工、物流业。具体产品或业务名未提及。:石油化工。
格式不对：0508.HK,餐饮业务、投资业务、证券买卖业务、融资租赁业务。:该问题无法明确给出一个产业分类class，因为该问题给出的业务类型涉及不同的产业。需要更具体的信息才能给出准确分类。
格式不对：000685.SZ,环保水务、固废处理、工程建设、市场运营、港口客运、金融服务与股权投资。:工业制造。

In [16]:
df.dropna(subset='gpt_prod').to_csv('E:\wangzhilin\QuantumGalaxy\server_openai\gptbackbone1.csv')

In [22]:
'1'=='1'

True

In [25]:
df[(df['gpt_backbone'].isnull()) | (df['gpt_backbone'] == '未找到分类')]

,name,briefing,gpt_prod,gpt_backbone
code,,,,
000010.SZ,美丽生态,公司是中国最早的上市公司之一，公司主营业务为园林绿化，主要从事园林绿化工程施工、园林景观设计...,园林绿化工程施工、园林景观设计、园林养护及绿化苗木种植。,未找到分类
000020.SZ,深华发A,公司是深圳证券交易所早期上市的公司之一，是全国外商投资双优企业。公司经营业务主要分为液晶显示...,液晶显示器整机业务、注塑件生产业务、保丽龙(轻型材料包装)生产业务、物业租赁业务。,None
000023.SZ,深天地A,公司是全国第一家以商品混凝土为主业的上市公司，主要业务涉及商品混凝土、房地产开发及物业管理等...,商品混凝土、预拌砂浆,未找到分类
000039.SZ,中集集团,公司是世界领先的物流装备和能源装备供应商，总部位于中国深圳。公司致力于在如下主要业务领域：集...,集装箱、道路运输车辆、能源化工及食品装备、海洋工程、物流服务、空港设备。,None
000040.SZ,东旭蓝天,公司是国内A股主板上市公司，主营业务包括新能源和生态环保。公司致力于成为国内领先的环保新能源...,智慧能源、生态综合治理、水环境修复及运营、土壤及矿山修复、危废/固废处理、新材料、安轩智能运...,None
...,...,...,...,...
WR.SHF,SHFE线材,上海期货交易所是依照有关法规设立的，履行有关法规规定的职能，按照其章程实行自律性管理的法人，...,上海期货交易所的主营业务是期货交易。,None
WXBF.HK,HKEX药明生物技术股期,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,香港交易所的主营业务为运营香港中央证券及衍生产品市场，提供交易、结算、存管、代理人和资讯服务。,未找到分类
YZCF.HK,兖州煤业股期,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,香港交易所的主营业务为运营香港中央证券及衍生产品市场，提供交易、结算、存管、代理人和资讯服务。,未找到分类
ZJMF.HK,紫金矿业集团股期,香港交易所是香港联合交易所有限公司、香港期货交易所有限公司和香港中央结算有限公司的控股公司。...,香港交易所的主营业务为运营香港中央证券及衍生产品市场，提供交易、结算、存管、代理人和资讯服务。,未找到分类
ZN.SHF,SHFE锌,上海期货交易所是依照有关法规设立的，履行有关法规规定的职能，按照其章程实行自律性管理的法人，...,上海期货交易所的主营业务是期货交易。,None

In [ ]:
df['name']=None
for code,r in df.iterrows():
    sql=f'select sec_name from ticker_brief where code="{code}"'
    name=mysql.read_query(sql)
    if name:
        df.loc[code,'name']=name[0][0]

In [ ]:
df.to_csv('E:\wangzhilin\QuantumGalaxy\server_openai\gptbackbone.csv')

In [ ]:
records[0].get('code',None)

In [ ]:
for r in records:
    code=r.get('code')
    prod=r.get('prod')
    backbone=r.get('backbone')
    sql=f'select briefing from ticker_brief where code="{code}"'
    brief=r=mysql.read_query(sql)
    if brief:
        breif=r[0][0]
    else:
        continue
    gpt_prod=prod_extraction(brief)

In [ ]:
code='300979.SZ'
sql=f'select briefing from ticker_brief where code="{code}"'
r=mysql.read_query(sql)

In [ ]:
r[0][0]

In [ ]:
cypher='match (c:Company)-[:produce]->(p:Product) where c.code ="603083.SH"  return c.code,collect(p.name) limit 2'
r=neo.read_query(cypher)
r