In [38]:
import pandas as pd

In [39]:
df=pd.read_csv('E:\wangzhilin\QuantumGalaxy\opt\zone\区域图_node.csv')
df.head()

  Unnamed: 0   name  code       x      y  external category cate_ch backbone
0   JrksTHPd  半导体设备   NaN  1075.0 -145.0       NaN  Product      产品      区域图
1   vnsljGF2     芯片   NaN   961.0  120.0       NaN  Product      产品      区域图
2   6fRrPCus     晶圆   NaN   961.0 -230.0       NaN  Product      产品      区域图
3   l5p8WcOp   功率芯片   NaN   501.0  340.0       NaN  Product      产品      区域图
4   QMRpIIbc  功率半导体   NaN   731.0  280.0       NaN  Product      产品      区域图

In [40]:
df[df.cate_ch=='产品']

,Unnamed: 0,name,code,x,y,external,category,cate_ch,backbone
0,JrksTHPd,半导体设备,NaN,1075.0,-145.00,NaN,Product,产品,区域图
1,vnsljGF2,芯片,NaN,961.0,120.00,NaN,Product,产品,区域图
2,6fRrPCus,晶圆,NaN,961.0,-230.00,NaN,Product,产品,区域图
3,l5p8WcOp,功率芯片,NaN,501.0,340.00,NaN,Product,产品,区域图
4,QMRpIIbc,功率半导体,NaN,731.0,280.00,NaN,Product,产品,区域图
...,...,...,...,...,...,...,...,...,...
278,Rqw7EtUT,干散货航运,NaN,-3203.0,92.88,NaN,Product,产品,区域图
279,ckcYyV7Z,集装箱航运,NaN,-3020.0,50.00,NaN,Product,产品,区域图
280,0aE0GBuA,成品油航运,NaN,-2944.0,-70.00,NaN,Product,产品,区域图
281,OOe6TbDa,滚装船航运,NaN,-3408.0,132.88,NaN,Product,产品,区域图
282,6Q3VHtJv,人造卫星,NaN,1372.5,810.00,NaN,Product,产品,区域图

In [41]:
df.shape

(291, 9)

In [42]:
names=df[df.cate_ch=='产品'].name.tolist()
names[:2]

['半导体设备', '芯片']

In [46]:
cypher=f'WITH {names} AS inputList \
UNWIND inputList AS item \
OPTIONAL MATCH (n) WHERE n.name = item \
WITH COLLECT(DISTINCT item) AS inputList, COLLECT(DISTINCT n.name) AS existingNames \
RETURN [name IN inputList WHERE not name   IN existingNames] AS ExistingNames'
#RETURN [name IN inputList WHERE NOT name IN existingNames] AS nonExistingNames'
cypher

"WITH ['半导体设备', '芯片', '晶圆', '功率芯片', '功率半导体', '芯片封装', '逻辑芯片', '模拟芯片', '种子', '农作物', '农业机械', '粮食作物', '化肥', '经济作物', '氮肥', '钾肥', '磷肥', '火箭', '飞机', '航空电子', '卫星导航', '航空器', '电网', '电力设备', '电', '热储能', '机械储能', '电化学储能', '储能站', '电站', '储能电池', '核电', '氢能发电', '水力发电', '火力发电', '水治理', '环保服务', '大气治理', '环境监测', '土壤修复', '固废治理', '噪音控制', '生活垃圾治理', '工业废弃物治理', '家禽', '饲料', '兽药', '猪', '家畜', '牛', '羊', '消费电子', '手机', '电脑', '消费电子外壳', '显示屏', '建筑机械', '房地产', '基础设施', '建筑材料', '住宅地产', '商业地产', '工程建设', '地产交易', '建筑装修', '地产融资', '通信基站', '地面基站', '太空基站', '通信服务', '智慧城市', '家电', '家居用品', '家居装饰', '家具', '其它家居用品', '床上用品', '稀土元素', '矿产', '有色金属', '矿山开采设备', '天然开采钻石', '天然石墨', '锂矿', '磷矿', '影视剧', '院线', '影视技术服务', '影视周边', '影视剧平台', '影视广告', '影视发行', '面料', '天然纤维', '家用纺织品', '纺织品', '其他纺织原材料', '服饰', '箱包等其他纺织品', '药物配方', 'CXO', '西药', '药物', '创新药', '中药', '医疗服务', '化学药', '生物药', '疫苗', '医疗器械', '医疗耗材', '医疗设备', '锂电池正极材料', '电池级碳酸锂', '锂离子电池', '动力锂电池', '储能锂电池', '锂电池负极材料', '锂电池电芯', '锂电池电解液', '消费锂电池', '小动力锂电池', '隔膜', '铝塑膜', '供应链服务', '线下消费零售', '购物中心', '餐饮服务', '线下零售店', '烟酒行', '零售商超', '货币资金服务', '银行信用', '存款准备金', '货币M2', '基础货币', '流通现金M0', '支付结算服务', '中间业务', '营业网点', '银行信息化建设', '存贷款业务', '风电场', '风机铸件', '风电整机', '风机叶片', '风电塔筒', '海缆', '风电变流器', '化工轻油', '芳烃', '烯烃', '合成树脂', '合成纤维', '合成橡胶', '塑料', '其它化工品', '列车', '公路基建', '陆运设施', '城轨基建', '高铁基建', '陆运服务', '物流', '铁路运输', '公路运输', '原油', '成品油', '天然气', '油气勘探', '油气开采', '旅游服务', '旅行团服务', '目的地服务', '住宿服务', '客运服务', '会展文旅', '体育赛事', '铁矿石', '钢材', '钢管材', '特殊合金', '钢板材', '钢型材', '生铁', '不锈钢', '云计算服务（算力产品）', '互联网数据中心(IDC)', '人工智能、生成式AI', '信息平台', '服务器', '通信设备', '数据中心配套设备', '内容', '数据', '软件解决方案', '工业执行设备', '工业通用部件', '工业机器人', '数控机床', '自动化控制系统', '建筑装修', '行业专用设备', '智能工厂', '工业互联网', '工业感知设备', '光伏组件', '光伏电池片', '光伏硅片', '硅料', '光伏胶膜', '钙钛矿电池片', '光伏系统', '光伏逆变器', '原煤', '煤矿', '动力煤', '炼焦煤', '焦炭', '煤化工', '广告媒体', '广告渠道', '出版物', '广告', '广告营销', '清洁类产品', '护肤品', '护肤乳液', '防晒剂', '化妆工具', '美妆产品', '医美设备', '保湿剂', '彩妆用品', '钠离子电池', '钠离子电池电芯', '储能钠离子电池', '电池生产设备', '钠离子电池电芯正极', '钠离子电池电解液', '钠离子电池电芯负极', '动力钠离子电池', '钠离子电池隔膜', '包装', '食品烟酒', '酒水', '生鲜食品', '冷冻食品', '饮料', '休闲零食', '乳制品', '香烟', '汽车底盘', '汽车车身', '汽车', '新能源汽车', '汽车热管理系统', '汽车附属系统', '动力电池', '素质教育', '教育', '出国教育', '早教服务', '职业培训', '考试服务', 'K12教育', '白银', '贵金属', '铂金', '黄金', '码头运营', '海运服务', '油气航运', '货船', '干散货航运', '集装箱航运', '成品油航运', '滚装船航运', '人造卫星'] AS inputList UNWIND inputList AS item OPTIONAL MATCH (n) WHERE n.name = item WITH COLLECT(DISTINCT item) AS inputList, COLLECT(DISTINCT n.name) AS existingNames RETURN [name IN inputList WHERE not name   IN existingNames] AS ExistingNames"

In [47]:
import sys

sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.neoapi import Neo4j
neo_uri = "neo4j+ssc://08ef0a79.databases.neo4j.io"
neo_user = "QG_Editor"
neo_password = "editor"
neo=Neo4j(neo_uri,neo_user,neo_password)

In [48]:
records=neo.read_query(cypher)
records

In [49]:
records[0].values()[0]

['逻辑芯片', '云计算服务（算力产品）', '互联网数据中心(IDC)']

## 把nova中所有公司，找到距离最近的主要产品，在atlas中连上