In [ ]:
import sys
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import MYSQL
from datetime import datetime,timedelta

In [ ]:
import  logging
def get_logger(name,level=None,file=None):
    logger=logging.getLogger(name)
    logger.setLevel(logging.INFO)
    
    ch=logging.StreamHandler()
    ch.setLevel(logging.INFO)
    formatter=logging.Formatter(fmt='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',datefmt='%m-%d %H:%M')
    ch.setFormatter(formatter)
    
    logger.addHandler(ch)
    if file:    
        fh=logging.FileHandler("E:/wangzhilin/QuantumGalaxy/logs/%s.log"%file,'a',encoding='utf-8')
        fh.setLevel(logging.INFO)
        fh.setFormatter(formatter)
        logger.addHandler(fh)
    return logger
logger=get_logger('logger')

In [ ]:

host='localhost'
user='Local_Editor'
password='QuantumGalaxy'
database='qgdbs'
mysql=MYSQL(host,user,password,database)

In [ ]:
code='LI.O'
pre_data=[{'start_date':'2021-07-09','target_date':'2022-03-31','xc':24,'pc':0.7,'xo':60,'po':0.3},
{'start_date':'2021-09-20','target_date':'2022-03-31','xc':19.8,'pc':0.6,'xo':40,'po':0.2},
    {'start_date':'2022-06-30','target_date':'2022-12-31','xc':44,'pc':0.7,'xo':94,'po':0.4},
    {'start_date':'2022-09-01','target_date':'2022-12-31','xc':44,'pc':0.6,'xo':90,'po':0.2},
]

In [ ]:
xo=60
po=0.3
xc=24
pc=0.7

In [ ]:
start_date='2021-07-09'
target_date='2022-03-31'
stock_start_date=datetime.strptime(start_date,'%Y-%m-%d')-timedelta(183)
stock_start_date=stock_start_date.strftime('%Y-%m-%d')
stock_target_date=datetime.strptime(target_date,'%Y-%m-%d')-timedelta(183)
stock_target_date=stock_target_date.strftime('%Y-%m-%d')

ev_data=mysql.read_query('select date,market_value from ticker_data where code="%s" and date<"%s" and date>="%s"'%(code,stock_target_date,stock_start_date))
ev_data=[ev for ev in ev_data]
stock_end_date=ev_data[-1][0]
ev_data

Xo = Math.log(issue.get("乐观认为利润(Xo)"))

Xc = Math.log(issue.get("保守认为利润(Xc)"))

Po = 1 - issue.get("乐观情景概率").round(2)

Pc = 1 - issue.get("保守情景概率").round(2)

no = (Po*10).round()-1

nc = (Pc*10).round()-1

ppf = [-1.282, -0.842, -0.524, -0.253, 0, 0.253, 0.524, 0.842, 1.282]

s = ((Xo-Xc)/(ppf[no]-ppf[nc])).round(2)

mu = ((Xo-ppf[no]*s+Xc-ppf[nc]*s)/2).round(2)

In [ ]:
import math
for data in pre_data:
    xo=math.log(data['xo'])
    xc=math.log(data['xc'])
    ppf = [-1.282, -0.842, -0.524, -0.253, 0, 0.253, 0.524, 0.842, 1.282]
    po=1-data['po']
    pc=1-data['pc']
    no=round(po*10-1,)
    
    nc=round(pc*10-1)
    #s=((xo-pc)/(ppf[no]-ppf[nc]))
    print(no,nc)

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [ ]:
pc=0.1
x=[]
#po<pc保守
for i in range(9):
    
    
    y = []
    for t in x:
        #y_1 = 1 / (1 + math.exp(-t))
        tmp=round((1-t)*10-1)
        #print(tmp)
        
        s=5/(ppf[tmp]-ppf[round((1-pc)*10-1)])
        
        y.append(s)
        #y.append(ppf[tmp])
        #y.append(y_1)
    plt.plot(x, y, label="sigma--po when pc=%s"%round(pc,1))
    #print('pc=%s'%pc)
    #print('po=%s'%x)
    x.append(pc)
    pc=round(pc+0.1,1)
    #print(xc)
plt.xlabel("po")
plt.ylabel("s")
#plt.ylim(, 1.3)
plt.legend()
plt.show()

In [ ]:
def calcu_norm(xc,pc,xo,po) :
    '''-> (s,mu)'''
    xc=np.log(xc)
    xo=np.log(xo)
    no=round((1-po)*10-1)
    nc=round((1-pc)*10-1)
    print(no,nc)
    s=(xo-xc)/(ppf[no]-ppf[nc])
    mu=((xo-ppf[no]*s+xc-ppf[nc]*s)/2)
    return(s,mu)

log(x) 是服从s,mu的正态分布

走廊近端：

中值为从起点想起60日的几何平均

上下为 (1+|-val)** 5|10* 中值

n值取法：

对走廊远端统一取查询时最新的远期n值

对走廊近端：

    最新预测取最新的近期n值
    
    对之前的多组预测，取下一组startdate的近期n值

C00001.QG-0004  中国n 中国n2 美国n 美国n2

In [ ]:
import scipy
import math

In [ ]:
def log_inter1(num:int,y0,y1):
    '''返回长度为num+2的插值列表。num:插值数量'''
    f=scipy.interpolate.interp1d(x=[0,num+1],y=[math.log(y0),math.log(y1)],kind='linear')
    res=f([x+1 for x in range(num)])

    res=[math.exp(r) for r in res]
    res.insert(0,y0)
    res.append(y1)
    return res
def geo_mean(data):
    return math.pow(np.prod(data),1.0/len(data))

# 静态数据准备

最新n值

688063.SH

8.25的波动率/ 60日几何平均

In [267]:

host='localhost'
user='Local_Editor'
password='QuantumGalaxy'
database='qgdbs'
mysql=MYSQL(host,user,password,database)

10-12 00:46 logger       INFO     using username Local_Editor
10-12 00:46 logger       INFO     accessed to database <qgdbs>

In [268]:
pre_data

[{'start_date': '2021-07-09',
  'target_date': '2022-03-31',
  'xc': 24,
  'pc': 0.7,
  'xo': 60,
  'po': 0.3},
 {'start_date': '2021-09-20',
  'target_date': '2022-03-31',
  'xc': 19.8,
  'pc': 0.6,
  'xo': 40,
  'po': 0.2},
 {'start_date': '2022-06-30',
  'target_date': '2022-12-31',
  'xc': 44,
  'pc': 0.7,
  'xo': 94,
  'po': 0.4},
 {'start_date': '2022-09-01',
  'target_date': '2022-12-31',
  'xc': 44,
  'pc': 0.6,
  'xo': 90,
  'po': 0.2}]

In [413]:

data=pre_data[3]
start_date,target_date=list(data.values())[:2]
xc,pc,xo,po=list(data.values())[-4:]
start_date=data['start_date']
target_date=data['target_date']
print(xc,xo)

44 90

In [414]:
import pandas as pd

stock_start_date=datetime.strptime(start_date,'%Y-%m-%d')-timedelta(183)
stock_start_date=stock_start_date.strftime('%Y-%m-%d')


ev_data=mysql.read_query('select date,market_value from ticker_data where code="%s" and date<="%s" and date>="%s"'%(code,target_date,stock_start_date))
ev_data=[ev for ev in ev_data]
stock_end_date=ev_data[-1][0]
ev_data

10-12 01:07 logger       INFO     got a cursor
10-12 01:07 logger       INFO     Accepted read sql query "select date,market_value from ticker_data where code="LI.O" and date<="2022-12-31" and date>="2022-03-02""

[(datetime.date(2022, 3, 2), 323.7632533529408),
 (datetime.date(2022, 3, 3), 310.597010437201),
 (datetime.date(2022, 3, 4), 277.21489539177526),
 (datetime.date(2022, 3, 7), 275.6732002284392),
 (datetime.date(2022, 3, 8), 254.685379424863),
 (datetime.date(2022, 3, 9), 259.6985318320048),
 (datetime.date(2022, 3, 10), 282.1384451929828),
 (datetime.date(2022, 3, 11), 276.17966987153784),
 (datetime.date(2022, 3, 14), 221.88954320931683),
 (datetime.date(2022, 3, 15), 182.3439325907301),
 (datetime.date(2022, 3, 16), 245.51733487911721),
 (datetime.date(2022, 3, 17), 266.91195929334066),
 (datetime.date(2022, 3, 18), 276.13991802650736),
 (datetime.date(2022, 3, 21), 276.6764531914319),
 (datetime.date(2022, 3, 22), 285.04263907073823),
 (datetime.date(2022, 3, 23), 282.12355618635144),
 (datetime.date(2022, 3, 24), 281.4848856243416),
 (datetime.date(2022, 3, 25), 270.6434287180658),
 (datetime.date(2022, 3, 28), 272.3042311587426),
 (datetime.date(2022, 3, 29), 278.37136496147383),
 (datetime.date(2022, 3, 30), 285.57826928117106),
 (datetime.date(2022, 3, 31), 277.890991928625),
 (datetime.date(2022, 4, 1), 270.5937370771945),
 (datetime.date(2022, 4, 4), 298.2860785909424),
 (datetime.date(2022, 4, 5), 298.2860785909424),
 (datetime.date(2022, 4, 6), 292.3536994808389),
 (datetime.date(2022, 4, 7), 286.2117412793343),
 (datetime.date(2022, 4, 8), 277.7770656499258),
 (datetime.date(2022, 4, 11), 255.1942704767602),
 (datetime.date(2022, 4, 12), 264.8693035409885),
 (datetime.date(2022, 4, 13), 262.11445397854743),
 (datetime.date(2022, 4, 14), 271.3922536029243),
 (datetime.date(2022, 4, 15), 271.3922536029243),
 (datetime.date(2022, 4, 18), 271.3922536029243),
 (datetime.date(2022, 4, 19), 265.47594109803384),
 (datetime.date(2022, 4, 20), 258.65406378803675),
 (datetime.date(2022, 4, 21), 247.28250290138982),
 (datetime.date(2022, 4, 22), 239.74837721450817),
 (datetime.date(2022, 4, 25), 219.55705534691452),
 (datetime.date(2022, 4, 26), 234.6638438812588),
 (datetime.date(2022, 4, 27), 233.91559928298324),
 (datetime.date(2022, 4, 28), 234.17541387180748),
 (datetime.date(2022, 4, 29), 254.70512609441516),
 (datetime.date(2022, 5, 2), 254.70512609441516),
 (datetime.date(2022, 5, 3), 240.22576492108922),
 (datetime.date(2022, 5, 4), 232.4595621099417),
 (datetime.date(2022, 5, 5), 237.022975261828),
 (datetime.date(2022, 5, 6), 223.8226953116196),
 (datetime.date(2022, 5, 9), 223.8226953116196),
 (datetime.date(2022, 5, 10), 209.0762940134539),
 (datetime.date(2022, 5, 11), 229.47149288139317),
 (datetime.date(2022, 5, 12), 213.02043516764633),
 (datetime.date(2022, 5, 13), 227.75692078230685),
 (datetime.date(2022, 5, 16), 224.20541128690678),
 (datetime.date(2022, 5, 17), 245.5197383281983),
 (datetime.date(2022, 5, 18), 247.24345248806588),
 (datetime.date(2022, 5, 19), 245.82399454002578),
 (datetime.date(2022, 5, 20), 255.61612498127408),
 (datetime.date(2022, 5, 23), 242.68995420187736),
 (datetime.date(2022, 5, 24), 236.32556381248193),
 (datetime.date(2022, 5, 25), 234.88196893371693),
 (datetime.date(2022, 5, 26), 232.76786830616376),
 (datetime.date(2022, 5, 27), 248.81755775378974),
 (datetime.date(2022, 5, 30), 252.77935302242142),
 (datetime.date(2022, 5, 31), 262.6695758600608),
 (datetime.date(2022, 6, 1), 265.9059936535665),
 (datetime.date(2022, 6, 2), 265.3488059880864),
 (datetime.date(2022, 6, 3), 265.3488059880864),
 (datetime.date(2022, 6, 6), 298.2886764231627),
 (datetime.date(2022, 6, 7), 298.859296241766),
 (datetime.date(2022, 6, 8), 310.93548325210503),
 (datetime.date(2022, 6, 9), 308.4913316384857),
 (datetime.date(2022, 6, 10), 322.9297897316399),
 (datetime.date(2022, 6, 13), 313.1570383498131),
 (datetime.date(2022, 6, 14), 324.46457528979795),
 (datetime.date(2022, 6, 15), 340.5173095760922),
 (datetime.date(2022, 6, 16), 325.2878999068918),
 (datetime.date(2022, 6, 17), 350.26198324803283),
 (datetime.date(2022, 6, 20), 367.099895119502),
 (datetime.date(2022, 6, 21), 361.30915878570954),
 (datetime.date(2022, 6, 22), 370.7797712003875),
 (datetime.date(2022, 6, 23), 405.7988799932502),
 (datetime.date(2022, 6, 24), 429.73997071745316),
 (datetime.date(2022, 6, 27), 416.86026967115487),
 (datetime.date(2022, 6, 28), 416.7782689051684),
 (datetime.date(2022, 6, 29), 379.9370927480825),
 (datetime.date(2022, 6, 30), 402.4643945972091),
 (datetime.date(2022, 7, 1), 402.4643945972091),
 (datetime.date(2022, 7, 4), 407.6518901339004),
 (datetime.date(2022, 7, 5), 397.5102426656175),
 (datetime.date(2022, 7, 6), 408.8189061640874),
 (datetime.date(2022, 7, 7), 403.2825590259051),
 (datetime.date(2022, 7, 8), 398.23603814366805),
 (datetime.date(2022, 7, 11), 382.1436904739016),
 (datetime.date(2022, 7, 12), 378.94296173214326),
 (datetime.date(2022, 7, 13), 386.726674024226),
 (datetime.date(2022, 7, 14), 397.0153267718495),
 (datetime.date(2022, 7, 15), 397.5224276926994),
 (datetime.date(2022, 7, 18), 401.99007530202255),
 (datetime.date(2022, 7, 19), 401.7263737481231),
 (datetime.date(2022, 7, 20), 373.03235142533305),
 (datetime.date(2022, 7, 21), 366.46606556800566),
 (datetime.date(2022, 7, 22), 372.82711762289017),
 (datetime.date(2022, 7, 25), 350.68272199977804),
 (datetime.date(2022, 7, 26), 360.95230375179153),
 (datetime.date(2022, 7, 27), 346.2130205054414),
 (datetime.date(2022, 7, 28), 342.5218511228129),
 (datetime.date(2022, 7, 29), 331.9671544869606),
 (datetime.date(2022, 8, 1), 353.0350431403205),
 (datetime.date(2022, 8, 2), 350.3916933409034),
 (datetime.date(2022, 8, 3), 348.2931787312105),
 (datetime.date(2022, 8, 4), 353.5808804588751),
 (datetime.date(2022, 8, 5), 349.87175087712365),
 (datetime.date(2022, 8, 8), 347.50066610524436),
 (datetime.date(2022, 8, 9), 336.7258676852082),
 (datetime.date(2022, 8, 10), 320.2663007887027),
 (datetime.date(2022, 8, 11), 330.18785278135647),
 (datetime.date(2022, 8, 12), 336.10859156723916),
 (datetime.date(2022, 8, 15), 331.73015547551915),
 (datetime.date(2022, 8, 16), 326.883623135856),
 (datetime.date(2022, 8, 17), 325.4608896629314),
 (datetime.date(2022, 8, 18), 317.5874466201412),
 (datetime.date(2022, 8, 19), 320.20707184744174),
 (datetime.date(2022, 8, 22), 315.6077706672677),
 (datetime.date(2022, 8, 23), 317.9944162114271),
 (datetime.date(2022, 8, 24), 300.9889088471207),
 (datetime.date(2022, 8, 25), 308.4745778199661),
 (datetime.date(2022, 8, 26), 314.55941330639456),
 (datetime.date(2022, 8, 29), 310.7931341431523),
 (datetime.date(2022, 8, 30), 306.8032669946947),
 (datetime.date(2022, 8, 31), 305.9487892507211),
 (datetime.date(2022, 9, 1), 295.08452647247105),
 (datetime.date(2022, 9, 2), 289.25010750118986),
 (datetime.date(2022, 9, 6), 279.3905288321805),
 (datetime.date(2022, 9, 7), 278.5731170862265),
 (datetime.date(2022, 9, 8), 270.35082512571074),
 (datetime.date(2022, 9, 9), 275.1364048740122),
 (datetime.date(2022, 9, 12), 275.1364048740122),
 (datetime.date(2022, 9, 16), 263.192300033108),
 (datetime.date(2022, 9, 19), 249.91335042763492),
 (datetime.date(2022, 9, 20), 264.52718341371383),
 (datetime.date(2022, 9, 21), 258.92748187218837),
 (datetime.date(2022, 9, 22), 248.56261906136547),
 (datetime.date(2022, 9, 23), 252.83307213897575),
 (datetime.date(2022, 9, 26), 263.4251811039811),
 (datetime.date(2022, 9, 27), 274.849536680223),
 (datetime.date(2022, 9, 28), 253.20832488526307),
 (datetime.date(2022, 9, 29), 250.81933781330213),
 (datetime.date(2022, 9, 30), 240.59133873361665),
 (datetime.date(2022, 10, 3), 239.6619019945795),
 (datetime.date(2022, 10, 4), 239.6619019945795),
 (datetime.date(2022, 10, 5), 254.0017831111527),
 (datetime.date(2022, 10, 6), 251.21347289404122),
 (datetime.date(2022, 10, 7), 214.16878000956055),
 (datetime.date(2022, 10, 10), 206.60197918997684)]

In [415]:
df=pd.DataFrame(data=ev_data,columns=['date','ev'])
df.set_index('date',inplace=True)

In [416]:
stock_data=mysql.read_query(f'select date,market_value from ticker_data where code="{code}" and date<="{start_date}" order by date desc limit 60')
vol=mysql.read_query(f'select vol from processed_data where code="{code}" and date<="{start_date}" order by date desc limit 1')
vol=vol[0][0]

10-12 01:07 logger       INFO     got a cursor
10-12 01:07 logger       INFO     Accepted read sql query "select date,market_value from ticker_data where code="LI.O" and date<="2022-09-01" order by date desc limit 60"
10-12 01:07 logger       INFO     got a cursor
10-12 01:07 logger       INFO     Accepted read sql query "select vol from processed_data where code="LI.O" and date<="2022-09-01" order by date desc limit 1"

In [417]:

stock_data=[float(p) for (d,p) in stock_data]
stock_data=geo_mean(stock_data)

factor=[(1-vol)**10,(1-vol)**5,1,(1+vol)**5,(1+vol)**10,]
start=np.outer(stock_data,factor)[0]
start

array([246.7281181 , 295.62629374, 354.21542636, 421.74614354,
       502.15150541])

In [418]:
stock_data

354.2154263645135

In [419]:
n=mysql.read_query('select value from customized_data where code="C00002.QG" order by date desc limit 1')[0][0]
n

10-12 01:07 logger       INFO     got a cursor
10-12 01:07 logger       INFO     Accepted read sql query "select value from customized_data where code="C00002.QG" order by date desc limit 1"

43.0196

In [420]:
s,mu=calcu_norm(xc,pc,xo,po,)
s,mu

7 3

(0.6535342798283141, 3.9495338067148245)

In [421]:
end=np.exp([mu-0.842*s,mu-0.5*s,mu,mu+0.5*s,mu+0.842*s])*n
end

array([1288.08740952, 1610.69733671, 2233.19736276, 3096.28031745,
       3871.764     ])

In [422]:
from datetime import datetime,timedelta

In [423]:
start_date=datetime.strptime(start_date,'%Y-%m-%d')
target_date=datetime.strptime(target_date,'%Y-%m-%d')

In [424]:
start_date,target_date

(datetime.datetime(2022, 9, 1, 0, 0), datetime.datetime(2022, 12, 31, 0, 0))

In [425]:
days=(target_date-start_date).days
interp_num=days-1
interp_num

120

In [426]:
day_list=[start_date+timedelta(i) for i in range(days+1)]
day_list=[datetime.date(d) for d in day_list]
day_list

[datetime.date(2022, 9, 1),
 datetime.date(2022, 9, 2),
 datetime.date(2022, 9, 3),
 datetime.date(2022, 9, 4),
 datetime.date(2022, 9, 5),
 datetime.date(2022, 9, 6),
 datetime.date(2022, 9, 7),
 datetime.date(2022, 9, 8),
 datetime.date(2022, 9, 9),
 datetime.date(2022, 9, 10),
 datetime.date(2022, 9, 11),
 datetime.date(2022, 9, 12),
 datetime.date(2022, 9, 13),
 datetime.date(2022, 9, 14),
 datetime.date(2022, 9, 15),
 datetime.date(2022, 9, 16),
 datetime.date(2022, 9, 17),
 datetime.date(2022, 9, 18),
 datetime.date(2022, 9, 19),
 datetime.date(2022, 9, 20),
 datetime.date(2022, 9, 21),
 datetime.date(2022, 9, 22),
 datetime.date(2022, 9, 23),
 datetime.date(2022, 9, 24),
 datetime.date(2022, 9, 25),
 datetime.date(2022, 9, 26),
 datetime.date(2022, 9, 27),
 datetime.date(2022, 9, 28),
 datetime.date(2022, 9, 29),
 datetime.date(2022, 9, 30),
 datetime.date(2022, 10, 1),
 datetime.date(2022, 10, 2),
 datetime.date(2022, 10, 3),
 datetime.date(2022, 10, 4),
 datetime.date(2022, 10, 5),
 datetime.date(2022, 10, 6),
 datetime.date(2022, 10, 7),
 datetime.date(2022, 10, 8),
 datetime.date(2022, 10, 9),
 datetime.date(2022, 10, 10),
 datetime.date(2022, 10, 11),
 datetime.date(2022, 10, 12),
 datetime.date(2022, 10, 13),
 datetime.date(2022, 10, 14),
 datetime.date(2022, 10, 15),
 datetime.date(2022, 10, 16),
 datetime.date(2022, 10, 17),
 datetime.date(2022, 10, 18),
 datetime.date(2022, 10, 19),
 datetime.date(2022, 10, 20),
 datetime.date(2022, 10, 21),
 datetime.date(2022, 10, 22),
 datetime.date(2022, 10, 23),
 datetime.date(2022, 10, 24),
 datetime.date(2022, 10, 25),
 datetime.date(2022, 10, 26),
 datetime.date(2022, 10, 27),
 datetime.date(2022, 10, 28),
 datetime.date(2022, 10, 29),
 datetime.date(2022, 10, 30),
 datetime.date(2022, 10, 31),
 datetime.date(2022, 11, 1),
 datetime.date(2022, 11, 2),
 datetime.date(2022, 11, 3),
 datetime.date(2022, 11, 4),
 datetime.date(2022, 11, 5),
 datetime.date(2022, 11, 6),
 datetime.date(2022, 11, 7),
 datetime.date(2022, 11, 8),
 datetime.date(2022, 11, 9),
 datetime.date(2022, 11, 10),
 datetime.date(2022, 11, 11),
 datetime.date(2022, 11, 12),
 datetime.date(2022, 11, 13),
 datetime.date(2022, 11, 14),
 datetime.date(2022, 11, 15),
 datetime.date(2022, 11, 16),
 datetime.date(2022, 11, 17),
 datetime.date(2022, 11, 18),
 datetime.date(2022, 11, 19),
 datetime.date(2022, 11, 20),
 datetime.date(2022, 11, 21),
 datetime.date(2022, 11, 22),
 datetime.date(2022, 11, 23),
 datetime.date(2022, 11, 24),
 datetime.date(2022, 11, 25),
 datetime.date(2022, 11, 26),
 datetime.date(2022, 11, 27),
 datetime.date(2022, 11, 28),
 datetime.date(2022, 11, 29),
 datetime.date(2022, 11, 30),
 datetime.date(2022, 12, 1),
 datetime.date(2022, 12, 2),
 datetime.date(2022, 12, 3),
 datetime.date(2022, 12, 4),
 datetime.date(2022, 12, 5),
 datetime.date(2022, 12, 6),
 datetime.date(2022, 12, 7),
 datetime.date(2022, 12, 8),
 datetime.date(2022, 12, 9),
 datetime.date(2022, 12, 10),
 datetime.date(2022, 12, 11),
 datetime.date(2022, 12, 12),
 datetime.date(2022, 12, 13),
 datetime.date(2022, 12, 14),
 datetime.date(2022, 12, 15),
 datetime.date(2022, 12, 16),
 datetime.date(2022, 12, 17),
 datetime.date(2022, 12, 18),
 datetime.date(2022, 12, 19),
 datetime.date(2022, 12, 20),
 datetime.date(2022, 12, 21),
 datetime.date(2022, 12, 22),
 datetime.date(2022, 12, 23),
 datetime.date(2022, 12, 24),
 datetime.date(2022, 12, 25),
 datetime.date(2022, 12, 26),
 datetime.date(2022, 12, 27),
 datetime.date(2022, 12, 28),
 datetime.date(2022, 12, 29),
 datetime.date(2022, 12, 30),
 datetime.date(2022, 12, 31)]

In [427]:
level0=log_inter1(interp_num,start[0],end[0])

level1=log_inter1(interp_num,start[1],end[1])

level2=log_inter1(interp_num,start[2],end[2])

level3=log_inter1(interp_num,start[3],end[3])

level4=log_inter1(interp_num,start[4],end[4])

In [428]:
level4=[level4[i]-level3[i] for i in range(len(level4))]
level3=[level3[i]-level2[i] for i in range(len(level4))]
level2=[level2[i]-level1[i] for i in range(len(level4))]
level1=[level1[i]-level0[i] for i in range(len(level4))]

In [429]:


level0=tuple(dict(zip(day_list,level0)).items())
level1=tuple(dict(zip(day_list,level1)).items())
level2=tuple(dict(zip(day_list,level2)).items())
level3=tuple(dict(zip(day_list,level3)).items())
level4=tuple(dict(zip(day_list,level4)).items())

In [430]:
down_pred_point=(level0[-1][0],level0[-1][1]+level1[-1][1])
pred_point=(level0[-1][0],level0[-1][1]+level1[-1][1]+level2[-1][1])
up_pred_point=(level0[-1][0],level0[-1][1]+level1[-1][1]+level2[-1][1]+level3[-1][1])
down_pred_point=np.round(down_pred_point[1],2)
pred_point=np.round(pred_point[1],2)

up_pred_point=np.round(up_pred_point[1],2)

In [431]:
down_pred_point

1610.7

In [432]:
df

                    ev
date
2022-03-02  323.763253
2022-03-03  310.597010
2022-03-04  277.214895
2022-03-07  275.673200
2022-03-08  254.685379
...                ...
2022-10-04  239.661902
2022-10-05  254.001783
2022-10-06  251.213473
2022-10-07  214.168780
2022-10-10  206.601979

[155 rows x 1 columns]

In [433]:
df['last_ev']=None
df['last_ev'][-1]=round(df['ev'][-1],2)
df

C:\Users\wangzhilin\AppData\Local\Temp\2\ipykernel_59968\3239692568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_ev'][-1]=round(df['ev'][-1],2)

                    ev last_ev
date
2022-03-02  323.763253    None
2022-03-03  310.597010    None
2022-03-04  277.214895    None
2022-03-07  275.673200    None
2022-03-08  254.685379    None
...                ...     ...
2022-10-04  239.661902    None
2022-10-05  254.001783    None
2022-10-06  251.213473    None
2022-10-07  214.168780    None
2022-10-10  206.601979   206.6

[155 rows x 2 columns]

In [397]:
df1=pd.DataFrame(level0,columns=['date','level0'])
df1.set_index('date',inplace=True)
df=pd.concat([df,df1],axis=1)
df1=pd.DataFrame(level1,columns=['date','level1'])
df1.set_index('date',inplace=True)
df=pd.concat([df,df1],axis=1)
df1=pd.DataFrame(level2,columns=['date','level2'])
df1.set_index('date',inplace=True)
df=pd.concat([df,df1],axis=1)
df1=pd.DataFrame(level3,columns=['date','level3'])
df1.set_index('date',inplace=True)
df=pd.concat([df,df1],axis=1)
df1=pd.DataFrame(level4,columns=['date','level4'])
df1.set_index('date',inplace=True)
df=pd.concat([df,df1],axis=1,sort=True)
df

,ev,last_ev,level0,level1,level2,level3,level4
date,,,,,,,
2022-03-02,323.763253,None,NaN,NaN,NaN,NaN,NaN
2022-03-03,310.597010,None,NaN,NaN,NaN,NaN,NaN
2022-03-04,277.214895,None,NaN,NaN,NaN,NaN,NaN
2022-03-07,275.673200,None,NaN,NaN,NaN,NaN,NaN
2022-03-08,254.685379,None,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2022-12-27,NaN,NaN,1219.603980,303.306612,578.408842,797.486509,720.156811
2022-12-28,NaN,NaN,1236.375694,308.022520,589.142007,813.421030,733.610636
2022-12-29,NaN,NaN,1253.378048,312.810968,600.066051,829.661451,747.313332
2022-12-30,NaN,NaN,1270.614215,317.673063,611.184273,846.213487,761.269464
2022-12-31,NaN,NaN,1288.087410,322.609927,622.500026,863.082955,775.483683

In [398]:
df

,ev,last_ev,level0,level1,level2,level3,level4
date,,,,,,,
2022-03-02,323.763253,None,NaN,NaN,NaN,NaN,NaN
2022-03-03,310.597010,None,NaN,NaN,NaN,NaN,NaN
2022-03-04,277.214895,None,NaN,NaN,NaN,NaN,NaN
2022-03-07,275.673200,None,NaN,NaN,NaN,NaN,NaN
2022-03-08,254.685379,None,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2022-12-27,NaN,NaN,1219.603980,303.306612,578.408842,797.486509,720.156811
2022-12-28,NaN,NaN,1236.375694,308.022520,589.142007,813.421030,733.610636
2022-12-29,NaN,NaN,1253.378048,312.810968,600.066051,829.661451,747.313332
2022-12-30,NaN,NaN,1270.614215,317.673063,611.184273,846.213487,761.269464
2022-12-31,NaN,NaN,1288.087410,322.609927,622.500026,863.082955,775.483683

In [399]:
df['down_pred_point']=None
df['pred_point']=None
df['up_pred_point']=None
df['down_pred_point'][-1]=np.round(df.iloc[-1,2]+df.iloc[-1,3],2)
df['pred_point'][-1]=np.round(df.iloc[-1,2]+df.iloc[-1,3]+df.iloc[-1,4],1)
df['up_pred_point'][-1]=np.round(df.iloc[-1,5]+df.iloc[-1,2]+df.iloc[-1,3]+df.iloc[-1,4],2)

C:\Users\wangzhilin\AppData\Local\Temp\2\ipykernel_59968\3707034510.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['down_pred_point'][-1]=np.round(df.iloc[-1,2]+df.iloc[-1,3],2)
C:\Users\wangzhilin\AppData\Local\Temp\2\ipykernel_59968\3707034510.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pred_point'][-1]=np.round(df.iloc[-1,2]+df.iloc[-1,3]+df.iloc[-1,4],1)
C:\Users\wangzhilin\AppData\Local\Temp\2\ipykernel_59968\3707034510.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['up_pred_point'][-1]=np.round(df.iloc[-1,5]+df.iloc[-1,2]+df.iloc[-1,3]+df.iloc[-1,4],2)

In [400]:
df

,ev,last_ev,level0,level1,level2,level3,level4,down_pred_point,pred_point,up_pred_point
date,,,,,,,,,,
2022-03-02,323.763253,None,NaN,NaN,NaN,NaN,NaN,None,None,None
2022-03-03,310.597010,None,NaN,NaN,NaN,NaN,NaN,None,None,None
2022-03-04,277.214895,None,NaN,NaN,NaN,NaN,NaN,None,None,None
2022-03-07,275.673200,None,NaN,NaN,NaN,NaN,NaN,None,None,None
2022-03-08,254.685379,None,NaN,NaN,NaN,NaN,NaN,None,None,None
...,...,...,...,...,...,...,...,...,...,...
2022-12-27,NaN,NaN,1219.603980,303.306612,578.408842,797.486509,720.156811,None,None,None
2022-12-28,NaN,NaN,1236.375694,308.022520,589.142007,813.421030,733.610636,None,None,None
2022-12-29,NaN,NaN,1253.378048,312.810968,600.066051,829.661451,747.313332,None,None,None
2022-12-30,NaN,NaN,1270.614215,317.673063,611.184273,846.213487,761.269464,None,None,None
2022-12-31,NaN,NaN,1288.087410,322.609927,622.500026,863.082955,775.483683,1610.7,2233.2,3096.28

In [401]:
df.index=df.index.astype('str',)
df=df.reset_index()

In [403]:
df1 = df.astype(object).replace(np.nan, 'None')

df1

,date,ev,last_ev,level0,level1,level2,level3,level4,down_pred_point,pred_point,up_pred_point
0,2022-03-02,323.763253,None,None,None,None,None,None,None,None,None
1,2022-03-03,310.59701,None,None,None,None,None,None,None,None,None
2,2022-03-04,277.214895,None,None,None,None,None,None,None,None,None
3,2022-03-07,275.6732,None,None,None,None,None,None,None,None,None
4,2022-03-08,254.685379,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
248,2022-12-27,None,None,1219.60398,303.306612,578.408842,797.486509,720.156811,None,None,None
249,2022-12-28,None,None,1236.375694,308.02252,589.142007,813.42103,733.610636,None,None,None
250,2022-12-29,None,None,1253.378048,312.810968,600.066051,829.661451,747.313332,None,None,None
251,2022-12-30,None,None,1270.614215,317.673063,611.184273,846.213487,761.269464,None,None,None
252,2022-12-31,None,None,1288.08741,322.609927,622.500026,863.082955,775.483683,1610.7,2233.2,3096.28

# dataset 装填

ev_data :从起始日向前183天到起始日
leveldata:从起始日到预测日
prd_point:预测日

padding到同一形状：从前183到起始日1

In [404]:
dataset4={}
dataset4['source']=[df1.columns.to_list()]
dataset4['source']
for i,r in df1.iterrows():

    row=r.to_list()
    dataset4['source'].append(row)
dataset4

{'source': [['date',
   'ev',
   'last_ev',
   'level0',
   'level1',
   'level2',
   'level3',
   'level4',
   'down_pred_point',
   'pred_point',
   'up_pred_point'],
  ['2022-03-02',
   323.7632533529408,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-03',
   310.597010437201,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-04',
   277.21489539177526,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-07',
   275.6732002284392,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-08',
   254.685379424863,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-09',
   259.6985318320048,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-10',
   282.1384451929828,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-11',
   276.17966987153784,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-14',
   221.88954320931683,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-15',
   182.3439325907301,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-16',
   245.51733487911721,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-17',
   266.91195929334066,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-18',
   276.13991802650736,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-21',
   276.6764531914319,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-22',
   285.04263907073823,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-23',
   282.12355618635144,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-24',
   281.4848856243416,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-25',
   270.6434287180658,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-28',
   272.3042311587426,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-29',
   278.37136496147383,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-30',
   285.57826928117106,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-03-31',
   277.890991928625,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-01',
   270.5937370771945,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-04',
   298.2860785909424,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-05',
   298.2860785909424,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-06',
   292.3536994808389,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-07',
   286.2117412793343,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-08',
   277.7770656499258,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-11',
   255.1942704767602,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-12',
   264.8693035409885,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-13',
   262.11445397854743,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-14',
   271.3922536029243,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-15',
   271.3922536029243,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-18',
   271.3922536029243,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-19',
   265.47594109803384,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-20',
   258.65406378803675,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-21',
   247.28250290138982,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-22',
   239.74837721450817,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-25',
   219.55705534691452,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-26',
   234.6638438812588,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-27',
   233.91559928298324,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-28',
   234.17541387180748,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-04-29',
   254.70512609441516,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-02',
   254.70512609441516,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-03',
   240.22576492108922,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-04',
   232.4595621099417,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-05',
   237.022975261828,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-06',
   223.8226953116196,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-09',
   223.8226953116196,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-10',
   209.0762940134539,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-11',
   229.47149288139317,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-12',
   213.02043516764633,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-13',
   227.75692078230685,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-16',
   224.20541128690678,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-17',
   245.5197383281983,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-18',
   247.24345248806588,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-19',
   245.82399454002578,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-20',
   255.61612498127408,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-23',
   242.68995420187736,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-24',
   236.32556381248193,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-25',
   234.88196893371693,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-26',
   232.76786830616376,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-27',
   248.81755775378974,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-30',
   252.77935302242142,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-05-31',
   262.6695758600608,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-01',
   265.9059936535665,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-02',
   265.3488059880864,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-03',
   265.3488059880864,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-06',
   298.2886764231627,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-07',
   298.859296241766,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-08',
   310.93548325210503,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-09',
   308.4913316384857,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-10',
   322.9297897316399,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-13',
   313.1570383498131,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-14',
   324.46457528979795,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-15',
   340.5173095760922,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-16',
   325.2878999068918,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-17',
   350.26198324803283,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-20',
   367.099895119502,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-21',
   361.30915878570954,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-22',
   370.7797712003875,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-23',
   405.7988799932502,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-24',
   429.73997071745316,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-27',
   416.86026967115487,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-28',
   416.7782689051684,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-29',
   379.9370927480825,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-06-30',
   402.4643945972091,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-01',
   402.4643945972091,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-04',
   407.6518901339004,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-05',
   397.5102426656175,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-06',
   408.8189061640874,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-07',
   403.2825590259051,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-08',
   398.23603814366805,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-11',
   382.1436904739016,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-12',
   378.94296173214326,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-13',
   386.726674024226,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-14',
   397.0153267718495,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-15',
   397.5224276926994,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-18',
   401.99007530202255,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-19',
   401.7263737481231,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-20',
   373.03235142533305,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-21',
   366.46606556800566,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-22',
   372.82711762289017,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-25',
   350.68272199977804,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-26',
   360.95230375179153,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-27',
   346.2130205054414,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-28',
   342.5218511228129,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-07-29',
   331.9671544869606,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-01',
   353.0350431403205,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-02',
   350.3916933409034,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-03',
   348.2931787312105,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-04',
   353.5808804588751,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-05',
   349.87175087712365,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-08',
   347.50066610524436,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-09',
   336.7258676852082,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-10',
   320.2663007887027,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-11',
   330.18785278135647,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-12',
   336.10859156723916,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-15',
   331.73015547551915,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-16',
   326.883623135856,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-17',
   325.4608896629314,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-18',
   317.5874466201412,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-19',
   320.20707184744174,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-22',
   315.6077706672677,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-23',
   317.9944162114271,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-24',
   300.9889088471207,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-25',
   308.4745778199661,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-26',
   314.55941330639456,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-29',
   310.7931341431523,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-30',
   306.8032669946947,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-08-31',
   305.9487892507211,
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None',
   'None'],
  ['2022-09-01',
   295.08452647247105,
   'None',
   246.72811810147834,
   48.89817563679725,
   58.58913262623793,
   67.53071717159429,
   80.4053618716161,
   'None',
   'None',
   'None'],
  ['2022-09-02',
   289.25010750118986,
   'None',
   250.1210664545806,
   49.67638869749254,
   59.8493680230236,
   69.10541712955529,
   81.94787979489809,
   'None',
   'None',
   'None'],
  ['2022-09-03',
   'None',
   'None',
   253.560673853338,
   50.46679602804781,
   61.134032957378395,
   70.71322034176819,
   83.51954301394125,
   'None',
   'None',
   'None'],
  ['2022-09-04',
   'None',
   'None',
   257.0475819422181,
   51.2695863792751,
   62.44357405977837,
   72.35478320224382,
   85.12089563195161,
   'None',
   'None',
   'None'],
  ['2022-09-05',
   'None',
   'None',
   260.58244118943645,
   52.08495139476213,
   63.77844582557532,
   74.03077464179233,
   86.75249181122706,
   'None',
   'None',
   'None'],
  ['2022-09-06',
   279.3905288321805,
   'None',
   264.1659110082977,
   52.91308565484832,
   65.13911074993251,
   75.74187636131944,
   88.41489595763096,
   'None',
   'None',
   'None'],
  ['2022-09-07',
   278.5731170862265,
   'None',
   267.798659880207,
   53.75418672125966,
   66.52603946503581,
   77.48878306938514,
   90.1086829084262,
   'None',
   'None',
   'None'],
  ['2022-09-08',
   270.35082512571074,
   'None',
   271.4813654793712,
   54.60845518242115,
   67.93971087961177,
   79.27220272409699,
   91.83443812352976,
   'None',
   'None',
   'None'],
  ['2022-09-09',
   275.1364048740122,
   'None',

In [405]:
dataset=[dataset1,dataset2,dataset3,dataset4]

In [ ]:
#dataset['source'].append(dataset1['source'])

In [ ]:
dataset1

In [ ]:
len(dataset1['source'])

In [ ]:
'''import json
#dataset 中source为对象数组，格式为【{series:'ev',date:'',ev:''}】
#evdata=[{'series':'ev','date':str(d),'ev':ev} for d,ev in ev_data]
#level0data=[{'series':'level0','date':str(d),'level0':ev} for d,ev in level0]
#level1data=[{'series':'level1','date':str(d),'level1':ev} for d,ev in level1]
#level2data=[{'series':'level2','date':str(d),'level2':ev} for d,ev in level2]
#level3data=[{'series':'level3','date':str(d),'level3':ev} for d,ev in level3]
#level4data=[{'series':'level4','date':str(d),'level4':ev} for d,ev in level4]
dataset={}

dataset['source']=[]

#dataset['source']+=evdata+level0data+level1data+level2data+level3data+level4data
dataset1={}
ev_data1=ev_data
pad=(len(level0)-len(ev_data))*[(None,None)]
ev_data1+=pad
dataset1['source']=[]
dataset1['source']=[['date','ev','level0','level1','level2','level3','level4']]
dataset1['source']+=[[str(level0[i][0]),ev_data1[i][1],level0[i][1],level1[i][1],level2[i][1],level3[i][1],level4[i][1]] for i in range(len(level0))]
dataset1'''
#dataset

In [406]:
import json
j=json.dumps(dataset)

In [407]:
j1=json.loads(j)

In [408]:
f = open(r'E:\wangzhilin\QuantumGalaxy\server\static\ev_band\example-li.o.json', 'w')
f.write(j)
f.close()

In [409]:
math.exp(mu)*n

2233.197362757718

In [410]:
f = open(r'E:\wangzhilin\QuantumGalaxy\server\static\ev_band\example-li.o.json', 'r')
content=f.read()
j=json.loads(content)
j

[{'source': [['date',
    'ev',
    'last_ev',
    'level0',
    'level1',
    'level2',
    'level3',
    'level4',
    'down_pred_point',
    'pred_point',
    'up_pred_point'],
   ['2021-01-07',
    317.43963398950007,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-08',
    310.29294516499994,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-11',
    296.6328184245,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-12',
    332.4567269625,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-13',
    321.60099710249995,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-14',
    313.91152178500005,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-15',
    294.91399453,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-18',
    294.91399453,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-19',
    320.605888532,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-20',
    322.05331918,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-21',
    319.97263762349996,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-22',
    311.559446982,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-25',
    289.3956651845,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-26',
    294.009350375,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-27',
    285.505695318,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-28',
    291.3858823255,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-01-29',
    291.7477399875,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-01',
    289.847987262,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-02',
    273.20253481,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-03',
    277.9971488315,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-04',
    278.992257402,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-05',
    275.01182312,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-08',
    274.649965458,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-09',
    288.3100921985,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-10',
    284.962908825,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-11',
    289.3956651845,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-12',
    288.1291633675,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-15',
    288.1291633675,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-16',
    275.01182312,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-17',
    269.041171697,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-18',
    266.327239232,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-19',
    269.945815852,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-22',
    251.85293275200002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-23',
    244.16345743449997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-24',
    259.451943654,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-25',
    234.03144289850002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-02-26',
    229.50822212350002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-01',
    233.94097848299998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-02',
    214.76252239699997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-03',
    205.9874740935,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-04',
    201.91657539599998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-05',
    203.183077213,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-08',
    192.96059826149997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-09',
    208.79187097399998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-10',
    211.143945777,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-11',
    235.38840913099997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-12',
    232.4030834195,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-15',
    234.302836145,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-16',
    233.76004965200002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-17',
    230.0510086165,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-18',
    226.70382524299998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-19',
    237.74048393400003,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-22',
    242.62556237099997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-23',
    238.55466367350002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-24',
    207.07304707950001,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-25',
    212.591376425,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-26',
    214.400664735,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-29',
    204.44957903,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-30',
    208.79187097399998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-03-31',
    226.16103875,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-01',
    228.4226491375,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-02',
    228.4226491375,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-05',
    225.618252257,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-06',
    230.9556527715,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-07',
    201.10239565650002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-08',
    210.14883720650002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-09',
    205.89700967800002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-12',
    197.031496959,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-13',
    197.393354621,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-14',
    190.879916705,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-15',
    178.03396970400001,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-16',
    174.41539308400002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-19',
    174.1439998375,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-20',
    173.329820098,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-21',
    178.93861385900001,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-22',
    181.290688662,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-23',
    186.35669593,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-26',
    188.25644865549998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-27',
    186.62808917649997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-28',
    182.376261648,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-29',
    176.8579323025,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-04-30',
    178.57675619699998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-03',
    175.862823732,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-04',
    175.68189490100002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-05',
    170.254029971,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-06',
    162.7454834845,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-07',
    165.188022703,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-10',
    153.87997076550002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-11',
    153.87997076550002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-12',
    160.84573075900002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-13',
    155.8701879065,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-14',
    166.00220244250002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-17',
    170.52542321750002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-18',
    175.59143048549998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-19',
    176.8579323025,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-20',
    183.37137021849998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-21',
    185.36158735949996,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-24',
    188.25644865549998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-25',
    180.83836658449997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-26',
    206.43979617099998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-27',
    213.9483426575,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-28',
    210.782088115,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-05-31',
    210.782088115,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-01',
    215.3957733055,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-02',
    220.190387327,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-03',
    225.79918108799998,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-04',
    231.95076134200002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-07',
    241.35906055400002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-08',
    257.5521909285,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-09',
    248.1438917165,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-10',
    244.25392185,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-11',
    254.2954719705,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-14',
    255.47150937199996,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-15',
    255.2001161255,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-16',
    256.91894002,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-17',
    279.354115064,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-18',
    272.3883550705,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-21',
    272.3883550705,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-22',
    261.7135540415,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-23',
    282.068047529,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-24',
    277.54482675400004,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-25',
    286.59126830400004,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-28',
    304.9555446505,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-29',
    309.8406230875,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-06-30',
    316.08266775699997,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-01',
    313.82105736949995,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-02',
    295.5472454385,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-05',
    295.5472454385,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-06',
    303.779507249,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-07',
    289.7575228465,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-08',
    287.5863768745,
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None',
    'None'],
   ['2021-07-09',
    287.857770121,
    'None',
    150.3295469563996,
    30.511952968627128,
    36.7048757360304,
    42.43664064410643,
    50.71473060853231,
    'None',
    'None',
    'None'],
   ['2021-07-10',
    'None',
    'None',
    151.2678218847455,
    30.780846532052834,
    37.15855200481869,
    43.01674008448015,
    51.29477178472371,
    'None',
    'None',
    'None'],
   ['2021-07-11',

In [411]:
len(j)

4