In [1]:
import pandas as pd
import sys
from jira import JIRA
jira=JIRA('https://research.quantumgalaxy.cn/', basic_auth=('bot2', "jira_bot2"))

In [2]:
def iter_jira_search(jql,maxResults=500,startAt=0):
    maxResults=maxResults
    startAt=startAt
    result=[]
    while True:
        result1=jira.search_issues(jql,maxResults=maxResults,startAt=startAt)
        
        if result1.current+len(result)>=result1.total:
            print('break')
            print('total issue:',len(result))
            break
        else:
            result+=result1
            print(len(result))
            #print(result1.total)
            #print(len(result)>=result1.total)
            
            startAt+=len(result1)
            #print(startAt)
    return result

In [73]:
issues=iter_jira_search('project = COMPSTUDY AND issuetype = 公司研究',maxResults=500)

500

In [1]:
issues

NameError: name 'issues' is not defined

In [36]:
target_jira.isLast

0

In [26]:
for issue in target_jira:
    if issue.fields.__dict__.get('customfield_11216'):
        if  (issue.fields.__dict__.get('customfield_10201')):
            print(issue.fields.summary)
            print(issue.fields.customfield_10201)

In [25]:
issue1.fields.summary

'奥特维'

In [20]:
issue.fields.__dict__.get('customfield_11216')

In [21]:
issue.fields.customfield_11216

In [3]:
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.neoapi import Neo4j
uri = "neo4j+ssc://534ea9b7.databases.neo4j.io:7687"
user = "neo4j"
password = "QuantumGalaxy"
neo=Neo4j(uri,user,password)
codes=neo.fetch_company_and_indicator_with_code()

In [4]:
import re
from tqdm import tqdm

In [10]:
code='002229.SZ'
issues=jira.search_issues(f'project = COMPSTUDY AND issuetype = 公司研究 AND 万得代码 ={code}')

In [11]:
issues

In [14]:
clue=issue.fields.__dict__.get('customfield_11216')
if clue:
    print(clue)

赛微电子7月16日公告，近日，公司控股子公司以MEMS工艺为某客户制造的系列BAW滤波器完成了小批量试生产阶段，开始进行BAW滤波器规模化量产。慈星股份参股武汉敏声，武汉敏声委托的塞微电子生产BAW滤波器（供应华为5G）。

In [4]:
with open('doc.txt','r') as r:
    doc=r.read()
items=doc.split('\n')

FileNotFoundError: [Errno 2] No such file or directory: 'doc.txt'

In [97]:
item=items[0]
item

'- 昊志机电300503.SZ(60.82亿元,+19.99%)：公司在空心杯电机，无框力矩电机，力传感器，谐波减速器方面均有产品，国内目前只有两家公司能做无框力矩电机，一家是步科股份，另一家为昊志机电；公司掌握六维力矩传感器技术，一个六维力矩传感器的价值量是2万元；减速器年产能为15万台。'

In [98]:
pattern = r'^(- )(.*?)\s*([A-Z0-9.]+)\s*\(([\d.]+[亿元万]*),([+-]?\d+\.\d+%)\)：(.*)$'
pattern=re.compile(r'^(- *)(.*?)\s*([A-Z0-9.]+)\s*\(([\d.]+[亿元万]*),([+-]?\d+\.\d+%)\)：(.*)$')
comps=[]
for item in items:
    matches = pattern.match(item)

    if matches:
        start = matches.group(1)
        name = matches.group(2)
        code = matches.group(3)
        market_value = matches.group(4)
        increase = matches.group(5)
        intro = matches.group(6)
        comps.append((name,code,intro))
    else:print(item)

In [99]:
comps[-1]

('苏常柴Ａ',
 '000570.SZ',
 '公司6月28日公告称，已收到常州市钟楼区给予的征收子公司房屋补偿款7000万元，该笔收入将计入中报。以此预计，苏常柴A中报业绩或仍有望翻倍。')

In [106]:
issue_list=[]

with tqdm(comps,desc='here') as t:
    for name, code, intro in t:
        
        get_issue=jira.search_issues(f'project = COMPSTUDY AND 万得代码 ={code}')
        if get_issue:
            issue=get_issue[0]
            try:
                issue.update(description='',customfield_11216=intro)
            except:print('error on :',name,code)
            #zhencha:customfield_11216
            #print('update exist issue:',name)
            t.set_postfix({'result':'update exist issue:'+name})
        else:
            issue_list.append({'project': {'id': 10000},
                               'issuetype':{'id':10100},
        'summary': name,
        'description': intro,
        'customfield_10201':code})
            issue=jira.create_issue(project='10000',issuetype='公司研究',summary=name,customfield_10201=code)
            issue.update(description=intro)
            #print('noissue:',name)

            t.set_postfix({'result':'noissue:'+name})

here:   5%|▍         | 14/296 [00:11<03:28,  1.36it/s, result=update exist issue:宝明科技]

error on : 宝明科技 002992.SZ

here:   5%|▌         | 15/296 [00:12<03:11,  1.47it/s, result=update exist issue:东尼电子]

error on : 东尼电子 603595.SH

here:  24%|██▎       | 70/296 [01:55<05:14,  1.39s/it, result=update exist issue:宝明科技]

error on : 宝明科技 002992.SZ

here:  27%|██▋       | 80/296 [02:09<04:24,  1.23s/it, result=update exist issue:中国软件]

error on : 中国软件 600536.SH

here:  35%|███▌      | 105/296 [02:46<03:30,  1.10s/it, result=update exist issue:聚辰股份]

error on : 聚辰股份 688123.SH

here:  49%|████▊     | 144/296 [03:50<03:59,  1.57s/it, result=update exist issue:荣昌生物]

error on : 荣昌生物 688331.SH

here:  51%|█████     | 151/296 [03:57<02:23,  1.01it/s, result=update exist issue:亚康股份]

error on : 亚康股份 301085.SZ

here:  56%|█████▋    | 167/296 [04:27<03:22,  1.57s/it, result=update exist issue:天娱数科]

error on : 天娱数科 002354.SZ

here:  63%|██████▎   | 186/296 [04:53<01:48,  1.02it/s, result=update exist issue:东方钽业]]

error on : 东方钽业 000962.SZ

here:  64%|██████▍   | 189/296 [04:56<01:45,  1.02it/s, result=update exist issue:中国稀土]

error on : 中国稀土 000831.SZ

here:  95%|█████████▍| 280/296 [06:55<00:16,  1.00s/it, result=update exist issue:铖昌科技]

error on : 铖昌科技 001270.SZ

here:  96%|█████████▌| 284/296 [07:00<00:14,  1.17s/it, result=update exist issue:横店影视]

error on : 横店影视 603103.SH

here: 100%|██████████| 296/296 [07:30<00:00,  1.52s/it, result=update exist issue:苏常柴Ａ]

In [101]:
jira._fields

{'cf[11441]': 'customfield_11441',
 'X值走廊参数': 'customfield_11441',
 'fixVersion': 'fixVersions',
 'cf[11440]': 'customfield_11440',
 '发生地域': 'customfield_11440',
 'cf[11443]': 'customfield_11443',
 '研究经验值': 'customfield_11443',
 'cf[11200]': 'customfield_11200',
 '组内停留时间': 'customfield_11200',
 'resolution': 'resolution',
 'cf[11442]': 'customfield_11442',
 '拟分配人员': 'customfield_11442',
 'cf[11201]': 'customfield_11201',
 '整体报告地址-废弃': 'customfield_11201',
 'cf[11720]': 'customfield_11720',
 '持仓价值': 'customfield_11720',
 'cf[11202]': 'customfield_11202',
 '资料包地址': 'customfield_11202',
 'cf[11203]': 'customfield_11203',
 '紧迫性等级': 'customfield_11203',
 'cf[11711]': 'customfield_11711',
 'QG_Code': 'customfield_11711',
 'cf[10621]': 'customfield_10621',
 '自动更新的近期市值均值': 'customfield_10621',
 'cf[10104]': 'customfield_10104',
 'Sprint': 'customfield_10104',
 'cf[11436]': 'customfield_11436',
 '推荐理由': 'customfield_11436',
 'cf[11710]': 'customfield_11710',
 'C指标操作台': 'customfield_11710',
 'cf[10622]': 'customfield_10622',
 '未来情景日': 'customfield_10622',
 'cf[10105]': 'customfield_10105',
 '等级': 'customfield_10105',
 'cf[11713]': 'customfield_11713',
 'E指标值': 'customfield_11901',
 'cf[10623]': 'customfield_10623',
 '预测目标日乐观市值': 'customfield_10623',
 'cf[10106]': 'customfield_10106',
 'Story Point': 'customfield_10106',
 'cf[11438]': 'customfield_11438',
 '全情景年化收益倍数': 'customfield_11438',
 'cf[11712]': 'customfield_11712',
 'T指标值': 'customfield_11712',
 'cf[10900]': 'customfield_10900',
 '已标记': 'customfield_10900',
 'cf[10626]': 'customfield_10626',
 '最新预测': 'customfield_10626',
 'cf[11439]': 'customfield_11439',
 '可参会时间': 'customfield_11439',
 'cf[11716]': 'customfield_11716',
 '参会场次': 'customfield_11716',
 'cf[10903]': 'customfield_10903',
 '所在层级': 'customfield_10903',
 'cf[10508]': 'customfield_10508',
 '所在市场': 'customfield_10508',
 'cf[10629]': 'customfield_10629',
 '缓存域': 'customfield_10629',
 'cf[10904]': 'customfield_10904',
 '特选层日期-废弃': 'customfield_10904',
 'cf[10509]': 'customfield_10509',
 '纳入普通层时间': 'customfield_10509',
 'cf[10905]': 'customfield_10905',
 '缓存文本': 'customfield_10905',
 'lastViewed': 'lastViewed',
 'cf[12000]': 'customfield_12000',
 '指标操作台': 'customfield_12000',
 'cf[12002]': 'customfield_12002',
 '被反映': 'customfield_12002',
 'cf[12001]': 'customfield_12001',
 '反映': 'customfield_12001',
 'priority': 'priority',
 'cf[10100]': 'customfield_10100',
 '史诗链接': 'customfield_10100',
 'cf[10101]': 'customfield_10101',
 'Epic状态': 'customfield_10101',
 'cf[11431]': 'customfield_11431',
 '指标单位': 'customfield_11431',
 'cf[10102]': 'customfield_10102',
 '史诗名称': 'customfield_10102',
 'cf[10620]': 'customfield_10620',
 '预测基准日': 'customfield_10620',
 'cf[10103]': 'customfield_10103',
 'Epic颜色': 'customfield_10103',
 'cf[10610]': 'customfield_10610',
 '市场情绪估计': 'customfield_10610',
 'cf[11303]': 'customfield_11303',
 '情景贡献人': 'customfield_11303',
 'cf[10614]': 'customfield_10614',
 '最新拆解详情': 'customfield_10614',
 'remainingEstimate': 'timeestimate',
 'timeestimate': 'timeestimate',
 'cf[11429]': 'customfield_11429',
 '指标代码': 'customfield_11429',
 'affectedVersion': 'versions',
 'cf[11706]': 'customfield_11706',
 '属于公司': 'customfield_11706',
 'cf[11705]': 'customfield_11705',
 '存在情景': 'customfield_11705',
 'cf[11707]': 'customfield_11707',
 '参与人': 'customfield_11707',
 'cf[10619]': 'customfield_10619',
 '纳入优选层时间': 'customfield_10619',
 'assignee': 'assignee',
 'cf[11709]': 'customfield_11709',
 '星图截图': 'customfield_11709',
 'status': 'status',
 'component': 'components',
 'id': 'issuekey',
 'issue': 'issuekey',
 'issuekey': 'issuekey',
 'key': 'issuekey',
 'cf[11300]': 'customfield_11300',
 '预测目标日区间半径': 'customfield_11300',
 'cf[11422]': 'customfield_11422',
 '相关骨干': 'customfield_11422',
 'cf[11302]': 'customfield_11302',
 '研究成果地址': 'customfield_11302',
 'cf[11414]': 'customfield_11414',
 '有子世界线': 'customfield_11414',
 'cf[10203]': 'customfield_10203',
 '结论基准日': 'customfield_10203',
 'cf[10601]': 'customfield_10601',
 '万得简称': 'customfield_10601',
 'cf[10602]': 'customfield_10602',
 '潜在问题': 'customfield_10602',
 'cf[11415]': 'customfield_11415',
 '有父世界线': 'customfield_11415',
 'creator': 'creator',
 'subtasks': 'subtasks',
 'reporter': 'reporter',
 'cf[10201]': 'customfield_10201',
 '万得代码': 'customfield_10201',
 'cf[11412]': 'customfield_11412',
 '受世界线影响': 'customfield_11412',
 'cf[11411]': 'customfield_11411',
 '影响公司': 'customfield_11411',
 'cf[11403]': 'customfield_11403',
 '可参会时间-废弃': 'customfield_11403',
 'cf[11402]': 'customfield_11402',
 '可见范围': 'customfield_11402',
 'A值': 'customfield_11405',
 'cf[11405]': 'customfield_11405',
 'cf[11009]': 'customfield_11009',
 '指标类型': 'customfield_11009',
 'cf[11800]': 'customfield_11800',
 '结论信心自评': 'customfield_11800',
 'cf[11803]': 'customfield_11803',
 '行情数据': 'customfield_11803',
 'progress': 'progress',
 'votes': 'votes',
 'issuetype': 'issuetype',
 'type': 'issuetype',
 'timespent': 'timespent',
 'project': 'project',
 'cf[11000]': 'customfield_11000',
 '成果库地址': 'customfield_11000',
 'cf[11001]': 'customfield_11001',
 '监测报告地址': 'customfield_11001',
 'cf[11002]': 'customfield_11002',
 '可能世界线': 'customfield_11002',
 'cf[11003]': 'customfield_11003',
 '市场情绪': 'customfield_11003',
 'cf[11005]': 'customfield_11005',
 '本次研究启动时间': 'customfield_11005',
 'cf[11400]': 'customfield_11400',
 '投资价值': 'customfield_11400',
 'cf[10302]': 'customfield_10302',
 '拷贝字段更新日': 'customfield_10302',
 'cf[10700]': 'customfield_10700',
 'Parent Link': 'customfield_10700',
 'cf[10701]': 'customfield_10701',
 'Target start': 'customfield_10701',
 'cf[10702]': 'customfield_10702',
 'Target end': 'customfield_10702',
 'cf[10703]': 'customfield_10703',
 'Original story points': 'customfield_10703',
 'resolutiondate': 'resolutiondate',
 'resolved': 'resolutiondate',
 'cf[10704]': 'customfield_10704',
 'Team': 'customfield_10704',
 'workratio': 'workratio',
 'watchers': 'watches',
 'created': 'created',
 'createdDate': 'created',
 'cf[11105]': 'customfield_11105',
 '预测基准日市值中点': 'customfield_11105',
 'cf[11502]': 'customfield_11502',
 '被荐骨干': 'customfield_11502',
 'cf[11106]': 'customfield_11106',
 '最新监测日': 'customfield_11106',
 'cf[10930]': 'customfield_10930',
 '最新预测Json-废弃': 'customfield_10930',
 'cf[11501]': 'customfield_11501',
 '推荐公司': 'customfield_11501',
 'cf[11900]': 'customfield_11900',
 '侦察员': 'customfield_11900',
 'cf[11107]': 'customfield_11107',
 '最新监测日-废弃': 'customfield_11107',
 'cf[11108]': 'customfield_11108',
 'X和市值258分位': 'customfield_11108',
 'cf[10932]': 'customfield_10932',
 '主要产品': 'customfield_10932',
 'cf[10933]': 'customfield_10933',
 '待定预测': 'customfield_10933',
 'cf[11901]': 'customfield_11901',
 'cf[11903]': 'customfield_11903',
 '总持仓': 'customfield_11903',
 'updated': 'updated',
 'updatedDate': 'updated',
 'originalEstimate': 'timeoriginalestimate',
 'timeoriginalestimate': 'timeoriginalestimate',
 'description': 'description',
 'cf[11220]': 'customfield_11220',
 '建议层级': 'customfield_11220',
 'cf[11100]': 'customfield_11100',
 '研究主责人': 'customfield_11100',
 'cf[11101]': 'customfield_11101',
 '研究小组': 'customfield_11101',
 'cf[11102]': 'customfield_11102',
 '预测界面提示语-废弃': 'customfield_11102',
 'cf[11104]': 'customfield_11104',
 '预测基准日区间半径': 'customfield_11104',
 'cf[11215]': 'customfield_11215',
 'test': 'customfield_11215',
 'cf[11216]': 'customfield_11216',
 '侦察逻辑': 'customfield_11216',
 'cf[11217]': 'customfield_11217',
 '知识成果地址': 'customfield_11217',
 'level': 'security',
 'cf[11218]': 'customfield_11218',
 '知识贡献人': 'customfield_11218',
 'attachments': 'attachment',
 'cf[11219]': 'customfield_11219',
 '相对年化宽度': 'customfield_11219',
 'cf[10928]': 'customfield_10928',
 '自动更新的近期波动半径': 'customfield_10928',
 'cf[10929]': 'customfield_10929',
 '预测目标日保守市值': 'customfield_10929',
 'summary': 'summary',
 'cf[11210]': 'customfield_11210',
 '侦察提交时间-废弃': 'customfield_11210',
 'cf[10000]': 'customfield_10000',
 '开发': 'customfield_10000',
 'cf[11211]': 'customfield_11211',
 '侦察复核时间-废弃': 'customfield_11211',
 'cf[11212]': 'customfield_11212',
 '经办人更新时间': 'customfield_11212',
 'cf[11214]': 'customfield_11214',
 '任务领取时间-废弃2': 'customfield_11214',
 'cf[11204]': 'customfield_11204',
 '侦察意见-废弃': 'customfield_11204',
 'cf[11601]': 'customfield_11601',
 'C指标值': 'customfield_11601',
 'cf[11722]': 'customfield_11722',
 '月涨幅': 'customfield_11722',
 'cf[11721]': 'customfield_11721',
 '市值走廊保守分位': 'customfield_11721',
 'environment': 'environment',
 'cf[11206]': 'customfield_11206',
 '结论模式': 'customfield_11206',
 'cf[11208]': 'customfield_11208',
 '侦察通过时间-废弃': 'customfield_11208',
 'cf[10636]': 'customfield_10636',
 '任务分配日-废弃': 'customfield_10636',
 'cf[11209]': 'customfield_11209',
 '整体研究结束时间-废弃': 'customfield_11209',
 'due': 'duedate',
 'duedate': 'duedate',
 'cf[10914]': 'customfield_10914',
 '保守情景概率': 'customfield_10914',
 'cf[10915]': 'customfield_10915',
 '保证金比例': 'customfield_10915',
 'cf[10916]': 'customfield_10916',
 '保守认为利润(Xc)': 'customfield_10916',
 'comment': 'comment',
 'cf[10918]': 'customfield_10918',
 '乐观认为利润(Xo)': 'customfield_10918',
 'cf[10919]': 'customfield_10919',
 '乐观情景概率': 'customfield_10919'}

In [107]:
issue_list

[]

In [76]:
len(issue_list)

37

In [77]:
issues = jira.create_issues(field_list=issue_list)

In [5]:
issue=jira.issue(id='COMPSTUDY-5679')
issue

In [7]:
issue.fields.__dict__.get('customfield_11216','None')

'公司在空心杯电机，无框力矩电机，力传感器，谐波减速器方面均有产品，国内目前只有两家公司能做无框力矩电机，一家是步科股份，另一家为昊志机电；公司掌握六维力矩传感器技术，一个六维力矩传感器的价值量是2万元；减速器年产能为15万台。'

In [20]:
issue.fields.summary,issue.fields.description

('昊志机电', None)

In [18]:
issue

NameError: name 'issue' is not defined

In [103]:
issue.update(customfield_11216='A new summary was added')

In [41]:
issue=issue[0]
issue

In [46]:
issue.fields.__dict__

{'customfield_11441': None,
 'customfield_11200': None,
 'customfield_11443': 0.0,
 'resolution': <JIRA Resolution: name='完成', id='10101'>,
 'customfield_11201': None,
 'customfield_11442': None,
 'customfield_11202': None,
 'customfield_11720': 0.0,
 'customfield_11203': '0|i02edj:',
 'customfield_10621': None,
 'customfield_10104': None,
 'customfield_11436': None,
 'customfield_10622': None,
 'customfield_10105': '1|i02fjj:',
 'customfield_10623': None,
 'customfield_11438': None,
 'customfield_10625': None,
 'customfield_10900': None,
 'customfield_10626': '尚无预测',
 'customfield_11439': None,
 'customfield_10903': '尚未纳入',
 'customfield_11716': None,
 'customfield_10508': '未知',
 'customfield_10904': None,
 'customfield_10509': None,
 'customfield_10905': None,
 'lastViewed': '2023-07-10T18:55:50.925+0800',
 'priority': <JIRA Priority: name='跟随', id='10301'>,
 'customfield_10100': None,
 'customfield_10620': '2022-11-01',
 'customfield_10610': '狂热',
 'customfield_11303': None,
 'customfield_10614': None,
 'aggregatetimeoriginalestimate': None,
 'timeestimate': None,
 'customfield_11706': None,
 'customfield_11705': 'SCENARIO-1455',
 'customfield_10619': None,
 'issuelinks': [],
 'customfield_11709': None,
 'assignee': None,
 'status': <JIRA Status: name='退出', id='10001'>,
 'customfield_11300': None,
 'customfield_11302': None,
 'customfield_10203': None,
 'customfield_10601': None,
 'customfield_10602': None,
 'aggregatetimeestimate': None,
 'creator': <JIRA User: displayName='彭雨', key='JIRAUSER11200', name='pengyu'>,
 'subtasks': [],
 'reporter': <JIRA User: displayName='彭雨', key='JIRAUSER11200', name='pengyu'>,
 'aggregateprogress': <jira.resources.PropertyHolder at 0x20b7d4347f0>,
 'customfield_10201': '300503.sz',
 'customfield_11412': None,
 'customfield_11403': None,
 'customfield_11402': None,
 'customfield_11405': None,
 'customfield_11800': None,
 'customfield_11803': "<table class='aui'><tr><th>date</th><th>收盘</th><th>成交</th><th>总市值</th><th>波动率</th><th>2w涨幅</th><th>月涨幅</th><th>季涨幅</th></tr><tr><td>2023-07-07</td><td>19.10</td><td>66984785</td><td>58.0</td><td>5.34</td><td>38.91</td><td>85.8</td><td>93.52</td></tr></table>",
 'progress': <jira.resources.PropertyHolder at 0x20b7d434100>,
 'votes': <JIRA Votes: votes=0>,
 'worklog': <jira.resources.PropertyHolder at 0x20b7d434760>,
 'issuetype': <JIRA IssueType: name='公司研究', id='10100'>,
 'timespent': None,
 'project': <JIRA Project: key='COMPSTUDY', name='研究管理项目', id='10000'>,
 'customfield_11000': None,
 'customfield_11001': None,
 'customfield_11002': None,
 'aggregatetimespent': None,
 'customfield_11003': <JIRA CustomFieldOption: value='狂热', id='10600'>,
 'customfield_11005': '2022-11-01T12:24:31.000+0800',
 'customfield_11400': -0.26895561664888074,
 'customfield_10302': '2023-07-09',
 'customfield_10700': None,
 'customfield_10701': None,
 'customfield_10702': None,
 'customfield_10703': None,
 'customfield_10704': None,
 'resolutiondate': '2022-11-26T20:49:33.000+0800',
 'workratio': -1,
 'watches': <JIRA Watchers at 2248369456896>,
 'created': '2022-11-01T12:24:31.000+0800',
 'customfield_11105': None,
 'customfield_11502': 'ATLASKEEL-37',
 'customfield_10930': '{}',
 'customfield_11106': None,
 'customfield_11107': None,
 'customfield_11900': None,
 'customfield_10932': None,
 'customfield_11108': None,
 'customfield_10933': '缺少市值信息，可能是错误',
 'customfield_11903': "<table class='aui'><tr><th>总持仓</th><th>杠杆倍数</th></tr><tr><td>0</td><td>1.000</td></tr></table>",
 'updated': '2023-07-10T19:04:17.000+0800',
 'timeoriginalestimate': None,
 'description': None,
 'customfield_11220': None,
 'customfield_11100': None,
 'customfield_11101': None,
 'customfield_11102': '1.上次做出的预测近端情况：无此前预测<br>\n2.自动更新的市场近端情况： ±  on 2023-07-10<br>\n',
 'timetracking': <JIRA TimeTracking at 2248369455216>,
 'customfield_11104': None,
 'customfield_11215': None,
 'customfield_11216': None,
 'customfield_11217': None,
 'customfield_11218': None,
 'attachment': [],
 'customfield_11219': None,
 'customfield_10928': None,
 'customfield_10929': None,
 'summary': '昊志机电',
 'customfield_10000': '{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@4c37e214[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@489cd169[overall=PullRequestOverallBean{stateCount=0, state=\'OPEN\', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@7782d1f7[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@59bb51f7[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@616b046c[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@502d9396[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3141ed0d[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@32f6263b[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@b070c6d[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@370a8fb8[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@99d25d1[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@ad90d27[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={"cachedValue":{"errors":[],"configErrors":[],"summary":{"pullrequest":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":"OPEN","details":{"openCount":0,"mergedCount":0,"declinedCount":0,"total":0},"open":true},"byInstanceType":{}},"build":{"overall":{"count":0,"lastUpdated":null,"failedBuildCount":0,"successfulBuildCount":0,"unknownBuildCount":0},"byInstanceType":{}},"review":{"overall":{"count":0,"lastUpdated":null,"stateCount":0,"state":null,"dueDate":null,"overDue":false,"completed":false},"byInstanceType":{}},"deployment-environment":{"overall":{"count":0,"lastUpdated":null,"topEnvironments":[],"showProjects":false,"successfulCount":0},"byInstanceType":{}},"repository":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}},"branch":{"overall":{"count":0,"lastUpdated":null},"byInstanceType":{}}}},"isStale":false}}',
 'customfield_11210': None,
 'customfield_11211': None,
 'customfield_11212': None,
 'customfield_11214': None,
 'customfield_11204': None,
 'customfield_11722': 85.8,
 'customfield_11721': None,
 'customfield_11206': None,
 'customfield_10636': None,
 'customfield_11208': None,
 'customfield_11209': None,
 'duedate': None,
 'customfield_10914': None,
 'customfield_10915': None,
 'customfield_10916': None,
 'comment': <jira.resources.PropertyHolder at 0x20b7d434580>,
 'customfield_10918': None,
 'customfield_10919': None}

In [45]:
issue.update(fields={'customfield_10201':'300503.sz'})

In [16]:
issue

NameError: name 'issue' is not defined

Reverse：

从codelist 获取jira和行情信息，整理成 各个字段+最终文本的xls表

In [104]:
import pandas as pd
import sys
from jira import JIRA
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import MYSQL,get_mysql
from datetime import date

In [4]:
'601919.SH,600519.sh'.split(',')

['601919.SH', '600519.sh']

In [4]:
codelist=['601919.SH','600519.sh','abcd.qg']

In [5]:
class ScoutHelper():
    def __init__(self,codelist) -> None:
        self.codelist=[code.upper() for code in codelist]
        self.__jira=None
        self.__mysql=None
        self.no_data_list=[]
        self.no_jira_list=[]
        pass
    @property
    def mysql(self):

        if not hasattr(self, '__mysql') or self.__mysql is None:
                # 连接到MySQL
                self.__mysql = get_mysql('qgdbs')
                return self.__mysql
        
    @property
    def jira(self):

        if not hasattr(self, '__jira') or self.__jira is None:
                # 连接到MySQL
                self.__jira = JIRA('https://research.quantumgalaxy.cn/', basic_auth=('bot2', "jira_bot2")) 
                return self.__jira
        
            

    def fecth_ticker_data(self):
        #市值、涨幅
        #sql=f'select a.code,a.date,a.market_value,change_rate_1d from ticker_data a join processed_data b on a.code=b.code where a.date=b.date and a.code={code} order by date desc limit 1'
        sql=f'''SELECT a.code, a.date, a.market_value, b.change_rate_1d\
            FROM ticker_data a\
            JOIN processed_data b ON a.code = b.code AND a.date = b.date\
            WHERE a.code IN {tuple(self.codelist)}\
            AND (\
            SELECT COUNT(*)\
            FROM ticker_data\
            WHERE code = a.code AND date > a.date\
            ) = 0'''
        ticker_data=self.mysql.read_query(sql)
        self.mysql_df=pd.DataFrame(data=ticker_data,columns=['code','date','market_value','change_1d'])
        self.mysql_df=self.mysql_df.round({'market_value':2})
        self.mysql_df['change_1d']=self.mysql_df['change_1d'].apply(lambda x: '{:.2%}'.format(x))
        tickers=[t[0] for t in ticker_data]
        for ticker in self.codelist:
            if ticker not in tickers:
                self.no_data_list.append(ticker)
        return self.mysql_df

    def fecth_jira_data(self):
        #summary,description  侦察逻辑customfield_11216
        jira_data=[]
        for code in self.codelist:
            get_issue=self.jira.search_issues(f'project = COMPSTUDY AND 万得代码 ={code}')
            if not get_issue:
                self.no_jira_list.append(code)
            else:
                issue=get_issue[0]
                summary,description=issue.fields.summary,issue.fields.description
                jira_data.append((code,summary,description))
        self.jira_df=pd.DataFrame(data=jira_data,columns=['code','summary','description'])
    
    def work(self):
        self.fecth_jira_data()
        self.fecth_ticker_data()
        df=pd.merge(self.jira_df,self.mysql_df,on='code')
        if self.no_data_list:
             print('no_data_list:',self.no_data_list)
        if self.no_jira_list:
             print('no_jira_list',self.no_jira_list)
        if not (self.no_data_list and self.no_jira_list):
             print('all good')
        df['text']=None
        for i,r in df.iterrows():
            df.loc[i,'text']=f"""{r['summary']}{r['code']}({r['market_value']}亿元,{r['change_1d']})：{r['description']}"""
        
        return df
    def main(self):
        df=self.work()
        df1=pd.DataFrame(data=[['这些标的没有行情信息：',self.no_data_list],['这些标的没有jira问题：',self.no_jira_list]])
        #shape=df.shape[0]
        path=r'E:\wangzhilin\QuantumGalaxy\opt\scout\files'+f'\{date.today()}.xlsx'
        with pd.ExcelWriter(path) as writer:
            df.to_excel(writer, sheet_name='Sheet1', index=False)
            df1.to_excel(writer,sheet_name='Sheet2',index=False)
        #worksheet.write(f'A{shape+1}', '这些标的没有行情信息：'+self.no_data_list)
        #worksheet.write(f'A{shape+2}', '这些标的没有jira问题：'+self.no_jira_list)
        print(df1)
        return df
    def __del__(self):
        if self.__mysql is not None:
            self.__mysql.close()

In [2]:
r=''.split(',')
r

['']

In [4]:
if len(r)<=1:
    print('n')

n

In [139]:
scout=ScoutHelper(codelist)
scout

In [140]:
df=scout.main()

no_data_list: ['ABCD.QG']
no_jira_list ['ABCD.QG']
               0          1
0    这些标的没有行情信息：  [ABCD.QG]
1  这些标的没有jira问题：  [ABCD.QG]

In [136]:
scout.no_data_list

['ABCD.QG']

In [8]:
from datetime import datetime
datetime.now().strftime("%Y-%m-%d %H:%M:%S %f")

'2023-07-14 00:50:00 962576'

In [13]:
df=pd.DataFrame([1,2,3])
df

   0
0  1
1  2
2  3

In [16]:
import os

In [22]:

with pd.ExcelWriter(path) as writer:
    
    df.to_excel(writer, sheet_name='Sheet1', index=False)
    pass

In [10]:
r'E:\wangzhilin\QuantumGalaxy\opt\scout\files'+f'\{datetime.now().strftime("%Y-%m-%d_%H:%M:%S_%f")}.xlsx'

'E:\\wangzhilin\\QuantumGalaxy\\opt\\scout\\files\\2023-07-14_00:51:03_785883.xlsx'

In [7]:
datetime.now().strftime()

TypeError: strftime() missing required argument 'format' (pos 1)

In [103]:
f'E:\wangzhilin\QuantumGalaxy\opt\scout\files\{date.today()}.xlsx'

'E:\\wangzhilin\\QuantumGalaxy\\opt\\scout\x0ciles\\2023-07-13.xlsx'

In [64]:
df.to_excel(r'E:\wangzhilin\QuantumGalaxy\opt\scout\files\sample.xlsx')

In [77]:
mysql_df.round({'market_value':2})
mysql_df['change_1d']=mysql_df['change_1d'].apply(lambda x: '{:.2%}'.format(x))
mysql_df

        code        date  market_value change_1d
0  600519.SH  2023-07-12  21528.717896     0.22%
1  601919.SH  2023-07-12   1487.218763    -1.32%

In [30]:
jira_data=[]
for code in codelist:
    get_issue=jira.search_issues(f'project = COMPSTUDY AND 万得代码 ={code}')
    if not get_issue:
        pass
    else:
        issue=get_issue[0]
        summary,description=issue.fields.summary,issue.fields.description
        jira_data.append((code,summary,description))
jira_data

[('601919.SH', '中远海控', '需求向好，格局向好，公司正在价值重估道路上。'), ('600519.SH', '贵州茅台', None)]

In [34]:
mysql_df=pd.DataFrame(data=ticker_data,columns=['code','date','market_value','change_1d'])

In [40]:
jira_df=pd.DataFrame(data=jira_data,columns=['code','name','d'])

In [41]:
df1=pd.merge(jira_df,mysql_df,on='code')
df1

,code,name,d,date,market_value,change_1d
0,601919.SH,中远海控,需求向好，格局向好，公司正在价值重估道路上。,2023-07-12,1487.218763,-0.013171
1,600519.SH,贵州茅台,None,2023-07-12,21528.717896,0.002222

"SELECT a.code, a.date, a.market_value, b.change_rate_1d            FROM ticker_data a            JOIN processed_data b ON a.code = b.code AND a.date = b.date            WHERE a.code IN ('601919.SH', '600519.sh')            AND (            SELECT COUNT(*)            FROM ticker_data            WHERE code = a.code AND date > a.date            ) = 0"

In [3]:
tuple(codelist)

NameError: name 'codelist' is not defined

In [6]:
scout=ScoutHelper(None)
scout.codelist

TypeError: 'NoneType' object is not iterable