In [1]:
from iFinDPy import *
import sys
import logging
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import MYSQL
from datetime import date
import pandas as pd
import numpy as np

e:\ProgramData\Anaconda3\envs\QGIBG\Lib\site-packages\iFinDPy.pth

In [8]:
df=pd.read_excel('E:\wangzhilin\QuantumGalaxy\星图节点挂钩指标.xlsx',sheet_name=[0,1,2,3])
df[3]

                指标名称      指标类型      国家  频率         数据代码               单位
0        即期汇率（美元兑日元）        汇率  日本, 美国  日度    USDJPY.FX              NaN
1          波罗的海干散货指数      货运价格      全球  日度      BADI.GI              NaN
2             天津航运指数      货运价格  中国, 全球  日度     S6402901              NaN
3   日本：货币供应量：平均余额：M1      货币供应      日本  月度     G0900089             万亿日元
4   日本：货币供应量：平均余额：M2      货币供应      日本  月度     G0900087             万亿日元
5   日本：货币供应量：平均余额：M3      货币供应      日本  月度     G0900088             万亿日元
6    日本：基础货币：平均余额：季调      货币供应      日本  月度     G0900062              亿日元
7        日本：准备金余额：实值      货币供应      日本  月度     G0900061              亿日元
8      日本：日元TIBOR：1周  货币市场金融工具      日本  日度     G1241481                %
9     日本：日元TIBOR：1个月  货币市场金融工具      日本  日度     G1241482                %
10    日本：日元TIBOR：2个月  货币市场金融工具      日本  日度     G1241483                %
11    日本：日元TIBOR：3个月  货币市场金融工具      日本  日度     G1241484                %
12    日本：日元TIBOR：6个月  货币市场金融工具      日本  日度     G1241487                %
13   日本：日元TIBOR：12个月  货币市场金融工具      日本  日度     G1241493                %
14    日本：企业债收益率指数：综合  货币市场金融工具      日本  日度     G1241528  1996年12月31日=100
15        日本：国债利率：1年     国债收益率      日本  日度     G1235655                %
16        日本：国债利率：2年     国债收益率      日本  日度     G1235656                %
17        日本：国债利率：3年     国债收益率      日本  日度     G1235657                %
18        日本：国债利率：5年     国债收益率      日本  日度     G1235659                %
19        日本：国债利率：7年     国债收益率      日本  日度     G1235661                %
20       日本：国债利率：10年     国债收益率      日本  日度     G1235664                %
21       日本：CPI：当月同比       CPI      日本  月度     G1254021                %
22           日经225指数    股票市场指数      日本  日度      N225.GI              NaN
23         TCE 3号烟片胶      大宗商品      日本  日度     RSS3.TCE              NaN
24            TCE 黄金      大宗商品      日本  日度     GOLD.TCE              NaN
25             TCE 铂      大宗商品      日本  日度  PLAT000.TCE              NaN
26        日本：消费者信心指数      居民收入      日本  月度     G0001054              NaN

In [13]:
#edb_str='G005464034'
THS_iFinDLogin('lzxh0011','450503')
data=THS_EDB(edb_str,'','2022-06-01','2022-07-25')

In [14]:
data.data

           time          id   value         index_name                rtime
0    2022-06-30  G002600362     9.1        美国:CPI:当月同比  2022-07-13 20:52:33
1    2022-07-15  G002600494  251000  美国:当周初次申请失业金人数:季调  2022-07-21 20:39:10
2    2022-07-08  G002600494  244000  美国:当周初次申请失业金人数:季调  2022-07-14 20:37:15
3    2022-07-01  G002600494  236000  美国:当周初次申请失业金人数:季调  2022-07-21 20:39:11
4    2022-06-24  G002600494  231000  美国:当周初次申请失业金人数:季调  2022-06-30 20:35:29
..          ...         ...     ...                ...                  ...
380  2022-06-08  L001619976  2.3003         国债到期收益率:2年  2022-06-08 00:00:00
381  2022-06-07  L001619976  2.3099         国债到期收益率:2年  2022-06-07 00:00:00
382  2022-06-06  L001619976  2.3025         国债到期收益率:2年  2022-06-06 00:00:00
383  2022-06-02  L001619976  2.2813         国债到期收益率:2年  2022-06-02 00:00:00
384  2022-06-01  L001619976  2.2786         国债到期收益率:2年  2022-06-01 00:00:00

[385 rows x 5 columns]

In [6]:
host='localhost'
user='Local_Editor'
password='QuantumGalaxy'
database='qgdbs'
mysql=MYSQL(host,user,password,database)

In [7]:
sql='select ths_code from edb_info where not ths_code is null'
r=mysql.read_query(sql)
r

(('G002600362',),
 ('G002600494',),
 ('G002600769',),
 ('G002600770',),
 ('G002600771',),
 ('G002600772',),
 ('G002600774',),
 ('G004786716',),
 ('G005464034',),
 ('L001618528',),
 ('L001618529',),
 ('L001619472',),
 ('L001619518',),
 ('L001619976',))

In [9]:
edb_str=''
for c in r:
    edb_str+=c[0]
    edb_str+=','
edb_str=edb_str[:-1]
edb_str

'G002600362,G002600494,G002600769,G002600770,G002600771,G002600772,G002600774,G004786716,G005464034,L001618528,L001618529,L001619472,L001619518,L001619976'