In [1]:
from iFinDPy import *
import sys
import logging
sys.path.append('E:\wangzhilin\QuantumGalaxy')
from QGI.mysql import MYSQL
from datetime import date
import pandas as pd
import numpy as np
from QGI.neoapi import Neo4j

e:\ProgramData\Anaconda3\envs\QGIBG\Lib\site-packages\iFinDPy.pth

In [2]:
neo_uri = "neo4j+ssc://08ef0a79.databases.neo4j.io"
neo_user = "QG_Editor"
neo_password = "editor"
neo=Neo4j(neo_uri,neo_user,neo_password)
sql_host='localhost'
sql_user='Local_Editor'
sql_password='QuantumGalaxy'
database='qgdbs'
mysql=MYSQL(sql_host,sql_user,sql_password,database)

In [55]:
r=neo.fetch_company_info()
df=pd.DataFrame(r,columns=['neoname','neonickname','neocode'],index=None)
df

        neoname neonickname    neocode
0          绿洲石油        绿洲石油      OAS.O
1          CEQP        None       None
2    phillips66        None       None
3          测试节点        None       None
4          兰花科创        None  600123.SH
..          ...         ...        ...
441    coinbase        None     COIN.O
442        赛伍技术        None  603212.SH
443        迈为股份        None  300751.SZ
444     Kranken        None       None
445          谷歌        None     GOOG.O

[446 rows x 3 columns]

In [56]:
df=df.replace({None:''}).sort_values('neocode',ascending=False).reindex()
df['与数据库代码一致']=False
df['qgdbscode'],df['qgdbsname']=None,None

In [57]:
df1=df
df1

    neoname neonickname neocode  与数据库代码一致 qgdbscode qgdbsname
36     中通快递               ZTO.N     False      None      None
339    ZOOM                ZM.O     False      None      None
103  Zillow                ZG.O     False      None      None
100    小鹏汽车              XPEV.N     False      None      None
291   埃克森美孚               XOM.N     False      None      None
..      ...         ...     ...       ...       ...       ...
134     同仁堂                         False      None      None
133    江中药业                         False      None      None
132    贵州茅台                         False      None      None
285    广聚能源                         False      None      None
244    北特科技                         False      None      None

[446 rows x 6 columns]

In [58]:
for i,r in df1.iterrows():
    if r.neocode!='':
        sql='select name,code from ticker_info where code="%s"'%(r.neocode)
        result=mysql.read_query(sql)
        if result:
            df1.loc[i,'qgdbsname']=result[0][0]
            df1.loc[i,'qgdbscode']=result[0][1]
            df1.loc[i,'与数据库代码一致']=True
    else:
        if r.neonickname !='':
            print(r.neoname,r.neonickname)
            sql='select name,code from ticker_info where name like "%%%s%%" or name like "%%%s%%" limit 1'%(r.neoname,r.neonickname)
        else:
            print(r.neoname,'none')
            sql='select name,code from ticker_info where name like "%%%s%%"  limit 1'%(r.neoname)
        result=mysql.read_query(sql)
        print(result)
        if result:
            df1.loc[i,'qgdbsname']=result[0][0]
            df1.loc[i,'qgdbscode']=result[0][1]
df1

招商南油 none
(('招商南油', '601975.SH'),)
Delek Logistics Partners none
()
中远海能 none
(('中远海能', '1138.HK'),)
阿斯塔农业 Astra Agro Lestari
()
statoil none
()
杭州市自然资源和规划局及各分局 none
()
川崎汽船 none
()
日本邮船 none
()
淮钢特钢 none
()
仁智股份 none
(('仁智股份', '002629.SZ'),)
商船三井 none
()
EQT none
(('EQT能源', 'EQT.N'),)
宝钢股份 none
(('宝钢股份', '600019.SH'),)
河钢股份 none
(('河钢股份', '000709.SZ'),)
沙钢股份 none
(('沙钢股份', '002075.SZ'),)
鞍钢股份 none
(('鞍钢股份', '000898.SZ'),)
Diamond back none
()
巴哈马超级石油海运 none
()
大陆资源 none
()
Microsoft teams none
()
石化油服 none
(('中石化油服', '1033.HK'),)
中国船舶 none
(('中国船舶租赁', '3877.HK'),)
森田化工 none
()
大宇造船 none
()
中远海控 none
(('中远海控', '1919.HK'),)
马士基航运 none
()
九九久 none
()
招商轮船 none
(('招商轮船', '601872.SH'),)
Scorpio Tanks none
()
碧迪 none
(('碧迪医疗', 'BDX.N'),)
前线海运 none
(('前线海运', 'FRO.N'),)
东华能源 none
(('东华能源', '002221.SZ'),)
江西铜矿 none
()
晋城市益兴达工贸有限公司 none
()
Smart Sand none
(('Smart Sand', 'SND.O'),)
EOG资源 none
()
中国有色集团 none
()
马本德矿业 none
()
中色华鑫 none
()
道明尼能源 none
(('道明尼能源', 'D.N'),)
西方石油 none
(('西方石油', 'OXY.N'),)
盛顺德化工科技有限公司  none
()
中国石油天然气股份有限公司大庆石化分公司 none
()
大型国有钢铁集团 none
()
地中海航运 none
()
桂林辉昂生化药业 none
()
Corbion-Purac none
()
上药云健康益药药房 none
()
江苏德元堂医药 none
()
字节跳动 none
()
Acme none
(('Acme联合', 'ACU.A'),)
Bernhardt none
()
测试节点 none
()
phillips66 none
()
每日优选 none
()
Kranken none
()
东平百成矿业有限公司 none
()
物产中大 none
(('物产中大', '600704.SH'),)
华达新材 none
(('华达新材', '605158.SH'),)
迪士尼 none
(('迪士尼', 'DIS.N'),)
以星综合航运 none
()
达飞航运 none
()
Bigcommerce none
(('Bigcommerce Holdings', 'BIGC.O'),)
STRIPE none
()
中集集团 none
(('中集集团', '000039.SZ'),)
新华昌集团 none
()
中国平安 none
(('中国平安', '2318.HK'),)
UPS none
(('Upstart', 'UPST.O'),)
DHL none
()
Fedex none
()
测试公司指标 none
()
元气森林 none
()
Gateway none
()
Facebook none
()
惠顿贵金属公司（WPM） none
()
猎户座矿业金融集团 (Orion Mine Finance) none
()
巴里克黄金公司 none
()
伊格尔矿业公司 none
()
东莞玖龙纸业 none
()
山东太阳纸业 none
()
金光纸业集团 none
()
金新农 none
(('金新农', '002548.SZ'),)
森达美种植 SIME DARBY PLANTATION
()
南钢股份 none
(('南钢股份', '600282.SH'),)
美国政府 none
()
国瓷集团 none
()
科恒股份 none
(('科恒股份', '300340.SZ'),)
亿纬锂能 none
(('亿纬锂能', '300014.SZ'),)
Ener Venue none
()
热能合作伙伴公司 none
()
Genvia none
()
中国核能工业 none
()
布鲁斯能源 none
()
美国铝业 none
(('美国铝业', 'AA.N'),)
CEQP none
()
路畅科技 none
(('路畅科技', '002813.SZ'),)
松芝股份 none
(('松芝股份', '002454.SZ'),)
奥特佳 none
(('奥特佳', '002239.SZ'),)
三花智控 none
(('三花智控', '002050.SZ'),)
万通智控 none
(('万通智控', '300643.SZ'),)
保隆科技 none
(('保隆科技', '603197.SH'),)
德赛西威 none
(('德赛西威', '002920.SZ'),)
北斗星通 none
(('北斗星通', '002151.SZ'),)
KeepTruckin none
()
天奇股份 none
(('天奇股份', '002009.SZ'),)
旷达科技 none
(('旷达科技', '002516.SZ'),)
麦格纳 none
()
李尔 none
(('李尔', 'LEA.N'),)
天成自控 none
(('天成自控', '603085.SH'),)
华阳集团 none
(('华阳集团', '002906.SZ'),)
继峰股份 none
(('继峰股份', '603997.SH'),)
富奥股份 none
(('富奥股份', '000030.SZ'),)
杭可科技 none
(('杭可科技', '688006.SH'),)
璞泰来 none
(('璞泰来', '603659.SH'),)
广汽 none
(('广汽集团', '2238.HK'),)
赢合科技 none
(('赢合科技', '300457.SZ'),)
Reima none
()
索尼 none
(('索尼克汽车', 'SAH.N'),)
金地股份 none
()
房天下 none
()
安居客 none
()
上海华谊 none
()
Mt.Cattlin none
()
ABY none
(('Babylon Holdings', 'BBLN.N'),)
雅保锂业 none
()
Mt.Finniss none
()
豪瑞集团 none
()
西安延长 none
()
Bentec none
()
国民油井 none
()
四川宏华 none
()
宝鸡石械 none
()
K&S none
()
恩捷股份 none
(('恩捷股份', '002812.SZ'),)
杉杉股份 none
(('杉杉股份', '600884.SH'),)
新宙邦 none
(('新宙邦', '300037.SZ'),)
天际股份 none
(('天际股份', '002759.SZ'),)
新泰材料 none
()
石大胜华 none
(('石大胜华', '603026.SH'),)
贝特瑞 none
(('贝特瑞', '835185.BJ'),)
先导智能 none
(('先导智能', '300450.SZ'),)
德尔股份 none
(('德尔股份', '300473.SZ'),)
耐世特 none
(('耐世特', '1316.HK'),)
采埃孚 none
()
亚太股份 none
(('亚太股份', '002284.SZ'),)
天齐锂业 none
(('天齐锂业', '002466.SZ'),)
贝壳集团 none
()
西部矿业 none
(('西部矿业', '601168.SH'),)
方大炭素 none
(('方大炭素', '600516.SH'),)
海油发展 none
(('海油发展', '600968.SH'),)
黄河旋风 none
(('黄河旋风', '600172.SH'),)
中海油服 none
(('中海油服', '601808.SH'),)
科威特石油 none
()
中粮集团 none
()
中兵红箭 none
(('中兵红箭', '000519.SZ'),)
力量钻石 none
(('力量钻石', '301071.SZ'),)
中国黄金国际 none
(('中国黄金国际', '2099.HK'),)
兴业矿业 none
(('兴业矿业', '000426.SZ'),)
白银有色 none
(('白银有色', '601212.SH'),)
五矿稀土 none
(('五矿稀土', '000831.SZ'),)
道森股份 none
(('道森股份', '603800.SH'),)
杰瑞股份 none
(('杰瑞股份', '002353.SZ'),)
北方稀土 none
(('北方稀土', '600111.SH'),)
山煤国际 none
(('山煤国际', '600546.SH'),)
大秦铁路 none
(('大秦铁路', '601006.SH'),)
润邦股份 none
(('润邦股份', '002483.SZ'),)
三一重工 none
(('三一重工', '600031.SH'),)
南玻集团 none
()
富田农业科技有限公司 none
()
Rocket none
(('Aerojet Rocketdyne', 'AJRD.N'),)
湖北宜化 none
(('湖北宜化', '000422.SZ'),)
云天化 none
(('云天化', '600096.SH'),)
太阳石油 none
(('太阳石油', 'SUN.N'),)
一汽集团 none
()
万里扬 none
(('万里扬', '002434.SZ'),)
赛轮轮胎 none
(('赛轮轮胎', '601058.SH'),)
拓普集团 none
(('拓普集团', '601689.SH'),)
华域汽车 none
(('华域汽车', '600741.SH'),)
朗科智能 none
(('朗科智能', '300543.SZ'),)
LG化学 none
()
宁德时代 none
(('宁德时代', '300750.SZ'),)
小鹏 none
(('小鹏汽车-W', '9868.HK'),)
理想 none
(('理想汽车-W', '2015.HK'),)
海泰新能 none
()
大众汽车 none
()
潍柴动力 none
(('潍柴动力', '000338.SZ'),)
先锋自然资源 none
(('先锋自然资源', 'PXD.N'),)
三菱重工 none
()
Canpotex none
()
长源电力 none
(('长源电力', '000966.SZ'),)
美图秀秀 none
()
盘江股份 none
(('盘江股份', '600395.SH'),)
三星 none
(('三星医疗', '601567.SH'),)
华为 none
()
同仁堂 none
(('同仁堂科技', '1666.HK'),)
江中药业 none
(('江中药业', '600750.SH'),)
贵州茅台 none
(('贵州茅台', '600519.SH'),)
广聚能源 none
(('广聚能源', '000096.SZ'),)
北特科技 none
(('北特科技', '603009.SH'),)

    neoname neonickname neocode  与数据库代码一致  qgdbscode       qgdbsname
36     中通快递               ZTO.N      True      ZTO.N            中通快递
339    ZOOM                ZM.O      True       ZM.O    Zoom Video通讯
103  Zillow                ZG.O      True       ZG.O  Zillow Group A
100    小鹏汽车              XPEV.N      True     XPEV.N            小鹏汽车
291   埃克森美孚               XOM.N      True      XOM.N           埃克森美孚
..      ...         ...     ...       ...        ...             ...
134     同仁堂                         False    1666.HK           同仁堂科技
133    江中药业                         False  600750.SH            江中药业
132    贵州茅台                         False  600519.SH            贵州茅台
285    广聚能源                         False  000096.SZ            广聚能源
244    北特科技                         False  603009.SH            北特科技

[446 rows x 6 columns]

In [68]:
df1.sort_values(by=['与数据库代码一致','qgdbscode'],ascending=False).to_excel('cache.xlsx')

In [59]:
df1.to_csv('cache.csv')

In [67]:
df1.to_excel('x.xlsx')